#+TITLE: Abolir Oscar

* PM - raquel
- tem como intencao premiar no ano quem foi o melhor producao artistica do ano
- gera influencia negativa em relacao a forma como a sociedade recebe aquela obra de arte
- pessoas que fazem parte do mundo que dao a premiacao, puderam ter acesso ao mercado elitizado, reflete que a gente tem uma cupula academica, extremamente ocidental, branca e elitizada.
- quando vao fazewr o julgamento dos filmes que chamaram atencao, obra de arte disruptiva nunca vai chamar atencao. existe um vies pessoal, isso é muito problematico em hollywood raramente dá premio para filmes que sao estrangeiros.
- quando vc tem essas elites, elas sao grande maneira de ganhar atencao midiatica.
  + preproducao
    - seja vc uma editora que vai lancar um livro, vc sabe que uma das maneiras da sua producao ganhar atencao, é conseguir ganhar esses premios e ser indicado, oscar bait, menina branca de classe media se encontrando no mundo, chama atencao da massa de criticos.
    - empresas sempre vao dar mais investimento para narrativas mais majoritarias, artistas que abranjem novos temas acabam sendo descartados pq emissoras nao querem lidar com o fator risco.
  + imperialismo cultural
    - quando vc tem esses criticos, isso gera um vies de autoridade na pop, se esse tipo de filme ta ganhando premio, nos compreendemos que esse é o melhor tipo de filme,  maior tendencia, isso afeta até mesmo num sistema mundial, seja no oscar, filmes britanicos e eua ganhando, gera uma concepcao interna das pessoas que é lá que tem arte de qualidade.
      + ex: brasil, despreza cinema nacional.
      + poderia diminuir pressao da grande industria de só fazer investimento dentro de obras que consideram que vai ser oscar bait, diversificar a producao e diminuir o fator de risco.
* LO - flavia
- esse debate n é sobvre o oscar
- é sobre abolir todos os premios criativos(globo de ouro, festival de berlim, festival jabuti, premio camoes e krl a quatro).
- 1g no cenario melhor dela -> academia homem branco e krl a quatro -> nois concede que a cademia do oscar é ruim mas tem mudado, momento disruptivo. por isso que parasita ganhou é um dos primeiros.
- principiologico
  + no piores momentos da humniadade as pessoas se refugiam na arte, buscam extravasar as tensoes cotidianas, reflete a vida das pessoas, os miseraveis retrata periodo de busca de igualdade
  + se a gente n tiver premiacoes, e reconhecer esses livros e musiquais, deixaria de lado, nao teria tanta publicidade, reocnhecimento para esses escritores e autores, e as pessoas talvez nao consumiriam obras que fariam falta para humanidade
    - essas premiacoes sao milionarias. conseguem movimentar todo mum mercado. pessoas comprar a mesma quantidade de livros, ou comprar o livro do gabriel garcia marquez.
    - essa premiacoes dao reconhecimento para obras que sao disruptivas sim, a gente discorda do 1g, a gente tem outras premiacoes, o globo de ouro premiando documentarios, as pessoas que se interessam, se orientam por esas premiacoes, reconhece para alem disso, tem o efeito simbolico na comundaide de dar visibilidade, autor de pantera negra ganhar oscar foi assunto em todos os jornais e isso tem representatividade.
      + ex: eu nunca ganhei debate, mas ganhei uma comenda, o que a gente premia é o esforço dos diretores e toda producao, e nao é simplesmente, a gente rotula como melhores? sao melhores para certos nichos
      + poi 2g -> as premiacoes dao visibilidade para grupo pequeno que engole visibilidade minoria nao indicada -> a gente consome mais cinema quando surge o oscar, essas premiacoes fazem justamente o oposto. trazem visibilidade para o cinema. ver filme do oscar fez eu me apaixonar pelos filmes. reconhecer um tipo de arte, o fato devc nunca premiar traz reforço negativo apra artes, de que nao é trabalho de verdade, reconhecimento e tals.
      + antes de surgir premiacoes o escritor era visto como alguem que vivia no ocido
* DPM - brenda
- premios sao elitizados
- op diz que gera reconhecimento, valorizacao, dissemina boas obras -> esses premios tem uma pretensao de serem absolutos, se isso for mais inclusivo ta sendo lento, a gente nao quer esperar por isso
- esses premios os mais legais os mais inclusivos, eles falorizm a arte dentro de padroes predefinidos, abordagem tematica, musical que sao preentendidas como boas. quais sao? as ocidentais.
- essas obras que sao preentendidas como boas vao sair na frente, massacre cultural,
- pantera negra fortalece o meu caso -> pantera negra é valroiza os negros por metricas tecnologicas, por fazerem coisa de bancoi top, tudo igualzinho dos brancos, mas eles fazem iss ocom umas roupinhas legais
- preoducoes locais sao vistas como que nao prestam, oiutros vieses sao -> literatura africana nao presta, mia couto que se encaixa da moldagem
- gabriel garcia marquez -> o outro cara que copiou ele(mia couto)
- gera incentivo pessoas irem no tema. hoje é uima coisa extremamente popularizada. isso é o opio, molda as pessoas a cultura, faz com que as pessoas e autores vao nessa direcao, a plateia agora paga pau pra isso.
- a arte, grandes momentos da arte, foram saltos que escaparam desse direcionamento generalizado, ex: picasso, distocao da leitura do tempo. dadaismo: distocao de finalidade impressionismo e expressionismo: alguma coisa
  + nenhuma dessas coisas ganharia nada por metricas estabelecidas na europa, mesmo no melhor cenario que o direcionamento nao é racista e fascista vc tá criando direcionamento
- poi flavia -> ainda no cenario de vcs o que que melhora abolir esse -> a gente para de imprmir esse direcionamento e condicionar o mercado os artistas, dá mais espaço para mais coisas de inovacoes, que sao extremamente raras, mesmo que vc conseguisse nao é o cenario, no meu cenario a gente abole isso, producao cultura pare de criar esse direcionamento. agr a gente tem uma chance, mesmo se nao fosse, uma metrica nao deveria estar sendo impressa.
* DLO - mateus
- encorajamento pra industria
- arte fala da importancia
- caracterizar -> ese tipo de premiacao ajuda a separar personagem do autor, personagens sau ruins e autores sao bons, esse tipo de premiacao mostra que aquelas pessoas tao interpretando um papel, pessoas que sao atores criacas sendo problematizados, nao tem choque james franco usar cocaina
  + desfazer rotulos -> esses premios trazem a tona essas pessaos famosos, separar autores dos personagens, premiacao justa, o oscar é inclusivo, autocritico.
- a arte inspira a vida -> a arte em geral é beneficiada -> a arte se mantewm relevante atraves do seu foco -> a gente é moldado por filme -> a arte é mais disseminada pelos premios -> a gente flerta com base em filmes -> isso foi extremamente relevante -> industria da arte é extremamente celebrada
- a cupula academica é depreciada nos proprios oscares -> eu precismo mostrar só pq as premiacoes nao estoa intrisicamente ligadas as premiacoes -> a competicao é boa pq estabelece padroes de sucesso com base em padroes de trabalho.
  + noi mundo da arte o trabalho notorio é que engaja, premios sao premio que mais decorrem de merito, pq precisam de engajar. as minorias crescem a todo tempo nessa populacao, 1/3 dos votantes dos socares foram minorias.
  + eu nao debate faz nem 3 meses -> eu conheco pessoas pq elas ja ganharam premios, pra ganhar com elas, incentivando producoes estrangeiras. as premiacoes nao dao premiacao a um grupo pequeno.
  + a cupula artistica nao tira engajamento. os oscares vao querer avancar as pautas. else vao querer qeu todo mundo ligue, eles vao querer qeu autores oscares ganhem, mesmo no pior cenario eles vao querer promover pautas sociais, mesmo por interesse proprio.
- a arte nao pode ser panelinha, engajamento sao, o erro é debater um oscar mais inclusivo, a abolicao do oscar nao prejudica ninguem. critico de cinema, diretcionamento de cinema sempre vai existir, pelos oscares serem mais midiaticos, os criticos de restuarante muito mais tendentes. os oscar vai ter que fazer um consenso.
* MG - victoria
- aboliriamos premios, n significa que estejam concedendo, majoritariamente as consequencias que eles trazem é ruim
- esses premios sao sempre formados por academias. os premios que possuem mais influencia, sao premios que surgem na cultura eua e europa. o oscar surgiu nos eua ainda segregacionista, homens brancos. na propria essencia nunca existiu oportunidade para minoria.
  + esses premios tem tido inclusivos por causa de pressao das minorias(e dai?) -> e minorias que nao tem visibilidade(boa) vao continar nao sendo visibilizadas, pq nao tem força suficiente pra pressioanr. herança do proprio impresialismo americano. meio de perpetuar a dominacao imperialista. a pop nao valoriza a cultura lolcal. pq o premio tao bem bisto ta reocnhecendo obras de generos especificos.
  + nao basta filme tenha elenco majoritairmanete negro, precisa de produtores negros, diretores negros, roteristas, essas pessaos tem acesso mtu mais dificultado. essa pessoas vem majoritariemten de grupos especificos. grupo majoritariamente da elite e branco. essas p[ess]vao ta sempre indicadno generos especificos. excessao so vai na based da pressao. se n fosse isso continuariam fazendo premiacoes da mesma forma essencia premios
  + poi flavia -> remover o oscar nao remove nenhum dos problemas que vc traz -> ele resolve os problemas, justamnnte no cenario de vcs existe uma falsa impressao de visibilidade. direcionam visibilidade das pessoas para obras especificas -> direcionam o lucro -> as ouras obras que sao a maioria das outras obras -> essas obras vao continuar nao sendo reconhecidas distribuicao dos lucros disparitaria. premios de locais minoritarios por elite local, premio jabuti por exemplo. ditado do que é consumivel molda direcao da populacao do que é cultura. nos casosainda tem o sudeste e tals, intraimperialismo.
  + abolir melhor solucao -> transicao, seja na premiacao na academia, é muito maior do que abolir esse premio.
* MO - ana
- o status quo pessoas nom undo todo sao influenciadas pelos paises ocidentais.
- isso acontece com ou sem premio -> nois vai ganhar por causa disso -> grandes paises eua e europa -> influencia no mundo > mtu dinheiro > influentes por si só > pop tem mais contato com cultura influencia desses paises > elitizacao da academia > sem esses premios o mainstream e elitizacao da academia existiria de qualquer modo
  + elitizacao nao é problema intrinseco, reflexo do problema da sociedade > premio e academia é um reflexo disso > momento de transicao >
    - esta influencia dos grandes paises nao depende desses premios, acontece de qualquer modo > a populacao brasileira inves de ficar compartilhando coisa sobre o brasil > mtu influenciada e compartilha coisas dos eua e europa, altamente influenciada. n sao a causa do problema.
- pq que a existencia permite reconhecimento da arte de paises menos conhecidos e valorizados
  + hoje a gente tem mtu mainstream e elitizacao da academia > pq nao é problema intrinsco
  + esses premios trazem audiencia > trazem pro holofote > oscar traz audiencia todo mundo pesquisa > essa empolgacao impulsiona a lgoica de mercado > conduzem as pesoas a pop mundial > verem e consumirem essas obras > enriquecimento cultural, representatividade, mitiga preconceitos > trazer pros holofotes literatura negra asiatica e krl a quatro > a gente prefere um cenario em que esas premiacoes acontecam e tragam visibilidade pros pequenos, e populacao seguir consumindo produtos depaises influentes > vai ir mais atras do filme do adam sandler > a gente aproxima a arte menos conhecida da popualcao > al africa a e asia > conteudo e documentarios de paises influentes > quando a gente tem as premiacoes da a chance dos paises falarem por si proprio > populacao vai ver um filme que um africano fez > vai ver como é a cultura daquele local e isso é mtu interessante do ponto de vista global. > quebras de preconceitos > nesse momento o mainstream é elitizado.
  + premios internos incentivam literatura brasileira inves de ir reto e premio jabuti e tals
* WG - rossane
- o 2g unico que traz garantia de como é dificil mudar probvlematica, victoria comprova que a essencia da premiacao, ambiente historico que foi mudado desa forma. a gente prova como que o processo é lento e por que
  + essa demora nao vale a pena ser bancada. o tempo que a gente gasta iria continuar as opressoes.
  + para de reforcar padroes(1g)
  + o eua terminou com segregacao a tantos anos e ate hoje é racista
  + cenario sem premiacao para de haver reforço - mtu mais distribuida - atores negros ganharem reconhecimento sem - populacao julgar pelo proprio filme sem influencia do premio.
- perda da visibilidade para filmes menores
  + 1g entenderem como se ganha aquele premio
  + nosso case é sobre visibilidade, dá tratamento diferente para filmes que sao indicados > a gente desconsidera os 60 filmes que concorram indicacao > quando a gente abole esse sistema sem o medo de serem engolidas por nao serem indicados, varios filems bons que nao sao indicados. nosso cenario nao vai ter filmes que ganham mtu visibilidade > varios filmes
  + a gente usa isso pra refutar 1op > esses filmes só ase aplicam aos filmes que foram indicados, os nao indicados foram feitos e mvao. os filmes indicados sao os que sao vistos.
  + ate hoje as empresas nao importam com o case
- case da 2o
  + a gente concorda, abolir premiacoes nao vai acabar com o racismo e xenofobia
  + menos dificil quebrar com a sociedade.
  + mtu menos dificil de quebrar
  + quando parasita acabou a xenofobia(lol) > um filme entre 50 que nao ganharam > ele literalmente fez a merda de 2o
  + cinefilo nao deixa de existir no nosso cenario. mas ele nao vai ser influenciado pelo que o pessoal fala que é bom.
* WO - neri
- o mainstream sempre vai acontecer isso é fato, temos a possibilidade de reconhecer uma cultura que é subvalorizada
- adj isso n é intrinseco ao premio(VAI TOMAR NO CU NERI) isso é um reflexo de dominacao cultural
- se nao premios para premiar e tals > o mainstream sempre vai acontecer, pq ele é mais aceitavel, mais acostumada > compram propagandas > mtu provavel que filmes de mainstream continuem super visiveis > vai acontecer com e sem premio > com o case da 2op o mainstream tem a possibilidade que ele consegue chegar > mesmo se ele nao ganhar > consegue chegar a premios muito altos > curioso, novo, enredo diferente ex: bacurau > mesmo que ele nao ganhe, ele ta concorrendo no top 3 > a gente mitiga os preconceitos, unica possibilidade dessas producoes independentes chegfarem a ser visto. é curioso.(PQP NERI), mitiga os preconceitos, o grande publico vai se acostumando aos poucos, quando esse filme vai para o grande publico.
- POI BRENDA > NO MUNDO SEM PREMIO, TEM ESPACO PRA ARTE SE REINVENTAR, O CONSUMO METRICA OCIDENTAL, ALIMENTA A VISEIRA -> Possobilidade de se reinventar, num mundo que existe premios conseguir se reinventar. populacao media quer ver, pq é curioso.
- grupo ja tem subjetividade feita -> lol, copia > só de poder concorrer já vai gerando midia >
- culturalismo > cultura europeia ser mais superior > 1g e 2g falaram > só a possibilidade de concorrer gera midia > num mundo que nao tem premios, só existe mainstream, num mundo que tem premio
