#+TITLE: ArenaNordeste01

* PM
** Case
- Glorificacao no sentido melhor cenario de atuacao das pessoas como proprios
  consumidor.
- Não é necessariamente depreciacao do mercado de capitais
- Gera tendencias dentro das empresas
  - Noçoes implosivas
- O que o mercado se propoe a fazer?
  - Empresas consigam demonstras as suas atuacoes e melhorar seus investimento.
  - Empresas que nao conseguem de outras formas
  - Por que a glorificacao mina esse objetivo?
    - Framing - > Empresas ricas, mas n é verdade, tem empresas medias
    - Você cria uma mentalidade do empresario que é algo necessario para
      empresas ser grande
      - Problema 1 -> Atrai as grandes empresas, que tem controle absoluto,
        capacidade de modificar
        - Qndo começam a dominar, tentam se proteger, proteção que tem
          capacidade de controlar o mercado de ações -> Dificultam entrada de
          empresas medias
        - POI(Danilo) -> Entra no mercado quem quer -> Eu entendo que haja
          liberdade -> Quando voce gera uma narrativa, empresas fortes que minam
          a entrada de empresas fortes(??????)
      - Problema 2 -> Mercado de intenções -> Intenções do mercado vao indo mal
        -> Mesmo se empresa vá indo bem, se o mercado entende de outra forma. A
        empresa perde valor mesmo estando com a empresa bem
        - Pq isso é ruim? Se submetendo a um cenario de instabilidade politica
          muito tempo -> Passa a narrativa que para elas serem grandes elas
          precisam estar no mercado de capitais(Que é altamente volátil) >
          Submete a maior parte das empresas cenario de instabilidade > Empresas
          agora sao condicionadas a o cenario de crise. Que transporta isso para
          os consumidores
** O que provou?
- Cria vinculacao para que TEM que entrar(?)
- Isso cria um dominio de gigante(?)
- Faz com que empresas fiquem mais sensiveis, a volatilidade, o que afeta a sociedade como um todo.
* LO
** Case
- Mercado mais usado diversos investidores, mercado de açoes é um grande mercado
  que conecta empresas e investidores
- Essa valorizacao traz investimentos que protegem o mercado
  - Capital em empresas promissoras -> Essas vantegens sao boas para os proprios
    investidores -> Quais empresas valem mais a pena.
  - O mercado é meramente privada -> A gente analisa de empresas mais eficientes
    -> Se a gente investe em empresas promissoras -> Isso é bom para pessoas
    pobres que conseguem empregos porque as empresas crescem
  - Isso quer dizer produtos de qualidade -> Voce investe empresas para que elas
    façam mais do que elas já fazem.
- Comparar com outros tipos de investimento
  - Tesouro direto
  - Poupança
  - Retorno é muito baixo, pessoas só guardam dinheiro para atividades bancarios
    que acabam em especulacao ou financiar divida
  - O retorno social é muito baixo( O que vc mais precisa é bons produtos )
  - Retorno pro indivíduo é muito mais provável
  - Principal stakeholder é a sociedade. Operações pode ter risco -> Exite uma
    capaciade de investidores escolherem -> A glorificacao é apenas para que
    eles veem com investimento
  - Empresas sao unicamente garantindo a produtividade, maior segurança pro investidor.
  - POI(Daniel) > Dominacao de grandes empresas -> As empresas que estao no
    mercado de ação tiveram a liberdade de abrir ou não o seu capital.
    Compararam e viram que é uma vantagem.
  - Ref previa > Fraudes > Concedemos que alguns vao ser prejudicados > Poderia
    ser igualmente prejudicado > Comissoes que fiscalizam
  - O mercado condiciona em ambos os cenario
** Resumo
- Garante que empresas promissoras podem crescer > O que é bom no geral
- Melhor que outros investimentos
* DPM
** Case
- Ref
  - Liberdade que existe >
    - Precisam ser aprovadas
    - Existe um lobby para essas empresas entrarem (Softbank que obriga certas
      empresas a fazer isso Ex: WeeWork)
- Pequeno investidor
  - Essa glorificacao gera uma grande enganação > Uma coisa muito mais incerta >
    Muito mais incerta > Do que juros
  - O homem médio?
    - Ele não compra ação > Um sonho > ILusao de um mercado > A glorificacao
      gera uma deturpacao > Dentro do mercado acionario eu preciso das grandes
      galinhas de ouro > Eu preciso vender essa taxa de ficar rico > O que
      deturpa o valor de mercado > Na verdade ele está escondendo o que essas
      empresas são > Inflacionando o valor dessas empresas Ex: Weework, Uber,
      Lyft, Paypal(Vale mais que o Itau e Bradesco juntos)
    - O mercado que era pra ser um catalogo vira algo ruim.
    - POI(Julia) > O despreparo é mais em decorrencia do que falta de educacao
      financeira > Eu posso ensinar educacao financeira > Inclusive piorando a
      deturpacao
  - Grande visor do mercado de todo o país
    - Praticas do mercado reverberam em toda a bolsa de valor
    - Tudo de ruim(Falto de tato)
    - Lucro pelo lucro > TOdas as más praticas sao reverberadas para todas as
      empresas como um todo. > No mercado financerio ao menos tem o bonus para
      voce ganhar dinheiro para aguentar aquilo tudo.
* DLO
** Case
- Precisa valorizar a liberdade empresarial
  - CEOs e o caralho > Não sao pessoas totalmente despreparadas, capazes de
    fazerem uma analise de mercado > Os riscos sao para aqueles que não estao no
    mercado
  - A gente nao deixa de lado apenas por serem pequenas > Investidores que
    gostam, de tratar com empresas que podem trazer riscos ou beneficios >
    Apresentam muitas startups > Grandes empresas que dominam grande mercado de
    capitais. Nao é coerentes com a realidade.
  - Valor inflacionado > Hiperinflacao > Ela nao é necessariamente atrleada a
    ela estar no mercado de capitais > Todo mundo usar uber usa lyft, influencia
    de marketing.
  - Mercado valoriza e desvaloriza independentemente de estarem no mercado de
    açoes > Elas vao sofrer por instabilidade de capitais independentemente >
    Temos um termometro > Mesmo estando mais escrachado > Um cenario em que não
    existe o mercado de capitais(POI(Daniel) Glorificacao absoluta, porque
    precisa ser glorificado) > Essas pessoas estao numa capacidade de
  - No nosso cenario a gente permite que as empresas façam, reparacao mais rapida
  - Ponto da transparencia > Empresas que nao funcionam do melhor cenario
    possível > Num mercado de açoes > Maior reparacao > Maior possibvilidade de
    curar esses danos
  - Mesmo num cenario de fraude > Os proprios estados já dispoem de meios > Isso
    vai desde punibilizar os dirigentes até sanções. Efeito chicote
* MG
- Glorificacao > Um mecanismo artifical > Trazer um tipo de influencia que se
  traveste de uma democratizacao da educacao financeira
- Valorização do trabalho > As pessoas trabalhavam e o caralho > Nao mais
  glorificar trablhar mais ganhar dinheiro somente > Canais do youtube > Hoje
  se vende que as pessoas se adentrarem nesse mercado > Pessoas se atraem pelo
  curto prazo > E passam a arriscar mais por isso
- Essa ideia que é vendida faz as pessoas pularem etapas > O mercado de ações
  não é feita para ser democratica > Pouco acesso para as pessoas > Tipo de
  estudo
- As pessoas estao muito mais dispostas a aprenderem > No caso de glorificacao
  do merado > Existe o fator de especulacao que o cidadao comum não consegue
  enxergar > As pessoas não procuram > Pessoas precisam de tempo > Coisa que não
  conseguem > Pessoas particulares nao estao dispostas a terem o mercado
  financeiro > A maior ilustracao disso é inves de ter grandes particulares
  ganhando muito dinheiro tem um ganho de crescimento de corretoras > Querem
  contratar alguem que vai resolver pra mim > Exemplo da Uber, pessoas que
  consigam aquela empresa e querer comprar > QUalquer pessoa com o minimo de
  conhecimento não investe na uber. > Isso exige um tempo uma dedicação e coisa
  que o cidadao medio nao está disposto
- Impede o aquecimento natural da economia > O trabalho > Vc vende esses atalhos
  > A atracao pela ideia perder os mecanismos de conservadorismo > Isso a curto
  prazo é pessimo > Invés de investir em si > Pé de meia naquele mercado de
  ações > Velhos estouros de bolha. Ex: 2008 e Tulipas
- A influencia em si não é ruim > O termometro e tals quando coloca uma
  glorificacao > Bota o mercado de acoes o protagonista de politicas > Pensar na
  populacao qualquer tipo de politica
* MO
- Perder transparencia
  - Depende das pessoas nao saberem investir > Grande subida de canais de
    youtube > No curto prazo podem até se lascar > Demanda natural por
    conhecimento > Muito mais provavel ter educacao > Mais canais que ensinam
    com qualidade
  - No mundo quem interfere na economia > Grandes empresas no estado > É todo
    mundo. Os poderes externos sao diluidos > Sao colocados em dinheiro > Estado
    investindo dinheiro em estados.
  - Glorificacao > Investimento é renda extra > Pai de familia vai investir o
    que sobra > Voce fala de corretora é menos ainda > Ensinar a investir
  - No longo prazo elas vao aprender a investir > No nosso mundo vai ter mais
    dinheiro sendo investido na economia > Dinheiro sendo injetado na economia >
    Pessoas medias > Investimento muito mais pleno sem forças do investimento
    estatal. Tem uma visao muito mais fiel para a economia > Lado que consome >
    Isso como sendo algo ruim > As pessoas vao investir nas empresas que elas
    consomem > No nosso mundo dinheiro que estava preso no lado do governo >
    Novas empresas gerando(1OP)
  - Fonte mais segura que não o Estado.
  - Gera inovação tecnologica > Empresas menores entram si > Isso nao impede
    elas de entrarem > Empresas menores que criam aplicativo > No nosso mundo é
    uma vitrine para essas empresas > Independe de uma linha de producao
    rentavel > Nao precisam ter lucro para serem valorizadas > Como é facil uma
    empresa startup entrar
  - N é interesse essas empresas entrarem no mercado e valorizem
* WG
- Um duplo reforço ingressar no mercado de ações > EC lamentar o mercado de
  ações > O debate é sobre a glorificacao > Ganhou tanta influencia ainda mais
  significamente
  - Nicho das startups > N é o investidor que entrou por causa da glorificacao >
    A galera que entrou > QUe vai entrar numa corretora alguem que "sabe
    investir" > Vai guiar ela para empresa > Empresas que tem maior capital >
    Lobby maior capital.
  - A Uber é uma empresa que é ruim, por causa da visibilidade de fora, o
    mercado tem uma impressao camuflada
  - 1 Gov introduziou a ideia > Mecanismo de influencia dentro da economia como
    um todo > Cidadao medio, o Brasileiro > No longo prazo nao é atraves de
    video no youtube, o que mais surge sao investidores que vendem essa ideia >
    Nós vamos ensinar a investir > Gosta de coisas seguras > Mercado n tem
    rodadndo > Lobbies grande > Vendem essa imagem > E é isso que as pessoas tao
    procurando > Pessoas nao estao se engajando > Querem a garantia.
    - Pq essa busca dessa garantia > Cria o lobby da visibilidade > Se utilizam
      na politica > Lobby quando foi pelo fim da quarentena bolsonaro foi na XP
    - Ideia da visibilidade > Lobby sabe que os mercados atuais > Curral de
      investidores > Agr ocorre no mercado de acoes > Continuam sendo
      incentivadas a nao aprender > Ciclo desses lobbies > Dentro do cenario de
      paises subdesenvolvidos > N tem infraestrurua > Perpetuacao de mercados
      precarios > Lobbies tem tanta influencia prejudicam a propria ideia >
      Elas pouco tem, sao adquiridas pelos lobbies, engolidas pelos grandes
      lobbies.
* WO
- Essa populacao vai saber investir > Lógica que bota a propria glorificacao
  maior serviços fazer aquelas pessoas > Mesmo se aceitemos que nao vao saber >
  Isso só ocorra inicialmente.
  - Resp satisfaotria LOL
- Inovacao das empresas pequenas > Mercado de acoes é necessario > Estados
  estarem colocando intervencionismo economico > As startups nao tem nenhuma
  chance em outro mercado > Small caps apenas empresas pequenas. > É só no
  mercado de acoes que alguem vê interesse em colocar dinheiro.
- 1 GOV
  - Empresas barram outras pequenas > Se ela entrar tem todos os beneficios
  - Empresas e comportamentos ruins sao espelho > Praticas de mercado que te
    tornem diferente e se tornem diferentes > Melhor que as outras empresas. Pq
    necessariamente empresas necessariamente entram no mercado.
- 2 GOV
  - Pessoas deixam de buscar com afinco > Isso é implausivel > Ideia totalmente
    errada de investimdno > Primorico > Primeira coisa que vai colocar é de
    ganhos a longo prazo > Eles confundem day trade com simplesmente voce
    colocar esse dinheiro nessas açoes.

    2G > 1O > 2O > 1G
