#+TITLE: Amistoso UDC vs UFC

* Motion
Líderes de direitos civis são figuras influenciadoras na promoção e na
implementação da liberdade política e na expansão de direitos e liberdades civis
individuais.
EC lamenta a idealização moderna de líderes dos direitos civis como moderados, pacifistas e respeitáveis.
* PM
Por que é mais sensato -> A linguagem precede o pensamento -> As formas
linguisticas moldam nosso modo de pensar -> Pensamento precede a ação -> Se a
nossa linguagem está necessariamente permeada de virtudes -> A gente perde de
vista importantes lideranças que não portam essas caracteristicas -> Além de
levar a ignorancia e menosprezo desas lideranças -> Mesmo buscando a promoção
dos direitos civis vao ser menosprezados -> Enxergar por um otica negativa ->
Postos vistos como viloes. -> MEIO que fogem do alcance da população.
Por que é algo maléfico -> Idealizar lideres desumaniza a politica, virtude
ditada pelas elites, e de temperamento neutro, a porpria sociedade não é
permeada, a humanidade carrega contradições -> TENDENCIA DE CONSERVAR O STATUS
QUO. -> A partir do momento em que a gente idealiza, cristalizar a estrutura
politica, impedir a transformações para se adequar as mudanças sociais.
Moderação e pacifismo -> N se restrigem apenas a atos, mas também a discursos,
quando a gente utiliza a linguagem subversiva. Que tenta através de esforços das
elites, incapacitada das mudanças.
A linguagem politica juridica é a linguagem das elites -> ELa que cria as reguas
de linguagem e de discurso > O que é moderado ou não > Até 15 anos atrás
Bolsonaro não seria moderado. > Vai moldando ao sabor da economia e da politica,
sao esses moldes que vao moldandos a estrutura politica juridica. Seguir uma
linha de linguagem formada por essas elites é congelar o desenvolvimento.
Obstar formas de discurso só porque não seguem a estrutura pacifista, a
subversao de paradigmas são as bases da politica, sao as elites que ditam o que
é crime o que é moralmente aceitavel, o que é louvável, na politica. Elas podem
ditar criminalizar o aborto com valores judaicos cristao.
Resumo: A partir do momento qm a gente nao adequa a nossa linguagem a sociedade
como é, anseios conflitantes, e também de conservar, a gente nao é capaz de agir
sensatamente, e o que a gente deve conservar, a gente invizibiliza certos
lideres, que podem ser fantasticos, seguir um padrado de etiqueta, vistos como
viloes de um debate.
A moderação e o pacifismo, a mudança de paradigmas, sao esseencialmentew
alicercadas, na subversao e mudança de paradigmas, mudar a moralidade e
lignuagem é essencial, para que a politica se torne um elemento de transformação.
* LO
Antes de tudo, um pouco da mocao -> O que sao lideres > Sao referencias,
espelhos e modelos, pessoas que admiramos e seguimos, n necessariamente na
elite.
Pessoas como esas funcionam como referencia para os outros, o PM falou que esses
lideres não o é, o povo n é perfeito, exatamente por nao ser pefeitos, buscam
ideais de perfeicao e pureza. O que sao direitos civis? Direitos basicos,
seguindo nessa construcao, eu queria exaltas os 3 valores.
- Moderacao
  Formar pessoas equilibradas, que entendam as necessidades dos direitos civis,
  pessoas moderadas, um lider inforrma e inspira pessoas, uma visao plena da
  sociedade, mesmo se não ter ovalores, admira e quer. Pode atribuir medidas
  moderadas, Obama, propos medidas palpaveis, sem ser extremista e sem ser
  pifio, não tem necessariamente aos direitos civis. Se o Obamacare fosse
  mandado por alguem que n é moderado, n seria aprovado. Ser moderado e propro
  essa proposta facilita a aceitacao delas, e os politicos que quando vem aquela
  proposta nao podem arregacar com ela. Eles tem pelo menos ter o dialogo. Ser
  moderado e polpavel mais fácil de ser efetivo. Lideres moderados conseguem
  fazer mudança.
  POI(Murilo) => Um lider pode mandar a mascara de moderação e agir com mao de
  fero por tras das cortinas. Isso não é malefico tento visto o fingimento. ->
  Obama nao atuou com mao de ferro por trás. Malcolm X inspirou mas destruiu o movimento
- Ser respeitavel
  Figura respeitada, essas figuras representam pilares da democracia, pessoas
  respeitaveis, seram lembradas e inspiram mudança. Qual a importancia dele ser
  respeitado? Eles sao facilmente atacados e destruidos, o tempo é a coisa que
  traz as verdades a tona. Por todos os ano Gandhi foi batido, mas nao bateram
  de frente. Malcolm X foi malvisto e escanteado, as pessoas se lembram pelas
  coisas ruins e nao pelas mudanças sociais.
- Pacifismo
* DPM
Existe uma metrica clara -> Ganha quem mostrar mais mal ou bem para o avanço
desses lideres e conquistar os direitos civis.
TOda a explicacao existe essa idealizacao influencia como as pessoas agem e como
elas aspiram em fazer. A partir do momento esses ideais sao impostos pela
propria elite que voce tá tentando lutar. Vc está jogando pelas regras do
inimigo. Sao eles que ditam o quao sao esses valores de pacifismo esses valores
moderados. Valores de responsabilidade. Está no interesse de uma elite, contra
seus interesses e ideologias, privilegios.
Essas virtudes sao pregadas pelas elites, meios midiaticos, como boa parte da
informacao se informa. Grandes canais de noticia. Sao a elite politica, como
searm educadas essas pessoas, quais movimetnso seram venerados ou não.
1 Op comceça dizendo que lideres sao mal vistos -> Esses é jsutamente o debate,
nós lamentamos a ideia que eles sao mal vistos -> A questao de malcolm x ser
visto apenas como algo ruim, dde nao ficar só no moderado, pintar que toda a
luta de malcolm x de instigar a revolta, por mais que seja criticavel, até que
caminhos eles tomou, ele teve uma parcela extremamente importante, nao tem como
fazer uma mudança se elas estao fadadas, desde cedo se adequar aos exemplos que
a propria elite colocou.
Ex: Todos os protestos sufragistas eram tidos como não moderados, mulhe era para
estar em casa(sufragistas), se fazer só com permissao do marido, exemplo de algo
que nao era moderados, por definicao é quase insustentavel algo com impactos
reais se ele só segue a regra do jogo.
O que a 1o Tras pra gente -> Maior facilidade de nao ser rejeitado e atingir
mudança -> Obamacare nao foi algo de direitos civis, n entra no debate, o que
nós temos aqui, mesmo que eu assuma que vc consiga os direitos pela forma
moderada, no longo prazo, esses direitos podem ser facilmente subvertidos, na
mesma hora que ele botou o obamacare e botou o trumpcare. N adianta vc fazer
algo se ele é facilmente reversível, uma das metricas para analisar conseguirem.
O mov civil dos negros, só teve coisas pq foi instigado eles nao serem
moderados, serem agressivos, qualquer meio ou justificativa possível. Nao ter
apenas mudanças moderadas e dialogar com uma elite que nunca teve vontade de
ceder. Negros conversarem com supremaciseas brancos. Se mostrar virtuosos e
merecedores de direito. Só conseguirem manter esses direitos, é é a moção e nśo
somos contra, se nao houvesse a estigmatizacao e ver alguem que se revolta como
um indigente, mas tbm de fazer com que esas pessoas lutem por sua causa e ter
efetivos resultados.
* DLO
Duas ideias que gostaria de trazar _> Moderado pacifista e respeitavel coisas
que mudam ao redor do tempo -> Conceitos que estamos avaliado como pessoa,
pessoa do seculo atual olhando a acao das pessoas naquela epoca, nós nao negamos
que ghouve uma luta, houve uma quebra de padrao, n precisa ser violenta, ou nao
moderada, ou pacifista. Nos olhos de hoje em dia, é pra mostrar como é
importante manter esse padrao em nome da democracia.
- Pacifismo -> Perigo da ** se formos olhar ao redor da historia, quando uma
  sociedade louva uma dieaa de guerra e violencia, aqueles toemos uma
  consequencia da sociedade mais jovem por aquele discurso, eles querem ser
  aquele heroi que vai pra batalha, desejo de guerra. Quando voce mostra isso a
  primeira opcao, é que elas querem batalhar. Qual o problema num cenario
  democratico -> A democracia se sustante no dialogo, quando é mais relevante e
  interessante, aquilo que vc aprecia, existe um grande perigo que as pessoas
  busquem seguir.  Deixar de seguir a diplomacia a discussao. Gandhi fez muita
  coisa no pacifismo, mesmo pacifica. Em nome da democracia isto é importante.
POI(Estevao) => A gente n tá propondo que seja idealizado o oposto, ao mesmo
olhar todos sendo julgados pela mesma forma -> Qual o problema? -> A sociedade é
uma coisa confusa, a democracia era uma coisa fŕagil. Muitos conflitos e muitas
ideias, risco de acabar com esas instituicao, ela ainda é a melhor coias que
ocnhecemos enquanto governo. E isso é relevante, a partir do momento em que
pegamos lideres que tem carater dubiso em questao de violencia.\
A partir do dialogo vc tem uma retirada -> Mesmo com conquistar com luta >
COnquistas com dialogo as pessoas tem uma revolta maior(Pq?) > Poxa mas foi tao
violento, nao era pra ter tirado. Quando vc foi colocando o sistema de forma
gradual, é uma forma que a populacao consegue aceitar, tem uma concordancia.
Quando a gente transporta a violencia de uma epoca, a gente transfere do
contexto.
A sociedade atual quer pacifismo, a conquista dos direitos também é uma coias
que é precedente.
* MG
Seriam as elites que definiriam os conceitos
Vamo dispensar a premissa -> Mundoa atual intensamente conectado pelas redes
sociais, extremamente mutaveis e gerados pela sociedade, há um debate politico
acontecendo pelas elites.
Black lives matter -> Surgiu por causa de morte de jovens negros por policiais
-> Fez manifestacao saiu na porrada com a policia. A midia como um todo por
causa dessa idealizacao, chamou de revoltados de quebradores, deslegitimou. Ao
rever esse tipo de feedback nao se tornou tao radical e tals. E isso
proporcionou o establishment, um contraataque o blues lives matter. No nosso
mundo se a gente seguir uma linha moderada a gente vai atribuir um caminho mais
lento e nao tanto impacto. Oportunidade do Estado te rebater na mesma moeda,
momento de dualidade dentro do meio virtual, colocado espantalhos no meio de
cada um, ambiente polarizado, dentro do proprio meio virtual, incentivo a
polarizacao ao apoiar, no mundo em que nao tem essa estigmatizacao n existe essa
desligitimizaçao.
Risco da democracia -> N é toda ideologia revolucionaria que vai fugir do
esquema de, galera que quer aborto liberado, nao tá ameaçando a democracia, essa
galera nao é extremista, no mundo de vcs porque a luta se torna menos
legitimada, ao dar esse meio de reacao ao establishment, essas coisas não dá pra
fazer. Se vc coloca essa idealizacao, vai ser mais agradavel a establishment,
ela só é mais agradavel ao establishment porque existe essa idealizacao(wtf).
No nosso cenario -> Militancia, militancia politica, só acontece por medida
imperativas e nao muito moderados e n respeitaveis, por causa dessa militancia,
no meio virtual, sejam colocadas ao menos em pauta, via reformista, indo pelas
beiradas, parte do pressuposto que elas ao menos cheguem em pauta, vetadas,
falta de desejo de mudança, na maioria das vezes entravam por causa desse tipo
de conduta(Isso é Murilo), todo mundo que nao segue esse tripartite é deixado de
lado.
POI(dANIEL) -> Dar espaço a uma resposta, n tá em contradiçao -> Um dialogo n
vai acontecer, vai rolar uma resposta, dar oportunidade para que o establishment
reaja, na maioria dos casos. ELes estao colocadno, a gente demorou em muito
tempo.
* MO
Moderacao pacifismo e respeirto . Bom senso, a posicao da 2 op precisam ser
idealizados pq sao os mais eficientes, dentro do contexto social e tecnologico,
porque o proprio respeito aos direitos civis esta ligada a ideia de bom senso.
Criar um modelo uma referencia, o melhor resultado.
Mecanismo > Existe uma diferenca clara entre o periodo historico e como essa
diferenca deve influenciar diretamente a forma de luta. Um pouco antes, a
violencia era muito mais centralizada institucional pq o acesso a informacao n
era tao amplo, lutava com opresoes contra estados de forma organizada, modus
operandi é completamente diferente do que acontece hoje, de forma muito mais
descentralizada, a velocidade e informacao faz com que a violencia n seja mais
moedade de troca, moeda de troca  com um ser mais forte e ter mais meios. Como
se comparar quem tem uma revolta, presidiarios, apenas a influencia estatal tá
com eles. Mas a sociedade que a gente vive hoje, formas mais eficientes, hoje
essa decentralizacao, faz com que essa postura violenta, retroalimetne a
violacao contra os direitos civis. > Essas violacoes sao alimentadas pelo
discurso de odio, cada pessoa tem acesso a sua ideolgoia, essa discurso de odio,
que permite que essas ideologia se difundam, lutar contra esse novo modus
operandi, nao idealizarretroaliemtna o discurso de odio, lideres como o da
defesa cria um loop de violacoes, ex: black lives matter.\
A propria postura combativa que criou outros movimentos com atuacoes tao
prejudiciais quanto. A greve policiais dos policiais por empregar a
violencia,acabou com um tiroteio, açao e reaçao.
POI(Guilherme) -> Restringir locais que já tem amplo apoio democratico, num pais
mais autoritario, deixar muito favoravel para vcs > Nao ta sendo feita pelo meu
debate, como cada populacao.
Lider moderado é mais eficiente pq tem um contraponto, precisa de algo
diferente, se a gente tá incomodada. Se a gente tá numa guerra ideologica,
garantir uma sociedae com valores mais justos e soidos, mecanismo é respeito, é
a forma de criar caracteristicas. O meio é mais importante que a mensagem. Hoje
a gente precisa criar um ideal que funcione no nosso contexto.
* WG
O problema que o discurso de odio que o JL, a realidade é simultanea nos dois
cenarios, por mais que seja negativo, polarizar a sociedade, n é o fato que
alguns lideres pregando um pacifismo, que vai realmente solucionar todos os
problemas da sociedade, mas sim pra todo mundo desse debate.
Pq o discurso de odio n é em todo rechaçado pela nossa bancada > Por mais que
possa causar essa polarizaçao, que estao lutando para direitos especificos, é
cada vez mais fortalecido, fidelizar o nosso publicos, se vc é amplamente
atacado na internet por ter se declarado feminista, vc vai sofrer um bauqe muito
grande, mas ao mesmo tempo a gente vai tá fazendo essa pessoa unir mais com o
movimento a qual essa realmente pertence. O que mais importa é que a gente
propague essa luta, n é o mainstream que vai proteger. Pelo simples fato que
quem vai pra rua ou pressionar proejtos de lei, que vai concretizar direitos,
sao as pessoas que estao engajadas naquela luta. A partir dom omento que a gent
sensibliza essas pessoas. Existem pautas especificas que precisam de uma
urgencia social. a gente precisa um aparato um posicionamento, a gente precisa
deixar bem calro, que ela necessariamente é negativa, isso é um efeito que ela
causa, parece que eu to deslegitimando os outros discursos.
POI(Daniel) > Intuitivamente elas já rechaçam, as pessoas que já sao contraele,
vao rechaças mais ainda, essas pessoas nao sao a rota da mudança, ou se engajar
de fato, nessas lutas de direitos civis, fazer com que esses direitos sejam
respeitados e sentidos ao longo prazo. É o fato que a gente precisa entender que
essas causa.
1 O -> Trouxe premissa que lideres vao inspirar outras pessoas, nao provam que
isso vai acontecer. AInda sim existem outros fatores que nao necessariamente
estao ligados aquela pessoas. que pode quebrar esse processo de inspiração. Vc
nao vai mirar no gandhi a ferro e fogo só pq ele existe. Independentemente de
quem tá ditando a linguagem, apesar de tudo isso ainda é importante que a gente
n idealize um determinado tipo de lider, existem lutas que sao mais urgentes, se
a gente foca muito no mainstream a gente perde uma fidelidade externa.
* WO
Caso da primeira oposicao cada uma das caracteristicas se tornam mtu relevante
dentro de umcontexto de luta civil. Pq JL é mais eficiente como oposicao, ele
consegue demosntrar impactos melhreos, Ex: Ideia de respeitabilidade cria um
processo de conquista com quem concorda e quem é contra. A ideia de
responsabilidade é unir caracteristicas, até quem discorda consegue respeitar.
Lider consegue ser aceito dentro do escopo de trabalho e quem discorda.
1G -> A linguagem precede o pensamento, linguagem ser controlada pelas elites, a
ideia de respeitabilidade sao antepostos, vem antes de toda a ideia de uma
linguagem, vc consegue ser respeitado num contexto de minorias como num contexto
de eleite. A linguagem n é necessariamente determinante aqui, vc pode usar
oideal de bom senso adequado ao seu publico. Por mais que existe uma diferenca
entre o que é considerado respeitavel ou nao, se vc tem um lider que consegue
seguir isso. Cada um dos grupos demosntrar dentro dos seues escopos respeito
perante a sua maneira, ele vai ser respeitado.
Toda a ideia do exemmplo do Malcolm X > Uma luta contra afigura do Estado, n era
um negocio diversificado, precisava ser combativo, uma figura poderosa, lutando
contra a figura estatal, é dividido entre o mainstream das pessoas. lideres
precisam demosntrar caracteristicas n para mostrar o Estado, mas convencer as
pessoas, esse mainstream que é maioria, alguem que consegue ser acessivel
POI(Estevao) => Vcs tem que admitir o escopo ele n é tao efeitvo= Ele é muito
mais efetiov num contexto atual, vc tava brigando contra o Estado, vc precisava
por uma figura revanchista. Quem faz politica é o youruber, que consegue alancar
multidoes.
Lideres violentos n sao pessoas más, pq nao servem para.

Ref a elite é que

2O > 1G > 2G > 1O
2O > 1G > 2G > 1O
1G > 2O > 2G > 1O
1G > 2O > 2G > 10
2G > 2O > 1G > 10
