#+TITLE: Debate02

* PM - Damares
- Uniao direcionar 15% do orçamento federal pra saude
  + Estados e Municipios para educação, 60% valorizacao do cargo de professores
- Quem é eleito pra gerir, sao pessoas que nao tem tecnica com trato da coisa publica
  + Pessoas eleitas por simpatia, eleitos para gerir o municipio
  + Ter uma verba condicionada a determinada pasta, garantia que sempre vai ter dinheiro para aquele determinado investimento
  + Cabe aos tribunais de conta ver se esse dinheiro esta sendo bem gasto
  + Se a gente vincula determinadas verbas a determinadas pastas, o que é prioridade não vai ser negligenciado, se for eleioto candidato que acredtia no homeschooling que ele direcione verba da educacao para outra pastas.
    - Continua caro para pessoas que nao votaram nele e nao acreditam no homeschooling.
    - Outro exemplo é vinculacao direito da aposentadoria, municipios repassar, mas existem muitos municipios, por desvio de verba previdenciaria.
- Orcamentos sao definidiso por leis orcamentarias anuais e leis dos mandatos, que sao aprovadas pelo legislativo, se a gente tem certas pastas e certos assuntos do minimo que deve ser investido, impede que leis que passam pelo legislativos sejam discutidas com base em ideologias.
- Impedir investimento minimo em educacao e investir em material belico.
- Herancas malditas -> Lei orcamentaria que eles vao executar ano que vem, vai ser uma lei do proximo ano, municipios recebam heranca malditas.
* LO - Saulo
- Vincular determinadas porcentagens para determinadas areas > Necessidade de um contador pessoa da area > Simplificar a forma de fazer economia, afasta forma de resolver a deficiencia.
- Impede heranca maldita
  + Já é coibida por lei de teto de gastos
- Orcamento fluido
  + N pode ficar engessada, burocracia, a partir do momento em que a gente coloca esse caixa fixo, a economia é pautada em tradeoff, o mercado passa por crises ciclicas, influencia diretamente nas escolhas economicas, possibilidade de reverter investimento nesses setores, a partir do momento em que a gente tem um banqueiro, agr a gente n tem isso, no cenario do governo, n tem como enxugar os gastos vinculados. a partir do momento em que a gente precisa enxugar gastos para diminuir a divida do estado. sempre vai ter o caixa fixado, é mtu pior nao utilizar aquele dinheiro de forma eficiente.
  + Deixa oportunidades passarem. mais recursos, investir em determinados setores.
- Pior custo beneficio
  + A gnt n precisa dessa determinacao de caixa prara reconhecer deficiencias estruturais, 1g fala simplificar prefeitos que nao sabem de nada, passa uma ideia de uma diretoria tributaria ta sendo simplificada e qualquer um pode assumir, a gente faz com que a complexidade, ele sim pode ser julgado, quando coloca complexidade faz com que banqueiros e economistas assumam esse tipo de decisao.
  + A gente n quer que eles passem por decisoes desse tipo.
  + A partir do momento em que a gente faz economia movimentar, quando a gente ta gerando emprego, gerando bem estar.
  + 1g esquece que determinados municipios tem diferentes condicoes socioeconomicas, a gente ta esquecendo, municipios difrfentes possuem urgencias diferentes, sao jose do mipibu, em relacao a saude é minimamente eficaz, o caixa restrito.
  + POI 1G > Vc falou que esse negocio da heranca maldita > heranca maldita é em relacao a orçamentos -> Prefeitos endividando a maquina publica, isso é resolvido com oteto de gastos.
  + resolver crise é na base de tradeoff, exemplo pandemia, n pode aumentar o dinheiro investido em determinado caixa.
* DPM - Hadassa
- destinacao dá pra pontos especificos, o orçamento todo n tá enrrigecido, em temos de crise é bom que determinados setores vao permanecer.
- sobre a lei de teto de gastos, orçamento pode ser prejudicial, os gastos ja estao limitados, ideais politicos, mudancas de partidos politicos, quantidade de destinacoes prioritarias, isso pode ser mitigado atraves dessas destinacoes diretas. garante que setores vao estar contemplados independentemente.
- é assim que o sistema democratico celebra, qualquer um pode botar no cargo do executivo,qualquer nivel de expertise.
  + pequenos municipios elegem pessoas que n tem tanto interesse de gestao.
  + mitiga pessoas que nao sao espertas no orçamento.
  + se for seu ze amigo da minha familia, essaa pessoa n vai negligenciar pequenos pontos que sao essenciais e nao podem ser negligenciados.
  + garante que nao vai ter cortes absurdos, tipo corte das universidades. nao foi positivo pra sociedade. pandemia nao vai entrar, pq aquilo é resolvido estado de calamidade publica.
- pq é bom?
- poi franco > n ficou claro, pq que pra vc ter uma fixacao percentual, vc necessariamente precisa destinacao direta, outras plataformas que garantam fixacao minima percentual > alem dos beneficios que a gente garante, fica muito mais calro como os tributos funcionam, onde sao aplicados. sociedade que n gosta de pagar cada tributo. n entende pq as coisas aumentam e abaixo, aquilo a gente entende. quando ela ta pagando IPTU ela tbm ta pagando tal coisa.
  + ACCOUNTABILITY, tributo X ta muito alto, eu sei quando eu pago isso eu sei o que eu to fazendo. Ficou mais claro pra populacao entender, populacao ativa no processo orçamentario publico. Entender melhor como o sistema ta funcionando, quando a gente facilita isso para areas essenciais, a gente consegue deixar mais claro. Fica muito ciente daqueles pontos pro governo.
* DLO - Ingrid
- 1 gov fala que vai ter taxacao unica para todas as realidades, hadassa falou que pode ter fluidez, mas n foi isso que foi passado, ela deifniu, fixos para cada municipio, taxacao unica para todas as realidades, ignora cada especificidade de cada realidade(oxi, só passar lei municipal), ignora realidades sociais, dificulta bem estar.
- proteger populacao dos politicos que n tem tecnica de administrar, a gente tem que entender um nucleo de comissao tecnica para entender. um politico deixou de investir em educacao, reeleicao, capital politico, serve de estimulo que façam uma minima gestao eficiente, ainda assim é importante que eles quebrem a cara populacao retirarem, muleta, e que simplesmente ficam assumindo cargos publicos, orcamento fisico é uma muleta, a gente quer qeu a pop crie politicos melhores. garantir setores basicos pq ele tem que garantir o minimo de eficiencia da sua gestao.
- eles falam dodesvio de verba e heranca maldita, isso acontece em ambos os cenarios, a populacao n sabe(hadassa respondeu), corrupcao e desvio de verba acontece em ambos os cenarios. destinacao de receitas é uma parcela, existem varias despesas, creditos publicos, o endividament n tá relacionado a isso. é muito mais plausivel no cenarioa do governo a gente tenha uma muleta.
- n estabeleceria, já explicou rigidez da medida, há municipios que tem mais liberdade que outros, governo antilocal conhece a relaidade da populacao, diferente do governante e uniao, municipios com realidades especificas.
- necessidades que surgem ao longo do ano, no cenario do governo o crescimento da economia é mitigado, despsesas invisiveis, quando existe esseorçamento fixo. n tem como ele destinar orçamento apra outras areas.
- prejuizo cenario do governo vai prejudicar medidas assitencialistas, politicas assistencialistas sao negligenciados(pq?) > existe resistencia natural para pagamentos de tributos, rechacao medidas assistencialistas, num cenario de orçamento vinculado fica exaurindo nos cenarios principais, pop cobra que seja destinado apenas para aqueles setores, a rigidez orcamentaria n tem como complementar essas medidas.
  + populacao cobra, para medidas assistencialistas.
  + populacao tem direito de escolher privilegiar educacao ou saude, vc tira poder da populacao
* MG - Daniel
1. Melhjora logica redistributiva de determinados impostos, alguns tipos de impostos tendem a ser mais progressivos do que outros, mais gravosa ou intensa populacao mais rica, impostos municipais e estaduais e destinados a taxar patrimonio. quem mora em bairros mlehores paga mais, quem tem carros mais caros vai pagar tributo que vale mais.
   a. Justamente pelo fato deles incendirem, nao vao retornar pros mais ricos, fazendo algum tipo de servico publico que privilegie esses mais ricos, o IPTU deve ser usado para financiar a saude dos mais pobres.
   b. populacao mais rica tem potencial de lobby fortissimo
      a. associacao de bairros fortalecidas(ex: rj associacao da moradores da gavea)
      b. populacao tem mais dinheiro
      c. cargos em altas empresas, chantagear politicos e tals
2. volatilidade dos impostos, cenario de crise, impostos que tem arrecadacao que cai aprubtamente, impostos sobre patrimonio, caem menos abruptamente, o ultimo bem que o rico vai se dsfazer é o carro e apt, impostos ICS, ICMS, sao impostos que em periodos de crise caem abruptamente. Nos cenarios de crise mais abruptamente.
3. vc faça vinculacao mas n seja especificamente vinculada nos impostos
   a. vincula imposto que tem menos volatilidade, esses impostos n vao cair por arrecadacao.
4. inventar imposto sob os mais ricos.
* MO - Julia
1. N é onus da bancada da oposicao, que a gente vai ter gestao melhor dos interesses, n tem onus de resolver a má gestão.
2. A gente n ta debatendo só sobre tributação especificas, quase totalidade dos impostos.
3. Parte de uma perspectiva nacional, exemplo do infoslide.
4. o mundo do governo, prever esse tipo de gastos, n vai estar atendendo a esses individuos, previso do ponto de vista federal, municipios possuem especificidades regionais, sao paulo precisa de mobilidae urbana.
   a. no nordeste tem demandas muito mais urgentes relacionadas a saude e saneamento basico.
5. enderecamento, sempre vai ter uma discrepancia de capital politico, sempre vao ter uma maior popuilacao, vao ter mais cadeira, maior capaciade de votacao maior, existem demandas diferentes. estados com maior riqueza, vao ter maior capital social. acoes empresariais, possuem riqueza maior como um todo.
   a. menor atendimento dos mais vulneraveis, sofrer engessamento. to fazerndo uma pessoa que ta sofrendo mais, alem disso aprofundamento das desigualdades regioanis historicas, se eu n me preocupo necessidades dos entes mais vulneraveis, a gente tem um aumento de uma desvantagem que já existe. discrepancias paridade de vida como um todo.
6. criacao de uma justificativa maior irresponsabilidade fiscal
   a. tem municipios que n tem hospital, n porque prefeito é ruim, mas pq n tem dinheiro. a partir do momento em que a gente passa,
   b. coalizacao de prefeitos, pressionar ainda mais uniao emprestar dinheiro para esses estados.
   c. n foi provado, como a gente aumente a otimizacao dos investimentos. dao mais justificativa politica
* WG - Rafa
1. existem dois debates
   a. primeira metade. pq precisamos vincular tributos que nao sao vinculados. eles tratam necessiadde de estabelecer fixos.
2. contraprestacao necessariamente precisa de um direcionamento especifico, muito mais concentracao de poder politico. sem nenhum tipo de retorno.
3. 1g
   a. contraprestacao, necessidade, incidencia do patrimonio, aspectos particulares, democratizar isso, incidencia sobre patrimonio seja para populacao mais pobre. populacao mais pobre sofra de flutuacao. assimetrias economicas. nesse tipo de imposto, vinculacao estatal, daquilo que beneficie a populacao mais rica. todos nossos impostos sequem em tempo de crise.
   b. redistribuir isso de uma forma muito mais democratica.
4. 1o
   a. impossibilidade de politica de bonus externo, n é excludente demanda externa
   b. diferenca tributar receita vinculada e vincular imposto, quando a gente fala de tributo de receita vinculado, ato do administrador publico escolher a aplicacao de valores.
   c. municipios distintos possuem problemas distintos, a gente n precisa vincular problemas espficicos, orçamento direcionados, orçamento direcionado aprovado pelas camaras municipais.
   d. n estamos debatendo vicnulacao de taxas publicas.
5. 2o
   a. logida de influencia regional, iptu e ipva coisa que quase todo mundo paga, esse dinheiro n é revertido terceiro setor. aumentar possibilidade de corrupcao.
   b. dinheiro pode pagar salario publico, n há garantia de aplicacao.
* WO - Franco
1. Primeiras casas tratam o debate como se tivessemos fixando orcamentario numa perspectiva macro, minimo essencial pra saude, nenhum momento pq isso precisa ser feito pela destinacao direta.
2. propria logica de incentivo para que isso exista. esse candidatos se reelegem, tao querendo colocar candidato deles proprios, ou ele pode se reeleger, se a gente pensar numa logica de interior, o que a gente acaba vendo mesmo se ele n se reeleja.
3. no melhor case do 1g hadassa
   a. pior experiencia de gestao, simplificacao do funcionamento apra pessoas. o backlash como as pessoas veem os tributos, perdfe capacidade de definicao, os governos nao disseram pq que é melhor vc atribuirt essa vinculacao direta, inves da populacao possa definir aquilo que é mais vantajoso pra ela. estabelecimento numa logica federal. pessoas engajar e definir.
   b. logica do fundeb, tiozinho da padaria n entenda sobre tributo.
4. 1o
   a. ter em sao paulo de terminado tipo de demanda, tipo de habitacao e tipos de recursos, a propria razao de ser, IPTU e IPVA, discrepancia regional, o que o IPVA significa,.
   b. 2g nao consegue mostrar essa adaptacao em cada regiao.
      a. pro 2g vencer esse debate, o superfiat, os ricos tem interesse e mais força e capital politico, e eles nao provam pq que quando a gente aprova esse tipo de medida do IPTU e IPVA, mesmo que a gente n compre isso, esses ricos n vao ter mais lobby e capacidade pra eles. logica de desfazimento de patrimonio, curral eleitoral.
      b. bolsonaro quer garantir curral eleitlral, uniao n tem capacidade de aguentar iso.
      c. ricos sendo tributados sob o patrimonio, mesmo qeu a gente compre isso, é inocencia presupor que os ricos já sonegam, alem disso, donos de grandes propriedades perdao de dfivida, igrejas. e isso serve para grandes empresas. os ricos n vao ver essa volta pra eles.

* Call
- Louise: 2G > 1O > 2O > 1G
- PV: 2O > 2G > 1O > 1G
- CC: 2O > 2G > 1G > 1O
