#+TITLE: Debate01

* PM - Caio
- Tecnologia tornar mais bem informadas VS Manipulacao
- Tecnologia muito mais faceis de se manipularem
- Elas tornam as pessoas mais divididas
- Guerra politica da informacao
  + Embora as noticas possam gerar algum tipo de utilidade em termos de confirmacao de crenca, propagacao de propaganda, isso impoe custos privados e tambem custos sociais, um custo social para o consumidir é a dessiminacao da desinformacao de buscarem a verdade.
  + 2018 polarizacao, para os consumidores escolherem um candidato eleitoral, as ferramentas ciberneticas sao usadas para criar efeitos psicologicos e os provaveis efeitos colaterais dessas atividades incluem o compromentimento da fidelidade das informacoes, semeando discordia.
- Processo democratico
  + O custo marginal social de noticias falsas é exponencial, quando vc compartilah uma noticia de nicho, quando esse mesmo artigo sao circuladas no facebook, essa externalidade negativa se multiplica. como resultado disso a quantidade demandada de noticias pode aumentar na temporada de eleicoes. A quantidade de noticias podem diminuir porque as pessoas tem menos confianca na midia tradicional.
  + Cria um cenario em que as grandes midias sao golpistas, recebia porrada dos dois lados dentro das redes sociais, nas redes sociais que promove mais desinformacao.
  + Polarizacao
    - Vc tem uma dificuldade de mudar de ideia com base no seu grau de instrucao. Aumento de polarizacao e a segunda é a empatia que poderia ser traziada como efeito positivo.
* LO - Jss
- Mais forte area de vida publica. Espaço vitualmente frequentado pela maioria, pertencimento, acao, estar presente.
- Inegavel que as redes sociais, agora publica, discussao e opinar, varias pessoas opinam, politicos podem ver e que de fato ta falando.
- Ascencao é natural, importante, e interesse politico, participacao politica maior metrica desse debate.
  + Agregar, classes mais vulneraveis, facilitacao da linguagem, adaptacao ao meio do que a gente ta frequentando, as redes sociais é linguagem mais ismples. Construcao da linguagem as redes sao superiores.
  + Buscar engajamento
    - POliticos buscando interesse e engajamento nas redes sociais, eles vao adapatar a sua linguagem. Pessoas mais vulneraveis consigam participar. agr a gente tem mais politicos se esforçando por umc ontato que n havia a 20 anos. ascencao da caracteristicas como motor disso. so politicos como trump faziam esse tipo de coisa, n é mais a extrema-direita, sao politicos de todas as classes, só aconteceu pela ascencao das redes. contato maior, politizacao maior. ampliacao do alcance, n só pela linguagem como desitelizacao da politica pelas proprias pessoas.
    - Atens politica era elitizxada, agr a gente tem a mudança, a politica vista antgimaente como inascecivel, agregando o fato de tornar mais proximo, tornar mais interessada, antes era afastamento, a rede social é um cenario de agora, sempre participe, o fato de vc podr comentar diretamente com o politico, faz vc fazer parte daquela historia, um rpobelma atual, democracias morrendo, as pessoas naos se vem fazendo parte.
    - Interesse da populacao pelo politico que ela acompanha, fiscalizacao
    - fiscalizacao, vc sabe que o deputado n tá cumprindo com o que ele prometeu. no nosso lado a gente teve o fim do monopolio da palavra, agr a gente tem uma pulverizacao total dos candidatos que vc pode conhecer, atens a gente tinha um total consenso do mainstream. importante pra logica partidaria. PSOL e NOVO. Na ultima eleicao a gente viu essa inversao, tipo o alckmin tinha todo o tempo de tv do mundo. Ex: Boulos 17 segundos na TV.
    - Monopolio da palavra quebrado, maquina publica, oposicao pode contraria nas redes sociais.
* DPM - Caio
- esse papel de agora é comprometido, porque nem todo mundo tem acesso a internet, muita gente tem acesso ao celular mas por exemplo vc tem as comunidades ribeirinhas, no sul e sudeste, se as pessoas subirem pro norte e nordeste, redes sociais que promovem discussao ampla, esa internet essas coisas, qntd de informacaoes nao chegam. essa discussao n cehga a discussao pra quem mais precisam.(pq é pior que o statrus quo?)
- rede sepecifica de filtro, começa a se miscuir? redes sociais, esse nicho vai continuar lá, vc n vai promover informacao, pq vc vai acompanhar essas pessoas, nem todas as pewssoas sao extremamente politizadas, nem se insteressam(pq é pior que o status uqo?) ele trabalha por muito tempo, n tem tempo de procurar politico, n tem tempo de chegar nas redes sociais.
- poi jess > ampliando o meio, n diminuindo, mais chance deesse meio politico chegar. -> entretanto, as pessoas que estoa na periferia nao conseguem usar redes sociais, minha mae que é analfabeta, inclusao digital daquela pessoa. na televisao tem uma maior fatualidade, quando aquele politico vem ate vc, encarnado de carne e osso, faz mais sentido vc conhecelo aquela internet.
- empatia > te aproxima das pessoas, no sentido que quando vc se identifica com causas de determinado politico, de quando vc se aproxima emocionalmente, vc passa a rejeitar veementemente pontos de vista.
- coemcou a falar de aves, e vegano, n entendi
* DLO - Bruno
- contrafactual do lado do governo, meios oficiais, forma de comunicacao muito mais limitada, chega uma quantidade muito menor de pessoas, no nosso lado temos uma quantidade muito maior, muito mais elitizada, beneficio é conhecer seu politico melhor, tem muitos assuntos que os politicos n abordam nenhum momento, legisladores eleitos ocm uma pauta unica, ate vc conhecer ele pelo mal, vc ta mais confianca de votar naquele politico, sem as redes sociais aquilo seria completamente obscuro, muito fraco, tem uma populacao muito mais engajada, politicos falam sobre assuntos relevantes. coisas relevantes que estao acontecendo.
- seus seguidores ficam miuto mais informados e mtu mais particpantes da democracia, reformas que estao passando, sa omtu importantes populacao ter.
- é melhor e mais justo debate entre politicos seja feito na internet, as pessoas estao na internet, o debate tem que acontecer onde a maioria das pessoas estao, mais de 90% da populacao term interet tem celular, tem iphone, no mundo do governo, dificlmente vai ter acessoa a outros meios, aida vai continuar existindo.
- poi caio >
- se vc restringe apenas aos meios oficiais, como a jessika ja trouxe, sao mtu mais restritos a quem tem mais poder politico, boulos com varios minutos na tv, coisas que passam na tv por propaganda governamental, sao coisas do governo. oposicao n tem isso.
- 1 gov se cofunde como a internet gera fake news e polarizacao > esse debate n é sobre discutir politica e falar na internet, esse debate é sobre os politicos estarem na internet, a maior parte das fake news, n foram posts de politicos, mas foram pessoas discutindo politicos na internet. canais de influenciadores, montagens vilarizadas, esse tipo de coisa existe nos dois lados.
- grande parte das fake news sao sobre politicos, mesmo nas mais toscas, esas fakew news, muita vezes sao mentiras, ate os politicos estarem bem nas redes sociais, se defendendo das fake news, se torna mtu mais claro o posicionamento deles. evitar a maior  parte de fakew news,
* MG - Carol
- informacao n só esta mais facil de ser acessada, e manipulada, quando deixamos a massas merce escritorios partidarios.
- metrica > qual cenario eleitor mais beneficiado escolha do candidato
- fomento do uso das fake news
  + eleitor medio, n é totalmente colocada dentro das eleicoes politicas, distincao entre informacao verdadeira e mentirosa
    - a gente achava que a populacao tava preparada mas ela n tava, plataformas sem moderacao, espaços sao moderados, candidato vai se sentir coagido a nao mandar fake news
    - candidatos que fazem show e espetaculo na tv, mas n conseguem ser bem votados.
  + nas redes sociais a gente tem o poder de dizer o que quiser. os politicos só pegaram a mesma forma marketeria de fazer politica, e passaram pras redes sociais, nas midias tradicionais a gente tem um mecanismo de moderacao. eles criam fake news, quem tem o twitter do trump e do bolsonaro sabe.
- potencializacao das bolhas eleitorais
  + n é democratizacao da politica, n é democratizacao do espaco de fala, uso de plataforma super poderosa, que a gente n pode afirmar que é uma informacao de qualidade, vai se inflamar, potencializando a emocionalidade do eleitor brasileiro.
  + a questao n é ser de direita ou esquerda, potencializar os problemas, fazer as bolhas ainda mais fechadas, elas alienem ainda mais a populacao, essa populacao fica totalmente alienada naquele discurso, internaliza aquilo, aquele cidadao nem vai ter a capaciadde critica, quando aquele candidato começar a ir no caminho contrario, eleitor medio n vai, o eleitor n vai estar aqui fiscalizando, as pessoas vao ficar alienadas, a culpa vai ser de qualquer pessoa que aquele candidato diz que é.
- fomenta o uso da fake news, manutencao dela, n tem veiculo moderador, potencializar a existencia das bolhas eleitorais, alienar o eleitor.
* MO - Eduardo Denis
- fomento do uso das fake news > sao os veiculos de impresnsa veiculados ao candidato, e n as redes sociais do politico em si, ele iria se queimar, n necessariamente essas informacaoes sao só no twitter, n só na rede social, na franca, um bagulho de crianca na rua.
- ascencao das redes sociais, auxliar o ciclo vicioso na maquina publica. coroneis atuam ao maximo de manter no poder, os alves, magalhaes neto, familia covas, perspectiva de dinheiro de fundo partidario, tempo de televisao, os candidatos tradicionais se beneficiam muito mais, em detrimento das novas renoavacoes politicas, intencoes mais nobres, essa ascencao trouxe a decadencia dos politicos tradicionais, cleptocracia, familia henrique alves, sempre se utilizou os mesmos recursos, justamente pra chegarem ao poder, de forma excusa realizar os famosas esquemas de corrupacao. trouxe candidatos novos, NOVO e PSOL, e nao paneas um problema em relacao a maquina publica, o jogo democratico é manipulado, centralizacao por parte da midia.
- O prefeito elegido como candidato da midia paulista, grande silencio da midia tradicional em relacao a esse candidato, todo candidato precisa ser alvo de escrutinio puliboc e sabatina publica, a midia escolhe silenciosamento seu candidato, seletividade nas crtiticas, certos candidatos sao muito mais leninentes as suas propostas.
- No EUA é mais incisivo, o NY Tames fez um editorial formal ao joe biden, com certeza vao ser muito mais lenientes em relacao aos outros, Brasil e Aregntina é extremamwente perigoso a midia tradicional se aliando, esse candidato tentar beneficiar a midia, realizar subsidios, a partida troca de favores. se aliando na perspectiva de permanecer no poder as mesmas figuras.
  + as midias mesmo polarizando, é um ambiente intelectualmente muito mais livre, nas midias sociais a relacao é reflexiva, deixam formacao politica. dentro dessa perspectiva, atuacao de figuras politicas controversas, esses politicos se tornam veradeiras vidraças, Trump e Bolsonaro. ver que o bolsonaro é deploravel.
* WG - Querino
- a gente vai fingir que a rede do candidato que é utliizada pra disseminar desinformacao, isso quebra toda aideia da mocao em si.
- ocore fake news em outros locais, moderacao, inibe mas n impede, Lula foi mentir fora do pais, mas n alienar os eleitores brasileiros.
- O jogo democratico é centralizado dentro da midia tradicional, as redes sao perfeitas e autoreguladas, problema dos dois cenarios, no cenario da oposicao, muito mais impactante, muito mais danosas no cenario em que ela nao existe.
- POI Jess -> a moderacao de conteudo twitter apagando, politicos tem medo de punicaoVSolavo de carvalho -> a acao do twitter é algo isolado, depois que o problema já foi criado, a gente tbm sabe que os influenciadores sao fruto do olavo, nao vao parar agora(esse é o ponto) mesmo que aquele post seja apagado, aquele cidadao medio vai continuar consuimindo aquilo, atacar a midia que ta falando a verdade.
- n proibimos politicos enquanto individuos, de verificarem as redes sociais, n devem fazer uso institucional das redes soiciais, fazer controle e mkt danoso, n é só bolsonaro n é só trump. politicos viram que funciona.
- facilitacao da linguagem > só que aqui a gente defendfe que a facilitacao seja levada meios que já existem(vc n pode fazre isso), buscar o engajamento é algo que politicos vao fazer, n defendemos o atrasado, n defendemos o uso das midias sociais sem menos controle.
- maior politizacao da populacao como vai ter maior politizacao usada majoritariamente pra espalhar fake news, politicos usarem as plataformas pra fuder oeleitorado
- beneficios de conhecer melhor o politico > o eleitor que vai lá na rede social e ver se condiz, é o mesmo eleitor, que iria atras da agenda politca do site, pra ver se o que o politico faz, o eleitor medio n vai pra rede social.
- fake news n foram politicos que botraram(fontes cabneça do visnadi porra alice) > carluxo compartilhando fake news. o partido cria, o mkt cria e usa os veiculos ofoiciais.
- 1gov vs 2gov > apontamos os perigos da manipulacao, manutencao das fake news. bolhas eleitorais. utilizamos a metrica o melhor cenario para fazer escolha eleitoral.
* WO - Babi
- a auto determinacao do elitorado vs analise da midia tradicional vem pro nosso lado, todo candidato rpecisa ser alvo de escrutinio publico, 2g fala que o eleitor medio n pesquisa tanto. eleitor medio n ficam assistindo propaganda eleitoral de forma interesada, ver tudo que todo mundo quer dizer, escutar o candidato que já tá querendo votar. 17 segundos n conhecer as propostas. mais provavel de vc conhecer os candidatos que fizeram coligacoes partidarias.
- no cenario do nordeste eles tem mais dinheiro para compar espaco na eleicao, mais chance de se eleger. maior tempo de tv e tals.
- cenario do nordeste, coroneilismo hhistorcio, mas n muda, pq n tinha redes sociais para pessoas terem amplo acesso. nos provamos que é possivel quantidade e qualidade de informacao, democratizacao é possivel, alienacao e fomento de fake news, é mais dificil de acontecer, todo mundo falando nas redes sociais. precisa de menos dinheiro pra falar nas redes sociais. bolsonaro se elegeu com um dinheiro minimo. vc precisa de um dinheiro muito infimo. comparado com tempo de televisao, muita coisa. n preciso gastar nada. é um ambiente democratico.
- mtu mais provavel pessoas conheçam meu conteudo com menos dinheiro, pq isso é menos alienante? pq todo mundo tem acesso a fazer a mesma coisa, é menos provavel que eu aliene, pq todo mundo pode alienar. ninguem pode fazer grande fundo partidario. ambiente livre e democratico que o outro. vai fomentar menos fake news, pq eu como politica entro nas redes sociais, a midia tradicional existem outras midias que sao contra qeu vao escrutinar essa fake news que eu falei, outros candidatos nas redes sociais vao falar mal do que eu disse, vai gerar um debate nas proprias redes sociais.
- debate moderado vs debate combater livrimente, isso é mtu posiitivo politicos virarem vidraças, alvo de escrutinio publico
- midia tradicional se recusa a fazer debates, importante a redes sociais. refem das midias tradicionais.
- politicos tem capacidade de comentar livremente suas opinioes, é importante pratodo mundo fazer.
* Call
- Iandra: 2G > 1O > 2O > 1G
- Marina: 1O > 2G > 2O > 1G
- CC: 1O > 2O > 2G > 1G
