#+TITLE: Semi

* PM - Julia
1. Maior grau ou menor grau
   a. Esse tipo de grana, doam grandes quantidades alivia a vida de algumas pessoas, alivia de forma temporaria, nao resolve todo o problema.
   b. Ação perene e ampla, só quem consegue de forma completa e no longo prazo nao apenas aliviar, é o estado, uma maquina tem o compromisso, colocando os investimentos, no que vai trazer mais propagando ou mkt positivo para si.
      a. É mlehor viver exclusivamente no estado ou nao
      b. Incentivo retira do estado a capaciadde de escolher
         a. Essas pessoas vao simplesmente, fazer esse tipo de doacao e ganhar isenção fiscal, excluir a capacidade dele mesmo. Estado tem maior capacidade quanto também é que a gente dispersa a noção de responsabilidade do estado.
         b. O estado se excusa de agir em determinadas regioes. Criacao de responsabilidade moral como um todo. Lastro da responsabilidade eterna, tem mais capacidade, maquina estatal tem mais capacidade como um todo. AProveitar da propria estrutura que ele já tem.
         c. A gente n é contra a filantropia, mas tirar a visao de que é sempre um fim. Agente retirar da jogada os oultraricos. Que sao agentes que acomulam capital e riqueza ilegitima.
         d. Estruturas que se equiparam da força dos estados.
         e. Reverter ideia de opreção. Ação extremamente publicizada. Atitudes que todo mundo vai ver e todo mundo vai cometer, essas pessoas passam a ser vistas como bonzinhas nessa logica social. Autopromoção. A gente ta fazendo essas proprias pessoas. Fazer com que as pesosas nao enxerguem.
         f. Essas pessaos acabam recebendo um perdão dentro da moral publica.
         g. Se existe um acumulo proporcional de riquezas, garante a continuidade de todas as desigualdades. Esse tipo de empresa. Capital politico
         h. Logica valorativa. Dentro das regioes, dentro de locais, a gente tem uma situacao, que o que aquelas pessoas representam. Processo de exploracao ainda maior
         i. Ideal de caridade, a igreja, vendem como algo positivo.
         j.
* LO - Diego
1. Filantropia n é somente doação. Filantropia é atuacao da sociedade privada, instituicoes privadas e autonomas e sem ligacao com estado, atuam nao somente onde o estado nao atua, atua beneficios sociais especificos. Todo mote da bancada de primeiro governo é ruim em si
2. Ainda que a filantropia como doacao, ainda sim, é efetivo, defender politicas publicas que estimulem a filantropia. acoes efetivas do governo, estimulam ganhos sociais, o egoismo humano, as pessoas podem ganhar uma imagem melhorada doando, se por acaso elas ganham politicas de estimulo, isso em si é uma coisa que o governo fazer o ersultado é uma melhoria social efetiva, usar os grands bilionarios para causas importantes.
   a. Mesmo no cenario do governo a gente consegue usar o egoismo humano em prol da propria sociedade
3. Estado tem condicoes de atuar onde elas devem atuar, necessarioa uma autoorganizacao da sociedade, grande peso que o estado tem, o estado tem uma funcao social, garantir saude, educacao, principalmente no canrio brasileiro, a acao do estado para resolver esses problemas, o que acontece é que o estado é mtu onerado. dentro dessa perspectiva é melhro uma autoorganizacao da sociedade,  atiar pmde p estado n atua.
   a. atuacao onde o estado é ausente > estado n consegue, estado tem dificuldade territorial, zonas rurais, sao regioes onde vc n tem celulas do estado, as acoes filantropicas conseguem atingir mais o territorio do proprio estado, vc tem filantropias, as proprias celulas de instituicoes privadas sao mtu maiores, o estado pode estimular isso ai para problema de alcance. polos de atuacao setorizados, nao sao concentrados numa acao social efetiva. setores que podem atuar mitigacao de desastres ambientais. vc tem uma acao social mais setorizada.(n entendi) esse nicho tbm fortalece a presenca do estado, o estado vai estimular a propria sociedade se autoorganize. desoneracao do proprio estado
   b. POI JUlia > Estado pressionado a resolver esse probvlema > Capacidade, vcs nao provam se o estado realmente tem capacidade, porção territorial gigantesca, areas isoladas que ficam a deriva. organizacoes privadas. essas regioes vao continuar sem a propria ausencia do estado.
   c. perspectiva da desoneração do proprio estado, essas inst nao possuem fins lucrativos, pedem auxilio minimo do proprio estado, ou qualquer outro tipo de ajuda, desonera a acao do proprio estado. acao tao gigantesca para um onus tao grande. facilitar o alcance do estado.
* DPM - Franco
1. a genbte concede de entidades privadas. melhor caso da 1op é logica de urgencia, privando pessoas do minimo de dignidade, falar bill gates e tirar logica de diarreia, existe problema estrutural que precisa ser resolvido, logica moral e prag pq a gente vence
2. n mostrar como o problema é mais facilmente resolvido. bill gates e warren buffet, eles tem literalmente organizacaoes, contratos que concordam em fazer um acordo n doem para o estado diretamente, n acreditma que os entes estatais sejam eficientes, cordenam entre si, a caoacudade deles é supranacional, conseguem controlar com base nos interesses pra onde vai esse tipo de filantroipia, logica de autointeresse, legitimacao da injustica, restricao geografica é necessaria, facilite a entrada daqueles paises, possam extrair minerios, ter materia prima naquele local, mantendo contexto de desemprego estrutural mundial. Jeff Bezos valor das acoes crescendo desproporcionalmente
3. esses caras querem manter os proprios beneficios, manter o imperio, colocam os proprios filhos para serem chefes de fundacoes. eles fazem isso para fugir de serem taxados, fundacao edson queiroz, o que ela faz é se colocar enqunanto uma fundacao, cobrando valores autissimos, eles criam numa escala, um contexto que eles n sao taxados, mas o mais relevante, ela n cria um mecanismo de cobrança, de que isso é completamente ilegitimo, n existe justificatriva alguem colocar qualquer riqueza, a maior prova de uma forma geral.
4. as familias italianas mais ricas de 500 anos atras sao as mesmas de hoje em dia, quantidade de dinheiro tao gigantesca, n tenham incentivos para cobrar, no nosso comparativo as pessoas mais facilmente entendem taxacao das grandes fortunas, lucros e dividendois. de uma forma geral esses agentes n tem incentivo para o que é mais bem intencionado
5. se eles forem bem intencionado, ele pode engajar com a propria acao estatal, cobrar o proprio estado, como a populacao deve cobrar, garantire que todo aquele dinheiro seja redistribuido, vs agente que individualmente faz isso com base em seus proprios interesse.
   a. mesmo no curto prazo, romper esse ciclo de opressao estrutural, existem cum contexto de legitimacao, pessoas sao exploradas diriamente, mark zuckberg se apropriam da força de trabalho daquelas pesoas, continuam achando que o estado é aquele agente que n quer fazer nada, garantir que as instituicoes engajem cada vez mais.proprio empoderamento delas. é que a gente vai conseguir romper com todo esse ciclo.
* DLO - Dek
1. Governo colocar politicas que desincentivem filantropia, na pratica quando o govern oconseguir, sociedade tao cega quanto qualquer outro cenario, desassitidas, n consegue resolver os problemas.
2. relevante rsolver um problema social, n bpode botar o povo pra sofrer
3. a filantropia sao bilionarios que age na africa, filantropia local, brasil, venezuela, mexico, n se trata só de grandes bilionarios, pequenas instituicoes de musica, futebol, acoes do governo vao impactar todo mundo(mas é limitar n acabar) conseguem ser uma forma legitima. dominadas por contextos de trafico, o estado n consegue entrar nesses setores ou é com a politica ou é matando, n consegue fazer nada lá, o trafico que consegue assumir essas posturas, o trafico consegue assumir.
4. filantropia é um meio legalizado pel oestado, criar solucoes eficientes para criar pelo proprio estado. deixo a merce de todos essses stores de trafico.
5. estado precisa reconhecer setores que ele tradicionalmente n consegue chegar, ele n consegue entrar lá, é parte dfa funcao dele reconehcer que existem setors que ele n consegue entrar, n consegue agirr, a partir da hora que ele impede, n somente de forma macro, da forma pequena, ele impede esse cenario de resolucao de problemas, estado que incentiva a filantropia, acao individual, problemas qu o estado n consegue resolver. estado como um todo que desincentiva resolucao indiviudal de problemas, sociedade mais instrumentalizada pelo proprio estado.
   a. na pratica a populacao n vai ficar mais consciente, mas menos assistida, essas politicas sejam icnentivadas para que nesse momento elas consigam ser supridas, sistema soscial como um todo menos incentivo dos problemas.
6. grandes ricos
   a. processo susb maquina publica
   b. insetir em locais
   c. dinheiro demais é errado
   d. vc tem dinheiro para caramba vou impedir de vc usar melhor seu dinheiro para sua sociedade(imposto) criar desincentivos fazer algo, n vai fazer mais.
   e. eles usam para reocnhecimento do nome, para vender a propria imagem(ok a gente concede isso) e n há um problema disso(mas o franco trouxe outros problemas),  cenario que a gente precisa resolver os problemas de agora, problemas que sao resolvidos de ofrma menor, n existe cenario do governo com sociedade que desincentiva a filantropia e melhor resolucao de problemas sociais.
* MG - Jess
1. capaciadde do estado é maior e mtu maior. toda fortuna dos dois maiores bilionarios do mundo n ultrapassa a arrecadacao nem do estado brasileiro, sequer vao doar todo esse valor, possibilidade do estado de gerar mudanças, o que eles doam é uma parte pifia em relacao ao que eles tem.  esse pouco já seria
2. mecanismo que a filantriopia usa para causar sensacoes que o ogverno mostra
   a. midia, publicidade, mostrar isso em redes sociais, polarizar ao maximo par autopromogcao, é mtas vezes pessoal, foco é capitalismo predatorio, mostrar que o capitalismo n é inimigo dos povos mas quem vai os salvar. para de fato gerar uma ideia
      a. ricos bons pro pobre
      b. problema ta sendo resolvido
      c. confiem no mercado, podem ficar tranquilos
   b. inibe buscar modificacoes, modificacoes politicas, atrapalham politicos que mostram esses problemas, quando politicos tipo boulos mostrando modificacoes estruturais, menor capacidade de mobilizacao. estao na verdade maquiando o problema. as empresas tbm fazem issos para mitigar cirticas (lidam com o mei ambitente tipo a vale e rockefeller, ou coca-cola) eles tentam mitigar por essa aparencia, em democracias que eles tem problema com o voto.
   c. o grande questoinamento, um estado que n quer mudar realidade, isso é bom, ele tira proveito de fazer de contas que as coisas tao sendo resolvidas(midia mecanismo mas juilia falou)
   d. declaracoes mais explicitas da populacao, correlacao entre filantropia e corrupcao, declaracoes de filantorpia tendenciosamente feitas para mostrar que empresa ta mudando alguma coisa ex: lobby e populismo crivella, agencias da universal, se mostrar como um grande filantropo
   e. filantropia é feita por compra de arte, compra por arte, tem abonos fiscais autissimos, pra simplesmente ter abono fiscal e ainda manter patrimonio, melhjor dos dois mundos, cria um onus para os cofres publicos.
   f. salvador branco, o neocolonialismo primeira forma de iflantriopia do mundo, culturalmente pior, danod da filantropia internacional, ganham isencao, venda de um mundo ideal, acao é ajudar ate um ponto, eles tbm vao instrumentalizar e fieis, s;o jeus é o caminho, e no final gerar ao apagamento cultural
   g. POI GUi > pq ela deixar de fazer filantropia deixar de > eles n vao mais poder se gavbar, n vai mais poder maquiar, simplesmente por estarem ajudando, n vao mais poder usar desse mecanismo, estado que vai estar fazendo, as pessoas vao cobrar mais, privatizar solucoes n é horrivel, fragilizacao do estado de bem estar social, isso vai ser ainda mais agravado. os danos sao muito ruins. um cara deses n quer que o boulos seja prefeito de sao paulo.
* MO - Alice
1. Efeitos psicologicos gera nos doadores e receptores
   a. Uniao populacional e perspectiva
   b. Doadores vivem numa logica egoista, pelo capitalismo, logica cada um por si, só vivo pra mim mesmo
   c. a gente n acha que eles teriam vontade se unir se nao no cenario que leles possam doar, a partir do momento em que eles doam, mais possiblidade de se verem como comunidade, eles podem se enxergar como pessoas que fazem parte da propria sociedade.
   d. logica nos potenciais doadores, mesmo se o bill gates doando por interesxse proprio, sao role model para a populacao, vistos como pessoa de sucesso, cidadao se sente mais pro comundade, mesmo que n entenda a logica, ele ve, eu me preocupar com a minha comudade é bom.
      a. no cenario do governo a gente tem cada uim por si, quando a gente tem esses bilionarios, pessoas se ajudarem no dia adia, veem com um valor socialmente bom, coibido pelo prporio estado.
      b. receptor tem um estado que já é abandonado pelo proprio estado, quando o estado ta coibindo receber ajuda, gera uma revolta dessas pesoas, auimento margem da ordem social, pior que um senso de salvador branco, onus eu já sou neglgenciado, vontade social de resolver essas coisas.
      c. esquecer a olpressao por meio da filantropia > as pessoas n vao se resoltar com o rico, mas se revoltar contra o estado, ele n tem culpa ou obrigacao nenhuma, ele ate quer ajuda, ele controlando a midia, ele ate poderia, mas o estado malvado ta sendo contra os ricos.
      d. mecanismo crivel, vao de fato, olhar porque que o rico ta fazendo alguma coisa ruim, olhar um estado que ta sendo contra essas pessoas que poderiam
      e. poi 1g > as pessoas cobrando mais o estado > pq as pessoas vao cobrar o estado, elas podem cobrar o estado pra serem mais leninentes com os ricos. tira o foco das pessaos das riquezas, e muda o foco deles para outro agente, é mais provavel.
2. Efeitos praticos
   a. vontrade politica fazer ese tipo de coisa
   b. estado ja n chega nesse tipo de lugares, tortua desnecessaria, que n é culpa desas pessoas
   c. paises que recebem mtu mais dinheiro do que eles tem pra arrecadar, tipo o mali, estado que n tem populacao consumo diferente, vc deixa o mais vulneravel ainda mais vulneravel.
   d. estado que de fato faz as coisas, essas pessaos contribuam em situacoes de crise, estado n tem vontade politica determinadas areas, bolsonaro n tem incentivo nenhum para ajudar mulheres e lgbts, n estao no proprio escopo do proprio estado em si. mais grupos sao atendidos quando é difuso.
* WG - Bruno
1. Pq filantropia n funciona
   a. OS POBRES sao maioria no mundo, n falta apenas dinheiro, implementacoes de infraestrutura masaiva, reformas tributarias profundas, amplas politicas de acesso a politica uinversal, falta coisas que a filantropia jamais poderia fazer, porcentasgem alta de um PIB de um pais. filantropia é casquinha da ponta do iceberg. irrelevante dentro do problemas que nos temos
   b. filantropia interessao de autopormocao ou no minimo visibilidade, nulka dos necessidades que sabem de alguma coisa.
   c. estado n consegue chegar em alguns lugares, estado tem mtu mais dinheiro para chegar em alguns lugares, isso é possigvel o que falta é vontade politica. incentivo soberano que e'popular.
   d. atualmente a populacao permite que o estado tenha esse comportamento, o estado deveria ser execrado pela pop pra manter uma nova despesa, a mentalidade popular n é que as necessidades desas pessoas sao respo absoluta de todos.
   e. filantropia carrega uma filosofia, somos os agentes de mudança, nosas cotntribuicao nao importa, ver essas coisas como coisas que as pessoas devem criar, engajando com o que alice trouxe, em qualquer mundo a dignidade humana é vista como importante, num mundo sem filantropia, essa interpretacao n seria possivel, o estado seria o a gente unico de mudanca, se alguma pessoa passa foma, o estado é assassino necessariemten, apenas nesse mundo, essa filosofia é a filosofia que esta em vigor. usar todos os seus recursos, mecanismo de resp é inift
   f. poi dek > a logica é do gov, hj em dia o cidadao deixa de ver que existe tanta fome no mundo pq o bil gates acaba com ofoem no mundo > problemas mais profundos da humanidade é uma resposanbilidade de todos, isso é uma completa ilusao, estado é assasino, a gente corrobora com isso,. as pessoas n tem a nocao que o estado tem responsabilidade absoulta. filantropia arrega que isso é responsabildiade coletiva, beneficio da filantroipia é minimo.
   g. frequentemente essas filantropias sao feitas por bilionarios, elas criam um mecanismo de gratidao, contribuicao significativa, essas pessaos essaes bilionarios sao responsavbeis pelas mazelas do mundo.
   h. a filantropia n funciona, n é efetiva, carrega uma filosifa, desresponsabiliza o estado
* WO - Guilherme
1. Logica falsa governo, impede o estado de estar atuando naquele local em especifico, governo bane filantropia, é basicamente condenar aquelas pessoas a sofrer duplamente, o unico comparativo, logca  que o estado é mais eficaz.
   a. mensagem fica, qual ente é mais eficaz.
      a. todas logicas dependem de como pop ve medida, a logica da jess é tudo baseado em mensagem, se toda caracterizacao da jess é que os ricos controlam a midia, perceba que o governo nunca mostra, ricos controlam jornais,  parcela de politicos e sistema de educacao, isso n tira esse controle. n é o suficiente para tirar todo o controle. se essas pessaos bilionarias ou muito ricas.
      b. Estado impede de ser feita > veja aqui o que oestado esta fazendo. eu em toda bondade do meu ser poderia estar te ajudando, mas o estado esta me impedindo, culpabilizacao é sobre o estado mas n sobre pessoas ricas, n adianta que vc só faz todo mundo ficar mais puto com o estado, n adianta se o governo acha imoral ou nao. pq que efetivamente esse dinheiro seja usado pelas filantropias
         a. comparacao n é tao igualitaria > 500 reais filantropia VS 500 reais usados pelo estado > logica de buracracia, folha de pagamento, fazem com que aquele dinheiro seja menor utilizado, apesar que eu concordar que ele deveria, estado n é uma entidade mistica, estado mesma elite mesquinha que o governo tanto repudia.
            a. os paises n tem politicas de estado mas de governo, boa parte das vezes o estado n tem essa acao perene e longiqua, cada politico tem seu proprio pano de poder, nenhum politico tem incentivo de politicas a longo prazo, o cara varios anos depois. politicos sao tao egoistas como todo o resto. sem essa filantropia esse dinheiro estaria indo pro estado.
            b. tax haven e loop na lei, um pouco desse dinheiro chega no estado.
            c. poi jess > rico n teria interesse de desastibiolizar o estado e sua segurança -> se os ricos dependem do estado, relacao promiscua privado e publico, esses politicos já estao dependem.
            d. essas mudancas no status quo. n tem problema de politicagem, mesmo n sendo feito no melhor interesse do povo. EUA n pode fazer projetos na africa, logica de longevidade, org filantriopicas projetos que n sao perenes, bill e melidna gates é sanaematno. n tem constante mudança de governo.
