#+TITLE: Debate03

* PM - Daniel
- N é sobre medida que vai ser implementada, n vai ter consequencias praticas na terra
- Qual a medida melhor para que avaliemos? A ou B
- Status quo, ordem capitalista, desigualdade intrinseca ao andamento, determinadas pessoas tenham algumas vantagens ouras pessoas vivam a mercê. As motivações e intenções estão dentro desse escopo chamado mundo capitalista.
- Sistema A é o meio mais legitimo
  + Pseudoconcretude, a partirdo momento em que voce esta olhando para o sistema A como otica de avaliacao, mais legitimo, coisa que nao depende de consequencias práticas. Nós estamos fazendo um tipo de filtração. Mecanização, o mundo vive de pessoas egoistas. Valorizar pessoas que não tem as condições concretas e materiais para ajudar o mundo utilitaritamente.
  + Sistema B é desigual per si. > SIstema B pessoas precisam de qualidade materiais para conseguir promover esse tipo de consequências.
  + No sistema A a gente tá dando a possibilidade para as pessoas que não tem esse tipo de maximibzação, as proprias pessoas pobres se juntam e se ajudam mutualmente, a intenção ela é boa, mas a maximização da felicidade não é possível.
  + Sistema A dá a mera possibilidade de todo mundo entrar no sistema.
  + POI Hadassa -> Não nada a ver pessoas pobres podem se fazer feliz, mas na capacidade de fazer outra vida feliz se não a minha -> Valorizar a intenção ou os valores práticos de maximizar a felicidade. Em detrimento das pessoas que são pobres.
- Ao escolher o Sistema B estaremos legitimando pessoas que ferem a dignidade humana, midialização do voluntarismo, não indica que você está adepto a essa causa, por conta do egoismo as pessoas elas querem acender socialmente, no sentido de ser limpinho.
  + Ferimento da dignidade humana, no lado da oposição a gente legitima o uso do ser humano como um meio. Vai estar aumentando a felicidade de um determinado grupo. Usando seres humanos como um meio para chegar a um determinado fim. Ex: Escravidão, gerou impacto a uma determinada classe. Mas isso esta vinculado a retirada de humanidade para algumas pessoas.
* LO - Takerou
- O caminho pro inferno está cheio de boas intenções lol
- O sistema A é o que mais injustiça as pessoas.
- O juizo de valor moral é muito relativo, cultura, geografia, e nos queriamos lançar uma pergunta, com ojulgar boas intenções se o valor é relativo. Impossivel de fazer de forma justa, porque algo que é bom para uma pessoa não é necessariamente bom pra todo mundo.
- POI Daniel -> Não tem debate pro governo > Essa parte de definição de como julgar o valor moral era algo que o primeiro ministro deveria ter feito. Como com toda essa relatividade moral nós julgariamos essas pessoas de forma justa. Seria algo extremamente injusto. Pessoas que praticam atrocidades com base em boas intenções. Cidadãos de bem. Querem proteger a familia tradicional, o cristianismo, e caralho a quatro.
- Complexidade psicológica do ser humano
  + Muita zona cinxa, ninguem é bom e ruim, as pessoas tem valores paradoxais.
  + O proprio valor de viver em sociedade é suprimir os sentimentos em prol de um bem estar coletivo. Não é necessariamente egoismo.
  + Mesmo se eu tiver com vontade de matar meu vizinho eu não vou fazer isso.
  + O ser humano se julga pela ação e pelas consequências. Atitude natural do ser humano. Com isso a gente pode pensar, como esse ato é do dia a dia a maioria das pessoas agem dessa forma, fazendo algumas bondades, mas que não estão necessariamente sentindo um zelo. E o que na verdade refuta esse ponto do pm que pessoas mais pobres nao teriam como maximizar a felicidade coletiva. pessoas pobrem podem tambem fazer varios atos. que vao fazendo bem pelas pessoas. dando um frescor a vida alheia.
- Sistema A seria injusto, a maioria do ser humano age da forma como o sistema B funciona. E não da forma A. O sistema A que seria o mais desigual. Já que se pegarmos essa métrica, o A premia pessoas que cometem atrocidades em nome de boas intenções. Quem consegue cometer essas coisas horriveis sao as pessoas que cometem atrocidades.
* DPM - Lais
- Oposicao tenta mostrar como o nosso cenario nao se aplica, mas nao mostra como  o cenario deles de mostrar pessoas sem boas intenções é bom.
- Pessoas com recursos poderem fazer mais diferença na prática. As pessoas não sabem o qeu vai acontecer depois da morte, então não vai influenciar nada. Por meio de caridades as pessoas que sao mais poderosas vão conseguir mais poderes.
- A gente coloca a desiguldade para o pós-morte, mesmo que sua intenção fosse totalmente negativa. A gente reforça a desigualdade para uma vida pósmorte
- as intencoes daquela pessoa sao muito mais nobres, principio da dignidade humana, nao podemos usar o meio de ajudar os outros como forma de ganhar.
- Uma pessoa que é motivada para ajudar os outros, uma pessoa vai ter muito menos impacto, pessoa ricassa promover ações de caridade.
- Ref Ops
  + Pobres podem fazer pessoas felizes, que em outro cenario podem nao ter a capacidade de fazerem pessoas felizes.
  + PESSOA que é boa mais é timida, mantem retraida em si, gerar esse tipo de infelicidade, mas que causa mal estar por causa da timidez, pode gerar impacto negativo muito maior do que o positivo, essa pessoa só com fins bons, iria ser punida.
- POI 1O > A magnitude da felicidade gerada também influenciaria > Sim, a gente ainda defende que as pessoas que tem mais recursos teria uma capacidade muito maior.
- Numa maneira geral voces só mostram como nosso sistema nao funciona, nenhum momento mostra que o de vcs é melhor.
- Se a gente partir da premissa do 1o a metrica do que é bom, vc vai ter que definir uma moral pras consequencias praticas, mesmo se fizesse por isso que a gente defende avalisar as impressões.
  + Ex: Cidadaos de bens, esse exemplo mostra como voces estao equivocados, mesmo que ele tenha uma intencao boa para com a familia, ele teria uma intencao ruim para contra outros individuos, intencao positiva com todos.
  + Pessoas pobres poderem fazer boas ações > É menos provavel.
* DLO - Victor
- 1 Gov traz varios exemplos > Exemplo de pessoas egoistas que só fizeram bem por conveniencia social. Ora entao a consequencia final foi ruim, o peso sobre quem fez essas atitudes hipoteticamente seria ruim.
- Naxista cheio de boas intenções viveria nesse paraiso(isso já foi tratado) mas um judeu que fosse recursador de não dar perdão iria para o inferno. Simplesmente ficou inerte.
- No cenario pela logica A ficaria cheio de stalinistas radicais, viveria com um paraiso com militares brasileiros de 64.
- POI Daniel > O sistema B bem coletivo. -> Se no cenario B não ocorreria esses beneficios, a lógica do B é a aprendizagem, passar de ano porque tive uma intenção de estudar. Eu não posso entrar num mundo que eu não mareço. Se eu errar mesmo com intenção boa, se em vida eu perceber que eu to errado, eu posso ver que eu errei, provando que eu verdadeiramente estou buscando o bem para os outros.
- Uma atitude revela muito mais sobre uma pessoa, do que uma intenção dela. A pessoa certamente não vai fazer mal ao ninguém. Não significa que eu fosse uma pessoa má, bolsonaro boas intenções, no cenario do A o Bolsonaro seria bom.
- A logica de relativismo não é bom, porque altera o que é bom -> A intenção era boa. O nazista que foi ruim nao por causa de odio, mas por acreditar em causa boa.
- No nosso cenario a pessoa é recompensada pelo aprendizado.
- Se a pessoa nao aprendeu com erro nao é justo que ela entre.
* MG - Alice
1. Ref
   a. caso oposição, cidadao de bem, ACHA, nao era que o hitler nao conhecia as consequencias, eles de fato conhecem as consequencias, mas ele escolhe não agir nesse tipo de coisa. o que a gente acha que talvez nao rola, seja o guarda que ficou na porta e recebeu propaganda.
   b. Pessoas que cometem essas atrocidades, moralidade relativa cristã, brecha moral que envolve mata, tortura criança é universalmente errado. brecha moral de matar crianças do proprio sistema de cranças deles. eles merecem o lugar ruim. se vc qiosesse salvar milhoes de pessoas num lugar bom.
   c. as pessoas vulneraveis acabam indo mais vezes no lugar ruim, a maior parte das pessoas sao instrumentalizadas por crenças. quando essas pessoas tem a intencao de serem boas. isso diz algo sobre o carater dessas pessoas, elas nao sao inerentemente más. se elas conhecerem a consequencaim, quase sempre vao escolher nao fazer. estao sendo instrumentalizadas.
   d. pessoas ruins que tiveram a sorte de ter gerado algum impacto. podem ser pessoas que foram sempre boas. por algum motivo aleatorio que as coisas boas que elas , mulher altamente oprimida que nao consegue ações por si só(isso é 1g) viveu numa situação que não teve a sorte de ter oportunidades de gerar o bem. problema de pessoas inerentmente más. se a gente pensa no impacto de uma pessoa que acaba poprimindo uma minoria, se essa pessoa representa essa maioria, as pessoas dessa maioria tenderam a ficar contentes. mas essa pessoa nao se importou de matar. inerentemente má. a gente acha que quase sempre os tipos de impactos estao ligadoa
   e. POI Hadassa > se eu sou uma pessoa má, uma coisa boa nao implica em coisas ruins -> bilionario vai pro ceu porque emprega um monte de pessoas.
   f. a experiencia na terra é mtu mais questao de sorte, mas as intencoes mostra outros cenarios.
2. Na maior parte dos sistemas juridicas no mundo, tentasr um crime e realmente conseguir é a mesma. É totalmente uma questão de sorte.
   a. A métrica existem dois sistemas, ambos tem ideia de colocar as pessoas boas, em qual lugar a gente consegue ter pessoas menores. Depende menos de sorte. Mensurar de forma mais precisa.
* MO - Damares
- Cenario real em que nao existem pessoas inerentenemten más e inerentemente ruins. O que pesa é o que vc escolhe ser no decorrer da sua existencia. Quando vc deixou ser levado pelas suas emoçoes.
- De acordo com sistema A as pessoas vao ser sempre iguais, intencoes sempre iguais, crenças iguais. as intencoes de uma pessoa com base num sistema A nao mudam, uma pessoa tem a possibilidade de aprender com as suas acoes, possibilidade de salvar mais pessoas. uma pessoa julga as proprias intencoes, individualmente ela nunca vai se condenar, o meio de se considerar uma pessoa boa, avaliar-se coletivamente ninguem é uma pessoa boa sozinha, em relacao aos demais.
- efeito pigmaliao > a forma de outras pessoas me vem, influencia a forma como eu me vejo, influencia a forma como outras pessoas se vem
  + um milionario pode ser visto como uma pessoa boa, por ser visto como uma pessoa boa, ele acredita que é uma pessoa boa, começa a fazer coisas boas. gerando muito mais bem do que mal. de acordo com o sistema A nao existe incentivo para a pessoa mude(n tem isso) no sistema B se vc gera uma boa ação, vc pode querer se mudar. o melhor sistema seria considerar os ambos. mediar os impactos positivos. no nosso cenario o mundo realmente ficou melhor, nesse sistema mais pessoas sao salvas, mudem evoluam, gerem boas ações. todo mundo consegue se ajudar e um resultado melhor no final das contas. uma acao que gera um resultado positivo pode gerar boas.
  + ideias e crenças, consequencias sao consequencias, ver se algo foi bom ou ruim.
  + os resultados sao uma metrica muto mais objetiva. apoio de outras pessoas, o que é uma boa intenção, o juiz deve ser alguem totalmente intolerante, que vai dar apara essas intencoes um peso positivo. intencoes sao baseados em subjetivos, pode ser parecer boas para seus pares mas nao para seus outros.
  + robinho nao tinha intencoes ruins, mas ele assediou e estuprou uma jovem albanesa, continua falando que o uqe fez nao foi errado.
  + enfermeira fez varias coisas ruins, estorque uma pessoa faz altas coisas ruins com base em intencao boa.
  + pessoa rica faz mais coisa boa > quanto mais rica mais bem a pessoa faz.
  + pessoas pobres podem fazer bem pra muita gente e um bem gigante.
* WG - Guilherme
- intencao
  + o que importa é o que vc queria fazer, ou o resultado que vc atingiu.
  + a intencao ser boa ou ruim, n depende do individuo ter ela.
  + o fato dele n considerar algo errado, n significa que ela é ruim. sigfinfica que ele concorda com a propria intencao
- a logica mais justa é pelo que ela decide fazer, capacidade de fazer.
- n adianta vc ter intencao vc tem que agir sobre ela, se vc tem a intencao de matar o bolsonaro n gera pontos ruins
- intencoes é mtu mais universalizado e seguro. n é algo que estava no poder dela. se vc quer matar alguem, e vc só n matou ela por causa que a pistola bambeou, tirado qualquer fator externo a pessoa teria cometido homicidio. nos ainda julgamos aquela pessoa da mesma forma. a pessoa n controla o vento que impediu ela de matar.
- ladrao vai assaltar uma casa, e encontra uma velinha desmaida no chao, ele sai correndo, quando o ladrao levantou a janela, aquele ladrao em tese fez uma coisa boa, mas a itencao dele era de roubar aquela casa. nos ainda iriamos querer prender aquela pessoa n estava no interesse dele. nos julgamos a pesoa pelo seu carater e n pelo o que o mundoi coloca. julgamos pela sua agencia.
- quem puniu n foram os soldados de nuremberg, mas os generais. as consequencias que os generais faziam eram feitas com intencoes ruins e por isso nós os punimos, mesmo que eles tenham matado varias pessoas pq as intencoes n eram ruins
- 1gov
  + n pode usar o ser humano como uma ferramenta, vc é julgado pela sua agencia, e é incorreto julgar algo fora do seu alcance. vc coloca aquela pessoa em especifo
- 2op
  + logica de maior coerencia. isso é mtu mais levavel no nosso sistema, se vc é uma pessoa boa, pela logica do ssitema B fruto do acaso. consequenciaa negativa de uma intencao positiva. o nosso preza pela coerencia, nos queremos ter o maximo de coerencia possivel.
* WO - Hadassa
- a humaniade n sabe que existe esse sistema
  + q é mais facil
    - vc faz varias coisas boas ou ruins e aos poucos vai melhorando.
    - se eu faço mal pra pessoa que ta fazendo bem
    - cheia de boas intencoes, com vontade de salvar pessoas do inferno, com vontade de ter um casamento saudavel, levar democracia, o mundo ja fez atrocidades.
      + n to tirando que vc se case com gay, pq eu nao quero que VC vá pro inferno
    - as minhas acoes falam mais que minhas boas intencoes, eu faco uma porrada de coisa se eu to querendo ou nao querendo, isso n muda o fato que o mundo tá melhor com a minha existencia. o mundo esta melhor porque elas passaram por esse mundo.
    - essa pessoa merece estar no ceu, ao longod a minha vida vou fazer varias coisas ruins e varias coisas más, se vc teve uma intencao boa, vc n é uma pessoa boa, pessoas bem intencionadas tbm estao fazendo bem ou mal atraves das acoes, capacidade de refletir, percebe o bem ou mal que fez.
    - n tem como fazer intencao sem açao > quando eu melhoro isso gera algo. pra eu ser uma pessoa boa, pq eu faço bewm pra alguma coisa. eu sozinho n tenho como fazer bom.
- 1gov
  + se a pessoa rica explora os trabalhadoras, tá perdendo pontos cada vez que torna a vida miseravel. se ela parasse de fazer açoes boas. cada acao vai ter pontos bons e positivos.
  + pessoas pobres n conseguem fazer vida feliz. se empenhar pessoas ao seu redor, e mesmo que a gente considere capitalismo, vai trazer pontos negativos e positivos para ambos as socias
  + pessoas pobres vao estar pontos negativos por coisas horriveis
  + ser humano n é preto e branco.
  + cheia de boas intencoes a gfente vai legitimar altos absurdos
- poizinho alice > agir de forma consequencialista, tirar as coisas que eu agi bem com vontade ruim > esse debate é sobre uma soma total de acoes ou intencoes. dar dinheiro pra mendigo sem pensar
