#+TITLE: Debate04

* PM - Andrew
1. Finalidade excepcional, producao de coisas
2. Web sem isso
3. Tecnologias eletricas. Trocaram padrão da tomada brasileira. Adotar um padrão que fosse melhor america latina
4. Beneficios nações. A União Europeia definiu uma serie de padroes, em relacao a padroes tecnologicas, tv digital. Usar uma tv na alemanha comprada na franca
5. Integração regional nunca antes vista, nações conseguem mais força pra enfrentar grandes interesses individualistas(n entendi como é o caso da china e eua)
6. Plenas condicoes de desenvolver padrões, excelentes não só pra nação como para o mundo inteiro
7. Desenvolver padrões que unifiquem
8. Mtu mlehor do que concentrar poder, integrar e ceder, diversidade social de agentes, agentes governamentais, entidades da sociedade civil organizada, aspecto fundamental. Transparencia no processo.
9. Comite com diferentes interesses, diferfentes perspectivas
* LO - Sofia
1. O caso do primeiro governo beneficio social, padrao pensado sociedade civil, sociedade civil entrando em conjunto. Conglomerado organizacoa vai ter dialogo entre empresas e orgaos governamentais, n há espaço pra sociedade civil, e mesmo se tivesse o que uma sociedade civil teria frente ao mundo?
2. Governo se ajuntar com grandes conglomerados, porque nao vou ceder, monopolio de producao e controle. Elas vao assumir esse orgao, esse orgao de debate vao ter ideias, vao querer e ter pensamentos do que é um padrão. Qualquer um que queira entrar nessa empresa n vai querer entrar. Essas empresas visam o lucro, e somente o lucro. Qual o motivo delas entrarem, completamente. Por que aautorizar a propria quebra de monopolio. No nosso caso a gente só estaria aumentando ele.
3. Empresas só vao deixar outras empresas parecidas como elas querem. Governo em desenvolvimento vai estar suscetivel para obedecer. Grandes empresas de paises desenvolvidos.
4. Relacao entre empresa americana vs brasileira. se uam empresa de um pais desenvolvido, os padroes que eles devem seguir, pequenas empresas vao quebrer para coisas os padroes.
5. Ǵrandes empresas vao sempre querer outras grandes empresas.
6. POI Andrew > Empresas, sociedade civil e governo > Um Estado vai conseguir dialogar facilmente com as 10 maiores empresas de telecomunicacao, não vão. O dialogo internacional é dominado por 5 grandes estados que controlam a porra toda.
7. Monopolio dos grandes estados, já tenho dificuldade de dialogar com eles. amazon tem um pib maior que o brasil(isso ta mtu errado). n tem dialogo, n consegue estabelecer uma conversa.
8. Analise do que é melhor, n é melhor para maioria dos paises.
   a. Aumento de lobismo, mas sim de um trafico de influencia, bolha de interesse mtu maior, perdemos um total controle daquilo que vai estar acontecendo.
9. falta de dialogo impedido de acontecer, tanto empresas e estados.
* DPM - Claudinei
1. Paises cedendo seus poderes na esfera interacional, fortalecimento do desenvolvimento itnernacional, maior iteracao entre paises, mtu mais facil pais a comercializar com pais b, seus produtos seguiram padroes internacionais, grande parte do comercio internacional, n conseguem se adequar a padroes segfuidos internacionalmente, paises ceder  padroes.
2. Varios paises, possam entrar no mercado interacional, partidos vao ficar em desvantagem, já estao em desvantagem hoje, forma de se desenvolver proprias. possibilidade mtu maior de paises poucos desenvolvidos, varios paises subdesenvolvidos, n conseguem se desenvoolver internamente. paises que n conseguem fazer ese tipo de dfesenvolvimento.
3. beneficios maiores. entrar na coompeticao internacional.
4. avanços tecnologicos muito maiores, n ter por conta propria. entrar mais facilmente nesse comercio internacional. teram esses mesmos padroes. comercializar com todos paises.
5. Já tem toda essa influencia de paises extremamente desenvolvidos, já tem grandes empresas fazendo a pressão, colocar mecanismo, usar seu poder para que agora a gente consiga ter algum tipo de retorno nisso. esses paises devem fazer isso para terem algum possabilidade de entrar no monopolio da tecnologia.
6. Monopolio dep aises que concentram producao tecnologica, favorecendo esses paises imensamente, trazendo prejuizo para esses povos, n conseguem avançar tecnologicamente, dever moral de defender que esses paises façam isso. um cenario onde a gente n tem isso, vai continuar com todos onus, vai continuar com essas empresas, n explicam como a gente mitiga isso.
7. possiblidade de um pais da nigeria dialogar com os eua > tripartido. quando a gente tem essa tripartição.
8. Monopolio das empresas, esses principais limites da moção, pode ter uma serie de prejuizos. toda argumentacao da primeira oposição, n é esse o ponto mais forte, os beneficios apontados, a gente vai conseguir ter esse tipo de fiscalizacao, mecanismo estatais, ainda que n haja esse tipo de gingerencia os impactos de se colocarem mais eficientes
* DLO - Marcelo
- Poder decisorio, coopetição.
- Toda e qualquer decisao do estado, vai impactar no ambito interno. quando vc toma alguma diretriz no ambito internacional, o estado tem esse fim social, a partir dessa premissa, o estado é o mais capacitado para escolher padronizacoes, lucro supere o bem social.
- diferença entre o dever ser de uma empresa e o dver ser de um estado. todo dver de garantir direitos fundamentais. dever n é trazer o lucro. interesses dos estados sao conflitantes com esse tipo de competição.
- estableecimento de coopeticao, tem o poder de aceitar quem eles quiserem, grande empresa n quer aceitar umn pais subdesenvolvido.
- a gente n tem paridade de discurso. é ilogico numa sociedade capitalista, tudo é voltado ao dinheiro. condição paritaria de dialogo.
- O pais n tem essa estrutura, competicao mercado interno, trafico de influencia. dialogo com o vgoverno, os proprios CEOs das grandes orgnaizacoes, n sao formadas por pessoas que sao exlcluidas dos espaços de poder. empresas interesse de mais vulneraveis.
- formar bolhas de dialogo, assimetria de informacoes, a amazon n saberia qual padrão tecnologico para a bolivia. governo tem esse maior dissenimento
- poi 2g impotencia dos estados frente a má produtos > empresas já tem interese afim.
- cenario de nao integração.
- escolher entre o principio de esoclher principios do estado e o lucro.
* MG - Nicholas
- n há dialogo, grandes empresas já definem a forma como elas iriam atuar. questoes extrativistas, e varios tipos de coisas. grandes empresas procuram por melhores condicoes dep roducao e, paises eternamente condicionados.
- grandes paises conseguem dialogar com grandes conglomerados, paises sao ameaçados, se a gente n pode produzir desse jeito, a gente n vai produzir esses serviços.
- grandes empresas respeitam grandes paises, consegue ter suas regulamentações respeitadas.
- procurar condicoes melhores em outros paises. copmpram o congresso. ameacando o governo executivo, flexibilização para regulamentaçÕes. simples de fazer o que elas entendem. estados flexibilizem a sua legislação. coloca paises onde a sua opinião é menos resolvida.
- paises concedendo para criacao de consoercios, a comparativa, é agr que esses paises tomam decisoes que os beneficiam, essas condicoes basicas, vao ser decantadas, e que n tem ocao de escolha, essa ideia n é de liberdade, essas empresas na busca por maiores condições.
- politica de redes sociais, padronizacao de produção. possibilidade de colocar limites. padrão que atende melhor a sociedade. entregam serviços ruins paises mais fracos.
- empresas sao predatorias.
- poi governo epqueno leis que beneficiam eles > esse governo atualmente n tem essa liberdade, atualmente esses governos dependem dessas empresas. apesar de condição ser ruim, n tem opção entre escolher entre o ruim e o pior.
* MO - Cafe
- esser consorcios n sao bocos economicos, n tem projeto filantropico, papel de gerar regulamentações. simplesmente vao gerar regulamentaçoes, ter espaço de discussão, planejamento, regulamentacoes relacionadas a o que a gente produz e caralho a quatro.
- mais interessante para os governos estarem a margem
  + já existem entre empresas, esses consorcios definem padronização. agr os estados abdicaram, nesses consorcios. na resoluição desses consorcios
  + empresas tentam controlar os estados a todo momento. ela n explica, a gente n estar nesses consorcios
  + EUA é um estado que, pegada é totalmente diferente.
  + papel de um estado gerenciando, vc tem mtu mais propensao, estados comunicar relacoes basicas.
  + relacao da onu, lá vc tem pauta que sao prioritarias, mais que relacoes de produção, EUA por mais que vc tenha esse loby politico, vc tebm tem questoes sobre fator cultural, os paises pequenos sao stakeholders principais.
  + caso do governo é pior, ele tem mtu mais beneficio, as empresas teram muita força. ele n vai barrar a empresa necesariamente. produtos e exportações minerais, vale empresa nacional. ela n ligava para as proprias leis do governo. proprio brasil perde a sua força, esta abdicando da sua autoridade por estado, colocadno voto igual uma empresa.
  + legalizando a influencia politica. EUA tem força, tem poder, num cxenario do gfoverno vc tem um bloco, duplo voto, que elas já tewm no proprio estado e agora com outro estado.
  + ele tem uma forma de miminizar os danos, questao do apoio, pelo menos por estar com relacao com outros paises. ele tende a continuar nas suas causas externas.
* WG - Brenda
- as nacoes do mundo hoje estao completamente derrotadas, coisas que sao funcao do estado, e agr ele esta se vendo incapaz de realizar, grande capital é flutuante, pode ser tiado e colocado ao bel prazer. se essa grande empresa nao gosta, 200 paises que pode comrpar e vender.
- mal produtos e mas producao, se perpetuam, estrategia cada um por si, só tem enfraquecido os estados, empresa que fazer o produto mais barato, as empresas querem hoje, 1governo n explica o problema, problema de mal produção e populacao refem, impotencia dos estados.
- pq consorcio vai mitigar o problema > colocar um lugar na mesa, poder de voto igual, op se apega a ideia de n ceder o poder, mas n conseguem ceder o poder.
- estado é mais capaz de decidir para a populacao, tanto faz o estado n consegue fazer nada sozinho.
- Pior cenario, cenario de panelinha > possivel cenario de varios paises agregados. ainda que seja panelinha alguns estados e organizacoes com opinioes relevantes.
  + hoje a gente tem decisoes monocraticas.
  + limitar tecnicas extremamente poluentes. vetar absurdos
  + possibilidade de estar entrando.
  + momento de decidir esclarecido.
- orgao que é capaz de decidir isso.
  + FOrum mundial economico > paises e org civis se juntam para exercer pressão, orgao esclarecido, uma porta aberta, pra quem n esta na mesa, agr sabe quando tá decidido e como tá decidido. no mundo da oposicao isso é decidido por baixo dos  panos
  + impotencia das nacoes frente aos grandes conglomerados.
* WO - Joao Victor
- como isso vai melhorar o pais, focando como os paises n terem força. como isso n reflete melhora na qualidade. papel dos consorcios, existiriam em ambos os cenarios, gerariam a sua regulamentacao, tende a ganhar n fazendo parte.
- forum de paises, tratar de relacoes de paises, paises falando de situacoes de paises, ponto da primeira oposicao, só consegue ser de fato colocado, abdicando de sua influencia.
- poi cluadinei > ceder poder para empresas, governos cederem poder para sociedade civil > criterios a serem seguidos, maiores empresas produzindo energia. paises entenderem, isso me leva ao segundo ponto, papel como esses paise conseguem sobreviver. conseguem ter mtu mais autonomia. manter seu papel de estado.
- paises que fazem as adaptacoes necessarias, esse modo de producao n vai mudar abruptamente, manipulados por essas empresas.
- fluxo de globalizacao, n necessariamente fazer parte, ele n pode usar essa tenoclogia, vai continuar sendo utilizada para qualquer um, n vai ter relacao direta para padronizacao.
- governos menores que n tem tanta força > esses estados já n tem essa força, beneficio para mudar as regulamentacoes, n vao mudar de fato, tendem a aceitar da mesma forma do status quo. abdicar das sua acoes internacioanias.
- importancia do meio ambiente > estados tem uma certa separacao entre consorcio e sua acao como estado.
- n
