#+TITLE: Biden Agressivo Vs Boring Adj

* PM - libero
- Mundo para mais chence de eleicao
- Contexto
  + Busca pelo poder objetivo vencer as eleicoes
  + Grande polarizacao
  + Visao de trump enquanto incompetente antes das eleicoes
- Mudanca no imaginario social
  + Devido a ineficacia do partido democrata
    - duas missoes
      + bem vistos
        - mostrar as porpostas, cria se no imaginario social uma imagem mais benefica do partido, o que gera mais empatia, jovens, indecidos, ou etc, por n terem consguido efetivar suas medidas.
        - ao focar nas propostas - acabar com a idfea de que apenas extremismo é que resolve - mostrar que existem ALTERNATIVAS Para o modelo de trump para a economia e caralho a quatro, mecanismo pscologico da influencia - plausabilidade ec coerencia do partido na mente dos eleitores, propostas alternativas, focado no proprio partido, e como seus representantes tem objetivo e qualidades que devem ser louvados, inves de dar palanque para trump se foque em melhoras para o partido.
        - eleitorado indeciso que n confia na politica, consegue trazer essas pessoas para o nosso lado. recebendo essa enxurrada de mensagens boas.
      + tirar o eleitorado
  + quanto se bate mais se coloca em evidencia
    - num outro cenario ele foi escrachado, pela midia, pelo partido democrata, fez com que o partido conseguisse mais eleitores, embora ele batesse, ficou em evidencia, as pessoas comecam a procurar e medidas extremistas que parecem ser uteis, ao inves do partido focar nas suas propostas e no que é bom, a continuidade do partido é melhor, quando vc faz isso vc faz que o partido tenha mais efetividade, focando no outro vc dá mais evidencia. conseguiu convencer mtu jovens? todo muindo sabe que ele é DOIDO, as pessoas coemcam a velo como a unica saida.
    - no nosso cenario vc permite que as pessoas vejam que o partido democrata tenha pessoas boas e tenha alternativas, convenca eleitorado, eleitorado jovem que ainda esta formando a sua opiniao, eleitores indecidos que possam mudar.
    - nos nao queremos dar evidencia pra trump.
- dar palco pra maluco e mostrar alternativa
* LO
- estrategia mais combativa, obvio qeu vai ter propostas mas n vai ser o foco
- trump usa de estrategias desleais
  + transofrma o partido num culto irracional
  + cria bodes espiatorios demoniza os imigrantes mesmo criancas
  + aliado a tudo isso uso mtu forte das redes sociais
  + exploracao de big data e de robos
    - robos pra espalhar fake news
    - algoritmo que destina uma fake news especifica pra um numero especifico de pessoas.
    - estrategia autamente combativa
    - robos que floodam posts de noticia e caralho a quatro.
    - garantia: redes sociais barrando esse tipo de noticia(man como isso vai pra sua metrica????)
  + alteracao de estrategia
    - precisa destruir a imagem do trump como o governo dele foi ruim foi horriel, mais facil comunicar com as massas falando mal de trump, n é possivel falar apenas no construtivo,
    - poi alice -> massas votaram em trump, falando que elas sao burras ou más, mtu mais reativas -> a gente n vai chamar um eleitor de burro, é mostrar que o trump foi eleito, e teve praticas que n foram boas, falar mal de trump, combater o trump, difamar o trump. trump se coloca acima da lei -> preciso quebrar isso
    - ex: the good fight, difama o trump, coloca ele como um personagem burro -> tenta angariar votos, uma pratica altamente combativa -> (isos deu certo?)
    - cenario de alta polaridade, grande diferenciacao entre os democratas e os republicanos, se precisa se comunicar mais com as massas -> trump é altamento populista -> altamente comunicavel -> é preciso que a gente combata isso de uma forma mtu mais forte destruindo a pessoa de trump, pra que a  gente angarie mais votos.
* DPM - claudinei
- contexto de enfraquecimento do partido democrata e alguma falhas que deixou opartido desacreditado.
- pq devemos priorizar uma estrategfia construtiva -> no sentido que vc vai optar apresentar a populacao o que vc pode ofercer -> poderam saber o que vc pensa e o que vc vai fazer quando chegar lá -> consegue n só o apoio das pessoas que já sao democratas e que precisam ser incentivadas -> vc apresenta para essas pessoas indecisas e convencer uma porcentagem para essa galera.
- quem ganha n é quem tem maior numero de votos da populacao -> gfrande parte dos estados já tem uma ideologia definidfa -> em alguns estados o numero de delegados vai ser proporcional -> em outros é winner takes it all -> competicao extrema pelo numero de delegados -> se a gente consegue uma campanha construtiva -> convencer os estados que sao historicamente indecisos -> e com esses estados consegue ganhar a eleicao que é o q a gente precisa disputar e assim ganhar a eleicao essa estrategia é mtu melhor que a ultima que foi extremamente combativa -> a hillary teve um maior numero de votos da populacao mas n teve maior numero de delegados.
- precisamos fazer uma campanha construtiva -> dando voz pro trump pras pessoas indecisas procurarem sobre ele
- a gente consegue ganhar mais facilmente pq consegue chegar nos eleitores e ter proposta pra resolver
- 2op poi -> se a propositividade é mais importante pq o trump conseguiu ganhar -> no cenario vc consegue crescer mas n consegue conversar com o eleitor, a gente já tentou -> so serviu do outro lado porque ele já estava em acencao -> o partido democrata JÁ ESTAVA LÁ, as pessoas acendessem o extremamente oposto -> vc precisa considerar o contexto historico que levou uma pessoa oa poder -> experiencia é negativa vai colocar o adversario em evidfencia -> as pessoas vao querer asaber pq essas pessoas criticam -> elas vao buscar sobre ele -> vao procurar sobre o nosso adversario e talvez se identifiquem mtu mais.
- a gente n consegue convencer os estados indecisos
  + da midia para ele, o opositor tem algumas vantagens, a midia já fala dele, a gente já fala dele, os indecisos, as pessoas que falam mal de nós.
  + a gente sabe que o trump fez uso de varias coisas zuadas -> isso é legal pra gente, mas enquanto chapa democrata n vai nos dar beneficios, e convencer os eleitores indecisos.
* DLO
- qual o status quo? -> enorme descrenca -> fazer uma campanha nas suas exaltacoes enquanto politico -> as pessoas n estam aceitando acreditar na imagem do bom politico -> nenhum politico é bom, é mais facil cosneguir votos com base no rfepudio de um candidato do que no real candidato -> bolsonaro focou em destruir o PT ivnes de exaltar as propostas -> no nosso lado é melhor pq alem da estrastegia nos teremos boas propostas, tanto em detrimento de exaltas os defeitos.
- a gente vai fazer mais ou menos igual o ciro gomes com o pt e o bolsonaro ele foca em uma campnha de difamação, combatendo ideias e propostas(?) e combatendo o que essas pessoas sao()
- os EUA soa pessoas mtu moralistas, o Trump é super imoral, chocar a população, mostrar atraves da repeticao que ele é o pior
  + reality show, assedio sexual
  + governo marcado por varios escandalos
  + 6 dos seus assessores foram condenados
  + varios escandalos sexuais
  + denunciado por trafico de criancas
  + tudo isos é desaprovado por essa sociedade de forma populista, precisa pegar no centro do que essa população mais reprova, as pessaos tem que escolher entre os dois, ela é mtu mais comparativa, é eu ou ele? -> é mtu mais facil que vc é a melhor opção que o seuy candidato, fazendo uma comparação com o candidato mtu ruim
  + difernte do que o 1g ta falando n é noticiario é rede social
    - campanhas de fake news, se a gente só tem 2 candidatos, vc ve que o trmp é a pior opcao que existe
  + poi 1g -> como qeu a gente consegue convencer os eleitores indecidos como esse tipo de campanha?
    - joe biden ta na frente com diferenca de 6%, que ele tem que manter os eleitores que ele tem, democratas democratas que ja vao votar nele, esse publico jamais votaria no trump em qualquer circunstancia -> tem que focar em quem esta em cima do muro e quem é ex-trump, eles precisam ver que o trump n é a solução, pessoas despolitizadas, tem esse interesse na politica, exemplo do brasil pessoal ficou tao focado no tudo menos o PT que deu no que deu.
  + ate ele ser eleito ninguem acreidtava nele, isso ele n vai fazer, isso ele n faz, a gente já viu o governo dele e é capaz de fazer tudo isso, esse cara é realmente doido e ele é perigoso, o quao ruim foi o governo dele para essa populacao. estrategia do ciro gomes combate honesto, n vai apontando o dedo na cara e falando que eesssee eleitores sao uns merdas.
  + a gente pode mostrar que vc FOI ENGANADO por ele.
  + de um lado o trump difamando o joe biden e do outro o joe biden falando do quao bom sao suas eleicoes -> a gente precisa de uma paridade de armas para competir com o mesmo nivel do trump?
  + a proposta do governo é baseada nos democratas, tem que ir no publico conservador que n se importa com politica.
* MG - pj
- a primeira metade ta equivocada do que foram as primeiras eleicoes do trump, ele era propostivio, uma proposta de mudanca uma nova alternativa, make america gret again, drain the swamp, mostrava algo que essas pessoas queriam acreditar, n foi ele simplesmente ser destrutivo
- campanhas negativas n geram apelo de
  + voto facultativo é uma postura ativa, mas mostra a qual grupo eu quero me associar, e os demoratcas precisam demostrar motivos para que seu voto em biden vai mostrar um novo amanha, convencer SAIR DE CASA
  + n é só negar o trump o biden precisa reconstruir a alma do que é ser americano, e parar dos democratas fazerem o jogo dos republicanos, os democratas precisam chutar toda essa construcao que o respublicanos construiram, os americanos vejam os EUA com seus proporios olhos, cidadao vendo o conflito social, fracasso economico, eles n precisam da humilhacao do eu te avisei, isso vai gerar maior raiva
  + o biden precisa se provar e isso é algo especialmente importante pq biden e harris sao figuras de backstage, vice e legislativo eles precisam construir uma imagem como liderancas politicas, mostrando a capacidade de gestao dele no obamacare vai de encontro com o covid, kamala mostrando que ela é firme destemida capcidate, contrario do trump que só fala merda, isso é mtu importante quando ela ta compondo chapa com um idoso
  + o macrom ganhou assim, uma alternativa otimista, elevando numero recode de franceses para as urnas
  + trump é desleal -> o trump teve um trabalho de fake news, os democratas entraram nese role -> fake news é conspiratorio, eu tenho uma proposta de um novo EUA para trazer um novo EUA. toda construcao de fake news é feito para nao ser falseavel.
  + n dá palco pra maluco
    - o discurso de associacao de fake news é mtu mais facil de ser comprado, a descontrucao de fake news é mtu mais trabalhosa, para descontrucao vc tem que mostrar a fake news primeiro, a propria ideia de descontruir fake news é pra colocar ela nas bolhas onde ela n é vista, as pessoas vao escolher as fake news, se o biden e a harris focarem e a idade que era um desafio se torna uma vantagem. as pessoas tao arrependidas de terem votado no novo, mostram que eles estao prontos dentro do primeiro dia, se mostrem como adultos na sala, nunca foi antes tao importante ter seguranca com suas liderancas que o trump n pode resolver nada, o covid fez a reprovacao para niveis historicos, se mostrarem como adultos na sala.
    - o eleitor ja tem a demonizacao do trump, caso o biden e a kamala parecam com o trump eles vao ter menos vontade de sair pra votar
    - swing states a mesma coisa, achar jsutirficativas para as decisoes de 2016.
    - a cultura já é anti trump
* MO - vic
- chapa democratica estrategia combativa -> essa é a unica maniera de ganhar controle da narrtiva, inimigo que se usa de meios escusos, tem que lutar com todas as armas que a gente tem(1o ate agr)
- contexto - momento inflamado, n só nos eua, pandemia do covid, grande crise nos EUA, em meio ao contexto da pandemia, blm, manifestacoes tomaram role internacional, grande insatisfacao como da populacao como as mazelas estruturais,m total falta de apoio do trump.
- poi 2g -> se a pop ja rejeita o trump, qual que é a efetividade do lado de vcs -> mostrar isso mais pra frente
- ja tem um contexto de insatisfacao -> mostrar os efeitos que os eleitores do trump, as consequencias das atitudes dele, ja existe esas insatisfacao no trump, ela n é total, como mtu bem é vsito, mta das causas que eles acreditam é falha, maquina de fake news foi disseminada, n existe um controle para essa maquina de fake news, e ewsse controle de narrativa maquina de fakew news foi efetivo. a gente precis e de uma combastividade para lutar a altura(salomao ainda)
  + por cauas do contexto de inflamcao popular, n só pelo BLM, mas justamente por causa da pandemia, precisa dominar a narrativa e a culpa que o trump tem dentro disso, mais passividade e construtividade, a gente ta sim perdendo controle da narrativa, pq o trump vai estar lutando com as maquinas que ea gente n tem cointrole, as fake news vao continuar existindo, a gente precisa sim dominar a narrativa, ele possui dinheiro para conseguir suportando e sustentando essa maquina, as redes csociais que tem essa alcance toa grande na populacao, e ele tem esse know how dessa desinformacao, se a gente tiver uma maneira de lutar a altura, a proposta A vai permitir qeu ele molde a narrativa da forma que ele quiser, trump vai usar dessa passividade para usar da forma que ele quer.
  + o mais importante é conseguir vencer as eleicoes, mesmo que n seja a estrategia moralmente ideal, a gente tem que lembrar que é um homem que acendeu ao poder de uma menria de estrategias escusas, precisa de incisividade, depois da eleicao do
  + poi 1g -> se os apoiadores veem tudo de ruim mas continuam apoiando melhor dar outra alterntiva -> n quer convencer os apoiadores ferernhos, mas convencer as pessoas indecisas, pq eles estao, a gente quer convencer a populacao que votou nele por causa de uma insatisfacao por causa das medidas dele, uma grande parcela, controle da narrativa, (eu ainda n entendi isso) as pessoa estao inflamadas querem resposta, como que a pop ta inflamada, querem uma resposta a altura.
* WG - alice
- o grande problema de plausibilidade ele só é resolvido pelos pontos od pedro
  + 1g
    - os democratas antes atacavam os trumpos por isso resolveram uma grande desconfianca
      + diferenca dos democratas naquela eleicao, tinham a confianca deles bastante colocada a prova, no nosso lado a gente combate essa desconfianca, esse ponto se torna mais plausivel com a exlpicacao do trump, combate a desesperanca e cria uma narrativa nova, a segunda ideia deles é se a gente bater no trump, n é meramente questao de expor, mas algo que vc possa acreditar, dar espaço pras pessoas conseguirem se associar
    - dando palco,
- fake news -> como trump tem meios escusos precisa colocar a altura
  + fake news n sao falseaveis, vc n vai conseguir provar por causa da teoria da conspiracao, dando palco pra fake news, se a gente n dá alcance pras fake news,
  + essse proprios escandalos n podem descontextualizar fez com que teve uns progressos, twitter ja tem mecanismo de combater, esse ponto já nasce mitigado, se a gente fosse luta a altura, sujar as mãos fazer fake news, no minimo sujam as nossas maos, se afastarem tbm, n é possivel a gente domar essa narrativa, ma construir uma narrativa nova, hoje ele esta ganhando pq é aunica narrativa, as bancadas de oposicao deveriam ser comparativas mostrar pq a gente deve domar inves de criar uma nova
- 1op
  + campnha desleal, as pessoas se invewstiram eemocionalmente no trump, naquele preocsso de america, olha só o seu proejto de marerica é um projeto que torturra criancinha, as pessoas vao ter uma resistencia para mudara ideia, e vcs foram conivnentes com isso, isso ta tudo associado a indentidade, atacando a indentidade americana(aquilo que me emociona, aquilo que me faz votar no trump tem coisas mas) quando vc ta dando uma nova proposta(poxa eu ous mais inteligente eu voto em coisas mais plausivel) vc n esta necessariamente chamando a pessoa de burra, os exemplos que a 1op oposicao trazem, o ciro gomes, faz com que as pessoas n levem a serio eles, isso explica os gfrandes fracassos do ciro gomes, o PT eo Bolsonaro  disputavam narrativas e mundos.
  + a narrativa do PT, mostrar que ele foi tao ruim, a narrativa do PT foi construida ao longo de anos, as eleicoes norte americanas sao meses, quando vc começa a criticar otrump da outro mecanismo, o do VITIMISMO, essas pessoas estao fudendo o seu projeto de america. dá mais razão ainda.
* WO - pazin
- a 2op trablaha com o contexto em que todo o caso da op é mais impactante, masi chance de acontecer
- cenario de 2020
  + grande levante popular
  + influencia popular milhares de pessoas ocupando multidoes
  + influencia eleitoral absurdamente grande, uma das maiorias por direitos civis desde a marcha de washington
  + pos pandemia
    - ingerencia do trump na gestao da pandemia
      + desastre no EUA
      + negacinismo cienfisicmo
      + temos que mostrar a ingerencia, mostrar o impacto negativo de milhares de mortes de maricanos, a ingerencia é extremamente importante nesse caso
      + contradicoes do governo devem ser mostradas
        - trump tem ligacao com supremacista
  + pq a gente ganha da 1op
    - n explicam pq os cenarios ocorrem
    - n deram os mecanismo
    - nem os impactos
    - 2 mecanismos
      + trump tem o controle da narrativa pq ele é bilionario
      + tem a condicao de fazer a disseminacao
      + fake news tem alcance, mesmo que fossem barradas ainda tem o impacto das redes sociais, n tem verificacao de fatos no whatsapp
      + eles falam com cenario propositivo, no whatsapp a gente vai ser destruido, o trump tem a maquina publica.
      + por mais que eles proponham, hadad foi propositov bom moço, mas foi destruido por eleicao.
      + as pessoas n pensam apenas no calculo racional, é necessario uma motivacao a mais, pq nos EUA o voto n é obrigatorio, seres humanos se movem pela emoção, eu tenho que mostrar para essas pessoas que elas tenham raiva, nesse cenario a gente tem mais chance de irem para votar nos democratas, pessoas tem medo tem raiva do trump, e isso qeu de fato faz, n é o convencimento, mesmo que a gente n fosse destruido o trump ainda seria extremamente forte. mtu importante mostrar as contradicoes
      + poi pedro -> contradicoes do trmp já sao expostas, p o trump vai resolver esses problemas -> ele pode fazer mostrar como ele quiser, se ele for atacado o tempo todo, n adianta nada, mostrar a mais bolhas, mas levamos para mais bolhas com outra narrativa, saco de pancada, é necessario dar esse palco para a gente controlar essa narrativa, a gente precis amodificar essas narrativas, mostrar as contradicoes. nos ja vismo que o trump é desastroso, só mostrar que ele é ruim, tudo isos é um contexto só mostrando arealidade, a gente prova que a narrativa é mtu mais plausivel.
