#+TITLE: Planeta Atea Adj

* PM - Rached
- Iniciando nova sociedade - do 0
- Esse debate n é -> Vai continuar sendo ateista sempre
- Qualidades morais nao sao inerentes
  + n vao comecar a ser mais, na pesagem geral o mundo vai ser positivo
  + 2 pontos
    - ciencia
      + reeligiao possui muitas cresncas e dogmas de muito tempo atras
      + n passaram por metodologia cientifica, dados repetiveis
      + n ha um metodo dentro da religiao, conflitando com a ciencia, neste mundo desenvolvimento cientifico mais rapido e desenvolvimento sociais mais rapido
      + relkigiao tende a espalhar suas crencas
      + aborto, embrionarias celulas, transfusao de sangue testemunhos de jeova
      + quando entra em choque, politica, dificuldade de passar leis, religiosos tenderiam aconflitar com a religiao
    - relacoes internacionais
      + sociedade divididas em povos autonomos, razao dos seus costumes
      + religiao fator de conflito -> (cristianismo, islam etc) -> dogmas sagrados defendidos, essas religioes podem considerar o outro povo tem costumes contrarios a sua religiao -> vistos como inimigos -> disputando terras sagradas
      + na comparativa nos reduziriamos os conflitos eliminariamos os motivos por motivo religioso -> ainda rola conflitos ideologicos -> religiao é conflituosa inerentemente porque parte de premissas ilogicas -> que n podem ser provadas(bom) -> esses religiosos venham a entrar em conflito entre si.
  + é preferivel que no mundo novo n tenham os conflitos
    - na maioria das vezes esses conflitos tendem a matar muito mais pessoas, gera efeitos drasticos -> religiao faz muito mais mal em termos de n temos cooperacao -> a cooperacao é muito importante pq estamos criando um novo mundo -> n vamos ter um mundo perfeito mas vamos reduzir -> reduz os numeros de mortes -> povos cooperativos vao fazer trocas economicas -> isso acaba tendo uma troca de tecnologia -> troca de riquza, postivias para os crescimento da humanidade como um todo
    - 2 premisas
      + ciencia entrando em choque com religiao
      + menos cooperacao
* LO - Iza
- exclarecimento
  + n é pq sao religiosas que sao extremas, fundamentalistas, toda essa fundamentacao é uma forma de barrar a ciencia -> quando isso aconteceu na historia do planeta terra -> foi pq as pessoas estavam numa epoca completamente diferente(exemplos atuais do rached). -> as pessoas ja sabedm do que aconteceu, se for de forma extrema
  + o melhor cenario n é um fundamentalis -> uma pessoa media -> uma coisa nao excluia a outra
  + cenario de 2020 -> pop cada vez mais cetica e cada vez mais racional -> obviamente que temos grupos extremistas -> a maior parte das pesoas é mais cetica -> igrejas perdem apoio -> em 2140 pessoas num nivel muito mais racional e cientifico.
- religiao importante
  + pra construir nova sociedade
  + a religiao é a base de apoio -> em um cenario de colonizacao -> cenario de incertezas duvidas e medo do desconhecido -> vc vai ser simplesmente encaminhado para um novo lugar, responsabilidade de fundar uma nova civ -> a responsabilidade e o medo é mtu grande -> no momento em que vc n confia em vc vc é mtu maiks provavel que faça uim bom trabalho -> incerteza é mtu prejudicial pq vc n toma decisoes. -> cenario de duvida e incerteza é mtu grande
  + religiao forma de confoto de seguranca -> o quao errado possa dar tem alguem olhando por vc -> é mtu mais provavel que essa pessoa consiga fazer o seu trabalho de uma forma mais funcional -> quando vc tem uma sessao de ocnforto ancora esperitual dando seguranca > é mtu mais provavel que vc tenha uma segurança maior.
  + cenario de medo mas tbm toda pressao e responsabilidade por estar criando uma nova civilizacao é a primeira coisa que as pessoas vao pensar, se isso der errado quando vc tem aquela base de apoio aquele medo seja um pouco mitigado, divido entre vc e essa divindade que esta cuidando de vc.
  + POI2G -> Pq apoio na religiao do que em si mesmo -> vc ja tem uma pressao mtu mtu grande -> todas essas pessoas vao ter essa pressao dentro delas -> lidar com essa pessoa e com as pessoas ao redor dela.
  + unica chance de criar um mundo mais plural e respeitoso
    - religiao é extremamente importante -> é mtu improvavel que no nosso mund otodas as religioes(mais importante) consigam conviver de forma respeitosa, preconceito de historia, novo mundo melhor chance
* DPM - Fischer
- 1 op foge do onus -> proprio onus de algum poder religioso -> partindo da premissa que vao ser menos religiosa n faria sentido fazer esse debate, nos temos que entender o onus de cada bancada o nosso é abdicar possivel caridade e o onus da oposicao leva de preconceito que possa vir junto. 2100 é só pra tecnologia(n sei)
- medo do desconhecido
  + a religiao te concede seguranca? -> a tecnologia nos concede mais seguranca -> se eu vou nadar entre os tubaroes é mtu mais seguro que eu fique numa jaula de tubaroes(lol) do que eu deixar na mao de deus, as pessoas se sentem mais seguranca(no novo mundo é tecnologia e religiao vc n refutou)
- reducao de preconceitos
  + a religiao sempre é conservadora, statuos quo 500 100 anos atras, conceito de dogma(cosmogonia quando se cria o mundo, esse proprio dogma impede a concepcao de casais afetivos, sociogonia, criacao de sociedade) -> se eu negar ese dogma eu nego o deus. manutencao da realidade primeira. quando nos vamos com o ateismo apenas temos averdade cientifica.
    - impacto
      + reducao de preconceitos, pessoas lgbt, negros, hereges n segfuem a moral especifica -> vida pautada pela propria existencia, lutar para n serem perseguidas -> no nosso mundo as pessoas vao ter a vida pautada pelo confoto
      + poi1o -> vc nega que apesar desses dogmas esses preconceitos tao sendo mitigados -> hoje em dia nos temos religioes que estao extremamente preconceituosas -> vcs podem criar uma religiao perfeita esquilo(agr faz um pouco mais de sentido)
      + n tem ideia de um grupo escolhido por deus ou por deuses(tipo judeu) ->
      + comparativas
        - desenvolvimento cientifico -> nova sociedade nos temos cooperacao -> metrica do debate ter uma boa cooperacao, essa ausencia de medo -> nos queremos fazer uma sociedade funcionando -> para ciracao de uma sociedade do 0. nos precisamos ter esse desenvolvimento cientifico para as pessoas sobreviverem, sociedade unida(insipiente) pessoas comecem a gerar extremos conflitos, ideologias comunismo e liberalismo podem ser pacificadas -> n tem uma questao que é inerente, religiao tem algo INERENTE(isso é importante) -> metodo cientifico é binario. analisar o com mais felicidade
* DLO - Malau
- espantalho do fischer -> quando as pessoas nao sao toa mais fundamentalistas e tals -> o que a iza ta tentando dizer é que dogmas mudam ao longo da historias e religioes n condenam mais negros. religiao é um reflexo da propria sociedade. igreja catolica falando de divorcio.
- religiao é importante pelo aspecto individual, nada pode se comparar
- poi rached -> as religioes se pautam de livros sagrados, impedimos progreso social de mil anos atras -> blz lol
- como a sociedade seria extremamente essencial
  + chance de construir um mundo melhor a partir de agr
  + principiologicamente errado
  + erram quando assumem que mandamos pessoas fundamentalistas -> pouco provavel, as religioes mudam -> pessoas capazes, melhor economistas do mundo, n existe vinculo logico entre ser ateu e ser mais capaz.
    - marie curie filha de catolica fervorosa. n existe vinculo de genio da ciencia.
    - perspectiva snecessarias, chance mtu maior de u mundo mtu melhor
      + melhores pessoas, a gente ta falando de mandar as mais inteligentes, levariam consigo preceitos da religiao, poderia mandar um economista que é budista, n só traria consigo todas as coisas de arcabouco cientifico que ele já tem. esse processo de ir pra um planeta novo, é atraves disso, maior pluralidade que a humanidade n foi capaz de resolver. budista tem a oportunidade de ver buda no espaço(?>) maior probabilidade de flexibilizar a religiao. religioes mais poderadas n trazem um mundo pior mais melhor -> temos as coisas boas de uma religiao ->
      + economia intrinscamente ligada a etica protestante
        - algo horrivel -> priva humanidade da propria historia -> mesmo no cenario do mundo ATEU, n tomaria conhecimento que já houve religiao -> privando humanidade de conhecer a si mesma. religiao é um aspecto inerente da nosa historia, privando de se conhecer a si propria, conhecer a si mesmo. coisas que evoluiomos. n conhecer a nossa historia é ruim, pq nao aprendemos o que erramos.
        - sabendo de onde a gente veio é importante saber onde vai, em termos principiologicos é importante(ela n explica, traz utilitarismo) -> ainda efeitos nocivos, a gente estaria nos privando de uma coisa muito mais importante, conhecimento é essencial para o desenvolkvimento humano(utilitarismo), principio de conhecer a si mesmo(exemplo?)
* MG - Karol
- qq a gente tem aqui? religiao foi usada na sua construcao para embasar alguns dos maiores problemas estruturais que nos vivemos, embasamento perpetuacao discursos e narrativas que oprimiram as pessoas
- ja que esses humanos sao ateistas, essas pessoas tem um conhecimento do que acontece na terra. se a gente imaginar hoje ja acontecem problemas de guerra, discursos de odio, que tem a religiao como resposta como fundamento, a gente imaginar o ano, a gente pode imaginar um cenario pior.
- construram um melhro mundo sabendo das consequencias negativas que os discursos religiosos tem sido utilizados.
- a gente vai ta utilizando se essas pessoas ateistas vao desvincular a questao do religioso
- agr elas n vao ter que recorrer a um ser superior, n vao ter que justificar com base na religiao -> n vai botar a culpa num ser supremo para poder legitmiar a opressao danosa para algum grupo especifico, esses humanos individualmente essas pessoas vao estar cada vez mais responsaveis pelas suas proprias atitudes, pq agr n vao ter uma desculpa(foi pq deus quis, ta na biblia)(isso é novo) n vao ter uma desculpa baseada na religiao. vc tem uma quebra significativa, esses seres humanos utilizam elas para fazerem. agr eles vao ter que enfrentar e utilizar a propria racionalidade, n vao poder usar o discurso que tem um ser superior.
- a gente vai ter agr uma quebra mais estrutural do preconceito e todas essas questoes negativas, a gente vai ter agora um pensamento mais individual de cada pessoa. e agr elas vao estar utilizando a razao de forma mais ativa(rached e fischer)
- mesmo que no nosso mundo a gente tenha essa questao de apoio a religiao, mesmo n tendo esse apoio, n só a religiao vai trazer, elas podem se apoiar umas as outras(fischer) -> a gnete entende que a religiao é de certa forma um conforto, tem outras formas, essas pessoas tem outros metodos para se apoiar, essas pessoas vao individualmente um pensamento. a questao do ser superior. questao mais racional. utilizar a religiao como resposta.
* MO - Leonardo
- n apenas pessoas ateias
- todos os governos falam que essencialmente a religiao é ruim -> esquecem de contextualizar a ciencia como disputa de narrativa. modificacao de framing
- n apenas uma logica crista
- religiao é importnate para consolidacacao da sociedade
  + durante toda a historia a religiao fez parte da humanidade, mil e uma religioes -> as religioes respeitam uma logica de fe, de que a gente tem um proposito melhor. em meio as dificuldades, a construcao desse miticismo é mtu importante para ultrapassar barreiras, importante acreditar em algum proposito, nesse novo pais é um planeta desconhecido, inumeras dificuldades, n vai ser facil.
  + as pessoas que so acreditam na ciencia, a partir do momento em que seus dados acabaram, elas acabaram, a crença que acabou n se limita aos dados e as questoes, ex; pessoas hoje em dia passando por dificuldade, forma de se assegurar e conseguir driblar as suas dificuldades, atraves da fe e das suas crenças. consolidacao da humanidade hoje em dia.
  + fischer -> quanto mais insipiente mais autoritaria ela é, azteca usaram escravidao, caso ainda pior -> vou responder o poi no segundo argumento
- ciencia faz parte narrativa de poder
  + religiao enquanto opressora, luz divina que vai desenvolver -> ciencia disputa de poder -> a ciencia mtas vezes foi utliizada de forma como oprimir as pessoas (darwinismo racial, foi a expressao da ciencia, pra naturalizar atraves de metodos cientificas pessoas negras sao inferiores, conhecimento orientais sao deixados de lado) -> n pode ter olhar cego para ciencia. olhar enviesado, como unica coisa boa, vai respeitar a estrutura da sociedade que é tbm opressora, alicercada a um grupo dominante, justamente essa ciencia quando a gente limita, ta limitando o debate democratico, a gente paira sobre esa questao.
  + pessoas religiosas que nao sao fundamentalistas -> padre fabio de mello, dialogo com outras vertentes, e n ta focado apenas naquela ciencia -> pq é melhor que os arugmentos, importancia da relgiao de enfrentar dificuldades, regulamentar vivencia de umlugar, muitas coisas perigosas. cenario razoavel
  + como a ciencia pode ser usada para opressao a religiao abre o debate, discusas cientifica.
* WG - Vanessa
- de que forma diferencia do 1g
  + reducao de preconceitos do 1g dogma inquestionavel
  + questao estrutural -> por mais que eu quebre por causa do dogma -> questao de poder simbolico -> n tenho conciencia que estou inserida -> n evnvolve questao estrutural(?????) -> quebrando questao estrutural -> tudo que eu estou fazendo no mundo to justificando com base no religioso -> a pessoa se sente confortavel em ver o negro naquela situacao, inconscientemente naquele poder simbolico -> afastando to dando maior protagonismo -> eu vou estar questionando e quebrando poder simbolico(o dogma n é a porra da estrutura????)
- 1 op
  + religiao n é a unica base de apoio -> colegas passando pela mesma pressao -> por mais que esteja tudno um caos vc tem uma pessoa lá
  + no momento que mesmo que todfo mundo esteja com a mesma pressao, nos estamos juntos nessa, vendo todo mundo lá na merdda comigo a pressao diminui(excludente?)
  + extremamente eficiente
    - pq é mais benefico? -> apoio da religiao vc abre para questao estrutural e simbolico -> vc vai estar se sentindo bem e apoiando aquela situacao -> n so to tendo mesmo beneficio, no moento que estou em mim edentro do meu colega, protagonismo, me libertando desses dogmas e preconceitos, sociedade mais justa e mais benefica.
    - cenario planeta extremamente pareicdo com a tela -> beirando colapso desse planeta(???) -> urgente e necessario que a gente tnha essa sociedade melhor e mais equilibrada(todo mundo concordou qe era a metrica) -> a religiao é responsavel por toda essa qustao estrutural, é algo tao antigo que esta enrriazado(fukin DOGMA)
    - n tem forma de conforto melhor, n explica pq ser ontologico é tao bom
  + vai apagar a historia da humanidade
    - a historia n vai ser apagada, historia da humanidade é diferente da historia da religiao -> os ateistas tao vindo do planeta tera, eles sabem tudo que aconteceu lá, vc pode falar da historia da humanidade sem aquilo, nos vamos deixar pessoas ateias que podem saber da historia da humanidade, pq é melhor por pessoas ateistas, perpetuando esse dogma, n voa estar enviesadas.
  + 2 op
    - caso extremamente fraco, n me explica pq essa regulamentacao da sociedade pela religiao é boa, vamos gerar esse poder simbolico, n acontece com o protagismo social
    - ciencia utilizada num cenario de poder -> atipicos e antigos(oxi, religiao) -> status quo estrutural por meio da religiao e ciencia.
* WO - Victoria
- 1g -> a religiao atrasa o conhecimento cientifico -> pior cenario possivel pessoas altamente extremista, quem vai ser levado n necessariamente sao pessoas, a base de nenhum ocnhecimento cientifico.
  + religiao com religiosidade -> religiao religar, todo ser humano ligado a lgo -> ja a religiosidade é que esta imbutida pelo homem para religiao, ela no passado que atrapalhou o conhecimento cientifico(WTF) -> acreditamos que a tera n é mais planta.
- 2g -> a religiao responsavel por todos os mares do mundo(ai exagerou man) -> religiao é algo que traz conforto, traz fe, ela consiga se sentir relaxada, toda sua doar para um ser superior, n é responsavel por todos os males do mundo(holocausto, negros devem morrer) -> esses sao problemas trazidos pela antiguidade instalacao da propriedade privada -> uma pessoa so por ser crista ou budista ela n é necessariamente aceitar -> mesmo uma pessoa sendo ateista -> que ela vai se desfazer dos preconceitos.
- reducao do preconceito -> religiao é conforto é amor, e a religiosidade é instalada pelo homem mas n colocadno ela em cima da religiao
- 2op n vai no pior cenario possivel(tratado pelo 1g) -> acreditam no fetichismo cientifico -> ciencia foi responsavel porvarias mortes no passado. eles falam que a religiao é menos propicia para ter conflitos Cesare Lombroso metodos cientificos.
- a gente mostra da 1op de modo mais eficaz sendo levada ao nosso novo planeta é algo importante que vai
- POI 1G -> exagerarm todo, se a religiao n atrapalha a ciencia, lobby transfusao de sangue -> existe m n quer dizer que foi aprovado. n vao ser pessoas extremistas n seriam levadas, n vao ser consideradas mais propensas a isso.
- a gente n trabalha no pior cenario possivel

* CALL
- 1g > 1o > 2o > 2g
- 1g > 1o > 2o > 2g
- 1g > 1o > 2o > 2g
