#+TITLE: Debate03
  - MESMO se a moção não tivesse nenhum efeito prático, mesmo se a moção
    literalmente trouxesse um backlash negativo prejudicando o mundo real, ainda
    sim nós acreditamos que o correto é indiciar o Bush. E é por isso que nosso
    caso é o mais relevante, porque todo mundo sabe que o cenario mais provavel
    é que o Bush seja indiciado, e nao seja responsabilizado de nenhuma forma.
  - Direitos existem porque são necessários para humanidade florescer, ou porque
    eles são necessários para que você seja tratado como ser humano em primeiro lugar.
  - O teste lógico para considerarmos algo um direito fundamental e inviolável é
    pensar: se nós violássemos isso constantemente, você ainda seria reconhecido
    como humano?
  - É por isso que o Direito a vida não é considerado absoluto, mas a dignidade
    humana e a legitima defesa são, todo ser humano tem o direito de se
    defender, independentemente das consequencias desse ato. Guerras acontecem o
    tempo todo, a gente considera até normal matar outros seres humanos, mas até
    mesmo dentro de uma guerra existem limites(Justamente a tortura)
  - Se eu torturasse alguém continuamente, ou tirasse seu direito a legítima
    defesa, ele ainda estaria em um estado em que poderia lhe considerar humano?
    Ou eu olharia pra ele e o consideraria tão deturpado que não me pareceriam
    condições dignas de um ser humano?
  - Nós acreditamos que Bush cometeu um ato horrendo, ferindo a lógica mais
    basilar da humanidade de um indivíduo em si, isso não deve ser aceito de
    forma alguma pois
  - Imagine qualquer resultado que você acredite ser bom (como maximizar
    felicidade, por exemplo).  Sempre ira surgir a questão: porque esse resultado
    em  específico é bom? Algo só é bom não é porque é desejado, mas porque o ser
    humano identificou ele como uma coisa boa e ativamente escolheu tornar aquilo
    uma coisa boa em sua vida. O quão bom essa coisa é não vem de ser, por si só,
    desejável, mas sim da dignidade e autonomia humanas que a tornaram algo a ser
    alcançado. O prazer e felicidade só são bons porque a autonomia e dignidade do
    ser humano possibilitaram que assim fosse visto, então não faz o mínimo
    sentido minar ou ignorar a autonomia e dignidade humana para maximizar
    felicidade e prazer. Felicidade e prazer são bens secundários, o bem primário
    e fundamental seria a dignidade humana.
  - Resumidamente, o que eu to falando é que a tortura recorrente e sistematica
    criada durante a Guerra ao Terror, significa em principio violação moral
    MAIOR do que até mesmo assassinato, sim, tortura é pior do que genocidio,
    por que? Porque quando vc tortura alguem seguidamente, voce tá literalmente
    matando o ser humano, sem dar nem mesmo a possibilidade de alivio com a
    morte, é infinitamente pior do que assassinato, o ser humano tortuado, deixa
    de ser ser humano, ele vira um mero objeto, perdendo toda sua dignidade se
    tornando apenas um meio para um fim.
  - Precedente
    - O que é uma corte internacional?
    - Uma corte internacional é um mecanismo do direito internacional que julga
      esses tipos de casos
    - E o que uma corte precisa na maior parte dos casos para poder indicar alguem?
    - Voce precisa de uma requisição legal, ou seja, voce precisa ter algum
      dispositivo normativo que mostre que determinado individuo violou alguma lei
      ou tratado -> No caso especifico mais provavelmente o tratado de genebra
      sobre crimes de guerra
    - Mas não só isso -> A maior parte dessas cortes internacionais, devido ao
      fato que os tratados acabam por serem muito "perenes" "porosos" "pouca
      densidade normativa", eles não sao extremamente precisos.
    - Se baseiam na lógica dos precedentes, a WTO é o mesmo, o GATT, etc
    - Voce precisa de um precedente pra embasar as suas decisoes
    - A partir do momento em que a gente indicia o George W Bush, nós concordamos
      que no pior dos casos, mesmo ele sendo condenado, o mais provavel é que ele
      não enfrente nenhuma punição, até porque o Bush continua tendo um certo grau
      de influencia no partido republicano
    - Entretanto, com esse tipo de incidiciamento e talvez até acusação, nós
      abrimos um precedente pra uma nova classe de individuos que causam danos tão
      grandes quantos a ordem internacional mas que antes não eram nem mesmo indiciados
    - Antes as cortes internacionais só agiam nesses senhores da guerra do
      terceiro mundo o Kony em uganda eu acho, o Slobodan na iuguslavia etc. Essas
      pessoas nao tem o mesmo perfil do Bush, que efetivamente ficava longe da
      "sujeira" digamos assim.
    - Agora a gente tem um precedente pra indiciar pessoas nesse estilo
    - A questão é que nem todos lideres desse estilo vão ter o poder e influencia
      do Bush, e esses sim podem ser indiciados e efetivamente condenados.
    - Que tipo de pessoas a gente tá pensando? Literalmente qualquer despota
      minimamente apresentavel para a comunidade internacional(Um exemplo é o
      governo atual do Myanmar em relação aos Rohingia) Essas pessoas normalmente
      não são indiciadas, porque não se encaixam no esteriotipo classico de
      Ditador africano vestido com roupa camuflada e matando gente com as proprias mãos.
  - Mini vertical
    - Isso tem um novo impacto principal.
      - Aumenta ainda mais a aversão do público americano para esse
        intervencionismo que só causa danos.
      - Ainda mais em um período em que o grande público já está esquecendo dos
        horrores de uma guerra, justamente pelo esfriamento das operações seja no
        Afeganistão seja no Iraque, inclusive boa parte dos soldados lá hoje em
        dia são contratados privados que muitas vezes nem mesmo são americanos
      - Qualquer indiciamento atual, significaria necessariamente em publicidade
        extrema durante o discurso do processo
      - A transparencia que a Carol fala, é extremamente necessaria porque ela
        pode ser usada por todos os não-intervencionistas atualmente em
        Washington, como muniçao para qualquer intervencionista no país.
      - Nós não acreditamos que a moção gera backlash, justamente porque no lado
        dos democratas/liberais americanos já odeiam o Bush de qualquer forma, e a
        base republicana conservadora, com a ascenção do Trump se deslocou
        completamente dos antigos republicanos do Bush, o Trump pegou o partido e
        virou de cabeça pra baixo(Ex: Ele xingando o John Maccain depois de ter
        morrido) (A forma como ele desrespeita as lideranças tradicionais
        republicanas) Isso significa qeu de um lado você tem munição para qualquer
        pessoa que não queira que o EUA se envolva em mais guerras, do outro você
        não tem maior radicalização do lado mais conservador do espectro político.
