#+TITLE: Debate04
    - Contrafactual
    - Mundo em que não houve um declinio do Marxismo
    - Por que nos aplaudimos esse mundo?
      - Imagine um mundo em que partidos marxistas continuam tendo força
      - O partidos comunistas na alemanha, na frança, na inglaterra não vão
        progressivamente perdendo seu poder na politica, no reichstag, em
        westminster etc
      - A gente tem que entender como se deve esse declinio
      - Se deve a partir da substituição progressiva da Esquerda pelos Sociais
        Democratas e Democratas Cristão exemplo da Alemanha.
      - Essa galera que assume controle na decada de 50
      - Consegue formular um milagre economico(Que nao foi devido ao Plano
        Marshall, exemplo o Brasil ter gasto mais que ele na nova matriz economica
        e mesmo assim não ter conseguido o mesmo sucesso)
      - Essa galera ganha o poder e consegue isso
      - Entao só por isso nós não lamentamos, porque o marxismo perdeu o seu poder
        nas democracias liberais ocidentais, não pode golpe, não por opressão, mas
        porque perderam o poder nas urnas. E aqui não existe fragmentação, num
        mundo em que o declinio não acontece, os sociais democratas
        permanecem, os marxistas pegam uma porcentagem desses votos, e
        consistentemente quem sempre vai ter controle dos parlamentos, vão ser a
        extrema direita. Porque o voto da esquerda vai estar sempre separado.
        Imagina o que acontece se o PCO vira uma força relevante no espaço
        brasileiro, era possivel que a esquerda nunca conseguisse emplacar um
        candidato no segundo turno. > O exemplo do Joao Doria é circunstancial,
        do mesmo jeito eu posso usar o exemplo dos Verdes que hoje em dia sao os
        partidos que mais crescem na Europa(Mais que a extrema direita que anda
        perdendo força)
      - E engajando com o 2G > Com a ideia de coletivismo > A gente entendfer
        que não é mais necessario, porque essas ideias de coletivismo já foram
        enrraizadas até mesmo no movimento liberal, Ex: Os Chicago Boys do FHC
        odiavam tanto pobre que criaram o Bolsa Familia pra acabar com eles.
      - E isso me leva ao meu segundo ponto, que o Marxismo literalmente tentou
        fechar as maiores portas de possibilidade de tirar os pobres do mundo da
        sua situação de pobreza.
        - Por que?
        - A gente tem que entender que a forma pelo qual os paises pobres do mundo
          passaram aconseguir sair da sua condição de pobreza. Até a decada de 90,
          a gente precisa entender que os paises pobres cresciam menos que os
          paises ricos, a ideia de pais emergente só nasce na decada de 90.
        - A partir do momento em que o Marxismo tenta controlar o capital, tenta
          impedir o consenso de washington, formulado, a partir do momento que o
          Marxismo é contra essa busca insesante de produtividade.
          - E aqui engaja com o ponto da Alice -> Sobre como o Capitalismo é
            sustentado com pessoas pobres trabalhando em sweatshops e afins
          - Nos acreditamos que a unica coisa pior do que trabalhar numa sweatshop
            10 horas por dia, é nào trabalhar numa sweatshop por 10 horas por dia
          - O mundo do governo é um mundo que essas pessoas invés de trabalharem
            10 horas por dia na foxconn, vao trabalhar 12 horas por dia no sol
            numa lavoura de arroz.
          - Um mundo em que os partidos marxistas continuam no poder, o que a
            gente tem sao cada vez mais tarifas, cada vez maior proteção
            economica, justamente porque qualquer perca de concorrencia entre
            uma empresa estrangeira e uma nacional, significa necessariamente em
            perca de poder pelo Estado, visto que empresa e Estado é a mesma
            coisa. Isso funciona também quando o país não é necessariamente
            Marxista, mas quando o Marxismo tem força, Ex: O Brasil desde a
            decada de 60 com as politicas desenvolvimentistas. Já refutando
            aquele ponto do JL que dá pra existir os dois(liberalismo e
            marxismo) e a gente conseguir
            algo bom.
          - Ou seja, os paises que tem condições de desenvolver o
            marxismo(Alemanha, França, Inglaterra) que tem um proletariado,
            esses paises nunca iriam tentar desenvolver os paises mais pobres,
            porque isso implica em perca pelo Estado.
            - O que vc tem é uma concentração cada vez maior das riquezas e
              expertises do mundo em poucos paises e povos que tinham condições
              iniciais mais favoráveis.
              - Isso é particularmente importante quando a gente vê que a grande
                queda de desigualdade no mundo > Nao veio na desigualdade entre
                os ricos de um pais e os pobres do mesmo pais, mas entre paises,
                ou seja, a diferença hoje em dia entre o cidadão dos EUA hoje em
                dia e um cidadão da CHina ou India, é dezenas de vezes menor.
          - O que o governo falha em entender é que na epoca em que o Marx
            escreveu mais de 90% de população mundial vivia no que hoje seria
            equivalente a extrema pobreza, hoje em dia esse numero é menos de 10%.
          - Todo o Marxismo pode ser refutado quando a produção agricola chinesa
            passou a aumentar 4 vezes nas decadas após a simples reinstituição
            da propriedade privada nesses locais.
            - Por que? -> Pelo mesmo motivo que o anarcocapitalismo é uma ideia
              idiota, no caso do marxismo todo mundo tende a não produzir porque
              a espera é que todos os outros vão produzir. No anarcocapitalismo
              isso funciona na parte das estradas, rodovias etc, no Marxismo é
              de literalmente toda produção global. Se toda produção é
              transferida igualmente entre os membros de uma sociedade, não
              existe incentivo para produzir.
          - E porque a globalização a lá anos 90 é excelente
            - (NAO FALAR) BERNARDO PEGA A CANETA E ANOTA OS NUMEROS
              - Os EUA na decada de 90 tinha um pib duas, 3 vezes maior que o da
                Uniao Sovietica mesmo com uma população menor
              - Numeros semelhantes podem ser observados em todas as comparações
                entre capitalismo e socialismo
              - A questao é que num pais socialista esse orçamento é 100
                redirecionado para a população, num pais capitalista apenas uma
                fração dessa riqueza é redistruibuida, entretanto quando a gente
                tem uma diferença no PIB as vezes de 2, 3 vezes, até mesmo uma
                pequena taxa de impostos de 33% ainda consegue qeu o Estado
                forneça a mesma qualidade de vida.
          - Engajando com esse ponto da ALice sobre empresas mais poderosas do
            que governos, no mundo do governo o que você tem são basicamente
            empresas maiores ainda, por que? -> Porque inves de voce ter
            diversas automotivas criando carros, num regime marxista voce tem
            uma só empresa de carro passe a existir, e mais importante essa
            empresa vai ser estatal, qual a consequencia disso? -> Que agora o
            que você cria são Estados cada vez mais poderosos -> E qual a
            consequencia disso? Praga em 1957, a principal consequencia do
            Marxismo são super estados que tem condições de literalmente
            esmagar completamente os outros paises menores, não adianta o que a
            republica tcheca possa fazer, ela nunca vai ter o poder da uniao
            sovietica, portanto se no mundo atual nós temos opressão de
            empresas VS povos > No mundo marxista nos temos opressão de Povos
            VS Povos -> Pq isso é ruim? Pq diferente de empresas que sao
            iminentemente racionais -> Povos sao odiosos, racistas,
            irracionais, um mundo completamente Marxista é basicamente a
            opressão da China e India sobre todo o resto do mundo. No pior dos
            casos eu nunca vi a Apple cometer o mal pelo mal, coisa que é o mais
            comum possível quando a gente tá se referindo a povos entre si. E
            antes que a Jessica venha falar que isso tudo é fruto da propriedade
            privada, não haveria nenhum tipo de guerra ou racismo dentro das
            sociedades primitivas, coisa que quando a gente vai ver é o
            contrario, a grande maioria dos fosseis dos indios(pre-1500) e
            aborigenes tem causa de morte violenta.
