#+TITLE: Debate01

- Decisão individual, o que importa são os valores morais do indivíduo, mas
- entrando na lógica do governo de próprio bem estar:
- Ganhos de riqueza não te afetam permanentemente, a tendência do psicológico é
ter um aumento com aquilo de bem-estar e depois se acostumar, mesma lógica
ocorre com pessoas que sofrem acidentes, regressão a média. É pior nesse caso
porque é uma fortuna inigualavel, significa que voce literalmente tira qualquer
objetivo que essa pessoa possa ter, porque no mudno de hoje voce compra tudo com
dinheiro.
- Em contrapartida, esse ganho de riqueza vem com um ônus psicológico de saber
  que você matou alguém, você passa toda sua vida agora tentando se justificar.
  É diferente do que a Alice falou, o fato do capitalismo existir não acaba os
  dilemas morais do mundo, a ética enquanto disciplina inclusive nasce junto do
  capitalismo, assumindo que essa pessoa é um ser humano normal, não o CEO da
  Corporação Evil do Mr.Robot, essa pessoa provavelmente nasceu dentro de um
  framework ética, seja por influencia do iluminismo, seja a igreja, seja os
  islã etc.
- O que a gente precisa provar? A vida de um UNICO ser humano, nas presentes
  circunstancias, é mais relevante, do que qualquer uso que o governo possa
  trazer para a moção, até mesmo acabar com a fome no mundo, que é o melhor caso deles.
- Imagine qualquer resultado que você acredite ser bom (como maximizar
  felicidade, por exemplo).  Sempre ira surgir a questão: porque esse resultado
  em  específico é bom? Algo só é bom não é porque é desejado, mas porque o ser
  humano identificou ele como uma coisa boa e ativamente escolheu tornar aquilo
  uma coisa boa em sua vida. O quão bom essa coisa é não vem de ser, por si só,
  desejável, mas sim da dignidade e autonomia humanas que a tornaram algo a ser
  alcançado. O prazer e felicidade só são bons porque a autonomia e dignidade do
  ser humano possibilitaram que assim fosse visto, então não faz o mínimo
  sentido minar ou ignorar a autonomia e dignidade humana para maximizar
  felicidade e prazer. Felicidade e prazer são bens secundários, o bem primário
  e fundamental seria a dignidade humana.
- Vamos lá
  - Agencia Humana
  - Nós enquanto sociedade, sempre protegemos mais as pessoas que menor agencia
    tem em relação as consequencias
    - Crianças(Menor grau possivel)
      - ECA
      - Coach de debate ensino medio voce nao pode ser amigo no facebook
      - Professores tem que se manter longe de crianças
    - Idosos
      - Proteção da lei
      - Previdencia
      - Etc
    - Pessoas com deficiencia
      - Artigos da ONU
    - O que tudo isso tem em comum?
      - Esses individuos sao aqueles que tem menor agencia sobre o que acontece
        em relacao as suas vidas
      - E enquanto agentes com pouca agencia, nós enquanto sociedade
        consideramos etico e moral proteger esses individuos, justamente pq eles
        tem pouca responsabilidade pelo que lhes aconteceu
    - O que acontece entao quando nós temos um individuo com agencia 0?
      - Caso da moção
      - N é nem muito pouca agencia
        - Ex: Quando alguem é atropelado por um carro, em tese aquilo teve
          agencia 0, porque ninguem escolheu aquilo voluntariarmente, mas
          implicitamente todas as microdecisoes daquele individuo ao longo da
          vida, levaram ele à aquele caso especifico -> E aqui vai refutando
          aquele ponto da Alice da morte, sobre como voce pode morrer de
          qualquer jeito, Ex: Um raio te estourar do nada, ainda sim, as suas
          escolhas fizeram te levar ao local do raio.
        - O caso da moção é diferente, nada que o individuo pudesse ter feito
          desde a sua concepção até o presente momento ia mudar
        - Se nós enquanto sociedade
          - Lógica utilitarismo -> Mato 1 pessoa pra salvar 5, se essa 1 pessoa
            é uma criança, ou um deficiente fisico, de repente existe um calculo
            moral a ser feito, porque existe o grau de agencia daquele individuo
          - Progressivamente quando nós vamos sopesando individuos com menos
            agencia, frente as necessidades de uma massa gigante de pessoas,
            progressivamente a vida dos poucos vai tendo mais valor
          - A moção nós traz a um caso em que isso assume o maior grau possível,
            que é o grau de completo e total falta de agencia
          - Portanto nós nao apertariamos o botão
            - Porque o valor dessa vida é literalmente infinito
            - A moção tem ainda um grau de um ser humano ser usado como um mero
              objeto, um meio para um fim.
              - Pegamos o exemplo do caso em que houve um ato sexual praticado
                contra o consentimento de uma mulher -> Essa mulher não se
                lembra de nada, seu corpo não tem nenhuma marca, o individuo que
                cometeu nao fez mais nada. O crime perfeito
              - E digamos que voce é um membro da policia que sabe do caso
              - Pela lógica meramente utilitarista do 1 Gov, nao houve nenhum
                problema no caso, visto que não houve nenhum desprazer para a
                mulher, a felicidade global do mundo apenas aumentou
              - Mas nenhuma pessoa minimamente sã iria considerar ok não tentar
                prender esse individuo
                - Mas por que isso é errado?
                - Por que nesse caso especifico, a mulher foi literalmente usada
                  enquanto objeto, nao houve nenhum grau de agencia dentro das
                  ações, isso significa que o ato não poderia ter sido mais pecaminoso.
                - O caso da moção é semelhante, numa logica utilitarista nós
                  teriamos uma felicidade infinitivamente maior no mundo
                - O fato do ser humano que morre nesse caso não teve nnenhum
                  grau de agencia ou consentimento, já mostra que o moral
                  framework correto não é utilitarista.
