#+TITLE: DT

Por que nos acreditamos isso
- Aquecimento global
- Aumento na desigualdade/Automacao

- O que nos acredtiamos por pior?
  - Condição material de vida pior
    - Menos comida, calorias diarias, saude, tempo de trabalho etc
    - PARA A MAIOR PARTE DA POPULACAO -> Isso significa que o que importa é onde
      a maior parte da populacao mundial vai viver daqui a 100 anos, que é
      justamente na africa(1 bilhao para 4 bilhoes de pessoas) e no sudeste
      asiatico
    - Nós acreditamos que os ganhos obtidos no mundo subdesenvolvido como a
      china, crescimento na africa vao ser efetivamente destruidos pelo
      aquecimento global e pela automacao
- Framing
  - Um mundo com um aumento significativo nos efeito estufa
  - Nada indica que isso vai mudar
    - Corona, pessoas nao se importam, porque é um problema global que todo
      mundo tem pouco poder
    - Exemplos:
      - TOdo ano batemos recorde de efeito estufa
      - No presente momento já temos milhares de mortes
      - Ondas de calor
      - Desertificacao da linha do saara
      - Falta de agua no oriente medio, tudo de ruim
  - O que isso significa?
    - Os paises mais vulneraveis sao aqueles que sao mais pobres
    - Curiosamente sao os paises que vao começar a entrar na renda media nos
      proximoas 15/20 anos
    - Mas nos proximos 15/20 anos que nós veremos as piores reacoes ao
      aquecimento global
    - Ao mesmo tempo nos temos a populacao da africa projetada para 4 bilhoes,
      Poque a africa é um caso a parte, que é um continente que hoje em dia
      cresce muito, mas de alguma forma a sua taxa de natalidade nao diminui,
      locais como nigeria que hoje em dia se aproximam cada vez mais da renda
      brasileira, continuam a ter mulheres com numero medio de filhos igual a de
      30 anos atrás, enquanto que o brasil por exemplo hoje em dia é igual a europa.
    - E por que a tecnologia nao vai no salvar dessa vez?
      - A gente precisa entender que a tecnologia nos salvou duas vezes, na
        revoluacao industrial, na revoluacao verde na decada de 30
      - Mas nunca a gente teve uma diminuicao na área aravel e um aumento da
        populacao, o problema portanto tem o dobro da urgencia
  - E isso significa que cada vezo mais fica mais dificil
    - E cada vez fica mais caro arar a terra, sendo que os paises que mais vao
      precisar disso, n vao ter chegado a aquele patamar relativo
  - O que nos projetamos portanto?
    - No proximos 10/15 anos nós temos uma evolucao continua na qualidade de
      vida global
    - MAS, a partir do momento em que os paises começam a exaurir os seus
      recursos naturais -> Ex: O petroleo na arabia saudita, os minerais raros
      na republica democratica do congo
    - Nós temos cada vez a possibilidade desses paises sairem do ciclo de
      pobreza diminuindo
    - Ao mesmo tempo em que esses recursos que possibilitam um pais ficar rico
      diminuem, ou acabam
    - Nós tbm temos uma diminuicao na área arável e nos recursos de subsistencia
      - Por exemplo o mar entrando nas áreas cultivaveis litoraneas
      - Issso em contrapartida a uma populacao maior é um ambiente perfeito para conflitos
      - E por melhor que os ultimos anos tenham sido pra populacao como um todo
      - Paises que entraram em conflito acabaram por piorar, Ex: Siria, O
        oriente medio como um todo é hoje comparativamente mais pobre do que a
        30/40 anos atrás
      - O que nos projetamos portanto é um aumento nos conflitos. QUais
        garantias nos podemos ter? O genocidio de ruanda foi um exemplo disso, a
        populacao do pais cresceu muito, a ponto de que cada pessoa n tinha
        subsistencia, e o genocidio ocorreu
      - O genocidio de darfur no sudao em 2010, foi em grande parte porque
        grupos do norte, invadiam as terras dos povos do sul em busca de pasto
        para seus rebanhos, que n tinham justamente por causa da desertificacao
        do saaara. Isso significou 100 mil pessoas mortas
      - Tudo isso implica num maior numero de conflitos
- Tecnologia
  - Ele só dá uns exemplos
  - Internet
    - Nao é verdade, a primavera arabe nao diminui
  - Vacina
  - A Siria é mais pobre que antes, SE A GENTE PERMITE QUE NAQUELE PAIS HAJA PAZ
    ESSE É O MEU PONTO
  - E porque esse crescimento acelerado nos paises subdesenvolvidos nao vai
    acontecer mais?
    - A pobreza extrema caiu vertiginosamente em paises como a India, China,
      VIetnam etc
    - Por que isso aconteceu?
      - Por que esses paises se introduziram nas cadeias de producao globais,
        justamente por meio da globalizacao
      - Ou seja, o pais que antes era compeltamente isolado e onde todo mundo
        morria antes dos 40, agora por causa das intensas trocas comerciais,
        começa a ter acesso a uma economia globailizada, a tecnologias de
        economia globalizada e todas as coisas boas
      - Mas pq isso acontece?
        - Por que ou esses paises tem algo a ofercer em termos de recursos
          naturais, o que ja foi explicado que n vai ter mais como explicado anteriormente
        - Ou mao de obra local
          - Locais como a india, bangladesh, vietnam ficarma ricos justamente
            por conseguir acessar esses mercados globais oferecendo mao de obra
            mais barata
          - E por que eles ficaram ricos com isso?
            - Vou usar o exemplo da china, voce começa oferecendo mao de obra
              barata, a partir do momento que voce começa a oferecer isso,
              significa que voce de repente aumenta o capital humano, porque o
              pouco de dinheiro que vc tem vc pode oferecer pra educacao
            - E de repente vc vai ficando cada vez mais especializado com certos objetivos
            - De repente vc começa a criar empresas proprias, voce começa a
              fazer produtos de alta tecnologia e comça a ficar rico,
      - Ou seja, se agente prova que essa porta de entrada dos paises para a
        riqueza diminui, isso significa que esses paises nao vao ficar mais
        ricos, portanto a gente ganha o debate
        - E porque essa porta de entrada vai acabar?
        - Porque de repente a gente começa a ter cada vez mais automacao
        - Isso já é algo exemplificado no caso dos EUA Entre cada 10 empregos
          diminuidos no EUA, 1 foi por outsourcing e 9 foram por automacao
        - ACABA COM POSSIBILIDADE DESSES PAISES FICAREM MAIS RICOS
        - GLOBALIZACAO DIMINUI PQ SÓ EXISTE TROCAS ENTRE PAISES RICOS, PAISES
          RICOS VAO TER CAPACIDADE DE APENAS TROCAR ENTRE SI
