* PM - Maju
- Retórica, pratica da boa eloquencia, como faziam os sofistas, na grecia
- Essa eloquencia n está ligada a uma argumentacao que faça sentido
- O status quo as pessoas aderem pela retorica religiosa sem qualquer tipo de
  pensamento critico, com a pessagem da moção -> Haverá estimulo ao pensamento
  crítico, vai mudar por exemplo Bolsonaro, que era colocado como escolhido de
  Deus.
- As pessoas se deixaram se levar na última campanha
** Impacto
- Teriamos também o foratalecimento da democracia como estimulo ao pensamento
  cŕitico, democracia esta ligada ao poder ao povo, as pessoas estariam
  realmente preocupadas, e engajariam nas politicas, se preocupariam com os
  debates na TV
- Evitaria o que aconteceu ontem, influencia n só os periodos de campanha, mas
  todo um governo posterior, ontem em horario nobre, presidente ocupase em falar
  de coronavirus sem pensar na ciencia e razão, sobre a desculpa de n sei, Deus
  curaria as pessoas, a associacao que as pessoas fazem. Sobre posicionamentos
  preocupados com a real argumentação.
  4:30
** Formulação Alternativa
*** Afirmação
Com a moção passando nós teriamos uma melhora na discussão política e mais
pensamento crítico.
*** Explicação - Dois motivos
**** Motivo 1
As religiões diferentes dos outros tipos de discurso tem uma característica
principal -> O dogma -> Isso significa que os axiomas religiosos não foram
feitos para serem questionados -> Isso também significa que os textos religiosos
duram muito tempo. Ex: O velho testamento com mais de 6 mil anos, o Corão com
mais de 1200... -> Isso significa portanto que a retórica religiosa não comporta
experimento nem questionamento -> A partir do momento em que você introduz a
religião dentro da campanha -> Pessoas religiosas, que vêem aquilo como centro
da vida delas, vão começar a levar a religiosidade do candidato como palco
principal -> E como religião é dogma -> Necessariamente elas teriam menos senso
crítico na hora de sua escolha.
**** Motivo 2
Na religião o lider religioso é um condutor de Deus -> Ex: O papa é quem
interpreta a palavra de Deus, o Aitolah é quem interpreta a palavra de Allah, e
os pequenos pastores a mesma coisa embora em menor escala -> Isso significa
portanto, que questionar o lider religioso, na mente de muitas pessoas é também
questionar Deus -> A partir do momento em que esses lideres religiosos passam a
colocar suas posições políticas(Ex: Um lider religiosos indo para comicios
apoiando candidato X) -> As pessoas de sua congregação que normalmente poderiam
ter escolhas divergentes, já que elas não estariam contrariando ninguém "acima
delas" -> Passam a ser obrigadas a concordar com o lider -> Isso não só
enfraquece a liberdade delas que foi de certa forma coagida -> Como também
diminui a discussão política -> Já que uma grande parcela da população
simplesmente deixa de participar das discussões.
***  Impacto
Portanto nós teriamos um discurso político mais enfraquecido, o que
necessariamente implicaria em candidatos piores -> Candidatos piores implicariam
em políticas públicas menos eficientes -> O que prejudica justamente a parcela
da população mais vulnerável, que é quem depende disso, são stakeholders
extremamente relevantes e em grande quantidade.
Não só isso, como o discurso pode também permear a vida política do candidato,
já que ele se sente obrigado, pra não "trair" o ideal dos seus eleitores, o que
causa por exemplo uma desconfiança com ciência...(Exemplo que você deu)
* LO - Rafael Costas
- Nessa relacao pros e contras seria mais malefico Pq? -> O povo é meramente
  religioso, tem uma religiao em si, mesmo que não praticante, baseia sua moral
  nisso, aquilo que é certo ou errado, deve ser seguido ou não. Essa é a
  linguagem que o povo utiliza -> Se o Estado vem e bane esse atrelamento, ele e
  esta distanciando o representante com os cidadoes, aqueles que justamentre o
  legitimam, falta de comunicacao entre eles. Vai tirar algo que faz parte das
  vidas das pessoas.
- Quando vem uma força maior e tira o habito da qq qqs pessoas, elas ficam perdidas,
  como vao ocupar aquele tempo, nao entender como a situacao esta, isso traz um
  impacto extrememante malefico.
- Corte de comunicacao n traz democracia mais forte, pelo contrario.
  2 Min e meio
* DPM - Maria Karoline
- Refutação -> Enfraquecimento do sistema, mas que sistema? o status quo que
  vivemos, essa retorica religiosa n vai trazer de fato um enfraquecimento, e
  sim um fortalecimento, o status quo a retorica religiosa é embasada em
  religioes evangelicas, vc n tem um enfraquecimento, mas fortalecimento pq
  todas as pessoas podem ser ouvidas, de todas as religioes e tbm quem n tem
  nenhuma religiao, n existe um enfraquecimento do sistema, pq quando vc coloca
  uma pessoa que utiliza de retorica religiosa, vc a cab tirando a possiblidae de
  outras religioes e sem religiao serem ouvidas(Pq?) -> N teram seus direitos
  basicos garantidos, todos seus esforços para garantir.
  2 MInutos e meio
* DLO - Jordania
- Quando Karoline fala que o banimento da retorica é viavel com o argumento que
  pessoas de outras religioees n poderam ter seus direitos guardados, eu
  discordo, tanto as pessoas que tem uma religiao cristã, todo mundo tem seus
  direitos separadamente. Retorica religiosa somente a um grpo religioso guardar
  os direitos de todos os cidadao, tanto cristã quando outas religioes, contanto
  que a retórica.
  1 Minuto e 50
* MG - Danilo Ferreira
- embora seja majoritarialmente catolico, desde os tempos de colonizacao, foi
  trazido pra cá, a maioria das pessoas sao cristas, mesmo sendo na politica tem
  que estar envolvido com alguma fé em deus, n seria justo com pessoas de outras
  religioes. Nosso presidente atual, bolsonaro, criticando outros grupos Ex:
  Bolsonaro LGBT.
- Grupos de outas religioes, mulheres. Isso n só afeta essas pessoas mas pessoas
  de outras religioes, Estado brasileiro é laico, isso é forçar a ideia que n é
  laico, politica com religiao n combina, n é justo usar ideais de uma religiao
  especifica em nome de campanahs políticas, só favorece o preconceito com
  pessoas de outras religioes, bolsonaro pretende colocar pessoas cristas pro
  cargo de ministro.
-
* MO - Sena
- Ninguem pode ser completamente isento da religiao, pois ela faz parte da nossa
  moral coletiva e individual
- Ex: Questoes delicadas, ela vai uma hora ou outra usar a religioes como supoerte
- N tem como ser totaslmente insenta, cerceamento da liberdade de expressao,
  abrir precedente para persiguiçao politicos e grupos religiosos.
- Faca de dois gumes -> Pois vai também servir grupos politicos, silenciaamento
  de grupos religiosos minoritarios, muito melhor controle e bom senso, a
  extinçào o
- Busca completa falta de religiao n é laico, é estado ateismo, subjulgacao do
  Estado a religiao
- toda discussao religiosa monitorada pelo Estado
- Ex: Deus abençoe a america -> N tem problema nenhum, pioneiros da democracia
  republicana que temos, simbolo de democracia
- Partido de Angela Merkel, Uniao democratica crista,
- Autoritarismo e barbarie n é o resultado da retorica religiosa
- Bolsonaro foi eleito n pelo messias foi pelo anti-PT, repulsa pelos erros
  passados do
- Angela Merkel -> Ela n se elegeu utilizando retorica religiosa -> Mas o
  partido dela, vc n se elege de forma direta, vc vota no PARTIDO.
* WG - Jess
- O politico que é eleito, a partir de um discurso de retorica religiosa, ele
  vai aplicar dentro do seu mandato, essa retorica, gera intolerancia e favorece
  preconceito, Ex: Bolsonaro ele utilizava uma retorica religiosa, e isso gerava
  discurso de odio grupos minoritarios, e isso pode afetar religioes menores,
  Brasil é um Estado laico, n deve adotar ese posicionamentos religios,
  enfraquecendo essas outas religioes, menor adesao a essas religioes menores,
  menor popularidade, e mais dificuldade de se perpetuar dentro do tempo, vao se
  sentir agredidas, o proprio Estado que deveria garantir, favorecendo
  detrminada religiao
- O ateismo sao pessaos que n buscam uma religiao , n quer dizer que n sigam uma
  moral, regrar a sociedade, afim de que haja harmonia, convivio harmonico, toda
  e qualquer religiao possa se desenrolar.
- Cerceamento de segunda oposiçao -> Dentro da politica, o politico que tem sua
  religiao, pode exercer ela fora do ambito da politica, pode utilizar-se
- POI(Sena) -> Estado laico, elas podem muito bem da retorica religiosa -> Como
  isso é maléfico, fora da politica cada um tem a sua liberdade de expressao,m o
  problema é dentroda politica, politica vai regular o Estado, se ele usou
  antes, vai se perpetuar, ainda hgoje em discursos da ONU ele cita versiculos,
  e isso é malefico porque gera intolerancia
- Se o Brasil tem uma grande populacao cristã, com o fortalecimento da religiao
  a partir dos politicos, que podem ter dificuldade de eleger, no melhor dos
  cenarios n conseguem, nenhuma religiao pequena tenha voz, Brasil é um país de
  grande pluralidade, prejudica a pluralidade brasileira, isso faz com que as
  pessoas nao se sintam representadas, elas n consigam ter voz na sdo
- Gera uma intolerancia dentro da sociedade, que pod ser fortalecido pelo
  discurso dentro da campanha
- Um ambiente realmente laico faz com que haja maior adesão, um politico sem uma
  religiao n vai afastasr as pessoas de fora das religioes, as pessoas vao ver
  nesse politico neutralidade, vao se sentir representadas por
* WO - Dennis
 - O banimento da retorica, sim seria prejudicial, isso é algo falacioso, uma
   tentativa de contradição, a 1 OP foi infeliz motivo pelo qual n
   enfraqueceria.
 - Todo politico é nada mais é que um representante dos eleitores, ele nada mais
   tá fzndo que evitar a representatividade de um grupo religioso na politica, n
   traz melhoramento da democracia, enfraqueceria a democracia, Brasil populacao
   majoritariamente religiosa, deixo de representar essa pop no congresso, nada
   mais que censurar um determinado grupo.
 - Censura é uma forma
 - POI(Maju) -> Vc acha mesmo que com a retirada, pessoas vao deixar de ser
   representadas pq há varios ouros aspectos, n ligados apenas a religiosidade
 - Resp -> As pessoas que possuem religiao como algo praticanete, se sentem
   melhor representadas, atuantes na religiao, ter um lider religioso.
 - N prejudica a pluralidade, eu estaria tambem prejudicando as religioes
   menores,
 - Metaanalise -> Pq de ser prejudicial
