* PM
- Servicos locais sao geralmente colocados em uma prioridade nesse moção
- Qualidade de vida das pessoas que consomem os produtos -> Transnacionais estao
  solidificadas no mercado
- Equilibrando a balança e equiparando danos
- Nivel regional, micro e macro(Paises)
- 1 Arg
  - Pequenos locais, regioes, onde n existe um bom desenvolvimento, sequer
    possuem bens e serviços de qualidade, baixa variedade. As pessoas passam a
    procurar de outras regioes, mais bem desenvolvidas
  - Por que? -> Oferta e demanda, lá n existe a oferta, que possa suprir a
    demanda, estao indo pra fora por n existir. Se a gente faz que as pessoas
    passam a consumir, cria uma demanda naquela regiao.
  - Mov da economia local, pessoas querendo usufruir dos produtos da regiao.
  - Geração de empregos
  - Esc(Daniel Rocha) -> Se já existe uma demanda -> As pessoas tao consumindo
    de fora e não de dentro, os produtores da regiao nao estao sendo impulsionados
  - Por que elas estao procurando fora? -> Variedade de serviços e gostos, nivel
    regional vai ter que se adaptar
  - Maior variedade de produtos -> Geração de emprego -> Minorias que sao
    afetadas com exodo rural -> Sao afetadas com desemprego por n ter
    oportunidade lá. -> Mais empregos sendo gerados ali
  - Competividade aumentando na regiao -> Se tem pessoas criando expectativa a
    oferta é necessaria, nao vao ficar em uma só pessoas. Uma lógica de mercado,
    se tem só uma pessoa oferecendo. Competicao gera uma melhora na qualidade
    dos serviços.
- 2 Arg
  - Em nivel internacional
  - Se elas consumem os produtos locais e nacionais, sua producao local seja
    estimulada.
  - Grandes empresas que dominam o mercado internacional -> Deixam de comprar a
    cajuina pra comprar a coca-cola
    - Dano a liberdade de escolha, falsa liberdade de escolha, consumidor nao
      possue uma liberdade de escolha??????
      - Pq nao poder optar? -> A partir do momento que o consumidor, e voce vai
        sempre comprar de fora, marginalizacao da producao regional -> N existe
        uma diversidade no mercado, n existem consumidor podendo ter seus gostos
        supridos. Vai apenas escolher oque o mercado pode oferecer.
      - Diversidade é boa, competitivdade.
* LO
- Pq os consumidores nao devem?
- Especializacao -> A gente acredita que ficar comprando produtos locais de
  forma difusa -> Apostar em um unico ponto seu ou comprar de uma empresa de
  fora ->
  - 1 Polo de produto X, garante uma qualidade de fornecedor X, compra da Amazon
    livros C4 Comida, se foca em um unico ponto forte. consegue oferecer um
    produto de qualidade malhor que em larga escala. Ex: SJ rio preto
    - Uma melhor qualidade do produto chegue em outras pessoas. Em detrimento de
      comprar açucar de outro lugar que n é especialista. conseguem COMPRAR o
      melhor produto.
    - O serviço é entregue da melhor forma possivel, aposta na sua
      caracteristicas, competicao difusa, ninguem é especializado em porra
      ninhuma. Ter uma internet pior em BH só porque quem oferece internet em BH
      é ruim.
    - POI(Bruno) -> Visnadi sao megaestruturas muito complexas -> Comprar acucar
      de um unico local, parte do aporte da aeronautica e açucar. N tem
      incentivo para melhora.
    - No cenario que vc compra do serviço local vc tem competicao de baixo nivel
      com varios niveis C4 competindo com o Extra.
    - POI(Saulo) -> Economias regionais que dependem para sobrevivencia
    - Pq é melhor focar em um unico player -> Amazon fornece muitos empregos, as
      warehouses sao mais estaveis, pagamento de imposto mais estavel, forma
      difusa em varios serviços. N sao toa sujeitas e flutuagem de mercado.
      Monopolio malvadao sao mais capazes, maior confiabilidade consegue comprar
      de um especialista,
      - se o seu produto nao vem da forma que vc quer. Consegue procurar a
        empresa e segura como responsavel. C4 independente da seca consegue
        comprar alface.
* DPM
- Danos que empresas transnacionais -> Elas basicamente possuem o dominio de
  varios serviços -> A Coca Cola fornece diversos outros produtos. Elas se
  inserem nas regioes nas localidades para vender esses serviços.
- Esses empregos na maioria das vezes danificam os direitos trabalhistas. Ela
  quer usar a mao de obra das pessoas, mineradoras europeias apenas para
  construir barragens e dar emprego e depois fuder tudo, n se importam com
  sistemas de fiscalizacao -> Muito pelo contrario responsabilizar essas
  empresas.
- Quando essa localidades que n cresceu começa a consumir as transnacionais ->
  Fode os lucros das transnacionais e fode ainda mais
- A gente tenta ao maximo equilibrar uma balança que está totalmente
  desequilibrada, comercio local é muito melhor? -> Equilibrio social é muito
  melhor, essas transnacionais fornecem empregos de trabalhos mecanicos, se a
  gente apoia os autonomos daquela localidade, esse empreendimento pode fornecer
  os empregos que as transnacionais fornecem e ter muito mais autonomos, ainda
  que essa empresa local nao domine o mundo, é muito maior que as pessoas que
 nao estariam se apoiasse.
- POI(Daniel) -> Se as empresas n conseguem atender tao bem quanto o consumidor
  -> Consumidor so vai consumir se tiver o serviço pra consumir -> Se n tem
  serviço vai consumir da transnacional, é  muito obvio que as empresas começem a
  crescer.
- Minorias transnacionais -> Empresa da Nike -> Quem consume nike é rico, e quem
  produz os materiais da nike sao pessoas completamente vulneraveis ->
  Totalmente errado as proprias minorias podem da o seu dinheiro pra produtos
  locais, começarem a destinar esse dinheiro -> Diminuicao de emprego -> ELa nao
  estaria entrando no sistema que oprime ela mesma.
- Ref -> Especializacao -> Se existe uma localidade que é especializada em
  produto X, se eles consumirem, ainda que tiver produto meia boca vai ter competitividde
* DLO
- Especializacao bancada pelas multinacionais -> Bancar o mundo por
  multinacionais, pq elas sao estaveis, contra as grande nacionais nao vai
  bancar.
- Geracao de emprego -> Movimentar a economia -> Como é melhor na logica da op
  -> Especializacao de multinacionais -> Estabilidade e garantia -> Falam de
  equilibrio social -> Existe crescimento social para a familia inteira dentro
  das multinacionais -> Mineradoras que instalam -> Levantam vilas do 0, a gente
  quer essas coisas.
- Geracao de emprego.
- Consumo de produtos nao locais -> Nao necessariamente um cenario de monopolio,
  se tem consumo vai ter provavelmente alguem oferecendo.
- Competicao entre gigantes -> Mercado de gigantes Pepsi vs Coca, BK vs MC, por
  estar bancando.
- Mais multinacioanis regidas pela logica da multinacional -> Ninguem curte ser
  trabalhador autonomo -> Do que viver em qualquer outro cenario
- Resp bruno -> Investimento total, dividido, pesquisa, construcao, prejudica a
  logica da eficiencia
- Costa do marfim se especializando -> Especializacao funcioanl -> Domine um
  mercado, se apoiar nisso para melhorar sua economia como um todo.
- Viver em um mundo com mais multinacionais -> Logica da eficiencia, fornecer os
  melhores produtos, ao melhor modo possivel.
- Lado do Gov tem que arcar com o onus de n ter melhores preços e produtos
- Empresas grandes e violadoras -> Uniao dos paises decida leis trabalhistas e
  ambientais minimas -> Invés de parar multinacionais -> Maximo da melhor
  maneira possivel -> Cenario padronizado -> Expectativa do consumidor seja
  padronizada -> Saber a qualidade -> Quando a gente tá falando de furtas e
  legumes -> Possibilidade de consumo muito mais amplas
- POI(Gui) -> Duas empregas grandes entrarem na logica de competicao -> N
  adianta nada ter muitas pequenas empresas -> Essa logica de gigantes ->
  Pressao por qualidade ->
- Metrica n é só eficiencia -> Do que que eles gostam? Preço -> Garantia de
  qualidade, ganha na disponibilidade de produtos.
* MG
- Mundo sem multinacionais -> N vai rolar uma uniao de todos os paises -> Elas
  vao continuar fazendo o que já fazem -> Elas poluem muito mais que empresas
  muito menores -> Elas jogam muito mais fumaça na atmosfera -> Muito mais
  chance de trabalho escravo -> Pessoas que produzem roupas na china ->
  Multinacionais costumam fazer mais do que empresas pequenas.
- Perigoso que existam empresas tao grandes assim -> Muitas vezes exarcebado ->
  Afrouxar leis ambientais e presidencias _> Lobby, parasitar empresas menores,
  impedir lobby
- Fortalecer o comercio local -> Muito bom focar essa coisa só -> N é muito
  pertinente pro debate -> Bom que a gente só foque na aerunautica -> As pessoas
  nao vao passar a dar menos dinheiro na aeronautica do açucar ->
- É otimo que os paises se especializem -> É muito melhor especializar produzir
  informatica do que cacau -> Sao muito maiores do que produzir cacau -> Mesmo
  se vc for o produtor de cacau melhor do mundo
- Ser bom em algo do produto n é algo intrinseco -> Consequencia de muita coisa
  -> Tornar um pais que é bom produzir cacau -> Produzir computadores -> Paises
  subdesenvolvidos -> Retroalimentando o esquema de enrriquecer os ricos
- A pessoa final que ta recebendo -> DInheiro possivelmente ta indo pra algum
  bilionario -> Que n vai fazer nada bom com isso -> Comprar de algum empresario
  local que n é tao rico -> Ele precisa muito mais daquele dinheiro
- Mesmo em termos de eficiencia -> Tem muito mais potencial de aumentar a
  produtividade -> Já tem produtividade maxima -> Potencial de aumento de
  produtividade -> Ele consegue comprar uma maquina mais produtiva -> Eficiencia
  da producao aumenta ->
- poi -> COnsumidor é onerado eu n quero um computador da positivo -> Curtissimo
  prazo ele vai pagar um pouco mais -> quando ele se industrializar -> vai
  melhorar -> Pq esses paises n conseguem se industrializar -> Pq eles n
  conseguem -> É imsposivel levantar uma industria -> Impossivel competir com
  essas empresas multinacionais -> No mundo onde as pessoas, vai ter uma certeza
  que vai ter demanda, os primeiros degraus.
- Em situacoes de oligopolio global -> Muito mais empresas nesse ramo -> Muito
  mais incentivo para competicao -> Com o dinheiro indo para elas, velocidade de
  evolucao vai ser muito maior, o
* MO
- Esclarecimentos -> Cenarios trabalhando ->
- Reenquadramento -> Majoritariamente paises subdesenvolvidos e emergentes -> Já
  concentram empresas grandes e multinacionais -> E competem mercado locais ->
  Maior capacidade de fornecer materias primas -> Ofercer produtos globais ->
  Diminuicao de qualidade -> Maior parte das vezes as necessidades globais
  conseguem fornecer melhor a capacidade.
- Criacao da necessidades globais -> N trabalham com necessidades absurdamenta
  especificas -> Coisas que o sistema globalizado dizem que todo mundo quer ->
  Por causa das necessidades globais -> Como elas conseguem crescer -> Tem um
  grande onus -> N conseguem atender demandas especificas.
- Deficiencia uma coisa absurdamente global
- Paises subdesenvolvidos, possuem maior taxa de fundacao de pequenos
  empreendimentos locais, demandas locais que ainda n sao atendidas.
- Gov apresenta um mecanismo e mostrar qualidades -> Vc incentivar as pessoas e
  depois as pessoas quererem consumir -> Capacidade do produtor local de
  produzir tudo que ele quer -> Eu quero comprar do produtor local(Leitura da
  mocao, priorizar) -> ELes precisam das empresas de fora também -> Poucas
  pessoas comprando produtos locais de menor qualidade
- Poucos compradores do produto de melhor qualidade -> Pequena elite de menor
  qualidade -> A longo prazo a narrativa do gov deslegitima a propria narrativa,
  esse mecanismo n consegue sustentar ->
- Narrativa de empreendedorismo atendimento das necessidades epecificos -> N
  tornando necessario atender outras necessidades -> Coisas especificas -> N ta
  falando so do arroz ou do feijao mas do acaraje
- As lacunas deixadas pelas grandes empresas -> Fortalecimento da propria ideia
  do mercado local
- Vc reitera um sistema local, atue nos vacuos das grandes empresas.
- Pequenas empresas n conseguem atender tudo. -> Ambito pequenas e medias
  empresas n conseguem atuar(Google e Nubank) -> Alem disso há um atendimento de
  produtos semelhantes -> Joaozinho pizzaiolo ele venda pizza a 10 reais, grupo
  gigantesco de pessoas -> E assim compram o produto dele??????
* WG
- EMpresas multinacionais conseguem com seu poderio economiico -> DOminar e
  ditar e botar as politicas que elas bem entenderem -> Estimular a parte local
  -> Esses consumidores esitmula a industrializacao -> Essas empresas que antes
  eram dominadas -> Bota a politica que ela bem entender -> Proprias taticas de
  dumping -> Tem poderio economico
- Populacao livre dessa prisao -> Importancia da industrializacao -> Mais
  pessoas -> Pessoa rica que mora na regiao -> Sabe que ela pode ganhar dinheiro
  disso -> Agr que ela sabe que a populacao -> É bem mais provavel que ela tome
  aquele risco -> Investir em maquinario em tecnologia para o proprio pais
- Pais se torna verdadeiramente independente -> Impactos mais relevantes
- É justamente a logica que o bruno mostra, inviabiliza a extensao do daniel
- paises subdesenvolvidos mais materia prima -> nos invetermos essa realidade
- multinacionais fazem demandas gerais -> todas as necessidades especificas > se
  vc quer produzir queijo canastra, n precisa de uma industrializacao >
  necessidade especifica > colocam uma necessidade global do produto,  tornar o
  produto global muito mais querido que o producao local
- se voltem mais multinacionais > a logica da multinacional nao cola mais >
- resp 1 op -> logica de competitivdade -> a logica perde, multinacionais n
  precisam competir > podem só chegar e botar a politica que quiser > todos os
  comercios locais > empresas n buscam melhoria n buscam competicao > ter um
  burguer king um mcdonalds e um bobs. quando tem varias pessoas em varias
  localidades >
- POI(Paises alugma coisas, a liberdade ta do nosso lado > cenario internacional
  tem uma dependencia tecnologia do nosso lado. se a gente desenvolvesse elas
  perderiam o mercado > tirando o monopolio > na verdade vem para o nosso lado >
  mais paises subdesenvolvidos.
* WO
- N necessariamente -> quando vc instala uma multinacional > movimenta os
  empregadores > mov textil > alimenticio > quem trabalha sente necessidades
  especificas que o empreendedor local deve sustentar > questao moradia > funcionarios
- a primeira defesa oferecem serviços basicos > quando o individuo > a demanda
  ja existe > demanda n é suficiente para gerar oferta se n tá capacitado para
  produzir, areas lacunosas do mercado, tentar abarcar todo mercado é
  prejudicial > produtos meia boca
- falsa liberdade do consumidor > consumidro tbm esta sujeito a uma falsa
  liberdade > mercado local é mtu mais restrito > menor qualidade > mercado
  globalizado tem um minimo de liberdade para o consumidor > grandes
  transnacionais violam > a busca por lucro é inerente para todo empreendedor >
  local é pior > mercado local age pela informalidade > ademais > multinacionais
  tem maior lucro > reputacao > excessivamente lesivo > por todos esses fatores
  > multinacionais exploram os trabalhadores > ele n prova como o mercado local
  vai garantir os direitos trabalhistas > n vai ter mercado pra todos os
  autonomos > regime mtu mais informal > abusos
- 2 def > rouba da 1 def > burlam a questao por lobby politico > como a primeira
  defesa > fazer os consumidores n vai levar as multinacionais a falencia > ela
  é inficaz > continuar comprando de quem já é forte > nosso caso prova que é
  muito mais efetivo > mercado nas lacunas > mercado inesploxaro
- pOI(ROSSINY) > Mais informalidade vao ter que se adaptar > entao se tu fala
  que quando ele crescer > as multinacionais tbm se adaptar as leis trabalhistas
- mais eles falham a partir do momento que > age com estrategia > investiram com
  estrategia > estrategia mais eficaz > agir nas lacunas das grandes empresas >
  nao suprem todas as necessidades dos individuos > grand empresa n produz >
  abre mercado novos empreendedores > investir num mercado inexplorado >
  investir de forma enfadonha, cercear a liberdade do consumidor > produtos n
  ter tanta qualidade.
- presenca das multinacionais sao essenciais > abrem novos mercados > superar 1
  op > alem da satisfacao do consumidor >
