#+TITLE: 01_07_2020

- Mesa > Eu defendo um mundo onde as pessoas tem o direito de serem preguiçosas.
  E digo que quem defende trabalho é pq nunca trabalhou.
- Newton nao conta porque ele nao estava "PROCURANDO" maximizar nada, ele tava
  fazendo atividade X e de repente depois dele aconteceu.
- Disclaimer
  - Nós acreditamos que os incentivos para trabalhar, se atualizar, estudar etc.
    Tudo isso já existe por natureza -> Justamente porque todo mundo quer viver
    bem, qeur um carro legal uma casa legal > O problema da Decada de Definição
    é que invés de vc ter o incentivo normal que é trabalhar para conseguir
    algo. O proprio trabalho se torna o meio e fim de colocação do individuo
    para sociedade. Isso significa que num mundo sem decada de definição não é
    um mundo de vagabundos jogando lol o dia todo, mas um mundo de trabalhadores
    que vêem o trabalho não como objetivo de vida, mas como meio para se
    conseguir uma vida melhor. Ou seja, MESMO se tiver todo mundo gastando tempo
    com rede social, isso só significa que essas pessoas colocam como valor
    principal o relaxamento, o problema é que a norma cria uma imposição, um
    mundo sem a norma da definição é um mundo que quem valoriza o trabalho
    trabalha que nem um corno, e quem não gosta não trabalha.
  - Qual a métrica desse debate?
    - Nós não acreditamos que a op seja capaz de mostrar que a vida das pessoas
      que estão morrendo de trabalhar seja necessariamente melhor, o que a
      oposição pode TENTAR provar é que a partir do momento que todo mundo tá
      trabalhando que nem um louco, a sociedade como um todo ganha e portanto
      todo mundo no geral tem uma vida melhor. Nós vamos ganhar porque vamos
      provar porque no final isso não é verdade
      - O segundo problema da Decada de Definição é que você cria um cenario
        onde todo mundo tá o tempo todo querendo subir de carreira, o problema é
        que se todo mundo tá tentando subir de carreira. Significa que o patamar
        minimo para crescer profissionalmente necessariamente tá subindo. Ou
        seja, se o objetivo do trabalho era melhorar a sociedade como um todo,
        se tá todo mundo se matando de trabalhar pra melhorar a sociedade,
        ninguem tem nem tempo pra conseguir aproveitar essa sociedade melhor. Ou
        seja, vamos dizer que no momento em que essa norma começa a ganhar
        tração na sociedade. Tudo bem é só o que a Op fala, as pessoas tão
        estudando, tentando consweguir os sonhos e caralho a quatro, o problema
        é que a cada geração você precisa se diferenciar e subir de carreira,
        isso significa que voce vai cada vez mais sacrificar mais, ou seja, algo
        que antes era relativamente saudável e servia como contrabalanço contra
        a preguiça, ao longo do tempo vai se tornando cada vez menos saudavel.
        Chegando ao exemplo de um Japão da vida onde as pessoas trabalham 60/70
        horas pela semana.
        - Voce tem um mundo onde as unicas pessoas que podem aproveitar uma
          sociedade melhor sào justamente aquelas que não trabalham, ou seja, é
          um mundo injusto porque todo mundo que produz tá infeliz, e quem não
          produz consegue aproveitar todas as melhoras na sociedade, o que por
          si só já é injusto.
        - Se cada geração que chega necessariamente é obrigada a trabalhar mais
          que a anterior pra conseguir subir. Isso significa que ninguem tá
          aproveitando os frutos do trabalho.
          - Mas vamos imaginar que o individuo esteja fazendo isso com base em
            poder aproveitar isso quando tiver nos seus 40/50. Se o patamar
            minimo de trabalho tá o tempo todo subindo, significa que essa
            pessoa na meia idade, nunca vai conseguir acompanhar o jovem que tá
            se matando de trabalhar. Ou seja, ele vai se matar de trabalhar, pra
            no final ser substituido por alguem que acabou de sair da faculdade.
      - O problema da "Década de Definição" -> É que você perde a saúde, ou seja
        mesmo se você ganhar mais você acaba gastando mais e você perde os
        melhores anos da sua vida que são os anos em que você tem a
        possibilidade de errar.
      - A norma também na maior parte dos casos não vai trazer um ganho material
        pra sociedade
        - Fator 1 -> Porque quem se beneficia com essa norma não é o trabalhador
          jovem, é o seu chefe
        - Fator 2 -> Porque na maior parte dos casos essa Decada de Definição
          diz respeito a o que?
          - 18 aos 30 anos -> Ela significa que esse jovem antes dos 30 ele já
            precisa ter a sua carreira completa, ele já precisa ter tudo
            definido, casa propria, carro proprio caralho a quatro
            - Mas porque ela é contraproducente até mesmo num cenario pragmatico
              de maior produção da sociedade como um todo?
              - Porque na economia e cenario globalizado e industrializado
                atual, cada vez mais as mudanças tecnologicas estão se
                acelerando cada vez mais
                - Se na idade media eu podia ter certeza absoluta que eu ia
                  nascer um fazendeiero e ia morrer um fazendeiro, porque uma
                  maquina ou uma nova forma de produção não ia tornar meu
                  trabalho obsoleto
                - No atual cenario isso não existe -> Porque não existem
                  condições de eu saber daqui a 20 anos se o emprego de advogado
                  vai ser ou não exisitir. Ou mesmo se existir ele vai ser da
                  mesma forma.
                - A norma de definição não é ruim apenas por fazer com que o
                  individuo seja obrigado a trabalhar que nem um louco, mas
                  porque ela tira o direito do individuo de errar, precisamente
                  no momento da vida em que esse individuo precisa ter o direito
                  de errar, justamente porque ele não tem nenhuma das
                  responsabilidade que um adulto tem(criança, conta, cachorro)
                - Então vamo pegar um cenario _> Um jovem que está nesse momento
                  entrando na faculdade
                  - Se esse jovem tem internalizado dentro de si a ideia de que
                    ele precisa ter tudo definido antes dos 30 anos, isso
                    significa que esse jovem é muito menos provavel de
                    - 1 > Mudar de curso, perceber que aquilo não é mais o ideal
                    - 2 > Após conseguir o emprego ele não vai querer poder
                      começar do 0 em outra carreira
                    - Isso tudo é ruim no sentido micro e macro da coisa
                      - No micro a gente tem um jovem que tem todos os
                        malefícios de importar demais com a carreira - Leia-se
                        se matar de trablahar, nao aproveitar a vida, nao
                        transar etc
                      - No macro a gente tem uma sociedade que necessariamente
                        não tem maleabilidade nenhuma. Porque todos os seus
                        membros não tem capacidade de mudar de carreira, porque
                        se a sua vida é definida entre os 18 e os 30 anos, e
                        esses anos são tidos como indispensáveis e devendo ser
                        aproveitados ao máximo, a pessoa deixa de tentar errar.
                        - No macro a gente também não tem uma sociedade mais
                          produtiva no geral
                          - Pq? -> Pq os empregos que vao realmente criar
                            vantagens competitivas para uma sociedade(Os
                            programadores, os engenheiros, os medicos) -> Esses
                            empregos exigem uma alta carga de criatividade. Que
                            só é desenvolvida quando a pessoa está no seu lazer
                            - É exatamente por isso que os paises europeus estão
                              o tempo todo diminuindo a carga horaria
                              trabalhista, e conseguindo o mesmo nivel de
                              produtividade do que paises como japão onde as
                              pessoas trabalham 60/70 horas por semana.
                      - E a quem isso beneficia?
                        - Isso beneficia grades empresas que compensam a sua
                          falta de inovação e capacidade, com trabalhadores que
                          estão o tempo todo se matando de trabalhar. E que são
                          verdadeiros zumbis.
- Principiologico
  - Nós somos contra a Decada de Definição per si porque ela é ilegitima e não
    beneficia os interesses dos trabalhadores
    - De um lado nós temos uma onda global nos paises desenvolvidos que estão na
      verdade diminuindo o trabalho dos seus empregados e aumentando os horarios
      de lazer. o que vai definitivamente contra a decada de definição
    - E de um outro nós temos empresas presas no método de antes, que exigem dos
      seus trabalhadores horas e horas de trabalho.
      - Por que? Porque os unicos trabalhos que possibilitam voce trabalhar e
        trabalhar são os trabalhos manuais, monotomos. Porque o trabalhador
        criativo quando ele fica cansado, ele perde produtividade, ou seja os
        ganhos marginais de um maior trabalho vão cada vez diminuindo.
        - Essa norma de decada de definição ela só faz com que os trabalhadores
          se matem e matem de trabalhar, pra no final quando tiverem maduros na
          carreira, sejam descartados pela nova geração de jovems.
        - Nós não nos opomos apenas porque ela é estupida para os trabalhadores
          como para a sociedade como um todo.
        - Como ela é estupida por não ser algo definido pelos trabalhadores como
          pelos empregadores.
