#+TITLE: ESL_EUDC_Guerra_Politica_Economica

* PM
- Potencias pressionam e caralho a quatro
- Negociacao é feita por pressoes economicas é totalmente injusta e tendenciosa.
- Resolve esse problema dois fatores
  - Resolucoes de formas mais justas
  - Metodos mais pacificos já que agora eles vao ter medo
- Potencias usam o poderio economico(Iraq, iran kuwait e arabia saudita) n tem
  esse poderio economico, pra poder lutar contra essas potencias e nao podem
  usar o exercito. -> Ficam de mãos atadas -> Se tornam donos dos paises fracos
  e perifericos.
- Os paises fracos se lascam duas vezes
  - O Estado fica enfraquecido, perde o poder sobre a população, deixa de
    conseguir alguns auxilios. Embargo não só lasca o Estado como população, vc
    acaba com a economia daquele pais. Causando fome e tals.
- Resol pacificas
  - Liberado atacar em forma de negociacao -> Agora tá legalizado na lei
    internacional, os paises quando eles forem fazer pressões economicas mais
    intensas, eles vão pensar nos contra-ataques.
    - 11 de Setembro > Mesmo um pais muito grande > Se vc ataca a população >
      Gera medo e repercussão social.
    - POI(GRP) > Se a gente deixar justificado, um ataque totalmente
      assimetrico, retaliando a retaliação -> Paises pequenos podem gerar
      grandes causas, economicamente não.
    - Menos guerras economicas, menos agitação no globo, ataques comerciais
      afetam todo mundo.
* LO
- Jeito de negociacao -> Isso não é válido -> Se a lei internacioanl reconhecer
  isso -> Vc vai ter uma criação de precedente de gastos militares -> Isso não é
  produtivo ->
  - Agr isso vai poder gerar medo pela propria população -> Pop vai ter fome e
    medo -> Todo um estado militar de guerra -> Soldados fazendo tudo e o
    caralho a quatro -> Gerar medo pela propria população -> Ataque assimetrico
    -> Quem consegue projetar danos atraves de apenas danos economicos(São
    potencias) -> Se ele já se quebra com ação não militar, imagina com essa
    ação não militar -> Esses embargos militares são geralmente uma troca
    economica ou algum recurso -> Já que nos somos mais fortes realmete invadir,
    precedente que ele vai atacar, legitima defesa. Criam precedentes para mais
    guerras.
  - Restringem direitos humanos -> Existem outros paises com interesses
    economicos com o mesmo recurso -> Inves de vc criar um escalonamento de
    conflitos vc pode criar uma conciliação(? n entendi) -> Não tenha
    escalonamento.
  - Vc pode ser descridibilizado no roel internacional -> Se vc nao ceder,
    minimamente não ser mais conciliador -> Vc vai ficar mal e perder outras
    relações -> Mesmo ele infringindo esse dano -> Esse pais vai ser
    descredibilizado com um pais que tá justificado a bater em outras pessoas ->
    A propria população -> No cenario de voces isso é descridibilizado
  - POI(Ricart) -> As regulemantecoes ja sao cagadas, a gente pode atacar o
    outro pais, as pessoas ja estao morrendo de fome -> Agr os recursos que elas
    possam usar para comer, vai ser usado pra fazer militar ->
  -
* DPM
- Criacao de um precedente militar -> Isso ja acontece -> Pq ele é tao melhor do
  que o cenario atual? -> EUA vs Coreia do Norte(WTF) -> Se eles se atacarem
  eles vai revidar.
  - Essa legalizacao criaria, cria nivelamento militar internacional, ele é
    melhjor do que um cenario em que ninguem, esse precendete militar é melhor
    do que um pais que nao tem poderio economico, se ele tem o poderio militar
    ele vai aumentar.
  - Medo populacional -> O medo nao mata, a fome mata(????)
  - Punicao -> Isso ja acontece
  - Hiposuficiencia -> Pais pequeno nao barganham ->
  - NIvelar o poderio internacional
    - Mesmo sendo criticados militarmente, esses pais pequenos, embora sofram
      problemas economicos, nao tem nenhuma força -> A partir do momento em que
      essa lei internacional -> MOeda de troca -> Paises vao ter medo do ataque
      e vao procurar solução mais pacificas
  - Pq que é legitimo
    - Soberania só é valida se ele nao invadir a liberdade de outro pais, se um
      pais do oriente medio fechasse o petroleo, petroleo é fundamental para a
      vida cotidiana.
* DLO
- Os pontos de negociacao sao injustos -> A partir do momento que um pais
  pequeno da africa, a frança faz os pressionamentos e esse pais africano faz
  esse confronto militar. Ela nao resolve o problema de recursos, apenas uma
  resposta violenta, quando há essa resposta violenta, vai ocorrer um
  tencionamento, essas subpotencias vao ter que se decidir em qual lado ficar,
  se hoje como a moção, o Brasil se posicionaria a favor de quem? -> Diante
  desse cenario de tencionamento, essas relacoes comerciais vao ser muito mais
  pro lado dos EUA, alem de um investimento militar que nao vai ajeitar nada, só
  vai apenas criar essa rotatividade belica, nao vai resolver nada, e ainda
  vamos ter com essa resposta uma fragilidade das relaçẽs economicas
- POI(Ricart) -> Guerras nao acabam com relacoes economicas, pq negocio é a
  parte -> Existem relacoes economicas, assim como o Brasil tinha relacao com a
  China, o Bolsonaro cortou, guerras nao acabam com a economia, temos justamente
  isso que todo corte na economia vai sim sofrer, exemplos do oriente medio, nos
  vamos ter justmante isso.
- alem de isso ser malefico, n vai existir uma paridade de armas, justamente pq,
  esses paises hiposuficientes nao vao ter dinheiro pra se comparar com o EUA
- POI(Lavijnia) -> Mundo todos paises tem poder belico -> Lavinia a unica coisa
  mais utopica, pais que passa fome vai ter recursos para se armar, China,
  Russia, fukin armas nucleares.
- Vai faltar dialogo.
