#+TITLE: Debate Treino 06_05_2020

- Primeira afirmação?
  - Qual a métrica desse debate? Nós acreditamos que a métrica a qual esse
    debate deve ser tomado é aquele que forneça a transição mais pacífica, com
    menor grau de violencia individual, e que portanto forneça as melhores
    formas desse governo adentrar dentro desses locais, e mudar a situação
    fática que deu inicio a esses movimentos em primeiro lugar.
    - Educacao
    - Sanemanto basico
    - Saúde
  - Caso inteiro da oposição -> Me de um bom mmotivo pelo qual eu enquanto grupo armado vou me render,
    quando eu sei que o que vai acontrecer é que eu vou ser preso, o que a
    oposição propoe portanto é literalmente continuar a guerra até que todos
    os guerrilheiros estejam mortos, todas as vilas queimadas.
  - Essa transição pode ser feita de duas formas
    - Prender todo mundo, prender ninguem, tirar alguns direitos de quem é ex-combatente
    - Quais as vantagens de apenas tirar alguns direitos
      - A perda de direitos políticos oferecem outras vantagens ainda
        - Na maior parte dos casos esses grupos conseguem financiamento por
          parte de conexão com redes criminosas(Justamente pelo fato de que eles
          precisam financiar suas operacoes de algum jeito) -> É assim com o
          Talibã sendo o segundo maior produtor de heroina do mundo e as FARC
          sendo a segunda maior produtora de pasta de coca do mundo.
        - Quando você de repente reintegra esses grupos dentro da vida social,
          você não está necessariamente acabando com os vínculos que eles tem
          com as redes criminosas internacionais
        - E isso se torna um perigo, justamente porque agora eles vao ter
          dinheiro, legitimidade e acesso aos meios politicos padrões.
        - O impacto portanto que é evitado é o desses ex-combatentes virarem
          verdadeiros coroneis em seus respectivos locais de atuação.
      - A terceira alternativa portanto é a de punir, mas sem acabar
        completamente com a vida das pessoas que fazem parte desses grupos, é
        preciso ao mesmo tempo um certo nível de legitimidade extraído através
        da punição. Ou seja, punir para que todos saibam que a lei existe e é
        para todos, mas não tanto a ponto de causar uma ruptura brusca na vida
        das pessoas.
    - E quais as outras alternativas?
    - A alternativa mais dura
      - Por que é preciso entender que em muitos desses locais esses grupos são
        gigantes, em certas regioes quase do afeganistão praticamente todo homem
        fisicamente capaz é membro do talibã
      - E qual o mecanismo que garante que esses grupos são tão integrados
        dentro da sociedade local?
        - Como esses grupos conseguem se sustentar? É justamente por meio do
          apoio da população local, nenhum grupo guerrilheiro consegue a
          logistica, os suprimentos e etc sem o apoio da populaçao, justamente
          porque eles sao soldados, nao sao fazendeiros.
          - Portanto qualquer grupo que permaneca minimamente no poder
            necessariamente tem apoio de uma certa parte da população local,
            justamente por se mostrarem uma altrnativa ao governo central que
            muitas vezes é distante e omisso.
      - Qual a consequencia portanto de prender todos esses ex-combatentes
        - Você tem o efeito backlash, só
          que dessa vez pelos familiares e circulos pessoais desses
          ex-combatentes. O que é particularmente nocívo para qualquer governo
          que queira conseguir legitimidade nessa população
        - Esses homens muitas vezes são os ganha-pãos de familias com vários
          integrantes, prender toda essa população significaria portanto acabar
          com qualquer potencial de angariar renda desses grupos, não só
          destruindo a economia local, como criando novos combatentes, que dessa
          vez em vingança ao governo por ter matado seus pais, tomam as armas.
    - A mais branda é fornecer completo e total anistia a esses grupos
      - Entretanto essa alternativa causa mais violencia ainda
      - Por que?
        - Qual o mecanismo? -> Na maior parte das vezes as violacoes aos
          direitos humanos embora sejam feitas em um framework de violencia
          sistemica, na verdade ocorrem em contextos individuais
        - O que eu quero dizer? Os agentes que perpetuam a violencia se
          aproveitam do contexto de anarquia para poder fazer avançar seus
          proprios objetivos pessoais
          - Ex: Massacres cometidos durante o genocidio em ruanda não por ódio
            aos tutsis, mas para conseguir roubar a fazenda do seu vizinho
          - Ex 2: Delatores durante a guerra civil russa que se usavam do
            contexto para poder subir de carreira dentro da burocracia
            destruindo os rivais
          - E por que isso importa? -> Isso significa que dentro de todo
            contexto de violencia existe milhares de pequenas "picuinhas"
            individuais esperando para explodirem, pequenas vendetas e casos
            familiares, que só ocorreram inicialmente por causa dessa situacao
            de anarquia
          - Portanto -> Integrar esses ex-combatentes dentro da vida civil, sem
            nenhum tipo de punição cria uma grande efeito backlash, em todas as
            pessoas que por anos se viram esmagadas pelos individuos desses
            grupos e que agora vêem eles com total impunidade.
          - E não subestimemos o sentimento de impunidade -> COisas como grupos
            de exterminio e de vigilantismo são muitos comuns em toda a america
            latina e especialmente em locais dominados por esses grupos.
    - Ou seja, de um lado nós temos uma parte da população que apoiava esses
      grupos e precisava dele do seu sustento, e do outro uma população que
      sofria diariamente sob a égide desses grupos.
    - Ganhamos o debate portanto, ao fazer a comparação entre todos os cenários
      possíveis e demontrando porque a opção do meio termo defendida pelo
      governo acaba sendo a que causa uma integração sem maiores violencias e
      com menos efeitos nefastos a longo prazo.

- Whip do Governo
  - Por que ganhamos do 1 GOV
    - Por que não assumimos que essas pessoas são necessariamente piores ou mais
      violentas do que qualquer outro. Nesse caso assumimos um cenário mais
      plausivel em que essas pessoas sao gente como a gente, com interesses com
      possibilidades etc.
  - Por que ganhamos de 1 OP
    - A Justiça para aqueles que sofreram a violencia
      - 1 -> O debate não é sobre as FARC, FARC é um exemplo
      - Me de um bom mmotivo pelo qual eu enquanto grupo armado vou me render,
        quando eu sei que o que vai acontrecer é que eu vou ser preso, o que a
        oposição propoe portanto é literalmente continuar a guerra até que todos
        os guerrilheiros estejam mortos, todas as vilas queimadas.
      - 2 -> Na maior parte dos casos a gente não pode assumir essa ideia
        maniqueista de esses grupos são um bando de bichos papão que só fazia
        genocidio e que não tinham nada na mente além de matar.
        - Ninguém entra em ressureiçao armada porque tá tudo bem maravilhoso, se
          esses grupos foram minimamente bem sucedidos significa que eles
          receberam o apoio de pelo menos uma parte da população(não toda e é o
          motivo da gente não simplesmente anistiar todo mundo) isso significa
          que existiam injustiças sendo feitas. Seja abusos dos latifundiarios
          colombianos, seja a truculencia da invasão sovietica no afeganistão.
          Isso significa que esse punitivismo exarcebado da 1 Oposição também
          esquece das injustiças perpetuadas pelo governo.
  - Por que ganhamos da 2 OP
    - Pessoas violentas
      - Elas não tem nenhum interesse na forma democrática -> O Taliban já fez
        acordos com o governo central de Cabul -> As FARC entraram em acordo com
        a Colombia
      - Ele não entende o que é anistia -> Anistia é do momento do acordo pra
        baixo, significa que se as FARC voltar a luta armada, esses ações
        posteriores ao acordo, vao ser punidas obviamente
      - Em que tipos de grupos isso vai ser aplicado e o que eles não entendem?
        - Por que um grupo que antes não acreditava no processo politico passa a acreditar?
        - O Taliban é um grupo formado desde a invasão sovietica do afeganistao
          na fukin decada de 80
        - As FARC é o maior conflito em termos temporais, sao mais de 50 anos
        - Os governos centrais MUDAM, eles não sao organismos monoliticos, em
          ambos os casos da moção, ela só acontece se os grupos consentirem
        - Antes eles não se rendem porque a alternativa é morrer
        - Eles não vão ficar putos PORQUE NINGUEM TÁ OBRIGANDO ELES
        - O que o governo oferece é uma alternativa de negociacao
          - Se eu sou o lider do taliban, e de repente eu vejo que a guerra não
            faz sentido mais
          - Eu não vou poder convencer meus membros a se rederem, porque se a
            gente se render é que as familias deles vao ficar vulneraveis porque
            o pai vai ser preso.
          - A moção fornece um meio de saida, para pessoas que já estao cansadas
            de guerra.
