#+TITLE: DT_19_06_2020

- Um mundo com aborto, a moção assume isso > Se a mulher precisa ser paga
  - N existe coercao estatal, significa que existe um contrato, nao tem como
    voce ter um contrato com alguem, em que a pessoa se compromete a nao cometer
    um crime
- Modelo: Igual ao que a gente tem para contratos em que existe uma grande
  disparidade de poderio entre as partes. Ex: Direito do consumidor com onus de
  prova, as protecoes que já existem. E que nós acreditamos que o direito tende
  a favorecer mães nas cortes.
- Em principio pq é melhor?
  - Pq qual a ideia central do aborto?
    - A liberdade da mulher
    - E porque a liberdade da mulher é ferida no status quo?
      - Pq assumindo que o aborto é legalizado, significa que a mulher tem
        liberdade para poder não ter a criança
      - Mas e a liberdade que a mulher tem de TER a criança?
        - Nós acreditamos que a mera possibilidade legislativa dessa mulher ter
          esse filho não é suficiente
        - É preciso haver possibilidade fáctica
          - Condicoes materiais dessa mulher ter essa criança
          - Fralda, mamadeira, brinquedo, caralho a quatro
          - Se um dos argumentos a favor do aborto é que muitas mulheres não tem escolha
          - A gente com esse mecanismo tá justamente dando essa escolha, a
            mulher que antes não tinha condições de ter a criança, agora tem
          - Onus da oposição provar como esse mecanismo nao aumenta a liberdade
            da mulher
          - A liberdade caracterizada como principio, justamente pq nós enquanto
            sociedade acreditamos que todos tem o direito de realizar o seu
            potencial maximo enquanto ser humano. O que para certas pessoas pode
            ser a maternidade.
          -
          - Não só como no pragmatico nós também ganhamos
            - Pq? A vida dessa criança e dessa mãe vai ser melhor > Pq qual o
              principal stakeholder? Mulheres qeu não tem condições de arcar com
              uma gravidez, agora elas passam a ter, o que nós temos
              essencialmente é literalmente dar dinheiro pra gente pobre.
              Aumentando a liberdade dessas pessaso.
              - Pq nós acreditamos que outros casos não seriam aplacados? -> Pq
                se voce tem dinheiro, voce simplesmente nao precisa qeu te
                paguem pra ter uma criança, se vc quiser abortar vc vai, se vc
                nao quiser voce nao vai. Esse nao é o debate.
              - Voce melhora a vida da propria criança, porque no pior dos casos
                essa mulher agora tem condições de provavelmente arcar com um
                pre-natal, imagine a mulher que nao iria abortar em ambos os
                casos, agora ela tem condições de ser paga por isso, mesmo que
                seus planos originais nunca fossem o de abortar, a gente garante
                portanto uma gravidez melhor para essa mãe, a gente garante uma
                menor possibilidade de mortalidade infantil.
            - Nao acreditamos que o sistema seria abusado
              - Pq? > Pq gravidez é um negocio complicado. Não se carrega uma
                criança por 9 meses por uma quantidade de dinheiro irrelevante,
                ou para apenas jogar essa criança num orfanato logo após.
              - Pq? Pq é punk, exige muito tempo e esforço
