#+TITLE: DT_22_05_2020

* PM - Rafael
** Case
- Nós não somos contras os movimentos de minorias
- Nós somos contra _> Atrlacao > Grandes empresas
  - Essa propoganda serve para uma simples valorizacaso da marca e nao se
    preocupem com a causa
    - O que mais prejudica a causa > Causa uma banalizacao de tudo aquilo > De
      todo o discurso que aquele grupo utiliza >
      - Propagandas sao postas > Exposicao ao senso comum > QUando a minoria é
        apresentada > Ela é apresentada de uma forma extremamente esteriotipada
        e de acordo com o modelo que a sociedade enrraizou de quem é aquele
        individuo
      - As vezes nem isso (Ex: Campanhas de shampoo de marcas de produtos para o
        cabelo > Mesmo trazendo a figura negra nao trazem aquela pessoa que
        realmente possui as caracteristicas da galera da figura negra > Negro
        que é mais esbranquicado Como um labio nao tao carnudo) > Isso nao
        agrega nenhum valor aquela causa
      - Aparicao de homosexuais em tv e campanhas publicitarias > Individuo
        extremamente exagerada > (Esteriotipada)
      - Isso leva justamente, banalizacao daquele discurso > Desmistificam e
        divide a opiniao em relação o que se deve se lutar em relacao a
        identificacao.
* LO - Karol
- Contexto geral > Essas causas sociais LGBTq, Racismo, Mulheres sao causas
  deixadas de lado, elas tem ganhando mais visibilidade. A maioria das pessoas
  nao leva em conta > Essa populacao é grande mais marginalizada.
- 1 Gov fala (Valroizacao da marca, apenas lucro) > Mesmo o objetivo sendo só o
  lucro é melhor que elas façam isso e coloquem essas pautas na midia como é o
  contexto da grande midia. > Começam primeiramente com o lucro.
- 1 Poonto
  - Alcançe dessas pautas > Marcas muito famosas > Traz essa populacao que é
    excluida para o consumo em si > Na maioria das vezes esas marcas sao
    destinadas a grupos privilegiados > QUando tem uma campanha anti racismo da
    Nike cria visibilidade que atinge os clientes tradicioanis(Ricos) > Essa
    pouplacao marginal se vê podendo comprar um tenis da nike e isso é normal >
    Parte
- 2 Ponto
  - Aumenta o proprio mercado > Além dos privilegiados voce ganha um novo mercado
  - Essas empresas sao fortes e grandes > Começam a fazer esse marketing > Mesmo
    que seja um lance de lucro no inicio > É melhor voce ter do que não ter >
    Essas empresas fortes > Estao conseguindo apoio da maior parte da população
    > Essas empresas menores vao ver que as grandes tao fazendo > Vao ter que
    fazer também > Vai acabar dando mais visibilidade ainda > Integrando essa
    populacao que é marginalizada (Ex: Victoria Secrets, ela tem um padrão das
    suas lingeries surgiu a faint(Marca da Rihana) que atende todos os corpos e
    perdeu o mercado)
* DPM - Lucas
- A gente é a favor do marketing mas nao atrleado a empresas
- Marcas nao estao objetivando aumentar esse discurso ou ter ele difundido na
  sociedade > Apenas o lucro
  - QUal o problema disso?
    - Gerar enfraquecimento dessas causas sociais
    - Enfraquecimento de discurso
    - 1 OP > Compra o onus da exposicao erronea que as marcas propoem >
      Exposicoes esteriotipadas > Esteriotipo dos LGBTs, mov feminista
      - Pq isso é ruim? > Cria uma problematizacao do discurso > Essas causas
        sao muito além do que uma menina negra fazendo propaganda de shampoo. >
        N é porque uma marca como a Nike tá fazendo algo que na Arabia Saudita
        vai mudar.
      - A partir do momento que a gente expoe de forma errada > SOciedade vai
        criar um esteriotipo sobre aquilo > Ex: LGBT feliz, nao coloca o
        homosexual passando por preconceitos, extremamente feliz, boa condição
        de vida > Isso faz com que os movimentos enfraquecam >
        - Ex: Movimento feminista > Mulheres se vangloriando por não serem
          feministas por causa de um esteriotipo que a midia criou. > Midia
          criou um esteriotipo.
        - No lugar de ter avanços vamos ter regressos. Ex: Victoria Secrets
          prega uniao feminina, mas prega mulheres bem sucedidas dentro de um
          padrão > Por anos nunca teve mulher negra > Cancelou seu desfile por
          nao ter mulheres plus size > Compradoras antigas, foi cancelado por
          causa da plus size.
        - Não tá visando criação de debates, inclusão de debates.
        - ALém de um discurso contra a causa é extremamente sobre a visao dessas causas.
* DLO - Layse
- Não está aqui pra discutir a intenção para colocar os efeitos e se existem
  mais pontos positivos do que negativos.
- Não há duvida que a visibilidade tem um grande alcance > Ex: Victoria Secrets
  temos empresas que surgem a gordofobia no momento em que surgem outras
  empresas todas as outras vendo que esse mercado cresceu > A gente traz essas
  pessoas > É uma cadeia, influenciando outras marcas.
- Justamente porque essas mercas estao visando o mercado > É Por isso que elas
  vao ouvir > Vao se transformando junto a isso > Há uma troca de cobranças >
  Ex: COmunidade LGBT apoiando uma marca por ouvirem, se há uma coisa que nào é
  tao legal assim, advento da internet. Há mais pessoas incluidas > Aumento no
  consumo, o que beneficia a economia tudo mais.
- Ex: Bandeira LGBT das propagandas > Banalizacao > Eles colocal em evidencia >
  E com isso a elaboracao  > É com fortalecimento com criticas com discussoes >
  Não há banalizacao
- Ex: Esteriotipada > Isso não é um problema causado pelo marketing é um
  problema estrutural, o primeiro passo para voce incluir essas pessoas > E com
  essa inclusao e visibilidade a gente vai mudando o esteriotipo > Mesmo tendo
  um determinado esteriotipo que isso vem a ser debatido > Melhor debater > Nem
  se quer
- N é pq uma marca faz propaganda que vai ter resultado > Vcs estao subestimando
  a causa da representatividade >
- Trouxe questao do feminismo que perdeu credibilidade > É muito simplista voce
  falar isso > FEminismo está em evidencia em muito por causa da ade
- POI(Lucas) > Solucionar os esteriotipos trazendo mais esteriotipos > Ele nao é
  criado pelas marcas independente do tipo > E voce colocar isso em evidencia >
  Forma de desmstificar isso Ex: Pauta feminista, pauta liberal > No momento em
  que voce tem o feminismo liberal em evidencia > Voce abre espaço para que
  outros tipos de feminismo falem > Haja a critica > Voce precisa conhecer uma
  causa para criticar a forma que ela está sendo exposta > Mais importante voce
  sentir que nào tem espaço nenhum > Primeiro passo importantissimo
* MG - Joao Manoel
- O foco desse debate > A sociedade > As causas(Pessoas representadas) e nos
  temos as empresas
- Por que essa casa lamenta?
  - Esse tipo de propaganda > Qual o principal objetivo dessas marcas? É o lucro
    > QUal o principal objetivo das minorias aceitam > É a busca por
    representatividade
  - E por que essa casa lamenta o marketing > Falsa ideia de representatividade
    > Esse tipo de marketing trabalha diante de um esteriotipo
  - Representatividade totalmente falhas > As pessoas negras grossas nao se
    sentem representatividas
  - Qual o status quo?
    - Cenario de polarizacao politica e ideologica > Comportanto mais facil que
      elas criem repulsa ao que vai contra sua logica ideologica > Visao ruim >
      Visao esteriotipada >
      - Pessoas cristas criando uma devida aversao a essas causas >
      - POI(Karol) > Podem criticar o esteriotipo, gerar um debate > criar uma
        discussao sobre esteriotipos, só que o objetivo nuncna foi criar debate
        dentro da scoeidade minoritaria > Mas dentro da sociedade maior > Essas
        pessoas vao criar respulsa
        - No melhor cenario nao vao aderir de forma legal > Mas atraves de
          esteriotipo >
    - Pq alcance não só basta? > Nao basta somente colocamos > Sem um debate
    - VIes de empoderamento nao contribui visto que as pessoas nao sao
      representadas pelo marketing
    - Formacao do padrao colocado > Padroes já existem > Padroes colocados pela
      sociedade nao sao de senso comum > Padrao de senso comum sao padroes de
      aversao > Adesao no melhor cenario vai ser seletiva.
* MO - Maju
- Mundo sem marketing de causas > Marcas nao se preocupariam > Negação da
  diversidade > Propagandas apenas com as elites > E enquanto isso num mundo com
  marketing de causa
- Ex: Negros com esetriotipo brancos > É Muito melhor do que nem termos negros
  em propagandas > Com o avançar dos movimentos >
- POI(Lucas) > Nao negamos que quer a existencia de um mkt mas de algo
  relacionado a marcas> Propagand esteriotipar a galera?????????????
- Até uma mulher negra com esteriotipo de negro > MUdança vagarosa >
- Primeiroa oposicao nao mostra o mecanismo > Vejam a causa > Comportamento de
  manada > Individuos em grupos reagem da mesma forma independente da direção >
  As pessoas nao aceitarem já é o status quo > quando vc nem sequer via uma
  mulher negra num desfile > Esses movimentos tem variadas demandas e elas
  sempre estarao avançando > Mais interesse em criar interesse > Identidade >
- Ex: Escolas hoje alteracao nas questoes de genero > Embora tenhamos
  resistencia > Muitas pessoas acabam por > disseminar ideias com maiores
  aceitacoes >
- Causas feministas estao fortalecendo > Causas da gordofobia > Mulheres amem
  seus corpos do jeito que eles sao >
* WG - Carolina Gerhardt
- Toda historia é só pra boi ver e
- Como a gente ganha do 1g
  - Já existe uma dicotomia muito grande, galera conservadora vai ver mais, vai
    aceitar da forma pra fora > Nao incita nenhum dialogo verdadeiro > To
    comendo da batata frita só pq eu gosto de batata frita.
    - Vc n está promovendo um dialogo verdadeiro
    - Posso botar num programa televisivo, isso sem vai ser muito mais eficiente
      do que simplesmente expor, imagens que mostem uma tolerancia, vai causar
      muito mais raiva.
    - 1 Op > Melhor das os primeiros passos começar um esteriotipo mais fora > O
      negro do traços mais grossos vai ter que lutar > Vai gerar minimamente um
      despeito > Por que ele vai necessariamente desdobrar > Já foi aceito >
      Gera um despeito > Eu estou disputando com quem mais deveria ser meu
      aliado > Gerando uma linha naquele movimento. (1g falou isso???)
    - Estou gerando um enfraquecimento dentro do proprio movimento(Isso é bom
      mas é novo)
  - Somente as empresas grandes vao ganhar
    - Se o McDonalds tem muita visibilidade > Bota a bandeira gay > Todo mundo
      vai querer comer e a batatinha daquele podrão > Ele n tem uma bandeira gay
      > N colocam esse mkt de causas?????
  - Tem tanto negro correndo de nike, atraves de metodos que promovem um dialogo
    >
* WO - Lavinia
- 1 Gov > Pior caso possível > Essas empresas so aderem ao lucro > N existe
  empresa que queira lutar por aquele movimento >
  - Banalizacao do discurso > N me mostram esteriotipos(Eles mostram) > Mkt já
    está tentando desesteriotipar uma sociedade que n aceita LGBT, que n eaceita
    mulheres em propagandas
    - Ex: Boticario dia dos namorados, n há uma banalizacao do discurso esse mkt
      tá lutando para desesteriotipatizar.
  - Nao compram o melhor caso possível. Chanel, mulheres aderirem > N pq ela
    queria lucro mas pq queria representatividade. Quanto mais pessoas lutando
    pro-minorias melhor.
  - Movimento feminista só cresce cada vez mais > Mulheres imersas numa
    cultura conservadora > O mkt de causa aceitacao cada vez mais da mulher.
- 2 Gov > Falsa ideia de representatividade > Colocam mulheres negros sao
  aclamadas pelo publico e eles cancelam as marcas que nao sao pro minorias >
  As pessoas reclamam > Elas nao estam se sentindo mal representadas > Elas
  querem mais >
  - N é onus da oposicao mostrar como vai mudar uma sociedade como um todo >
    homosexuais vao se sentir representados >
  - Rivalidade enfraquece > Individuos que sao CIS nao necessitam de
    representatividade já sao a maioria > Diretamente e sempre foram
    representadas > Minorias trabalharem com pessoas que sao maiorias >
  - Livre mercado medias e pquenas empresas vao começar a ideia de mkt de causa.
