#+TITLE: DT_29_04_2020

* PM
- Status quo -> Existe industria do belo, cultura do belo
- Objetivo do mov feminista > Promover um bem estar das mulheres de maneira
  geral, não só igualdade
- Falar que a beleza não importa, é melhor do que falar que todos os corpos são bonitos.
- Quando você fala que tudo é belo, você mantem a beleza enquanto um critério
  que deve ser relevante e nesse sentido o efeito não acontece.
  - Porque você continua dando uma valorização do corpo, aspectos da industria
    da moda, que criam esses padrões de beleza.
  - Quando fala que a beleza não importa em si, você foca em outros aspectos,
    deixa de ser tão relevante como era antes.
  - Se todos os corpos sao bonitos eles ainda tem uma relevancia. E isso é bom
    porque tira ao menos alivia a pressão que sob as mulheres.
  - Minimamente mitigar o aspecto da beleza.
  - POI(Marcus) -> Até quem não está submetida, as pessoas que não se submetem
    estariam contempladas pela narrativa -> Existe essa industria, e ela
    enforça, e vai afetar direta ou indiretamente, umas vez que as pessoas que
    estão sob o aspecto da industria da moda.
  - POI(Marcus) -> Se existe um padrão de beleza, algumas pessoas sao mais
    bonitas que outras. Admitindo que todas sao bonitas isso é mitigado. -> Você
    não tem só esses critérios. Você ainda vai dizer, as pessoas não vao achar
    isso. Ainda vai ter gente que não vai ver o corpo como bonito. Quando tu diz
    que a beleza não importa de fato.
* LO
- Algum parametros importantes: Uma ideia de beleza, porque ela é importante.
- A beleza é importante para construção do mundo, perpassa todos os mundos,
  monumentos e discursos, a beleza. A sensibilidade é algo que a gente percebe a
  gente sente a gente vê. É uma parte extrememanete importante para a psique da
  psicologia humana, vai permear tudo que minha vida.
- O que não importa é os padrÕes definidos pelo marketing.
- A beleza é necessaria para construção do mundo, para digerir o mundo eu
  preciso ver as coisas como mais sensiveis. Eu preciso dessa beleza para que
  ela entre dentro de mim antes de tudo.
- Devido a beleza importar ela cria o empoderamento feminino. A beleza cria uma
  certa autoestima, não estou falando do padrão de marketing, beleza X ou Y. A
  beleza em si, que pode ser a sensibilidade que cada um traz pra si. Quando eu
  tenho beleza eu consigo me construir enquanto pessoa. A gente tira a
  capacidade de contemplação de autoestima de cada um.
- Quando a gente tira, a gente não vai ter norte, a beleza não importar eu não
  vou ter um norte. O que vai realmente importar? Ao dizer que beleza importa eu
  estou dando empoderamente. Voce é bonito com tuas marcas com tuas cicatrizes,
  porque a beleza cria sensibilidade para qualquer pessoa. Quando a gente cria
  esse conceito de sensiblidade para a beleza pessoas se enxergar melhor.
  Mulheres mais empoderadas, aceitar seu padrão. Sim você tem beleza, ela
  importa no mundo mas não vai depender de padrão X ou Y.
* DPM
- POI feito pelo Marcus Felipe -> Nem todas as pessoas se submetem ao mundo da
  beleza ao mundo da moda -> N é confirmado > TOdas as pessoas sao submetidas. A
  gente tem que lembrar que beleza importa? Existe um padrão social.
- Trouxeram toda uma argumentação, q beleza que importa? Ao longo da historia
  foram construidos varios padroes. Mitigação do aspecto da beleza, por que a
  gente não quer que a beleza seja mais importante? Vai trazer uma varolização
  dos aspectos secundarios -> Como inteligencia, carater, todos que não são
  levados em conta.
- Stakeholder das mulehres > As mulheres são sempre só vistas como corpos, se
  elas tem determinado corpo da moda. Quando você levnate a bandeira de que a
  beleza não importa, que elas olhem para outras caracteristias, como a
  inteligencia o carater. Você vai provavelmente acabar fazendo com que a
  sociedade outros elementos sejam avaliados. A blz qeu a gente tá falando aqui
  é um padrão social não é todos os tipos de beleza. Isso faz com que as
  mulheres se sintam desestimuladas e n se sintam confiantes.
- Questao economica -> Grandes industrias da moda de maquiagem, com essas
  questao da beleza, sempre colocam > Essa questao da beleza > Construi toda uma
  questao de um marketing de consumo. Pressão social, seguir um padrão. Só
  continuem aumentando seus lucros. Se concientizem na questao do consumo, eu
  realmente preciso daquele produto, consumo mais consciente. Valorizando outros
  aspectos como inteligencia e carater.
  POI(Joao) > Excluindo pessoas com problemas mentais > Quando a gente valoriza,
  que abeleza não importa, a sociedade que outros aspcetos que não somente a
  beleza. Somente existe um padrão de beleza.
* DLO
- Situacao apenas hipotetica e impraticavel.
- Como ser humano sua ideia da beleza, qualquer aspecto, cada ser humano sempre
  teve algum estilo que mais lhe agradou. Por que aquilo foi de acordo com a
  personalidade.
- Adotar o discurso que todo mundo é bonito, todo mundo pode ser bonita para
  outras pesssoas ou até para elas mesmas.
- Industria da moda pode e deve ser combatido, também é algo que nem todo mundo
  precisa seguir, adotar um molde que necessariamente, caracteristiacas
  particulares.
- Quando vc adota o discurso que abeleza n é importante > N pode ser praticado,
  na mente humana.
- Blz não é importante e não deve ser.
- Discurso qeu uma pessoa vai se sentir feia, autocompreensao do ser humano, ele
  nao se aceitar ainda, ele n realmente compreender seu corpo enfim. Seria muito
  melhor se ohuvesse uma reeducacao, autoaceitacao, caracteristicas e tal. Pode
  ser bonito para alguem, é bonito para si mesmo.
- Se vc apaga o adjetivo, as pessoas vao ivnentar outro adjetivo???? Nadar
  contra a maré
- Ataca a liberdade de expressao > Alguem casado escreve uma poesia sobre sua
  esposa conjuge, ela vai ser boicotada, pq as pessoas vao simplesmente vao agir
  contra ela.vai se impedida de se expressar.
- Aceitacao identidade do ser humano. Isso ai é porque o ser humano, conformado
  com sua realidade, achar feia, vao ter outros aspectos, pode se achar pouco
  inteligente, pouco habilidosa, apagar a beleza do dicionario, por isso que a
  oposicao ganha.
* MG
- Onus do debate? Qual a narrativa.
  - Diminuicao da pressao social
  - Pressao que ela sente dentro dela mesma
- Blindar a mulher com essa relacao?
  - Como vai blindar, framing do que que foi a beleza na historia da mulher,
    quando era mais cheinha, era melhor pra ter filhos
  - Sempre relacionadas ao padrao de beleza, n há consenso do que q seria belo,
    isso leva objetificacao da mulher, homens com a mulher, mulher passou a vida
    toda objetificada pelo seu corpo, considerada mais bonita, ela é bem, mais
    valorizada do que outras.
  - Acontece no trabalho, mulheres mais bonitas mais a frente, pra namorar só
    pessoa bonita
  - Nos nao estamos aqui falando que vamos mudar o mundo ou quebrar os padroes
    de beleza, mudar a mentalidade. Quando a mulher começa a deixar intrinseca a
    narrativa dentro dela, e falar que beleza não importa, ela nao vai ter o
    padrao de beleza dentro dfela. N vai ligar para a pressao interna.
- Importancia da narrativa para luta feminista
  - A mulher n é só o corpo dela, isso é o que a narrativa prega.
  - Mulher deve ocupar lugares e cargos muto altos, valorizacao da mulher e
    empoderamento de mulher
  - Mulher n é só seu corpo, quando o movimento começa a se dessa narrativa.
    Narrativa que as mulheres nao sao bonitas
  - Representar seus valores. Quando ela respeita as suas raizes, consegue
    influenciar as mulheres, todos os tipos de feminismo, quando a beleza n
    importa, ele vai conseguir atengir cada parcela das mulheres, quando o mov
    feminista se utiliza dessa narrativa consegue infleunciar as mulheresm, se
    blindando sua cabeça seu psicologico. AVai blindar a mulher de sair na rua e
    enfrentar varios conceitos patriarcais, aop longo prazo se blindar, vai
    comecar a n ligar para isso, influenciar todas facetas da sociedae.
- Impactos
  - N queremos mudar o mundo, o mov feminista tem que empoderar varias pessoas,
    essa influencia é mtu importante, dá aquela ideia do we can do it,
    influenciava mulheres acontinuar trabalhando. QUando o mov fmeinista
    consegue implantar aquilo dentro da sua propria narrativa
  - POI(Joao) > Patriarcalismo assunto estranho a moção > Não
  - Blindagem feminina. quando tem uma mulher blindada, vai ter menor pressao
    social nas mulheres, mulheres já sofrem cabelo liso inves do cacheado,
    quando as mulheres n sofre esse julgamento o psicologico bem melhor.
* MO
- 1 Def ->  Status quo é industria da beleza, no feminismo o bem estar é maior
  do que a igualdade
  - Problema dos padroes de beleza forcados imprimem desequilibrio, esse é o
    ponto princial, ultma coisa que eles dizem, nós não queremos dirimir a
    valrozicao do estetico, mas sim dirimir o desequilibrio estetico.
  - Mtu dificil a narrativa da beleza n existe. Atualmente pedromina uma noção
    estetica, mulheres fora dessa noção estetica, insatisfação e infelicidade.
    Comparemos com essas mulheres infelizes.
  - Quando a gente, beleza n importa, a gente n precisa de beleza pra ser feliz,
    vc está contemplada dentro do padrão, teria que provar que beleza n importa.
  - Outros aspectos seriam salientados quando a gente tira beleza do jogo, a
    beleza existe, plausivel que as pessoas admitam que a beleza n importa.
    Muito forte e enrraizada na narrativa cultura. Vcs n conseguem, a mulher
    mesmo que diga que apoia essa ideia, esta em insatisfaçao.
  - No nosso ambito, esses segundos aspectos, nossa narrativa é mais pratica,
    todos os corpos sao bonitos > Invariavelmente satisfeitas com o padrao
    estetico, caracteristicas secundarias vao ser elucidadas, pq o problema da
    beleza já foi sanado.
  - Provo plausiblidade > Filosofoia perpectiva aristotelica > Há padroes
    universais equilibrio, harmonia, essa corrente estetica, colocar nos olhos
    da pessoa que tudo é belo. Ela é muito relativa, subjetiva, se a gente
    consegue implementar a narrativa de que todos os corpos sao belos, vc
    consegue colocar nos olhos das pessoas que elas estao sendo colocadas nos
    olhos da beleza.
  - Padrao com equilibrio dos corpos. Todos os corpos tem sua beleza. Industria
    multicultura, na midia vem trazendo mulheres gordas, miscigenadas, pressao
    do feminismo.
  - Feminista > Feminista diz que mulheres podem ser gordas saudaveis e belas
* WG
- Nenhuma bancada onus de beleza. Pra essa moção fazer sentido, para ter um
  conceito de belza é preciso um conceito de feio.
- Mov feminista deve se portar > Mudar as perspectivas das proprias mulheres.
  Deixar as mulheres empoderadas
- Onus da defesa que a beleza é irrelevante > Concordamos que a beleza é
  relevante, nós dissociamos a mulher como ela ve seu proprio valor.
- POI(Marcus) > Que é mais práticos que as pessoas admitirem > N importa o que é
  mais fácil e mais dificil > Mas o que traz mais impacto > Dissociar da
  imposicao masculina > Mesmo se ela sendo feia > Tu é bonita > Botando um haval
  da sociedade masculina > Agr ela está aceita > Agr ela adquire valor > Mesmo
  que possa trazer todos os aspcetocs, prefere que ela n tenha esses pontos, mov
  feminista quer qeu ela n dependa do aval masculino, aqui que an ossa narrativa
  é mais forte, for para a sociedade, tu é bonita e tu é feia. Mesmo se ela se
  achar bonita, ela n vai conseguir namorar, se nós trazemos um caso que isso n
  é importante > Se desenvolver como pessoa > Consegue cumprir seu dever > Para
  conseguir esse tipo de preconceito estrutural > Mesmo que ela consiga adquirir
  essa narrativa > Ou ela se afasta do feminismo que mentiu para ela > Va ter
  danos de autoestima > Conflito interno se é bonita ou feia.
- Tu é bonita, tu é feia, isso n importa, valorizar em qualquer cenário, tu vai
  ter o teu valor, valor per si, isso é mtu mais forte, valoriza a luta da
  mulher. No nosso caso, o valor depende da pespectiva da mulher prorpior sonho.
- Estaria basicamente um conceito guarda chuva, faria para as pessoas aceitarem
  ela. Botar a mulher do aval
- Beleza seja importante > Os dois lados mantem > Op enfraquece isso, beleza
  depende da feiura, vem pra nosso caso, temos uma distincao perfeita do bonito
  e feio, nos temos esse conceito de beleza como existente, ainda que ela seja
  feia, n é essa objetificacao que deve pautar a mulher.
- Em relacao ao 1 gov > Roubamos os pontos > Inteligencia e carater n é bem
  mostrado > Impactos só sao desenvolvidos com a inaam.
* WO
- Refutando 1 def > Status quo n fornece beneficios para as mulheres > Se o mov
  feminista sustentar a ideia que todos os corpos sao bonitos, isso ia fazer com
  que, mais pessoas se sintam motivadas a melhorar sua saude, e sentirem
  valorizadas etc
- Com a ideia proposta pela extensao > A participacao da industria multicultura
  no processo > A industria é amiga e devem aceitar > Todos os corpos sao belos
  > Isso já vem acontecendo ao longo dos anos > Até mesmo dentro das proprias
  empreas > Mulheres assumem cargos de liderança, uma consequencia disso é uma
  mudança no parametro normativo. Que poucas mulheres conseguem atingir, com a
  minha proposta esse parametro vai mudar, em favor das mulheres. Todas sao belas
- POI(FIshcer) Apesar da mulher se achar bonita a sociedade vai se achar bonita
  ou feia > Todas as mulheres se sintam bonitas
- A sensibilidade perpassa diversos aspectos da vida > Nossa proposta isso vai
  ser um dos pontos centrais > Industria multicultural > Mov feminista tbm > As
  mulheres vao ter mais autoestima > Porem uma mulher vai falar beleza n importa
  > Corre o risco de ter autoestima baixa > SOfrer danos psicologicos como
  ressaltados pela minha extensao > Depressao suicidio.
- Invés de todos os corpos sao belos > Inteligencia importa, outras qualidade
  importam > Qual o motivo da beleza ser uma qualidade com tratamento
  diferenciado. Inteligencia tbm é uma questao preconceituosa.
- Consumo consciente > Nem todas as mulheres vao se sentir valrizdas > Comprar
  produtos que se sintam agradaveis >
- 1 def status pior ainda > mulheres se sentem desvalorizdas mesmo sem ser belas
  ou não.

Rafael -> 2G > 1G > 1O > 2O
Murilo -> 1O > 2G > 2O > 1G
CC -> 2G > 2O > 1G > 1O
