#+TITLE: UniaoEuropeiaPublicacoesSatiricasAdj

* PM
- Pensamentos xenofobicos, ultranacionalistas, desumanas e absurdas e vão contra
  a existencia da uniao da uniao europeia
- metrica
  - cenario ex direita diminui
- modelo
  - uso de piadas e conteudo satirico, programas, tv, internet
  - fazendo parte do cotidiano do cidadao
- motivo da acensao
  - manip emocional pelos partidos
  - conseguimos apelar para o mesmo campo -> massificado de satirica ->
  - aconteceu durante a crise migratoria
    - ex direita pegou os imigrantes e colocou todos os problemas em cima deles
      - ex: alemanha e taxa de crimes, quesitos da economia diminuindo
      - partido de extrema direita pega uma populacao que possa causar dano, e
        potencializa aquilo (UE destruindo o pais, Imig destruindo o pais)
  - IMP -> Ex-direita nao é convencida com razao mas com emocao
  - Stakeholders
    - pop geral
      - nem todo mundo compra a retorica
      - ou reforco de algo que eles ja sabem
      - tornar mais forte um conviccao que eles ja tem
    - eleitores da extrema direita
      - o FOCO do debate
      - o motivo que elas mudam é por cairem nessa logica emocional -> força um
        efeito oposto -> atraves de satira qualquer logica ou ideal da extrema
        direita é totalmente ridicularizado.
      - logica que é continua ate que o problema acabe
      - isso pode ser colocado em escolas para que pessoas crescerem sabendo que
        os ideais nao prestam e nao funcionam.
      - mais provavel que elas nao cedam para esse emocional -> a primeira
        reacao nao vai ser tocar no medo mas ISSO É RIDICULO já tem todo um
        coirpo de populacao que já ve o governo ridicualrizando e que iria me
        ridicularizar tambem -> Coerção dupla
    - partidos
      - ganhar motivos e tals
        - comparando a capcidade de propaganda de partido VS A UNIAO EUROPEIA ->
          a visao da uniao europeia vai ser mais passada.
        - antes quando nao faziamos nada nos temos a UE fazendo diretamente,
          mesmo se ficarem pistola eles tem menos retorica
* LO
- vai desfazer a UE
- disc -> partidos minoritarios isso é uma inverdade por si so, partidos de
  extremadireita estao perdendo o poder (poder italia, hungria, poder do reino unido????)
- legitimidade
  - se a uniao europeia financia contra esse grupos -> vao ser vistos como
    vitima -> isso vai ser usado como ferramenta
    - eles vao fazer um recorte, pra utilizar de fake news. vai gerar um maior
      engajamento no proprio grupo de extrema direita. os seus proprios
      apoiadores vao estar mais proximos e vao estar mais engajados, infla a
      base como um todo.
      - o gui admite que ampl da base vai acontecer(ele faz isso?) eleicoes
        regionais e pro parlamento nao precisam de maioria, 20% dos votos? eles
        engajam mtu bem e conseguem eleger no congresso. ??????????
      - na UE nao existe voto obrigatorio, baixo indice de voto(isso é bom e faz
        sentido), é preciso de engajamento pra que o eleitor vá a urna, vao para
        a urna mais que os outros partidos.
      - poi gui -> ex direita continua crescendo no nosso tem todo um bloco
        economico fazendo propaganda contra ele --> eu ja falei que a ex direita
        é dona da italia. nao sao grupos pequenos.
- cidadao medio
  - passar narrativa pro cidadao medio -> quem gera mtu engajemtno aparece pra
    mais pessoa -> qudno a gente tem muitos apoiadores com engajamento, vao
    compartilhar mais, vao passar a mensagem pra mais pessoas -> pq o cidadao
    medio vai aderir? pq eles usam da mensagem de medo de emocao que a extrema
    direita esta usando como vitima de perseguição.
* DPM
- a UE é legitima de fazer tudo isso -> obras satiricas papel fundamental
  descontrucao de pensamentos, n apenas para diminuir a força mas como mosotrar
  a UE como uma unidade
- UE pressuposto de defender os direitoso humanos. mostrar que ela esta a frente
  a ocombate para qualquer tipo de expressao e atos ilegitimos.
- extrewma direita vai contra a unidade da propria uniao europeia
- o cidadao comum que ainda n tem o pensamento ele pode vir a ter
  - eles vao ver que a extrema direito é ridicularizada, pensamentos
    irracionais, vai lutar contra esses pensamentos.
  - quem é contra esse tipo de pensamento recuperar os membros levados para o
    outro lado.
  - nos precisamos apoiar essa causa para que a extrema direita nao seja a UNICA
    a lutar contra isso.
  - o cidadao comum que foi desvirtuado tem que ver o outro lado.
  - se a unica medida sao esas satiras e compeltamente viavel fazer isso.
  - o cenario da ex direita na italia foi justament edeixando ela crescer sem
    fazer nada para isso.
  - n é porque tem muitos paises de extrema direita, que vc n vai deixar de
    lutar, vai lutar mais ainda, a extrema direita ja foi minoria.
  - poi karol -> agr que esta utlizando as satiras como que seria para
    distinguir uma a outra pop cada vez mais ocnfusa -> ela estaria mais
    informada, a UE estaria litealmente dizendo "esse pensamento é um que deve
    ser reprimido" e as pessoas iriam identificar esse tipo de pensamento,
    DIFERENTE da pos verdade, eles pegam e mudam as noticias.
  - no que sao minoria nos previnimos que eles sejam a maioria. previnir que se
    tornem a maioria
* DLO
- 1g fala que vao ser afetadas -> a consequencia n é a dada pelo 1g ->
- as pessoas que ja sao de extrema direita so vao ficar com mais odio, vai
  legitimar as bases. vai inflamar, contra a uniao europeia(eles ja odeiam)
- efeito backlash
  - empatia com extrema direita -> se nos ridicularizamos terceiros, temos ideia
    de uma vitima e de um opressor(ue) -> a vitima sera a ex direita ->
    construcao narrativa sera extamente essa, mesmo tendo poder menor, nos
    tempos atuais n quer dizedr nada -> pq a difusao pelos meios de internet
    amplia ate mesmo com robos.
  - 1g fala de vergonha -> os cidadaos medios que sao naturalmente tendentes ao
    lado injusticado a figura da midia -> se as pessoas estao vendo na tv
    qualquer tipo de ridicularizacao(moco que agrediu verbalmente o motoboy, as
    pessoas passaram a falar do motoboy, agredir de volta o opressor do motoboy
    ridicularizando suas caracteirsticas fisicas) -> candidatura do bolsonaro
    tudo na base de meme, inves de enfraquecer ele fortaleceu. base vai ficar
    mais engajada.
  - apropriada como bandeira, mov feminista sofreu bastante com varias satiras e
    termos chulos, mesmo que tenha uma grande rede de odio, mov continua a
    crescer, mais uma vez temos uqe a satira vai fortalecer a bandeira, engajar
    a base e vai arrecadar pessoas que n simpatizavam com a extrema direita.
* MG
- UE pessoas sao burras.
- sao atingidos pelo emocional, eles sao ignorantes, sao burros, as massas nao
  ligam para campanhas politicas serias, eles acham aquilo mtu distante.
  principalmente os pobres.
- o humor ele afeta essas pessoas de forma ludica e direta > o humor alem de
  passar um impaocto mtu maior, atinge de forma mtu mais ampla, as pessoas
  começam a leva aquilo a longo prazo. e no curto prazo acham aquilo divertido.
- esfaqueando 1g -> tem movimentos mtu grandes de extrema direita -> charles
  lapim todo mundo leva a serio o grande ditador. presidente da ucrania era comediante.
- o maior medo de alguem de extrema direita é n ser levado a serio, ele n vai se
  eleger.
- fora da pop local
  - efeitos no estrangeiro -> paises mal falados, paises tratados como piada,
    sao considerados chacota, perdem coisas e tals. italia foi deixada de lado
    mta coisa na uniao europeia(alemanah e fança olham e riem)
  - inglaterra ao sair da uniao de europeia perdem acordos comerciais(???)
  - grecia n vao ser levados a serio(????)
- e o efeito backlash
  - um lado flaando verdades de forma ludica satirica, um outro lado putinho e
    chorando por ser piada, isso so aumenta a piada
  - prefeira de paris ganhou a eleicao, a unica proposta de anne hidal, foi
    querer mudar isso e trazer represntatividade, ela foi eleita, e foi
    reeleita, as piadas atinger as pessoas, as massas, atuam no curto e longo prazo.
* MO
- caracterizando aprtidos de extrema direita
  - eles sao xenofobos, ultranacionalistas
  - eles n vao ficar no canto, vao reagir
- caraterizando politicas satiricas
  - publicando um alvo
- estabilidade no bloco
  - pq q a UE é formada? pelos proprios paises, a logica é que um proprio pais
    esteja se atacando, os politicos vao utilizar isso ao seu favor.
  - ainda que a votacao n seja exarcebada -> vc tem uma pop nacionalista, burra
    e com emocoes -> imaginem um cenario em que essa pop ve os seus partidos
    eleitos democraticamente ridicularizado
    - esses paises n sao tao adepatos a uniao europeia, ao financiar esses
      partidos politicos, estao degastando cada vez a sua confiança. o problema
      é que UE se mete demais na politica interna.
    - instabilidade do bloco
  - embora extrema direita deva ser combatida
    - importancia economica desses paises que trazem para o bloco
    - mercadores italianos n vao se sentir engajados, o governo n vai gostar. a
      economia do bloco é fundamental. a UE deve pregar pelos direitos humanos,
      tem paises que depndem disso.
    - POI Gui -> em nenhum moemnto falou de ridicularizar paises -> publicacoes
      satiricas elas n sao de bom humor -> elas criticam, chamam seu presidente
      de idiota, vao justamente isso.
    - a emocao é o ponto mais fraco do gov -> essas pessoas sofrem pela emocao
      -> tem senso de vingança mtu mais alto que o cidadao medio.
    - POI Ric -> paises de extrema direita n podem optar por n fazer comercio pq
      vao se lascar -> italia tem o minimo de sobrevivencia. pq ela tem poder de
      producao -> ??????
    - paises pequenos que sobreivem da uniao europeia -> n tem envolvimento com
      extrema direita mas vao ser afetados caso o bloco entre em instbiliade.
* WG
- n a legitmidade -> UE é quem mais tem legitimidade -> esses paises se uniram
  para estabilidade e paz
- mesmo que sejam de humor negro ->
- extrmea direita tem um arsenal, precisa de algo que bata de frente ->
- maju fala de identificar com a vitima -> as pessoas n querem ser alvo da
  critica -> e a gente n quer ser o alvo da piada -> tem a pessoa que é burra e
  ignorando por ela ser morna, po ser desse jeito n vai querer ser o alvo da
  critica vai querer ser quem critica
- pessoas venceram eleicoes com base em piadas -> entao sim a uniao europeia
  pode mudar alguma coisa -> a uniao europeia tem capital para acabar com isso
- há uma disparidade de poder.
- 2op -> as satiras valem de humor negro -> humor comum -> humor negro n se
  caracteriza por usar um xingamento vai mtu alem disso. ja tem esses paise
  querendo sair da uniao europeia -> eu tenho a maioria de pessoas sendo
  ignorantes medias etc, n sao as extremistas.
- poi lavinia -> bolsonaro é chamado todos os dias de burro e idiota -> n migram
  pela esquerda mas ainda sim a gente tem uma media ignorante, essa populacao
  morna n quer ser oprimida.
- senso de vinganca
  - competicao qde quem faz a piada melhor, ela aina sim via enviesar de n ser a
    minoria que ta sendo criticada
- pq 2g na frente de 1g
  - ricart traz que pessoas sao burras, por isso que elas tendem a enviesar
* WO
- qq é mais importante?
  - nos dois lados queremos diminuir o discurso de extrema direita
  - a medida n só é ineficaz, no melhor cenario que ela seja eficaz, acabando
    com a extrema direito do mundo inteiro.
  - como q tamo rolando odebate politico, disc politicas vao estar para satira e
    n argumentos e propostas. politicos vao usar de satira e n vao utilizar argumentos.
  - no nosso lado nos temos medidas contra mas n vamos utlizar a satira.
  - cada vez mais a propria uniao europeia vai estar utilizando dos mesmos
    artificios, para acabar com eles. é uma soma zero. n vai ter efetividade mas
    vai acabar com o debate politico(???????????????)
  - aumento da polarizacao a UE(mecanismo -> existencia de um mal a ser
    combatido, endoassar o lado oposto, a eles estao me atacando, estao sendo
    contra mim.)
    - a gentre diz que vai ter o endossamento cada vez maior de um maml a ser
      combatido , vai piorar pq vai acabar piorando o debate politico
  - 1g
    - o uso da emocao, atrair essas pessoas
    - apelo emocional, pessoas cada vez mais confusas, duas narrativas(n ja tem
      isso?) -> que ja ta super confusa, UE se fortaleca os proprios partidos
      que n sejam de extrema direita.
  - 2g
    - pessoas sao ignorantes e elegeram partidos, humor vai afetar as pessoas de
      forma mais ludica -> medo é n se eleger, vao usar narrativa que tao sendo atacados.
