#+TITLE: DT_29_05_2020
1O > 1G > 2O > 2G
* PM(Carol)
- Conjunto de leis e normas super engessadas > Aplicadas sem considerar os
  contextos
  - Jurisprudencia > Permite nossa atuação ocorra
  - Levar em consideracao diminui os crimes por vingança > Quando os familiares
    da vitima > Consideram que o crime não foi devidamente reparado > Ex: Crimes
    ligados e violencia domestica, assassinatos. Ou leva muito tempo pra
    acontecer, ou o pedido é indeferido. Pessoa que comete o crime tem um status
    forte na sociedade, o que pode tornar uma coação. Vitima nem procura o
    Estado. Se a gente começa a mostrar pra população, que o espaço deles vai
    ser respeitado, eles vao se sentir mais amparados e seguros e que existe um
    sistema penal que dá uma resposta que equivale a uma agressão.
  - A gente faz que factualmente se diminuia os crimes por vingança
  - Beneficio no processo de recuperação das vítimas > Vítima se sentindo
    realmente justiçada > Psicologicamente sensação de justiça e paz > Vai
    começar conseguir um processo de cura e seguir com sua vida em diante e
    tornar-=se uma pessoa funcional Ex; Vítimas de estupro que sentem que foram
    reparadas pela justiça que a pessoa recebeu uma pena cabivel a violação,
    entram num processo de recuperação é muito mais eficiente. Mulheres que se
    sentem injustiçadas sensação de insegurança, abandonada pelo Estado, muitas
    vezes essa mulher socialmente ativa, socialmente produtiva. Muitos casos
    como esses em que a vítima tem que provar, ordens de restrição. Essas
    pessoam acabam ficando dependentes do Estado
  - Resumo > Proposta que vem buscar os indices dos crimes de vingança, vao se
    sentir que justiça foi feita, a gente tem um cenario processo de
    recuperação. Processo de recuperação, colocar, seguir com o tratamento,
    voltar a ser ativa e funcional na sociedade.
* LO(Maju)
- Moção fala sobre, como o governo nao fez essa delimitacao (40% de influencia ?????????)
- 3 Pontos de argumento
  - Conceito de justiça pode ser abstrato > Pra ser justo é necessario que seja
    imparcial e razoavel. É Preciso o equilibrio entre as partes, com peso
    consideravel as vitimas
  - Se nos admitimos, linha muito tenue e a vingança > A Carol fala que as
    pessoas deixariam de se vingar, agora o Estado vira o instrumento de
    vingança dessas pessoas. Cheias de medo ou raiva. Vontade de descontar no criminoso
  - Quam sao os mais afetados?
    - Negros e pobres, nossa sociedade nao se indigna pelo filhinho de papei
      preso por drogas, mas sim com o pobre que trafica a mesma coisa. E acha
      que ele nao vai ter futuro ou recuperacao alguma.
    - Ex: Operacoes policiais > Isso seria muito mais gravoso, se em todos os
      processos a vitima pudesse ter 40% de influencia na pena. Carol fala em
      questoes de vingança. Algumas familias tratam isso com vinganças
      particulares. Se nos deixamos passar esse tipo de moção, Estado seja
      instrumento disso para atacar essas pessoas.
    - 1 Gov apela para a opiniao publica para questoes de estupro > nao
      significa que vai ser algo bom na pratica, se eu tenho um suspeito e ele
      vai a julgamento com todas as partes, e a pessoa imbuida por medo ou
      raiva, quer um culpado pelo crime que ocorreu, atribui para uma pessoa
      errada, essa pessa vai ser muito mais gravemente afetada porque a raiva e
      esse ódio interno, das vitimas, vai afetar na sentença
    - POI(Yas) > Como é que vc prova que vai ser mais parcial > Se voce atribui
      um peso consideravel e maior influencia > Como que voce vai ao mesmo tempo
      o equilibrio, mais peso mais ouvido a vítima do que as alegaçoes.
    - Os problemas sao por outras coisas, morosidade, que advem de outros
      problemas e nao necessariamente da pena, ou de algo semelhante a isso.
* DPM(Yasmini)
- Ref da 1 Op > Imparcialidade da justiça sendo que ela no proprio discurso,
  mesmo hoje os filinhos de papai na nossa sociedade já tem vantagens, se eles
  fizeram algum ato infrator provavelmente eles nao vao ser nem punidos. Sao
  mais ouvidos do que as proprias vitimas, não é imparcial e nos como primeiro
  governo acreditamos que dar mais voz a vitima.
- Ela falou também sobre prejudicar os negros e pardos e pobres, e nao provou
  como isso vai prejudicar esses stakeholders, eles já sao mais assegurados pela
  justiça, que já é parcial. Como é que a moçào vai prejudicar esses stakeholders.
- A Carol já falou sobre a vingança, dar mais paz, maior sensação de segurança,
  principalemente pras vitimas de estupro e violencia domestica
  - Flexibilizacao da pena > Nao só pra menos rigorosa mas para mais rigorosa >
    Nosso Estado tem uma lei que é engessada > Aquela pena é de tanto tempo até
    tal tempo, voce nao pode nem ser a menos nem a mais > As nuancias das
    situacoes nao sao ouvidas, as vozes da vitima nao sao ouvidas. Os prejuizos
    nao sao levados em conta.
  - Ex de flexibilizacao > Um roubo é um roubo para justiça brasileira, se uma
    pessoa ela tem uma situacao economia legal e mesmo assim ela rouba um
    pequeno produtor, ela vai responder a mesma intensidade de pena, se fosse a
    mesma pessoa roubando uma grande fabrica. Discursos da vitima, o pequeno
    produtor de leite, a visao do pequeno produtor de leite do dono dessa
    fabrica, as perdas sao totalmente diferentes.
  - Ex 2 de flexibilizacao > Mulher que nao tem como alimentar os seus filhos,
    se for levado em consideracao e o dono souber da historia daquela mulher, se
    ela se compadecer, a pena pode ser até anulada.
  - A voz das vitimas venham ser ouvidas para que a busca da justiça seja feita.
* DLO(Lavinia)
- Linha tenue naada razoavel para a jsutiça, nao é bom pra vida, pro estado ou
  pro criminoso
  - Cidadaos nao tem a minima nocao do direito, nem fundamentacao etica para
    aquela pena
    - A vitima nao age racionalmente, pode sofrer de stress pos traumatico, pode
      ter raiva pode ter medo, colocando sentimento no meio pode botar uma pena
      mais branda ou uma pena mais ferrea. Ex: Pedro e Jao roubaram o mesmo pao
      mas nao vao pagar a mesma pena pq as vitimas nao sabem
    - Vc nao dá o poder de justiça para a sociedade, etica, cientistas e caralho
      a quatro.
    - A vítima está passando por um processo de recuperacao > Medo da vitima de
      que haja vingança por parte do criminoso, integrante do PCC que vai ter
      sua pena retaliada. É muito provavel que essa vitima por medo,  essa
      vitima tende a dar prisoes mais brandas.
    - Essas vitimas podem ser compradas, essa vitima pode escolher, pra poder
      dizer x ou y, aquele criminoso nao me pagou.
    - Criminoso mesmo dentro da cadeia tem como prejudicar a vitima do lado de
      fora, envolver a vitima em questoes de fundamentacao penal. Testemunhas já
      sofrem com isso. Vitima nao vai ter protecao da imagem porque todo mundo
      sabe quem é a vitima, criminosos já vao atras dessas testemunhas essa
      moção só prejudica uma coisa ao ponto dessas vitimas sao punidas duas vezes.
    - Crimes sendo mais relevados > Direito sem ser levado a sério > Cidadao nao
      tem fundamentacao teorica > Nao tem a minima noção disso, pessoas pagando
      mais que as outras.
    - O negro > George do EUA morto por um policial, brancos sao mais
      beneficiados socialmente, negro sendo julgado por um branco, sofrer um
      pioramento dessa pena. Vitima traz um preconceito, diferente do Estado
      tentar tirar todo o preconto toda. Acentuacao dentro das cadeias.
    - Acentuacao dos crimes por vingança > Vai piorar o beneficio de processo,
      imparcialidade nao vai existir.
* MG(Rafael)
- Historico da evolucao da maria da penha
  - A lei ela surgiu para punir as vilencias domiciliares, ela levava afinco de
    tudo aquilol que a justiça traz. A denuncia nao valia praticamente de nada
    alem da testemunha e crime em flagrante, e viram que isso deferia ser modificado.
    - A voz da vitima passou a valer muito mais, trouxe um resultado positivo em
      relacao ao que ela era e a voz da vitima, a acusacao da mulher nao valia
      de praticamente nada.
      - Medo de rechaçamento a vitima retirava a sua denuncia > Abdicava do seu
        poder de fala > A partir do momento em que uma acusacao é feita, e vai
        la denunciar o seu agressor ela nao é mais retirada sob hipotese alguma.
        E aquele casal aquela mulher, por mais que haja artificios que levem
        alguma sentença, com isso eu trago
        - Se valorizamos o discurso da propria vitima, nos trazemos uma situacao
          de seugrança para aquela denuncia. Isso foi totalmente efetivo, hoje
          em dia, há um numero maior em relacao a violencia domestica. Numero de
          denuncias tem aumentado cada vez mais, a partir do momento em que vc
          considera a opiniao da vitima, cada vez mai segurança.
        - Vamos trazer para outos crimes, abusod de autoridade, insgurança
          tremenda, com exceção da lei maria da penha, os outros crimes
          continuam naquele primeiro modelo. O discurso da vitima é praticamente
          desconsiderado, aquela vitima simplesmente nao denuncia mais. Um
          policial do ponto de vista legal já apresentar um maior poder
          politico.
        - 1 Op medo de retaliacao > A partir do momento que aquela vitima nao
          tem um discurso efetivo e validado, os serviços de observancia legal
          nao dao protecao a ela, aquele caso a impunidade é muito mais
          provavel, do que se vc n tivesse em consideracao aquela vitima. Varios
          artificios legais a fala da vitima, nao vai todas as outras acoes da
          vitima.
* MO(João Manoel)
- Validacao da mocao vai diminuir crimse por vingança e maior beneficio de
  recuperacao > Nao vai acontecer o que a 1 op disse(????????????) Estado nao
  vai virar um agente de vingança, pq as vitimas nao foram vingança. Nao vao se
  sentir recuperadas.
- Lado construtivo
  - Pq a 2O se opoe totalmente a moção?
    - Colocar uma vitima para influencia penal a gente tem que partir do
      pressuposto, vitimas de estupro, tentativa de assassinato e vamo tal. A
      mente dessa vitima fica totalmente lascada, totalmente penalizada. Qual o
      problema dessa visualizacao, pressupondo o desejo de vingança é bem mais
      facil que essa vitima veja o reu com olhos de falta de humanidade, olhos
      de um criminoso, de um monstro. Do que muito mais um processo juridico
      racional. Qual o problema? Pessoas que veem o reu como um monstro para
      presumirem a pena.
    - Por ter um juiz para mediar nao vai ser totalmente o que ela quer, isso
      vai levar avitima nao ser reparada.Diante disso é bem possivel as
      garantias desse deliquente sejam desrespeitadas. Já que a vitima tá com
      esse olhar de monstro.??????????
    - Poder de persuasao da vitima > Se nos colocamos um juiz para ouvir uma
      pessoa que acabou de ser estuprada, nao estamos mexendo apenas na area
      moral e etica desse juiz. Mas nos estamos mexendo com articulacoes
      psicologicas. É bem mais facil que esse juiz determine uma sentença
      desequilibrada para o reu pq seu senso de humanidade foi atacado.
    - POI(Yas) > Por que que a justiça n ligada a humanidade? A gente nao ta
      dizendo que humanidade e justiça sao dissociados, guarda a sua humanidade,
      um senso de humanidade. Um lado mais psicologico mais racional.
    - A flexibilizacao é muito problematico > Nos temos duas pessoas que
      roubaram a mesma coisa e que vao ser penalizadas pelo senso de reparacao
      da vitima, quando na verdade deve ser reparado diante do Estado, n apenas
      OLHO POR OLHO(E N TEM VINGANÇA?????) Senso de disciplina diante de leis
      morais.
    - Mais uma etapa no processo judicial vai deixar o processo judicial mais lento.
* WG(Lucas)
- Ref 1 Op
  - Imparcialidade e razoavel > Discricao do que é justiça > Quando existe um
    processo existe uma arcada de processos por tras > Que relatam qual deve ser
    a decisao do juiz > Colocar seria apenas mais uma soma do que (Consideravel,
    como é diferente de hoje?)
  - A vitima vai agir por medo? Vai ter medo de denunciar, nao vai ter garantias
    pra a vitima, é justamente isso na fala do rafael, dar voz para ela se
    sentir mais protegida, possa ser mais ouvida.
  - Vitimas poderiam ser compradas e etc > Acabar com essas possibilidades de
    uma vitima ser coagida pelo medo, que queremos dar ouvido para a vitima para
    ela ser coagida por medo??????????? Vai ser sim resguardado, muitas vezes as
    vitimas nao fazem denuncia porque nao se sentem protegidas, vai ter uma
    efetividade maior.
  - Deve sim dar ouvido as vitimas > Justamente por ter dado ouvido os
    resultados grandiosos.
  - POI(Lavinia) > A Vitima já é ouvida pelo processo legal, só aumenta, a
    vitima já é ouvida > Vitima é ouvida mas o seus discurso é colocado em
    cheque, a vitima pode ser deixada de lado. Ex: Taylor Swift por uma luta
    judicial de anos, discurso foi colocado em cheque, assediador nao,
    julgamento seja mais verdadeiro. Sociedade extremamente machista. Vitima
    desamparada.
- Ref 2 Op
  - Atraso no poder judicial (FODASI INDEPENDE) estamos fazendo julgamentos,
    vitimas desprotegidas. A gente tem que garantir que essas vitimas sejam
    ouvidas.
  - Se nao ouvir vitimas de agressoes domesticas, n vai tersolucao domestica
  - Juiz mediador, só vamos adicionar dentro do processo a voz da vitima.
* WO(Carol Gerhardt)
- Caso do 2 gov deve ser desconsiderado dar voz a vitima, para que elas possam
  durante o processo e nao apos o role lá e nao depois da denuncia, a moçào é
  apos a sentença.
- Se vc começa a demorar e a enrolar ouvindo um processo a vitima, e mediando
  pra colocar auqilo ali, voce tá deixando de usar esse tempo pra outras
  vitimas. Que podem estar sendo protegidas
  - Ifrator segue impune pq vc demora pra ouvir ele.
- 1 gov
  - FIlinhos de papai já tem vantagem, e a grande MAIORIA, pessoas negras e
    pobres, que n tem voz, uma consultoria juridica, que talvez a vitima tenha,
    essas pessoas sao muito mais impactadas. Nao seja tao punitivo com quem já
    vive muito bem.
  - Ta cometeno o role por causa do contexto, vc vai e pune ela mais
    agressivamente e vc n promove aquele processo de reintegrar o individuo na
    sociedade. Certo que tem uns filinhos da papai que já tem muitas vantagens.
  - Vitima vai se sentir mais paz interna > Odio no coraçao toda movida por
    sentimentos nunca vai se sentir, a partir desse ponto eu fui justiçada(?)
    - Esse é tgrabalho pra terapia. E nao descontar lá na hora dá sentença a
      raiva dela. Invés dela resolver depois, tá descontando tudo na hora, e
      talvez nao veja a realmente saciar o desejo, até onde vai esse desejo?.
  - POI(LUCAS) > Essas denuncias vao influenciar mais denuncia > Escutar antes
    ou depois e as outras vitimas, vao ver cada vez mais > Em um processo
    juridico ambas as partes devem ser ouvidas igualmente. A vitima querer dar
    pitaco. As outras vitimas continuam se sentindo apoio, para continuar
    denunciado. Se a justiça já foi feita. Vc já teve uma enorme vantagem.
  - Comparativo
    - Como o juiz nao vai fazer toda a vontade da vitima
    - Pode se sentir comovido com avitima
    - Vitima pode se sentir injustiçada.
    -
