#+TITLE: FinalDesseCaralho

* PM - Juan
- Nao vai ser porque vou impor, n vou abrir pra qualquer pais, taxa de juros
  pode ser regulada pelo pais que esta pedindo, pode condicoes para determinado
  valor.
- imposicao de como gerir as politcias finais fiscais financieras
- paises em desenvolvimento e leste europeu
- pq que é errado?
  - seria um ato lesivo > paises em situacao emergencial > pessoas passando fome
    > ou passando por uma situacao de pandemia global > nesse sentido esse pais
    precisa urgentemente desse dinheiro. Paises que nao tem outras opçoes.
    Paises que necessitam ou do BCE e que estao em situacao extremamente
    problematica.
  - Pessoa que esta passando fome, n existe paridade de armas, paises obrigado a
    aceitar aquelas circunstancias. O pais nessa circunstanica,
    independentemente, elas sao obrigatoriamente aceitadas pelo pais
    - principiologicamente errado.
  - introduzo um meio de controle sobre uma economia interna
    - esse ente fiscal. ele pode ser imparcial e nao ter interesses
    - dando para esse ente interno controle para a politica economica desse
      pais. eu estou atribuindo para um ente, esse ente tem muito mais interesse
      de ver sua divida paga do que ver o pais se estabilizando.
    - mas pro FMI ele impoe a medida que ele acha melhor para pagar a divida. É
      equivocado eu atribuir para alguem que nao tem interesse no pais.
    - e isso no melhor cenario onde ele é imparcial, sendo que esse alguem nao
      tem tanto interesse assim. no cenario razoavel esse pais.
    - no pior cenario, interesse de impor dominacao, eu posso estar agravando
      esse contexto.
    - poi(iz) > interessse fundamental qeu esse pais saia da crise e pague a
      divida > existe uma possibilidade de aplicacao de juros, o BACEN quem te
      coloca uma divida nao te obriga a como gerir esse dinheiro
    - legitimidade do chefe de estado
      - poder de como determinar o funcionamento economico de um pais, quem
        mandana economia é o chefe do executivo, quem incute na forma daquele
        pais é o chefe do executivo, poder de realizar o planejamento economico.
        mas ele quem tem legitmidade ou poderes incutidos.
      - ele quem tem nocao da ideologia intenra na gestao interna daquele pais.
        tudo depende da ideologia.
      - é principiologicamente inviavel que eu dê o poder que é do chefe para um
        ente externo, esse chefe já vai ter que mudar com base na crise. Num
        cenario que esse aproveitamento vai ser feito com base nas diretrizes do
        FMI, to assumindo um risco que ele n seja mais regulado pel oFMI.
* LO - Lucas
- assumir que toda pessoa a frente de um pais sabe gerir é nao olhar para o
 asno que esta na presidencia da republica brasileira, a gente presa por
 eficacia mas nao por dar dinheiro sem nenhuma condicao
  - BC nao é teletom e nao tem role de se importar com outros paises
- ref 1 g
  - o fato desses paises estarem em crise só mostra que eles vao aceitar(oxi)
    vao ter boa cvontade de mudanças
  - no cenario do governo n é que vc tem dinheiro sem ennhuma condicao > os
    bancos nao vao ter nenhuma garantia para retorno notem o que ele vao fazer
    oiu é dar menos dinheiro ou dar dinheiro com mais juros isso automaticamente
    já mitiga a eficacia de qualquer dinheiro.
  - se o presidente aceitou as condicoes ele esta concordando
- gera mais efetividade
  - mais garantias
  - essas reformas garantem estabilidade
    - elas funcionam em si mesmo
    - em quem a gente confia
      - nos representantes que afundaram o pais
      - ou num banco mundial conhecimento tecnic o especifico no nosso mundo é
        mais provavel mudanças fiscais aumento de accountability, coisas como
        corrupcao tendem a diminuir, teto de gastos. ou como contencao de
        inflacao. notem como a gente ta lidando com pessoas que sabem o que
        estao fazendo. que deu certo em paises desenvolvidos.
      - ja em termo de comparativa no pior cenario, vem com tiradad de direito,
        se a gente mostra eficacia, no nosso lado tem mais accountability,
        Estado fiscal menos efetivo que gasta menos, e no long oprazo consiga
        voltar os direitos.
      - no pior estado do governo ou nao recebem e recebem menos, ou fica igual
        a grecia e faliram do mesmo jeito e ate hoje tao sem dinheiro e sem
        emprego.
      - garantia:
        - recebem mais dinheiro
        - equilibrio de contas e saude financeira
        - os paises subdesenvolvidos vao negar o auxili, os politicos querem
          sair como salvadores de crise.
    - pq que a efetividade é bom?
      - num pais em crise quem sofre mais com as crises, pessoas sem base
        economica, se o pais gastou demais e sem accountability, esse pais nunca
        vai sair dessa vala, pessoas que nao estao com dinheiro poupado, essas
        pessoas trabalham na cadeia de producao que é menos importante, todo
        mundo eperde dinheiro na pratica mas os pobres perdfem muito mais. eles
        nao só naoi tem base monetaria como sem educacao financeira.
        (poi danilo) > esse debate é sobre politica fiscal ou monetaria existe
        um politica fiscal ou monetaria mais corrupta > reforma fiscal, inserir
        meios de politica fiscal de paises que dao certo, a gente acha que isso
        é intrinseco a moção. tbm relacionado a ouras coisas, diminuicao de
        gastos. coloca um teto de gasto.
        - que no longo prazo o simples fato essas instituicoes estao gastando
          menos, se eles devolvem, notem que no longo prazo a gente consiga
          ajudar mais pessoas se ele tem mais dinheiro ele consegue ajudar mais
          paises. é obvio que salvar um pais é muito caro.
* DPM - Kim
- o que a bancada de op ignora o contexto
- crise emergencial
  - apenas ineficacia do proprio estado
  - na realidade é que nao é isso, é de paises macroeconomicos(china, eu) paises
    que tem economias fortes, crises reverberam nos paises que dependem deles.
    paises minoritarios, no mesmo passo que sao eles mesmo que vao se propor e
    melhor vao vender uma condicao a essa ajuda.
- ideia do governante incapaz
  - pq que magicamente ele vai seguir?
  - o governante corrupto vai ser em qualquer lugar(recurso de accountability),
    quando quer se fazer de forma errada vai acontecer. alem da gente meramente
    colocar condicoes é deixar na mao do proprio estado reconhece o que é mais
    relevante a curto prazo.
  - pq eu vou dar uma politica fiscal que fuja do meu espectro de influencia,
    paises que sao naturalmente dominantes utilizam mecanismo de influencia
    secundaria para os erros que eles causam, eficacia nao é garantida, politica
    fiscal n é apenas eu explicando x y z, mas toda uma estrutura de governo, os
    governantes dentro do estado.
  - condicao do incapaz
    - condicoes impostas no ritmo que a gente quer, a gente coloca na mesma
      moeda todo mundo, os contextos cada um sao diferentes, paises que dependem
      de commodity momentanea, nesse momento de emergencia eles que devem
      decidir. vc cria um sentimento de mal estar, condicionando ele a continua
      atrelando aos paises majoritarios que vao colocar as condicoes para resolver
    - poi(1op) > crises mundiais a gente ta falando de crise dentro da nacao ->
      as crises mundiais nao sao espontaneas, elas acontecem repetidamente, que
      apesar de ter crise economica ainda sim é um pais que tem mais impacto
      alem de paises africanos.
    - vc falar sobre irresponsabilidade dos lideres, vao existir de ambos os
      lados, nem o paulo guedes conseguiu ajeitar
    - poi 2op -> como que no cenario de vcs a seugfrança do retorno vs
      investimento -> vc quer condicionar para que ele realmente volte ->
      - priorizar que a economia se restaure no sentido macro, quando o lucas
        fala de engenheiros os grpos que regem vao ser os beneficiados
      - grupos que foram prejduicados por essas crises, estamos condicionando.(n
        explica direito)
- estados serem ineficientes, atribuicoes que damos para os nossos erros
  - nenhum pais é ingfressado na economia depois de uma crise, e que de uma
    forma.
  - motivo de crises externas essas crises afetam e legitmidade do proprio
    governo, dentro desse sistema integrado, impor nossas politicas que vao
    perpetuar esses erros.
* DLO - Iza
- o framing em qual cenario a gente consegu resolver esas crise e retornar a
  divida, n é doação n é ceridade
- o que é melhor para esses paises e pro FMI e BCE e pros paises qeu botaram dinheiro
- essa politica fiscal foi o que levou a crise
  - nunca vai se recuperar
  - existe um dever moral para pegar por principio
  - interesse legitmio de rfeceber dinheiro de volta ate para receber
  - para pagar é preciso recuperação da saude fiscal, se ele n faz isso ele se
    afunda numa crise ainda pior
  - e se ele nao consegue pagar
    - forma permanente
    - se fode mais e um rombo gigante e uma divida, 1g nao mostra como ele iria conseguir
    - impactos se ele n pagar > divida externa ta aumentando > se ele n paga
      existe um calote e outros paises ficam prejudicados.
    - arrecada mais do que gasta e ele saca o orcamento
      - n existe incentivo para mudar, mecanismo que faz com que eles mudem a má
        geração, diminuir gastos publicos
      - responsabilidade social só vale com politica fiscal
- existe politica fiscal mais corrupta > com maior accountability, ta tendo
  menos gasto publico vai querer fiscalizar ainda que n tenha, existe uma
  reducao de gastos, ela per si dá mais chances de otimizar os recursos, se vc
  ta condicionado a essa politica de gastar menos. segurança saude e educacao.
- alguem deuaquele dinheiro aquela verga
  - isso fode o pais que investiu, existe um incentivo para eles paguem,
    pandemia nao é metrica, inclusive na pandemia isso se agrava com a
    irresponsabilidade do governante, muitas vezes nao vai se mudar sozinho,
    competencia do cara vir nao vem do nada. crises economicas afetam outros
    paises, podiam pedir pro banco nacional pq nao tem recurso pq eles fuderam o
    banco nacional tbm > brasil com a dilma gastava muito mais que retornava, o
    bolsonaro com a pandemia, a grecia foi uma crise nacional, nem sempre é o
    cenario, a crise nacional
    - ate no cenario de uma crise mundial a forma como um estado lida com a
      crise, uma administracao eficiente lida com isso.
  - paises suvbdesenvolvidso
    - é muito pior com os pobres, o poder de consumo é deterioriado, sem
      orçamento pela ma admn, n tem incentivo para melhorar
    - no nosso cenario a gente consegue que esas politicas fiquem mais perto das
      grandes potencias mundiais, melhorar essa balança comercial e conseguir
      exportar mais do que importa.
    - o populismo lideres messianicos é uma constante desses paise que estao em
      crise, esses caras dominam e se so fuder o pais deles, no cenario de vcs
      existe um incentivo para irresponsabilidade real. Eles nao mostram como a
      melhora seria garantida, nem como o lider seria competente.
    - favorecimento e dominacao
      - FMI e BCE incentivo de varios paises, esass pessoas merecem seu
        dinheiro, responsabilidade coletiva de manter a saude fiscal. unica
        forma de garantir.
      - insistir no erro é ver se voltar com o ex vai mudar, esse incentivo para
        politicas mais eficientes.
* MG - Jessika
- na bipolaridade os entes fortes, para o capitalismo eles precisavam para um
  mecanismo para tirar paises de crises, FMI no casoglobal e BCE para europa
- paises ricos como os EUA, eles precisam que o sistema precisa, eles n querem o
  dinheiro de volta, esses entes sao entes de defesa do capitalismo
- as crises sao ciclicas, n é pelo dinheiro da divida, propria sobrevivencia do sistema
- bretton woods os paises se uiniram para manter o capitalismo, eles criaram
  dois sistema principais BC e FMi, auxlios do FMI sao emergfenciais, o BCE foi
  criado para garantir uma estabilidade de umam moeda, eles nao emprestaram para
  a grecia por moeda
- em um cenario de globalizacao as crises sao cojnulntas, crise de 0089 crise
  russa, elesa sao bancos publicos com uma finalidade especifica, é sobre eesse
  cenario de estabilidade, cadeia global se a grecia parassa por uma crise, é
  por isso que eles precisam agir para a grecia sair
- atrelar para medidas de politica fiscal seria um dano, pq alguns se negariam a
  crise seria ainda mais agravada.
- quem financia o FMI e BCE
  - os proprios membros que podem pedir esse auxilio, é legitmio que eles estao
    lá financiado para um dia precisar daquilo, aqueles paises que dao aquelas
    cotas maiores, de saber que é comum, comum acordo disso, e n devem
    simplesmente atrelar isso, n é um favor, eles pagaram por aquilo, recebendo
    auxilio que foi garantido. auxlio analisado
  - é imoral atrelar a um sujieot uma demanda
    - EUA é o maior ente disso, eles geram um caos no pais como o chile,
      problemas sociais gritante, no longo prazo esas politicas so agravam
      crises, e os estados devem se importar com isso e paises mais fortes
    - crises nao só na gestao, em 98 e 97 FHC mesmo com LRF sofreu com a crise
      da tequila e russa, a crise emergencial é inerente ao capitalismo, a gente
      precisa entender que a 1op acah que o FMI na tem um processo de analise,
      tipo EMERGENCIAL a uma justifiativa da crise.
    - a transparencia no usso das democracias no uso desse dinheiro, vc pode
      perguntar como ta usando.
    - crise sao mas gestoes, o efeito do petroleo no covid, mesma coisa com o
      turismo, a gente precisa pela saude global do capitalismo que o FMI
      favoreca, mas sim respeitar que aqueles entes especificos
    - 2 op > sem esses condicionais mais dificuldade de dinheiro, e emprestimos
      mais caros no futuro. -> é muito pior no cenario de vcs a gente tem queda
      nessas moedas que sao compartilhadas -> o proprio mercado já preza pela
      saude fiscal > o mercado para atrair investidores, para atrair se adequam
      as leis de responsabilidade fiscal, o mercado já é o ente que força isso,
      mas é o mercado que decide isso, é pq ele quer uma saude fiscal
      especifica, se a gente tem dois entes, se esse pais simplesmente se nega
      em invesitr na economia, muita vezes ele pode ter um agravamento da
      situacao fiscal e n sair da crise, economia muda o tmepo todo, imagina se
      o bolsonaro tivesse atrleado, n podia fazer auxilio emergencial.
    - narrativa do banco central europeu, muitos paises já fazem isos, a crise é
      um momento de excepcionalidade, meirelles falando pra imprimir dinheiro.
    - essa é a razão de ser do FMI salvar as economias, dever historico com essa emergencia.
* MO - Rafa
- contextualizacao
  - FMI e BCE problemas dentro da balança de pagamentos
  - contribui esforços, reservas internacionais, moedas e tá, restaurar as
    condicéos, depois da gestao de crise, a gent se esquece do depoiss
  - o FMMI e BCE, a gente concorda que isso seja, cobrar politicas e medidas
    especificas, objetivamente alcancar o que pretendemos.
  - 3 metricas
    - mundo melhor agr
      - a importancai da politica monetaria
        - autoracao de autoridade monetaria com a modea em circulacao, essencial
          deixar que a economia ativ
        - quando a gente n consegue que politica fiscal ee monetaria andem em
          conjunto, despessas de governo, seja por parte de emprestimos
          - 1 eficiencia na atuacao exige esses dois mecanismo
            - para que resolver situacao de crise, atue que esse regime de
              fiscal, deve ser restritiva, há uma pressao inflacionaria
              - elevacao de carga tributaria
              - diminuicao de gastos
              - governos nao fazem isso
                - nunca querem fazer isso, isso imp[acta di] diretamente a
                  qualidade de vida das pessoas, a pop ainda asims n entende
                  essas informacoes, governo tende a rechacar, eles querem se
                  manter no poder, eles n se importam com a economia, pouco se
                  importando para a poppulacao, governos tendem a se coisar com
                  eleicoes, elas sao essenciais para que a gente consiga botar
                  dento desssa politica algo de contrla a longo prazo.
                - moeda de troca para ter dinheiro do FMI, a populacao vai
                  sofrer a longo prazo, aumento no desemprego, as empresas nao
                  vao querer injar dinheiro no pais, empresas deixaram de
                  engajar com a grecia, nao tinha como garantir que a moeda
                  estabilizasse, pessoas tgendem a comprar mais.
                - empresas colaboram diretamente com a estabilizacao > se
                  vivemos num estado diversas pessoas nao tem direito ou acesso
                  para comprar bens, abrir mao em troca de dinheiro rapido e
                  esquecam completamente de problemas do futuro, e isso é ruim
                - poi(juan) > simples atribuicao de parametro vao ser sempre os
                  melhores -> a incapacidade de haver ligacao, valuation ->
                  agencias de regulacao fazem isso -> ninguem quer pagar 100
                  reais no quilo da carne no mercado de capitais ninguem, se n
                  temos controle tende a perpetuar, quando o mercado regula ele
                  vende ao preço que ele quer, instituicoes estatais nao prevem
                  crise, a regulacao desses orgaos, esses condicionais ao longo
                  prazo que paises ricos dentro do BCE continuem a perpetuar
                  isso, garantir maior sustentacao do pais e maior qualidade da democracia.
    - mundo melhor longo prazo
    - temos mais capacidade de recuperacao fiscal e garantias de emprestimos futors
* WG - Danilo
- 2 op -> politica monetaria é importante, isso n é um clash -> paises tem que
  engajar. -> diversos paises que tem um contexto de social democracia -> uma
  boa forma de governo -> paises liberais como o chile que ta todo lascado de
  divida -> jessika explica que existe um regime capitalista -> mesmo que a
  gente queira dizer que o EUA esteja bem intencionado ele esta enviesado sem se
  preocupar com uma serie de outros fatores -> exdiste uma problematica muito
  grande que determinada politica economia ou monetaria vai sr mais util -> 2op
  quais politicas necesariamente mudariam isso, pq necessariamente uma pessoa
  que decide ser corrupta, a politica economica do meu pais é tal(errado)
- jessika responde isso de duas formas, FMI n é o teletom, mas esse dinheiro n
  foi tirado da bunda dos EUA, mpaises se filiaram com FMI e contribuiram com
  suas cotas -> uma vez que os paises fizeram isso, eles precisarem -> é uma
  sacanagem muito grande, vc entrou aqui no FMI e agr numa eventual crise vc vai
  ter que sujeitar as demandas, n é caridade n
  - 1gov fala -> povo ta passando dificuldade e o presidente é o presidente, se
    o presidente no final decidir, entao é legitmidade, essa contextualizacao, n
    só de quem contribui com as cotas, a propria narrativa que o FMI é
    controlado por um grpo pequeno de paises -> a gente simplesmente n fere a
    legitmidade só pq ele aceitou pq estava sofrendo -> a pessoa n ta pedindo
    favor pq investiu -> existe um grande interesse de lucro que faz justamente
    que muitas vezes politicas economicas e monetarias -> botando o que é mais
    interessante para eles -> o que acaba fudendo o povo nesse pais.  o povo tem
    autonomia do que é melhor para si. fodasi os empresarios estrangeiros se o
    povo quer assistencialismo isso é muito mais importante que um empresario
    externo. essapo liticas existindo ou nao, paises escandinavos
  - 1 op -> se há uma interdenpendencia precisa haver eficacia -> politica
    fiscal e monetaria e decide como el quer -> uma politica ou outra é aliada a
    corrupacao -> EUA n tem corrupacao mas é super libveral -> se é a corrupacao
    que tá acabando com um pais(isso ta errado) ->
  - iza fala modelos que fizeram certo -> dois paises com politicas monetarias e
    fiscais diferentes -> EUA mereceu e é rico assim por causa da sua politica
    sem falar da imperialismo, pq o chile n é o EUA.
  - esses emprestimos vc pode acordar como eles devem ser usados sem mudar a
    politica economica de um pais -> FMI pode executar a divida caso ele n
    queira pagar -> eles n querem ser executados, meios menos gravosos.
* WO - Renato
- casos mais fraco da defesa -> controle economia interna, formados por
  conselho de presidentes, formado por um titular de cada pais, já faz parte do
  FMI, legitmidade do FMI estabelecer condições, direcionamento nas politicas,
  quem estabelece, esse conselho o qual todos os paises membros.
- precisamos reconstruir as reservas interncaionais -> medidas especificas as
  quais os paises n tem vontade de dar -> só a rafa explica como os emprestimos
  vai ficar mais caros -> se vai ter um menor incentivo para esses paises ->
  menos dinheiro -> esses emprestimos se n tiver um lastro financeiro -> ou esse
  pais vai pro mercado as politicas do mercado naturalmente tem uma taxa de
  juros maior -> emprestimos do FMI vai ficar mais caro
  - durqante a crise o folego de recuperacao vai ser menor -> Jessika ->
    jsutamente por interdeendencia desses pais -> por causa das politicas
    fiscais e necessarias -L> maior controle da populacao -> se eles sao tao
    interdependentes cabe ao FMI ser o responsavel pela reconstrucao desse
    emprestimo -> diminuicao nos gastos publicos, nenhum governo quer diminuir
    direitos da populacao, ele n quer ser mal visto, mecanismo pelo qual, é no
    curto prazo, durante a crise, no pos crise essa recuperacao dá no role de
    poder de compra, controle financiero ndas acoes -> maior transperencia no
    uso -> os g overnos agem diretamente de forma nao transparente -> grecia bce
    emprestou e a grecia agiu de forma escusa, esses governos ainda sim
  - a jessika vem falar mas esses paises tem cota no FMI -> uns tem mais outros
    tem menos eles tbm aceitaram as condicoes dos emprestimos, um nao exclue a
    outra, o caso da legitmidade é nosso, tanto pelas cotas esses paises.
  - poi danilo -> esses paises investiram quando precisarem -> eles n ivnestiram
    para quando precisar, cotas para equilibrar FMI agir de forma necessaria ->
    n fazer casa de mae joana, equilibrio das contas, ente responsavel.
  - estavbilizaco e valuation -> no final de tudo a comparativa em qual dos dois
    cenarios mais gestao da crise, nao há um incentivo de prsidentres da
    republica em cortar gastos -> decincentivo em chefe do executivo querer
    cortar gastos(melhor que 1op) unico meio pelo FMI tem alguma garantia pela
    qual, alguma forma atuando.  somente no caso da oposicao nos temos mecanismo
    de impor responsabilidades, somente no mecanismo da segunda oposicao, o PIB
    pode se estabvilizar.
  - o mercado no geral cobra juros mais altos(isso n foi case da jessika), n é
    casa da mae joana, vc precisa cobrar. n há incentivo nacional ou propostas
    de auestiridade, FMI fica cada vez mais esquecido, n há lastro financeiro.
    no final de tudo a gestao de crise. retomada de confiança.

    GUI: 2G > 2O > 1O > 1G
  - JULIA: 2O > 2G > 1G > 1O
    LARA: 2O > 2G > 1G > 1O
    CC: 2G > 2G > 1O > 1G

    - Lara ->
      - 2G reframing principal objetivo n é receber dinheiro de volta para
      o capitalismo funcionar. -> rafa trabalhando dentro disso -> emprestimo
      sem condicionantes e recontrucao -> isso nao salva ninguem da crise.
      - serviço direito a um emprestimo
      - crise nao sao sobre uma má administracao
      - politicas fiscais nao sao a solucao -> situacao emergencial pais ferrado
        -> nao tenho dinheiro sao medidas que nesses casos necessarias para o
        pais admitir. politicas nao vao ser toleradas por governantes.
      - renato responde é um serviço aceitou entrar, entrou na logica -> so pq
        vc investiu vc n tem emprestimo incondicional.
      - se acoisa é tao ligada, o FMI precisa intervir.
