#+TITLE: Debate04

* PM
- status quo
  - dominacao, constante, instituicoes proeminentes, senso de moralizacao,
    subcultura sendo esmagada
  - de certa forma perdermos a cultura > mulheres que deixam de praticar
    cultura, mas sobretudo a gente ta fazendo isso com a politica de nao sejam
    suprimidas, exterminadas pela politica dominante.
  - 1
    - os lideres da instituicoes, proprios responsaveis pela educacao, narrativa
      de conflito entre grpo marginalizado e dominante
      - caca as bruxas, dificil conciliacao, conciliacao é importante para
        amnter viva as pessoas representantes, aceite perder pratica da
        religiao, sempre em troca para fazer com que sirva
      - senso de ocmunidade é muito importante, pessoas sejam aceitas, essas
        pessoas sao vistas como pessoa do trafico.
        - sujeitos imorais, deve ser alterado. dentr da instituicoes que possam
          dominar o debate publico.
        - mesmo se nao for fiel, as pessoas que estejam dentro das instituicoes
          proeminentes conhecer, e manter a cultura a longo prazo
    - poi(gio) > qual a metrica? > a metrica em que mundo nos conseguimos que
      esssas pessoas conseguem ser mais felizes, mais respeito, suas historias
      mais dentro do debate public.
    - 2
      - se nao vem que esses sujeitos forma de identidade, narrativas
        dominantes, repele ainda mais e marginaliza, pessoas que ja sao
        marginalizadas, nao entender que é importante, colocar PARA dentro desse
        debate, nao para tirar de um senso de contestação, a gente querf fazer
        que tenham voz ativa dentro das instituicoes, sejam aceitos dentro
        disso, essas pessoas ficam cada vez mais a margem.
        - considerar LGBT aberração, muda quando as igrejas praticam a politica
          de respeitabilidade, quando as pessoas aceitam essas pessoas
        - POI(Videira) > pq vai haver uma caça as bruxas, cultura dominante
          submeta as pessoas -> quando a gente coloca elas a margem, no status
          quoe elas sao mais marginalizadas, e sem voz ativa. Essas pautas podem
          ser vistas e abordads em instituicoes proeminentes. a gente consegue
          trazer a contestacao.
        - prefree mante dentro dessas pautas, mulheres falarem sobre feminismo
          dentro da igreja.
* LO
- o contexto do governo é que existe uma cultura de conciliação
  - descaracterizacao desse conceito de que o mainstream tende a oprimir
    - o que sao esssas comunidades marginalizdas -> nao tem escolha sobre o
      sistema economico -> n tem escolha -> tem cultura propria.
    - pop continua excluida > existe uma tendencia > eles continuam sendo
      discriminados, há uma tendencia de estranhamento, por parte da cultura do
      mainstream, só pelo sentido de vc ser diferente. só por ter um fenotipo
      diferente. isso esta tao inerente na nossa sociedade parte disso. racismo
      vai continuar, n existe politica de inclusao social eficiente.
    - continua sofrendo violencia, percebam como o abandono dessas praticas traz
      um abandono do seu passado, nao ter todo esses simbolos, vc vai ter uma
      negacao da cultura, aspecto central, tirar toda sua condição histórica que
      foi criada, a opreção nao parte para as praticas sociais, as praticas
      sociais vai continuar pela identificacao(?).
    - aceitar o seu pertencimento, e trabalhar dentro dela, vai haver um
      empoderamento por traz disso, n se sacrificar pelo mainstream, desenvolve
      mais valores culturais, as isntituicoes vao colher esses frutos, seja na
      igreja, seja na comunidade, a cultura africana é pouco vista, vai ter um
      respeito a si proprio, as praticas de agressão podem diminuir, essa
      cultura vai se blinda
    - poi(rafa) > há 10 anos atras, a cultura de margem tomado muito mais força
      justamente por praticas identitarias e de calsse
    - ascenção do movimento social tbm ascencao da extrema direita. mujito mais
      importante se blindar eviver na nossa bolha, e que essas pessoas subtraia
      e agente acolhe a discriminação depois. e isso é importante para ter uima
      contra cultura, revelar os estigmas e traços de opressão, o revelar.
* DPM
- o caso da 1op ainda que eu compre que o mainstream gera supressão > na
  comparativa o lado dele é pior.
- instituicoes proeminentes geram ascenção de novos comportamentos, ligação
  direta com os marginalizados tanto dfentro como fora, esses novos
  comportamentos influenciam a forma como essas pessoas se enchergam dentro da
  sociedade.
- unico caso da 1op é suprimir, tanto dentro da comunidade, nos estamos dando
  voz para as pessoas marginalizadas da comunidade, a 1op confundiu, n é sobre
  pessoas proeminentes INSTITUICOES proeminentes, é contribuir para a harmonia
  comunitaria, contribuir para a comunidade em volta, nos conseguimos trazer
  esses entes marginalizados, para mais perto dessa instituicao proeminente.
  Como as igrejas tem feito com os skatistas, trazendo eles para dentro.
- o estado o mainstream já oprime já exclui essas pessoas, ser um bastiao da
  aceitabilidadeo qual essas pessoas nao tem, contribuir para a harmonia
  comunitaria, ascencao de novos comportamentos, fortalecimento da identidade
  que essas pessoas se enxergam
- comparativa 1 op das instituicoes > o lideres dessa comunidade vao ta sempre
  batendo de frente ou com os moradores ou dois com os entes externos, essa
  ocmunidade já é marginalizada n tem voz.
- nos vamos ter um afastamento direto das pessoas para essa instituicao, na
  falta do estado, esas instituicoes que oferecem trabalho social, oferecem
  ajuda social, levando medico, essa politica de respeitabilidade, mesmo dentro
  da comunidade vai fazer com que a comunidade como um todo se sintam mais
  dentro
- POI(Videira) > o Estado vai providenciar, caridade so vem quando essas
  instituicoes sao aculturadas muito injusto > elas nao sao aculturadas, a
  identidade sempr permanece viva. vamos abrir mao de alguns traços culturais >
  esse debate é sobre instituicoes, precisam ter uma politica de respeitabilidade.
- poi(ref) > centro comuntario passe a respeitar os moradores e se adequar aos
  padroes externos > se adeque aos padroes externos n exclui a identidade
  cultural das comunidades, gera um maior dialogo, 3 nem todo centro comunitario
  apoia e aceita as pessoas da comunidade, mesmo dentro da comunidade muitas
  vezes n tem força.
- supressao de parte da nossa identidade, é necessario que essas instituicoes
  tenham a politica de respeitabiildade, o mosntro nao se destroi por fora, mas
  por dentro, só empoderando e trazendo um papel relevante. o onus da oposicao é
  que a contracultura deles nunca vence, enquanto no nosso cenario nos
  dialogamos com o mainstream externo e com as pessoas marginalizdas.
-
* DLO
- 1 > pq as circunstancias n vao mudar > fator mais importante no racismo, n é
  questao de cultura, é uma questao de raça > ex: pessoas negras nos EUA, ricos
  tudo bem essas pessoas continuam fudidas, pessoas pretas e educadas em
  posicoes de poder. independente do tipo de cultura que elas tem. Proprio
  Obama, ainda assim as praticas racistas continuam a ser bastante forte.
  - aculturacao, n temos mais recursos, simplesmente fazerem algo mais similar a
    cultura dominante, respeitando os valores do protestantismo.
- 2 > as instituicoes sao feitas por pessoas que moldam, efeito contrario,
  instituicoes modal como as pessoas agem, se na escola somos ensinados de
  alguma forma, igreja e caralho a quatro. significa que as proprias pessoas
  ficam aculturadas.
  - essas insti servem de representacao, mantem a cultura dessas pessoas, te diz
    que vc tem que mudar, e deve aprender uma nova funcao da historia, impostas
    pela comunidade que seculos nos oprimiu, oposicao que antes era feita pelos
    nosso lider, a nossa propria comundiade oprimindo a nos proprios o que doi
    ainda mais. Pense nos indigenas forçados a abandonar suas praticas
    ancestrais, acreditar no capitalismo como funcã́o e tals., mas tbm para
    manutenção do proprio grpo
- 3 > sobretude para quem n consegue mudar, mais dissimilares passam a fazer
  mais opressao, mais pobres envolvidas com crime, quem prefeer seguir a cultura
  antiga,
- poi(iza) > n mostram no sistema status quo elas conseguiriam n gerar o efeito
  de backlash de empatia
- 1 gov > a mais praticas identitarias com aculturacao > vao querer se afastar
  de apresentacao e tals, reparem que o mainstream é opressivo, esas logicas vem
  do ocidente para qessas culturas, enquanto que contrariamente fosse dominadas
  pelas pessoas.
  - resposta ao poi do iza > do nosso lado nos temos pessoas mais provaveis de
    se unir e reconhecer os problemas que o grupo como um todo tem, e mesmo que
    a curto prazo, se autoempoderando, e de responder ao mundo exterior. nos
    temos menos descriminação sobre os mais vulneraveis.
* MG
- vilarejos que reproduzem a cultura islamica e se isolam de todfa sociedade.
  - excluidas socialmente
  - sem acesso a direito
  - nem sabem que existem
  - sem direito politico
  - relegadas a uma vida pessima
- respeitar nossa cultura a todo custo e ter uma vida merda e condenar as
  pessoas ao seu redor
  - 1 gov > simplesmente de uns pressupostos que nao existem, tendo nesses casos
    de poder vao poder fazer mudança
    - pq seram aceitas? > reproducao de privilegios, fingir ser catolico, fingir
      ser hetero > faz com que na pratica vc tenha privilegio, iguala a
      competição, n existe backlash, propagar discursos de mudança social
      backlash, as pessoas ficam na defensiva.
    - ascencao da extrema direita > é uma reação, fazendo disrupção que volte
      com mais força > fica com medo > no mundo tem os privilegios > muito mais
      direita extrema > notem como na pratica, essas pessoas já estão em
      posições de poder, se ele n concorda com seu discurso militante, continua
      dando discurso contra racismo > vai tirar sua oportunidade de emprego(pior
      que faz sentido) > como que a gente vai ter mudaná
    - estar em cargos de poder dá poder politico e economico
      - influenciar politicas publicas, passar leis, quando estarem nesas
        posicoes, especificamente, hermeneutica valorativa, é mais facil
        convencer alguem que ela é catolica, inves de dzier que a biblia ta
        errado, achar dentro da biblia razoes, deus é a amor, carai genial,
        dentro das politicas dominantes, hermeneutica, convencer mais as pessoas
        conservadoras, n consigo achar motivos.
      - poi(1o) > violencia sempre vai existir, no status quo os pais na frança
        conseguem esquecer n enteid nada > quando a gente fal ade violencia
        muito mais provavel quando vc n está, matam e espamcam, a disrupção é um
        risco na pratica. essas instituicoes moldam essas pessoas e tenham
        certos compotamtneos, responsabilidade inerente. pessoas com posiçao de
        vulnerabilidade, notem que o pai tem o dever de dar a melhor proteção ao
        filho. pai protegendo o filho. notem que existe um dano enorme,
        violencia e fisica, dever de responsabilizacao de darem a cultura que
        gerew menor dano.
      - perder apoio politico
* MO
- falaram qeu ao mesmo tempo que querem incentivar que os moradores mantenham a
  cultura original, instituicoes
  - n compram exatamente o onus, se ta mantendo a cultura a instituicoes nao
    estao sendo incisivas
  - comportamento individual definido pelas instituicoes
- menor autoestima interna
  - perda de sentimento de pertencimento
  - grupos marginalizados precisam desse senso de comunidade, n se vem na midia,
    el;es precisam de alguma forma de uma comunidade que os apoiam
  - eles nunca seram brancos(videira)
  - quando vc nega essa ideia de coesao interna, vc esta perdendo um sentimento
    de pertencimento.
  - esas minorias teram que adotar ideias que nao se adequam a sua realidade,
    essa cultura n é feita nem pelos marginalizados, nem para os marginalizados.
  - vc acaba fazendo concesão mental de uma narrativa que é excludente.
  - ex: babu > ladrao ladrao tim maia
  - as geracoes atuais futuras, olhando para a cultura dos seus antepassados
    como algo que pode ser abrido em mao
  - propria percepcão interna de valor, nasceu na cultura errada
  - no melhor cenario do governo > mesmo se cultura for menos importante que
    qualidade de vida > esas politica de respeitabilidade reforça >
    framing(escravidao tinham que esconder sua cultura e religiao, n fez
    marginalizados se ) > superioridade cultura > vies de confirmacao > quando
    vc tem essas instituicoes proeminentes que tem um grande papel, agr falando
    pessoal vamos nos adequar ao mainstream, se eles tao se adequando, é pq
    minha cultura é superior.
  - escravidao ouve escravidao e agr tem conciliacao > sao jorge é ogum, hj tem
    tanto conflito quanto antes > mecanismo é coerencia a lealdade, elas
    valorizam uma certa coerencia
  - vira lata, americano olhando brasileiro lambendo bota
  - menor percepcao de valor, se o que o governo queria melhorar a qualidade de
    vida.
- reforça a percepção externa de inferioridade
* WG
- distincao 1g
  - metrica n explica muita das coisas que so ficam claras no nosso discurso,
    o que esas instituicoes tem?
    - responsabilidade, elas sao parte do sistema, dentro do sistema, incentivam
      que as pessoas mostrem os valores
    - impacto maior
      - justamente de tudo que a 1op falou, backlash, essas pessoas que sao
        conservadoras, tem o poder de impeidr a entrada dessas culturas
        minoritarias, mostrar os valores que nao sao compativeis, e assim elas
        tem uma reaçao social muito maior.
      - empatia e visiblidade > regudiados frances > eles tem visibilidade, sem
        aproximacao n tem poder politico real, n tem possibilidade de poder de
        mudança de dentro. atraves desse mecanismo de empatia. consegue entrar
        dentro do sistema.
      - 2 op > caso muito bonito sobre cultura
        - autoestima - vao perder senctimento de pertencimetno
          - isso piora quando essas instituicoes n tao dentro
            - sao mais marginalizados, as pessoas terem uma aproximacao
            - o obamacare so conseguiu fazer pauta, pq ele entrou no mainstream,
              dialogou com pessoas brancas. reforma num sistema tao
              consolidados, trabalha com empatia, nao gera uma reaçao social tao forte
              - cultura n é imutavel, a cultura ela se transforma, n existe
                ganho nenhum ganho real em manter a cultura
              - num cenario de globalizacao todo mundo abre mao da cultura
              - a partir da reputacao que ela é melhor gerar aproximacao, ate
                mesmo valor interno, com menos marginalizacao o empoderamento
                acontece mujito melhor utilizando o mainstream, tem uma questao
                de cota e tals
              - pessoas minoritarias, bolsonaro que bota negros e indios ainda
                que minima, dentro daquele sistema de merda, as minorias sejam
                minimamente ouvidas.
              - 1op > negros e fnotipos, politicos negros so conseguem isso
                quando performam o valor, eles nao conseguem provar como esse
                respeito efetivamente viria, ela nao consegue uma ascencao
                social, alem disso como negros sobre bandidos o backlash
                acontece no nosso cenario. os valores sao muito distantes. isso
                de ver engro como bandido. elas podem ser mitigadas dentro do
                nosso cenario.
              - urgente que esas pessoas vivam melhor.
              - possiblidade de ascencao social
* WO
- eles trabalha com a ideia de fenotipos
- so o giovanni engaja mesmo se individuos acendam os prejuizos que vc vai ter
  pra comunidade superam o ganho individual para certas pessoas. percepcao de
  inferioridade vai ser manutenda, direitos hipocritos
- cenario dos centros comunitarios
  - eles mesmo sao lideres comunitarios
  - eles costumam ter uma grande influencia, e aquilo que faz eles sentirem
    parte de uma comunidade
  - qualquer poder de grupos, eles tem influencia, cenariode poder, todo o
    posicionamento da instituicao vai terinfluencai
  - essas comunidades ja nao tem um acesso a escola e educacao
    - ao abrirem mao da sua origem, o que relaciona sao as praticas culturais,
      senso de pertencimento menor
    - ex: obama, n resolveu a questao de posicionamento, obama so foi aprovado
      pq ajudava os brancos, a partir dom omento que eles se adequam eles
      precisam se adequar nas pautas
    - vamos assumir que elas acenderam
      - precisariam abrfir mao de pontos importantes
      - vao ser vistos como imitador, n vai ser visto como mainstream e totalidade
      - vai ser visto como o pobre que acendeu
      - negra que alisa o cabelo
      - reforça os esteriotipos
      - abra mao de uma cultura minoritaria
      - cria a ideia de que se elas puderam se adequar orestante tbm pode,
        reforca a ideia de que eses individuos so vao ser respeitados pq se
        adequadream,
        - lgbt o que nao é afeminadao
        - negro que nao se adere a umbandias > manutencao do maisntream dadno
          direito a qume "merece" esses individuso individualmente tenham esse
          ganho, a populacao muito atrelada, esa opiniao da pop nao vai se
          alterar, o preconceito continua.
        - pelo menos a gente tem omvimentos de valorizacao dos individuos
          - processo de globalizacao n é igual
          - culturas que ja sao valorizadas, n é sincretismo de cultura, alguem
            ta sempre se favorecendo, se n existe esse movimento de alguem fazer
            ponto a isso, na pratica isso vai desaparecer, n é um contexto de globaliz
          - iza > em nenhum cenario se resolve tudo, mas algumas pautas nao sao
            excludentes > aumenta a visiblidade como um todo > pauta em comum
            com o mainstream -----> dando direitos basicos para a populacao,
            focar em politicas publicas de > vc nao esta resolvendo o problema
            de opressao cultural, tende a barrar sua ascencao
          - n existe esse backlash, campanhas na midia para valorizacao de
            mulheres com transicao capilar, a midia tem dado bastante espaço pra
            isso. ignorar os canais alternativos da midia.
