#+TITLE: Debate01

PM Tati DPM Ruth
LO GRP DLO Daniel
MG Abigail WHip Ivan
MO Saulo Whip Ingrid

* PM
- Resposta da periferia e pobres e pretas
- Pq lamentamos?
  - Como resposta na verdade tá de fato acender bens materias, acaba escondendo
    os repais problemas dessa parcela, mudança de foco??
  - Mudança de foco, das musicas pessoas representam
  - Condicoes precarias que vive essa sociedade, onde o preconceito irraizado na
    sociedade vê nela a todo momento
    - Ex: Branco e preto ocorre um assalto naquele momento, vao pensar primeiro
      em quem?
    - Tirar o foco da realidade dessa parcela
    - Representatividade
      - Essas pessoas que representam esse estilo musical, passam uma imagem
        para essas pessoas, sentimento ruim para essas pessoas, sentimento de
        culpa, só nós sabemos nossa luta nosso dia a dia? Culpa, incapacidade de
        chegar a esse patamar, haver essa mudança, da real realidade que essas
        pessoas elas passam.
      - Trazem uma imagem totalmente diferente, veio para representar mas traz
        algo que não condiz.
* LO
- Respostas > Esconder os reais problemas > Rappers quando sobem podem ter
  mudança. Essa mudança de narrativa muito esforço, muito tempo visibilizando
  esses problemas. Mesmo se agora eles parem, existe um percurso.
  - Sentimento de incapacidade > Rappers advindo dessa classe e podem mostrar
    que essa classe pode mudar o jogo > Mesmo se for falsa > Minimamente que eu
    me identifico.
- Aplaudimos grito de vitoria > KRS-One Public Enemy > Esas vivencia é marcada
  por exclusao e repressao > Corpo policial > Sistema em si é preconceituoso >
  Negros se sentem consistentemente hostilizados > Coisa muito cobrada > Ser
  autentico é cobrado > Cobrar postura > Rappers advem dessas comunidades >
  Todos querem chegar o mais perto Racionais e Sabotage > Mesmo sendo
  alternativos sao minimamente parecidos.
- Cobrado pelos ouvintes de rapper que a luta seja dita > Só pode falar de
  rapper se tiver a vivencia > Rappers glorificando mostrando que conseguem
  superar as estatisticas > Sisifo(BOnito)
- Pq devem ser ganhos materiais > Negro é heroi injustiçado atraves de superar
  por parte da luta mantendo a postura > O cara tem que provar que tem poder e
  isso é com glorificação.
- Sistema capitalista, se eu nao tiver dinheiro eu nao vou conseguir nada, as
  pessoas negras sao erxcluidas, se vem indigentes, justamente por nao ter muito
  dinheiro, quando eles mostram que podem ganhar dinheiro que eles podem comprar
  todas esssas coisas que sao absurdas, msotram que sao poderosos e ganham a narrativa
- Material > Felicidade é realização de expectativas, felicidade é com base em
  cumprimento da expectativa, comprar o que eu quiser, mostrar o poder que eu
  tenho.
- A minha vitoria é a sua vitoria > Individuo tenta se auxiliar com base na sua
  rede de apoio > Vou me ver como semelhante a minha familia > QUando eu vejo
  pessoas negras no topo comprando carro caro eu vejo que agora e eu posso
  chegar lá um dia, no pior cenario se o rapper esquecer da quebrada, só pelo
  fato de alguem muito poderoso muito rico, alguem muiotm mais interessante que
  eu, posso me identificar e personificar naquela pessoa. Pessoas se sentem
  muito mais confortaveis, há ganhos psicológicos tanto para o individuo quanto
  para o rapper.
- É necessario que a gente tenha, nesse sistema capitalista que sempre fode a
  gente, subverta.
* DPM
- Sistema de desigualdade racial em que o rapper surge como forma de resposta a
  esse sistema
- Rapper nao surge como forma de ostentacao mas como forma de demosntrar
  resistencia, resistir e critiar o sistema o qual vc está inserido
- Nao obvjetivo de ostentar, dar voz a grupos marginalizados, outro estilo de
  musica que nao sao identificados
- Pq a gente ganha?
  - Longo prazo > Mudar a mentalidade racista dentro da sociedade, 1 Op ignora
    contextos muito diferenciados, Ex: EUA, comprar rapper EUA e Brasil,
    contexto absurdamente diferente, lá os pretos, vc já teve um presidente nos
    EUA, vc vê pretos na politica, lider de empresa, já tem uma ascenção.
    - Comparar sociedades de maneiras diferentes > Pessoas que receberm voz pelo
      rap(subdesen) contexto é diferenciado, pq é importante, nos queremos ter
      uma mudança a longo prazo, nao vai mudar mas pode empoderar os grupos,
      quando vc trazem argumento dos ganhos materiais, o rapper nao é apenas uma
      forma de personificar, criticar o sistema de uma maneira explicita, quando
      vc fala do Djonga exemplo, nao faz sentido, empoderamento surge como uma
      forma de grupos sociais recebendo um poder, n é um INDIVIDUO, mas um GRUPO
      SOCIAL, pessoa preta e milionaria, caguei
    - stakeholder é a sociedade em si, quando vc foca muito mais nos ganhos
      materiais, vc mitiga a luta, resistencia muito menos efetiva, foco fica no
      fim e não no meio, quando vc foca uma musica em todo o dinheiro, quando vc
      foca nisso, vc nao fala da luta que trouxe ate o momento, vc mitiga dentro
      da mentalidade como essa sociedade permanece racista, quando vc aparece no
      jornal uma pessoa preta que enriqueceu com a musica, as pessoas tao
      focando muito mais na riqueza e isso é muito mais relevante, manter a
      idfeia de critica do rap, e sim algo focado na luta e na resistencia em
      si, só atraves da mentalidade da luta, quando vc ve muitas pessoas
      brancas, e um grupo social inteiro tendo contato com esse rap, claro que é
      importante que vc tenha os ganhos sociais, mas esse nao deve ser o foco
      das suas musicas, a gr que vc ganhou o foco agr que vc ganhou poder tem
      que falar da resistencia e do racismo, muda a mentalidade das pessoas
      brancas do racismo, permita que as pessoas tragam mudanças na sociedade.
    - Psicologica e da autoestima > Quando vc fala pra uma pessoa que é parada
      pela policia, quando faz paar ela focar nos ganhos materiais, mas eu nunca
      vou chegar nesse topo(probabilidade) > olha como eu ganhei, olha esses
      cargos essa grana, vc ta focando no fim e nao no meio, na grana q1ue vc ta
      ganhando e nao no meio, olha como foi facil pra mim, simplifica a
      narrativa, nao ta focando na narrativa mas na finalidade. Nao foca na
      narrativa de batalha. Gere a representatividade influenciadas a exercer
      seu maior potencial Ex: Funkeiros cults nao é sobre ostentacao, mas gerar felicidade.
* DLO
- Refutacao primeiro governo racionalizacao cultural imputa necessidade de
  manifestacao, trazer pauta de empoderamento e justiça social, a gente trazer
  uma pauta de empoderamento nao garante a visibilidade no inicio da carreira,
  para o individuo chegar no auge da carreira.
- GRP trabalhou no melhor cenario, a gente nao tem uma obrigatoriedade
  justamente pq tem uma autonomia desse individuo, o rapper, tem um foco no
  ganho material, uma necessidade intrinseca dessa sociedade marginalizada,
  muito importante que essa pauta tenha adesão da população e representativa da
  populacao, pop pouco engajada, pouca conciencia da propria situação, dentro
  disso tem uma manifestacao intrinseca dessa pessoa, nesse icone simbolo que
  seria o rapper, em relacao a manifestaacao cultura, na grande massa dessa
  populacao, desejo intrinseco de suprir essa privacao material que vivem.
- Rapper pode trazer sobvre empoderamento e material > Respeitando totalmente a
  autonomia do rapper, pode ser um rapper que nao carrega toda essa bagagem
  social, precisa empoderar mas o rapper que faça o ordenamento de pauta, caso
  queira ???????????? Funçao de representar sua populacao.
- Populacao funciona parecido com o orgulho LGBT e antes tinha uma opressao,
  representatividade e link identitatario, essa pessoa simbolo carrega uma visao
  de mundo e do grupo.
- Principio do afeto > Poderes e forças que afetam o individuo. Intrinsecamento
  um dinividuo é afetado por uma privação individual, ele segue aquele
  individuo, as afetações, aquilo sim um objeto de desejo. Star power se ele nao
  ter essa base, para ele depois trabalhar o empoderamento, a espontaniedade,
  quando a gente traz toda essa espontaneadada dessa populacao, desejo muito
  grande, representatividade
  POI(Ruth) > Thelmionha ganhou BBB, foco é justamente na historia dela, nao é
  sobre ter grana, mas o que te levou até lá, nao estmaos proibindo o rapper ostentacao.
- Ref meio e fim > Como isso pode impactar a população mais vulneravel, esse
  meio poderia ser preenchido, a gente acha que isso é inerente dentro da
  representatividade, o rapper tem si uma responsabilidade de arcar com isso.
  Tem sim que acompanhar esse meio funciona, por mais que a pessoa não acenda, é
  muito importante que ela tenha um escopo de esperança pra lidar com aquele
  cotidiano esmagador, discurso de justiça social moroso, inflamação social
  muito grande, saturada totalmente incultada de uma responsabilidade social que
  ela nao necesasriemnte tem que assumir.
* MG
- Rap miuto tempo mensagem cultura a ser passada, forma de liberdade de
  expressao, toda essa ostentacao absurda por tras, existe diversas formas de
  ostentacao, essa maneira de ostentar radicalmente, usando palavras abusivas,
  com partes mais delicadas da sociedade, traz a tona roubos, nao somente aquela
  coisa que eu to aqui, eu venci na vida,(trabalho, desempenhei) existe
  diferença do que ta sendo discutivo, uma letra pesada, que as vezes
  vangloriam, abusos sexuais, retratar assedios sexuais, eu tenho dinheiro eu
  tenho mulheres, tudo que tem por tras disso é assalto é roubo. Reflexo para um
  adolescente, rapper abusivo, nao é que traz uma mensagem, certo que realmente
  com o tempo, esas pessaos massificadas se esgotaram. Há um limite de tudo, a
  mensagem que estao retratando esse tipo de rap pesado, alem de atacar eles
  mesmos, acabam atacando mulheres as vezes, a forma desses rappers, é muito
  pesada, abusiva.
- Personificacao social > Formas de mostrar ostentacao(? quais) > COmparado a
  questao LGBT, eles lutam em prol de realmente botar a cara a tapa e mostrar,
  mas nao é dessa forma que agride outras pessoas, coisas que propagam o mal,
  nao é pra ter o respeito a gente precise sair xingando, menosprezando os
  outros, existe divisao entre brancos e negros, respeito, visao, eu to ali
  atras de minha grana, minha grana, se pondo em um lugar, massificando.
- Essas mensagens devem ser passadas de forma verdadeira, varios tipos de
  rappers, outras formas usando, esse caminho, entretanto nao tao pesado.
- POI(Saulo) > Pior cenario, n é inerente ao rap, louvar ou não esses ganhos
  matewriais?
- Tem muitas formas de louvar todo esse ganho por tras, eles devem ter outra
  forma de mostrar isso, maioria dos clipes é um lucro que fvem por tras de um
  roubo, podem sim essa forma de passar essa imagem de mostrar o ganho material.
* MO
- MOção lamentar ou nao, vamos provar como o mundo é um lugar melhor
- Quebvra da narrativa do fracasso
  - Historica de um povo negro invisibvilizado, vistos como incapazes, vistos
    como problematicos, povo alvo de uma necropolitica, sempre crimalizou
  - Qualidade de vida desses individuos :
  - Racismo estrutural, afeta esse povo diretamente :
  - Ao contrario do GRP quebvra de estatistica e representavidade. A menor
    mudança no status quo, quando vc coloca o dinheiro em questao vc mostra que
    sao capazes, que o preto tbm tem dinheiro, ao contrario daquela narrativa
    contruida historicamente
    - A gente gera auqele povo que nunca esteve naqueles espaços de poder agora
      lá, else precisam mostrar dos problemas, essa narrativa de luta é
      extremamente desgastante, nunca mostra possibilidade de sucesso de
      victoria, desestimulo(Amaral ou nao?)
    - Nao mostra so para essa populacao que ela devce estar na luta, quebra a
      narrativa, mostra tnato pros pretos que eles sao capazes quanto para a pop
      branca, morar que vc tem carro é instigante para aquela populacao que nao
      tem perspectiva de mudança(GRP) só isso n é o suficiente para instigar a
      luta, nao é narrativa de fracasso
    - Como a gente garante que essa narartiva existe > Criminalizacao da
      capoeira, EUA  grande taxa de carcere, essa narrativa de fracasso esta
      encrustrada na narrativa social. Por menor que seja é importante para
      gerar uma coesao social na sociedade, sociedade vê esse negro como
      inimigo, ta mostrando que eles sao merecedores, pq é importante gerar essa
      coesao social, politicas publicas direcionadas e reformas estruturais,
      sociedade vendo ele nao como diferente mas agr como igual
    - POI(1G ) > De que adianta se instigar, o preto pobre olha para realidade e
      contradiz, nunca vai chegar nesse ponto > Probabilidade ele nunca vai
      chegar, mas vai pensar que nunca via contra, ele vê que ele tbm é
      capaz(GRP) Psiclogico dessas pessaos que sempre estao marginalizdas,
      inercia pior que tá nao fica
    - A propria acensao veio com esses conteudos > Problemas estruturais e
      carrao, afeta principalmente esse povo negro que sempre foi marginalizado,
      atinge todas essas pessoas, o branco ao asiatico que também gosta de
      cantar sobre isso. Eles tambem crescem na midia, eles também crescem no
      mainstream, espaço para eles motrarem. Cardi B fala dos problemas da
      populacao negra, nivel muito maior que o 1G, rapper que fala um pouquinho
      sobre resistencia, artista negro ir lá pr ogrammy mostrar os problemas que
      a pop negra passa.
* WG
- objetificacao > ele falou de um negro tem que ter uma coisa para demonstrar
  seu valor na sociedade, eles nao precisem disso, sim eles nossa sociedade é
  bastante preconceituosa, é bastante opressora, eles nao precisam se diminuir
  dessa forma para mostrar seu verradeiro valor.
- isso mudou, e eles podem sim trazer uma nova realidade, foram vistas por muito
  tempo, entretanto eles tentam contornar isso atraves de video, eles podem
  retratar isso, de outra forma, sem massificar a si proprios, objeto na mao de
  gente branca, um homem é formado de outras coisas
- POI(Daniel) > Em relacao a manifestacao da cultura, se isso estiver intrinseca
  e isso for o que eles querem mostrar isso nao é legitimo? Sim, mas depende da
  maneira que é passada. vc tao botando a raça deles para baixo. Isso ta sendo
  pautado, forma racista e engraçada, somente desse ganho, eles estao se
  objetificando, se massificando.
- POI(GRP) > Esses rappers mostram para objetificacao para ressignificar > Da
  pra fazer sim, n precisa ofender ninguem, existem sim letras de rapper que dá
  pra ter esse avanço. Se eles nao querem o mal nao faça o mal, se vc quer o
  respeito vc n preicsa impor o respeito?
- POI (Saulo) > Para ganhar fama com esse tipo de rapper > Dá oportunidade para
  chegar naquele local de fala. Forma que vc ta falando é objetificada, mipor
  isso de maneira errada.
* WO
- Comparando 1 Op > Instigar a classe negra apenas SAaulo que nos exlpica que
  esse empoderamento é tornar o negro em um cargo de poder que é costume de
  branco, aceitabvilidade é tao importante? Seja escutado, se nao houvesse a
  narativa o rapper nao seria tao consumido, nem tao popularizado, advindo dessa
  glorificacao.
- Pedro pq a inspiração deve ser necessaria n explica porque deve ser pela
  glorificao, quand ovc mostrar só as lutas vc desestimula a classe, mostrar
  apenas o meio, isso desestimula, instigar a luta, mostrar mudança pratica
- 1 op quebra perspetica do rapper > importante para o proprio movimento, como
  essa popularizacoa permitiu, só saulo nos provou pq o rapper precisou dessa
  role para se popularizar
- respostas 2 gov > analise esteriotipada do rap, associa ao roubos e abusos
  sexuais,
- respeito nao se resume a essa narrativa, nenhum momento 2 def mostou uma
  narrativa eficaz,(nao precisa, explicar no feed)
- 1 def mostra que o rapper é uma resposta dos pobres e negros, por isso que o
  rap tem que se distorcer e manter.
- a grande questao se nao fosse essa narrativa o rapper nao seria consumido por
  brancos, perspectiva do consumo, capitalismo, entrou na casa dos brancos redes
  sociais brancas, branco nao vai consumir uma luta negra, permitir a
  popularização, alcançar esses brancos, permitir a assenção economica, na
  verdade como saulo nos provou foi a glorificacao que garantiu o rap, nao iria
  ter essa popularizacao, ele fala de luta sim, ele por si, a sua vida por si é
  a resistencia
- POI(Ruth) > Stakeholder é o empoderamento e autoestima das pessoas negras > É
  por isso que o seu argumento nao vence > Vai se sentir culpado, se for se
  sentir fracassado por qualquer coisa, esse é o grande problema, entre essa
  perspectiva de causar culpa, nao tem sentido ele se esntir intimidado, em
  nenhum momento ele vai se seentir, o rapper tem que focar no meio, as
  estatisticas ja focam no meio, todo mundo ja foca na derrota dos negros, é o
  pior cenario da gente, a glorificacao possibilitou o sucesso do rap,
  sofrimento nao vende tanto quanto dinheiro e carro caro.
