#+TITLE: Debate02

PM Brenda DPM Nicholas
LO Barbara DLO Dias
MG Rossiny WhipG Juan
MO Liza WhipO Diana

* PM
- Disclaimer
  - POV Mov Vegano acredita em ambas
  - Qual mais condizente com os fins e meios mais capazes
  - Secassão da exploração
    - Divulgação da relativamente do sofrimento, relativo choque, provocar
      reações de empatia, todo mundo é humano, sofrimento é apelativo.
  - Problemas do consumo da carne
    - Sociedade egoista, ignore origens e sofrimentos que nao sao o proprio,
      quando vc opta lida no curto prazo soc que só pensa no proprio umbigo.
      Melhor caso da Op
  - Qual o prob caso op
    - Vazio, nunca vai a raiz do problema, sempre vai ter outro animal para
      explorar, nao consegue extremamente abrangente, sempre vai jogar
      beneficios(Carne de porco tem problema vamo comer frango, vamo criar de
      outro jeito) > Logica de varrer para baixo do tapete. Carne é relativo de
      costume, vao fazer tentativas de evadir isso. Essa narrativa é uma
      narrativa das pessoas nunca lidem com o verdadeiro problema.
  - Nosso lado
    - Parte justamente no ponto central, premissa no caso da op, mesmo vivendo
      numa sociedade que vive no proprio umbigo, narrativa necessaria, usa dessa
      possibilidade, vc efetivamente consegue lidar com um mundo que as pessoas
      sao incapazes de pensar no outro. Blindagem(Diferencial nesse debate, ir
      na logica centrl do debate ou evadilos > Mov vegano diferente de outros
      movimentos, que conseguem ser melhoradas com coisas como inovacao, nao
      acontece no mov vegano, acabar com o sofrimento dos animazes, FIM da
      exploração animal, só ocorre quando a gente tem uma mudança efetiva de
      mentalidade. Mesmo se a gente mudar a produção, a vaca ainda ta prozindo
      leite, o fim ultimo da vaca é isso, a consequencia dessas cadeias
      pordutivas, advem das pessaos nao terem empatia, criticar a lgoica
      antropocentrica de superioridade) esse tipo de logica que legitima o abuso
      do animal. QUe o mov vegano quer impedir.
    - Qual o problema dessa ideia antropocentrica?
      - A op nunca efetivamente questiona essa logica, atirando e furando, no
        nosso cenario, o mov vegano, a pauta nao pode ser resolvida contornando
        o problema, é um fim bom em sim mesmo, é uma coisa boa que tenhamos soc
        com empatia. Unica coisa que muda a premissa da op, que todo mundo é
        egoista.
        - Lida com o frfaming longo prazo e lida com o fim essencial
        - E nao faz com um meio que é condecendente

* LO
- Pq que seria necessario que a gente focasse nos prejuizos causados pela carne?
  E n pela exploracao animal etc
- Cultura de consumo da carne muito forte
  - Questao de comer arroz ou feijao, questao cultural muito forte, carne é ter
    provisão, pessoas trem sensacao que carne pode nutrir mais, carne é simbolo
    de status. Criando a ideia de que os animais foram feitos para serem
    consumidos.
  - Habito muito dificil de ser quebrado, abandonar e trabalhar esse cenario.
    Para quebrar essa questao, acabam fazendo o que a Brenda falou, mostrando
    video dos animais morrendo.
    - Dois problemas
      - Nem todo mundo vai ter empatia, pessoas acreditam que isso faz parte da vida
      - Videos muito desagradaveis, boi sendo morte pintinhos sendo massacrados
        - Ninguem quer ver isso, concientizar que as pessoas precisam ver,
          veganos pessoas extremamente chatas. Perde a paciencia. Nao absorve da
          forma que elas querem, nao é muito efetivo.
        - POI(Brenda) > Meu onus nao é video de pintinho virando nugget -> Tá,
          ta bom
- Pq seria mais importante a outra narrativa?
  - Questao de desagradavel, os videos sao os melhores
  - Mesmo se forem concientizar as pessoas nao tem tanta empatia, a gente
    demonstra que teriam prejuizos para pessoas. Ou até mesmo com vc mostrando
    para aquela pessoa. Buraco camada de ozonio, aquecimento global e o caralho.
    Um mundo onde vc nao consiga viver bem. Pq vc ta comendo muita carne.
    - As pessoas vao passar de um animal apra outro > Movimento vegano vai
      tentar mudar o consume de carne no geral, esse n é nosso onus falar que só
      vai mudar(bendra nao falou isso)
    - POI(2G) > QUando vc fala com problemas ambientais e trabalhos escravos >
      Mudar outras soluções para esses problemas que nao sejam a pauta do
      consumo de carne.
    - Mais empatia com trabalho escravos de outros humanos.

* DPM
- Op insuficiente, n lida do problema real, debatem fora da moção
- Faz com que o mov vegano se dobre das vontades alheias, sem colocar sua
  ideologia, função de moldar a politica, se ele se dobra no curto prazo, mostra
  que sua ideologia é dobravel, portanto o mov vegano no cenario da op se
  apequena frente a realidade dos fatos.
  - No cenario da op, a gente resolve os
  problemas de tecnologia, e a gente continua consumindo carne, com esse
  constante shift de pautas, n tem uma cara para de defender, fisologico nao
  ideologico, muda as pautas direto.
- COnsumo de carne é muito forte
  - Tipo de divisao, a gente sabe que faz merda mas nao se importa, pq nao
    estamos conectados na cadeia, eu sei que eu to endossando essa logica, todos
    os animais existem para nosso bel prazer, eu sei que isso é um problema, mas
    eu continuo com isso pq eu n me importo com a cadeia produtividade.
  - A cadeia produtivida é ruim por si só, ainda se nao tivesse esses problemas
    nos mudariamos, pq ela subsiste com os sofrimentos dos animais.
  - A gente muda com o ponto da brenda empatia, se a gente n se liga ao animal,
    precisamos do choque, choque do pintinho morrenod,. é por isso que esse
    choque gerado, impacto e empatia, observa um animal morrendo, pasa a ser
    algo que te marca profundamente, é nesse ponto que o choque de empatia,
    maior adesão no curto prazo, algo emocional, ainda que a oposicao venha,
    empatize com o trabalho escravo > se resolver o trabalho escravo essas
    pessoas vao abandonar a pauta. resolve um problema e deve ser usado. A
    empatia gera uma mudança individual, a gente tem a iudeia do governo grandes
    empresas devem mudar, joga a nossa culpa da cadeia, no longo prazo nos
    provavelmente vamos resolver os problemas do co2 tornando logica de consumo
    mais eficiente, mas isso só torna mais animais morrendo, e vcs da op jogam
    isso pra fora, as pessoas percebem que conseguem continuar matando animal.
    Ponto da empatia, individualmente mudem essa logica de consumo.
    (POI) > Vcs consideram um cenario em que os animais possam ser tratados
    decentes > Consumo carniça exarcebado, animais logica de abate, pode viver
    por 25 anos, logica de eficiencia vaca possa ter vida de 2 anos, expandir
    para mais pessoas, pop crescendo, mov vegano vai conseguir fazer com que as
    pessoas consumam menos carne, mas nao vai mudar a real.
  - Nosso verdadeiro problema é como o serr humano se enxerga frente ao mundo,
    varioas outras organizacoes tem essa pauta de mudar a forma como a carne é
    produzida, mas o mov vegano é o unico e tals, ele fica de escanteio.

* DLO
- engajamento com mecanismo do gov
  - a falha se aplica a eles tbm > mais evasivo > coloca as coisas abaixo do
    pano(no nosso) > excecoes existem em ambas as casas > empresas e
    instituicoes que priorizam o bem estar do animal, dando boas condicoes pro
    animal, pra no final ele ser habatido de forma conciente e indolor. O
    proprio nicholas falou que é improvavel.
    - A carne prejudicial para pop pq os animais sao maltratados, toda logica de
      baixar pra debaixo do pano, já que os bois sao maltratados vamos para os
      galos, se um existe maltrato, outro pode ser mascarado, nos conseguimis
      atingir muito mais areas e efetividade. A simples existencia da criacao em
      massa.
      - ainda sim traz beneficios para o meio ambiente, a simples existencia
        dessa criaçao, já vai gerar o impacto tanto pros individuos quanto para
        o ecossistema como um todo.
        - contextualizacao > tendencias individualistas da sociedade, os ganhos
          pessoais estao acima de tudo, a logica capitalista de producao
          responsavel pelo proprio fim > as pessoas estao se preocupando cada
          vez mais consigo mesmo > paralelo a isso já existe barreiras naturais
          para a inexistencia do veganismo > grandes empresas que falam que a
          carne é essencial(nutricionistas e tals tbm falam). Onus para o
          governo e para a oposição, veganismo é prednominantemente ruim. Os
          individuos ja nao se sentem motivados, vai ser muito caro para vc se
          manter enquanto vegano, dificuldade de sociabilidade, necessario para
          responder a essa pressao do individuo
        - POI(Nic) > Mov vegano coadjuvante que já vao passar de qualquer forma,
          ja vai ser atingido de uma forma ou de outra > nao, essas narrativas
          maiores sempre vao existir, é um contexto muito especifico, no curto
          prazo vao parar, para que haja uma producao que vá demandar uma
          producao em massa, se a gente assume que é ruim para o prejuizo
          individual desses animais, vai ser ruim para os
        - Narrativa de fuder o individuo > Precisa atingir diretamente o
          individuo, se ezxse cara tá tao preocupado em atingir um futuro
          saudavel , ele precisa se preocupar com a saude, falar como isso afeta
          a sua saude, cogitar virar um vegano. ALem disso, de nao só afetar o
          individuo mas afetar o ciclo social que ele tá, aquele grupo esteja
          bem, desse desequilibrio hormonal, saude dos seus proximios e suas
          futuras geracoes.

* MG
- destaque enquadramento necessario
  - priorizar, pauta trabalhista ambientalista pode ser pauta mas nao deve ser a
    prioridade, alem disso, moção de agente, o maior stakeholder é o movimento
    vegano, em qual ele está melhor.
  - Principiologico
    - Se vc nao acata, fode os principios do movimetno vegano, movimento vegano
      nao do vegetariano. 1 G se preocupa com as consequencias que o movimento
      terá, e como a sociedade terá esse movimento, independe das consequencias
      nao vegana vai enxergar esse movimento, a gente quer que ele seja
      estruturado enquanto movimento vegano.
      - movimento fem inista > deve defender contra majoritarias da sociedade
        independe das causas > pauta é concientizar as proprias mulheres
      - principio do movimento vegano é a nao exploracao do animal > animais nao
        sejam explorados, nao tem como principio salvar os animais ou salvar o
        meio ambiente, veganismo nao só quer acabar com o consumo de carne,
        produtos que por mais que nao sejam de origem animal, o proprio testes,
        ovo e tals, fazer teste em animal nao traz, vc esta mitigando a propria
        essencia do movimento, misturando com a essencia do movimento vegano e
        trabalhista, nao vai ter o maior principio, vai ter pessoas que defendem
        o fim do trabalho escravo e tals
      - os impactos precisam de um movimento bem estruturado, suas pautas e seus
        principios, no melhor cenario da oposição, o movimento vegano nao vai
        estar cumprido, vai ter meios de produtos que nao causam esses danos.
      - vivermos em uma sociedade que naturalemten desincentiva, capitalismo e
        tals, se a gente nao prioriza o principio do movimento vegano, vc esta
        desestruturando o proprio movimento vegano, se trata de uma moção de
        agente, principal stakeholder do debate, para ele ser bem estruturado
        internamente. Isso é uma pauta do mov vegetariano, que quer acabar com o
        consumo de carne, ele é essencialmente com a exploracao animal,
        confundindo com o movimento trabalhista e ambientalista.
      - argumento da nao exploracao animal é mais irrefutavel, o impacto
        ambiental do consumo de carne, a sociedade como já esta enrraizada, o
        consumo de carne ela sempre vai procurar meios alternativos, o consumo
        de carne faz parte do conforta da sociedade, para nao acabar com esse
        seu conforto, se para acabar, ela vai sugerir maior fiscalizacao, para
        acabar com os danos ambientais, vai produzir tecnologia, se a gente traz
        como pauta principal nao tem como acabar sem tornar as pessoas
        veganas(Nich em parte) > A sociedade de fato de fato adote o objetivo vegano.

* MO
- engajando com o 2 g  > exatamente o que nos da 2 o > para o mov vegano
  conseguir adeptos e mais adeptos, priorizar a pauta > impactos da estrutura
  alimenticia > vao ter uma interferencia muito maior.
- quando a gente fala de prioridades ambos os lados vao ser beneficiados > a
  pauta dos animais tbm vai ser beneficiados > todos os atores vao ser
  beneficiados > ponto principal qual o melhor cenario que pessoas entram dentro
  da lut.
  - Diminuir o consume de carne animal e modificar a estrutura de producao >
    pessoas realmente veganas e nao consumam de forma alguma nada que, sociedade
    que olha para o proprio umbigo, vê os animais como secundarios, vao ver as
    pessoas sempre como um topo.
    - pessoas muito adeptas consumo carne animal
    - precisa contribuicao da sociedade, mais pessoas dentro do movimento, muito
      mais gente.
    - olhar da sociedaded, olhar estigmatizado, pensa que a pauta n é tao
      importante, bando de jovem comunista natureba, a gente precisa modificar
      essa imagem, prioriza essa pauta como um toda.
      - focar que essa estrutura da propria populacao > a gente trata isso como
        um beneficio para o proprio movimento, angaria adeptos, pessoas possam
        ser sensibilizadas, impacto possibilidade de sensibilizacao. movimento
        que nao quer só beneficiar os animais, as pessoas vao ver um mov que vai
        conquistar pessoas, dieta alimentar muito mais saudavel, pessoas meio
        ambiente.
      - POI(Bendra) > As pessoas nao entram na luta vegana pq estao longe do
        movimento.
      - Nao cortar o mal pelo raiz, a empatia dos seres humanos seria incrivel,
        gera a empatia quando els já estao dentro do movimento, entrem dentro do
        movimento, entenderem que seu proprio umbigo vá sofrer
      - alem de angariar adeptos, a partir do momento que a gente prioriza,
        maior relevancia as pautas, nao só em relacao ao que a pop vê, a gente
        conversa melhor com a populacao, vao ter impactos diretos com ela
        propria.

* WGOV
- 1 op
  - nao necesasriamente vao ter empatia com os animais e tals > pra que a moção
    faça sentido do jeito que tá inscrito > o debate é de agente > para esse
    debhate é mais importante pensar no movimento vegano > como as outras
    pessoas se importam > a pauta do movimento vegano é difernte do movimento
    vegetariano, acabar com qualquer consumo de exploracao animal > a partir do
    momento que elas só n tem empatia vc nao ta emglobando a pauta vegana.
    existe uma serie de produtos que sao derivados da exploracao animal que
    estao dentro da pauta vegana.
  - POI(Dias) > Qualquer exploracao animal gera dor ao individuo > se eu testar
    um cosmetico em coelhinhos, se eu testar em coelinhos eu n tenho nenhuma
    consequencia individual.
  - Mais eficiente mostrar os prejuizos para, tendencialmente as pessoas tem um
    conduta de consumir carne, se vc tem a tendencia a comer carne e ve aquilo
    como cultural, e focar no problema da exploracao animal, as pessoas vao
    tendencialmente a acabar com o trablaho escravo, acabar com o desmatamento(nich)
  - 2 op > as pautas animais sao necessariamente beneficias quando a gente poe o
    foco no consumo de carne, nao todas as pautas animais sao beneficiadas,
    consumo de lacticineo vc nao ta consumindo carne, mas vc ta tendo exploracao
    animal.
  - POI(Liza) > Tornar as pessoas veganas veganas como um todo, para simpatizar
    as pessoas > Quando vc foca os problemas, a sociedade de vcs tem um olhar,
    vc quebra o estigma, a tendencia naao é que as pesoas mudem, a cultura
    enrraizada de carne, entao vc ta mostrando um problema que NAO é o consumo
    de carne, entao ele nao vai pra pauta vegana, mas vai pra pauta trabalhista
    e amiental, elas vao tendencialmente resolver outos problemas
  - 1 gov > para que o movimento vegano tenha todo o impacto na sociedade,
    necessariamente ele vai ter uma estrutura bem consolidada, que só vem no
    caso principiologico, do meu colega, ele vira um movimento ambientalista,
    vira um mobvimento só vegetariano.

* WO
- as segundas bancadas entendem o real problema dessa moção > vou engajar o
  problema da 2 def
  - o qq a gente quer enquanto mov vegano > ele tenha pessoas mais adeptas,
    pessoas mais sensiveis ao movimento, pq nos temos mais adeptos, considerando
    que as pessoas, sociedade é individualista, consumo nao só da carne como
    produtos que geram animais como teste, impactos na agua que eles nao vao,
    ter, nossa possibiliade de gerar é muito maior
  - a gente mostra pelo movimento vegano pessoas dentro do movmiento para depois
    entrar, mesmo se elas nao pararem de comer carne, eles vao pensar duas
    vezes, e isso é bom, pelo menos vai obrigar as empresas a mudar seus
    habitos, pessoas vao parar, primeiro trazer pessoas simpaticas
  - rossiny > para qualquer impacto, ele precisa ser bem estruturado, se vc traz
    pautas ambientalistas e trabalhistas vc fode o proprio movimento > a gente
    concede que a pauta é a diminuicao do sofrimento, a gente vai terpessoas
    mais sensiveis, ele é internamente bem estuturado e ele sabe as pautas dele,
    vc nao vai deixar de mudar as causas, o nosso caso engaja diretamente com o
    2 gov
  - diferenciacao da 1op > só nos demonstramos os impactos para omovimento
    interno, quanto o o impacto externo, diminuicao do consumo desses consumos,
    impactos internos e externos.
  - POI(Brenda) > A conquista das pessoas nao é um fim em si mesmo, animais ou
    agrotoxico, o que tem a gasnahr se ater o seu na reta > nao haveram mais
    adeptaos no cenario do 1 gov, isso nao funciona, as pessoas so pensam em si
    mesmo, pensar no futuro proximo, no filho dela etc, preferem negar que
    aquilo esteja existindo.
  - nossos impactos sao maiores, pessoas dentro do movmiento vao questionar a
    producao, mais facil criar a empatia.
