#+TITLE: Debate03

* PM - Ana Livia
- Defin > Meios ficionais(filme, serie etc) afetam principalmente as pessoas que
  consumem cultura pop, jovem, adolescente
- Consumidores vao ser afetados > Forma como essas pessoas encaram a figura do
  vilão.
  - Quando o vilao tem uma narrativa por tras dele > Cria um fandom, pessoas que
    gostam daquele vilão > Desenvolvem uma empatia > Construido de forma humana.
    Idolatrar
    - INdependemtenete das justificativas eles cometem, vilao toma atitude
      negativa, que prejudicam pessoas > a partir do momento que vocÊ tem esse
      fandom, acreditando que elas sao justificadas. Pq há uma justificativa por
      trás, essas pessoas justificam a violência.
      - Isso se constroi a partir do momento que ela desenvolve a empatia, ela
        passa a procurar as motivacoes do vilao. Sempre procurando as motivacoes
        do vilao, tornando ele mais humano e se identificadn com ele, seu senso
        de vilencia é prejudicado.
      - POI(Brito) > O que vc ta falando sobre antiheroi, a gente ta falando de
        vilao que já ta sendo contraposto
        - Isso é pior pro cenario de vcs, a partir do momento que elas vem as
          circunstancias, elas confundem herois com antiherois(pq isso importa?)
          > pq elas vem o mal pelo mal, eles passam a nao confundir, identificar
          mais claramente a figura do vilao. E como ele é negativo.
        - Passam a nao pressionarem tanto assim esse combate, elas passam a
          acreditar  que a punicao e o combate nao é tao necessario, ve de certa
          forma o vilao de forma, que era obrigado afazer aquilo. Isso indica
          tanto a trama ficcional como a visao de mundo que essas pessoas possam
          ter. Passam a querer que o vilao tenha sucesso para com as suas
          atitudes. Nao tem a confusão que o vilao possa vencer, que deva
          vencer. Percebem que o mal é inerente a ele, e que pode ser vencido e
          deve ser vencido, melhora a trama ficcional e a sua visao de mundo.
* LO - Paulo
- O fato de eu ter mais empatia com detrminado vilao, vai fazer eu justificar os
  atos dele, matar continua sendo errado, nao vou achar que é bom só porque teve
  um contexto por traz. Ele continua sendo um ato reprovavel.
- Exite uma associacao das pessoas a um discurso que referenda que pessoas se
  erram é uma falha de carater intrinseca, e como esse discurso na sociedade
  dificulta que o proprio perdao seja uma atitude estimulada. O nosso cerebro
  funciona por cadeias de sinapses, gerados caminhos no nosso cerebro, nosso
  subconciencte, vai associar determinar situacoes, sem que pensemos
  racionalmente, esse caminho é formado por repeticao tentativa eerro, se eu sou
  massacrado desde a minha infança, se as pessoas sao inerentemente más toda vez
  que elas fazem um ato errado, algo que é incuravel.
- No cenari contrafactual que humnaiza os viloes que apaser de estarem errados,
  evidentemente negativos, mas nao sao inerentemente maos, e que sua historia
  poderia ter sido diferente se o contexto mudasse, dá um feedback, vc deve ser
  punido mas vc pode melhorar. Estimular o perdão as pessoas.
  - Num cenario de eu enquanto indiivduo possa errar e eu quero que pessoas
    devam me perdoar. Pq eu nao posso erar pela minha circunstancias.
  - Existem estruturas opressivas(machismo, racismo, homofobia) sao
    comportamentos que nao por mais nos reproduzimos e que sao ruins. Ex: Alguem
    que fala que na favela tem muito mais crime, vc evidentemente tá cometendo
    uma coisa errada, agora vc necessariamente racista, nos acreditamos que não.
    A partir que a cultura pop fala o tempo todo que os viloes que poderiam ter
    mudado se o contexto diferente. Essa é a narrativa que nós temos que
    defender. Sujeito que cometeu coisas erradas pode se tornar um cidadao muito
    melhor.
  - Filmes devem estimular por meio do subconciente por meio da cultura pop que
    os viloes tal qual pessoas nao sao inerentemente mals.
* DPM - Joao Vinicius
- Pq o publico tera um empatia com aquele vilao
  - 3 Personagens(vilao, o mocinho e o anti heroi)
  - As historias por si só, tratando do primeiro exemplo, o vilao tem um lado
    inerentemente obsurco, retrata aquilo que nos temos, nossos sentimentos
    reprimidos, o leitor, ele tem no vilao aquela perspectiva tem reprimido
    dentro de si. O mocinho tem a jornada do heroi. A gente tem no heroi os
    individuos, o que eles querem para si, quaisquer que sejam seus objetivos, o
    leitor se vê no mocinho.
  - O antiheroi é sim aquele vilao que é criado pela circunstancia, mas n é um
    antivilão. É aquele individuo pelas  circunstancias, que a priori nao era
    mal mas se tornou mal, nesse sentido, a gente tem que as pessoas nao devem
    incentivar, nao devem ter empatia com os viloes, eles mostram o lado obscuro
    dos individuos, que é inerentemente ao vilao. Ao passo que as pessoas devem
    ter empatia com os antiherois. Coringa e a Malevola(Coringa é um antiheroi????)
  - Nos temos a malevola que era uma pessoa boa que virou má. Adoreada pelo
    publico alvo.
  - Os viloes devem ser inerentemente mals, para traduzir as historias fielmente
    no que tá na realidade.
  - POI(bRITO) > diferenca para heroi e antiheroi > vilao é inerentemente mal, e
    o antiheroi é criado pelas circunstancias, vilao é o galactus.
  - Mesma circunstancia pode ser usada como inicio da jornada como heroi.
- Mostrar que o nosso onus nao deveriamos perdoar o vilao
* DLO - Victor
- nao faz melhor sentido(obvio)
- heroi é quem faz bem, e vilao é quem faz mal. antiheroi é quem faz mal para
  vilao mas nao tem os mesmos preceitos do heroi(top)
- ref
  - preferem trazer a narrativa que os vilaos sao intrinsecamente maus, vai
    justificar o mal > vc entender e concordar com uma atitude, sao coisas
    extremamente distintas e opostas > eles fez aquilo por algo disso disso e
    disso > concordar é achar bom
  - melhor narrativa
    - sobre o que leva um individuo a fazer determinado ato, a melhor famra de
      enfrentar o problema, n é falar que tal pessoa é intrinsecamente mal e nao
      tem volta. Vc compreender aquele processo. Saber quais atos vc deve tomar.
      Vcs consegue enfrentar o problema sabendo dos atos.
    - Concordamos que o vilao tem o mal dentro de si. Ele ta fazendo aquilo
      justamente pleo o que ele sofreu(Harlequina medica inteligente e virou má
      pq foi pro coringa, coringa teve um infança totalmente traumatica)
    - pessoas que nao sao más intrinsecamente, sofreram algum mal, alguma perda.
  - Dois cenarios
    - Dels, criaçao uma crença que a pessoa nasce má, e nao há chance de
      mudança, endossa o punitivismo. Paulo trouxe o mecanismo. Bandido bom é
      bandido morto, mal deve ser combatido com mais mal ainda. Pune pune pune e
      o mal nao diminui. Com essa mentalidade do governo vc endossa esse
      discurso e pensamento punitivista, pau que nasce torto nunca se indereita.
    - Endossa que pessoas que cometem erros, nao possuem chance de redenção,
      quem pagou pelos crimes, quando vai voltar pela sociedade, vai ver com
      mals olhos. Nao pq vc nasceu numa favela muito pobre, e essa pessoa nao
      vai ter nenhuma forma de resocializar. eles continuam mals
    - Cenario da op
      - Contexto, problemas, raizes daquele problema, o que acontece vc mitiga
        essa mentalidade punitivista, aqueles vilaos cometem aquele mal pq o que
        fazem, vc mitiga essa mentalidade punitivista, esse fenomeno e como ele
        se deu. Combater o mal pela raiz. Vc cria um senso de que o mal deve ser
        sim punido.
* MG - Daniel
- metrica > influencia dessa narrativa para o imaginario social(rly?)
- sobre como essa narrativa influencia os espectadores, os vilaos nao sao
  criados pleo meio ou circunstancias, casos de corrupção, sao as pessoas que já
  nasceram numa situacao de privilegio, já nascem com intuito de enriquecerem
  mais ainda. A narrativa contraria as pessoas com base no contexto, mas isso
  nao explica a resolucao dessas problematicas
- Sempre há uma escolha > escravização de pessoas negras > esse ato pode ser
  justificado de certa forma de mao de obra barata????????? > a gente pode
  relativizar as reais motivacoes das pessoas. Essas pessoas simplesmente
  queriam bem materiais. Como que esse fato não é se não o egoismo que está
  intrinseco a natureza humana.
- Numa relativizacao do comportamento humano > a gente nao tem a real
  problematizacao do que esta acontecendo. Nos percebemos de que de fato os
  maiores viloes > real viloes > abarca todos os problemas que sao inerentes aos
  problemas da sociedade > na esfera economica sao os ricos.
- os ricos usam quaisquer mecanismos para se favorecer > a partir do momento que
  a gente usa essa narrativa > como que os ricos de fato necessitavam e poderiam
  desumanizar porque as circunstancias favoreciam.
- quando a gente tem a narrativa que os vilaos sao inerentemente mals, pode de
  fato compreender, a porrada de tragedia na nossa sociedade > HQ mostram que os
  vilaos sao inerentemente mals > 1 Op nao me mostra como isso se mostra > real
  fonte das problematica
- POI(Paulo) > a partir do momento que é intrinseco nao vejo poder de mudança,
  nem todos os ricos sao mals > muitas vezes nao há mudança, como que no status
  quo, essa elite economica é má per si, luta de classe
- POI(bRITO) > se ele é mal pq ele é rico, a circunstancia nao continua sendo
  mal pelas circunstancias -> Onus que as HQs quando preferem esse tipo de
  narrativa criado pela circunstancias, podem de fato mudar(mas vc nao mostra
  como mudar) >
- com a narrativa que eles sao inerentemente mals eles conseguem ver a real
  realidade.
* MO - Luan
- utiliza uma metrica de qual dos casos a defesa ela vai ter um cenario mais
  fidedigno pra sociedade, um vilao intrinsecamente mal, vai ser mais verossimel
  com a sociedade. e segundo ponto, o deputado que me anteveio do capitalismo e tals
- existe tambem o vilao do colarinho branco, tbm existem os outros viloes, so a
  gente vai mostrar como isso ocorre como um todo
- pq que a arte vai ser melhor?
  - pq isso vai ser ainda melhor pra sociedade e tals
  - jornada do heroi inversa > joao vinicius introduziu jornada do heroi > é vc
    entender os percalços e tals > por completo e tals > a jornada do heroi
    inversa, é mostrar o que levou aquele vilao a ser assim, o que é muito mais
    fidedigno pq se asemleha com a vida real, existe mais de um lado da
    historia.
  - vai ser melhor pra arte
    - melhor construcao narrativa nesse storytelling, vai esmiuçar a aobra, a
      gente torna ela mais detalhista, a arte consegue explorar ainda mais
      lados. magneto vira vilao e tals. A propria obra como um todo, ganha um
      apego muito maior, aquela arte esta sendo mais fidedigna, maior atencao do
      publico, maior atencao, a gente tem dois lados se opondo. A riqueza de
      detalhes na historia da arte.
    - nos primordios do capitalismo > fazia sentido contar uma historia com um
      lado, somente mostrar que o vilao é ruim por si só nao é suficiente, arte
      ganha com isso.
  - pq vai ser melhlr pra sociedade
    - precisa entender essas pessoas, os erros do passados nao podem ser
      cometidos no futuro, a propria historia em si serve para que a gente veja
      os erros do passado e nao os cometa no futuro. mal intrinsecamente por ser
      mal, ela faz por invisibilizar, na verdade onde há um relativismo das
      coisas é na defesa, quando a gente tem uma narrativa da construcao da
      escravidao, aqui a gente mostra exatamente como aconteceu, no caso da
      defesa, a escravidao aconteceu e beleza, aqui a gente faz isso com todos
      os detalhes
    - quando a gente esmiuça, a gente dá a criaçao dos mecanismos para mitigar o
      mal como um todo. a gente explicita exatamente os mecanismos pelo qual
      ocorreu, a gente vê extamente porque, e nao ele é mal por si só, quando a
      gente mostra como aquilo aconteceu. É mais fácil de vc identificar, a
      defesa parte do pressuposto, esse vilao é por si só, nao vai ser fidedigno
      pra sociedade,
* WG - Douglas
- narrativa que viloes sao criados pelas circunstancias, vao tentar desculpar e
  cometer seus crimes, vamos analisar um cenario de um cidadao que vive em um
  ambiente insalubre > acordam cedo todo dia para manter mais um dia para manter
  sua dignidade e seus 10 filhos
- os ricos os poderosos os viloes da patria tem tudo em maos e mesmo assim
  matam todo mundo fodem tudo e tals
- as circunstancias o tornaram assim, o dinheiro assim, o capitalismo os
  tornaram assim? > dona maria que nao teve uma escola ou esses ricos que
  passaram por uma escola > seus atos por si só mostram sua falta de carater.
  aqueles que roubam, matam seja no cinema ou no real mundo em que vivemos.
  sabem o mal que cometem sabem que estao cometendo e fazem pq o querem.
  preferemos uma narrativa que o vilao é intrinseco e que mata por si só.
- POI(Paulo) > aiunda que a pessoa tenha uma falha de carater, nao significa que
  ela possa mudar, uma narrativa muito menos verossimel, vou começar a
  normalizar. -> ambos tiveram o conhecimento do que é o carater, se a gente
  analisar a questao, eles sabem que estao cometendo o mal, mas que eles já
  cresceram assim.
- Justamente apois chegar no poder tiram essa mascara.
- Entam assim, 1 op fala que levamos em consideracao o meio em que os vilaos
  estao inseridos. o meio no qual o individuo nasce nao transforma mal.
  - Naruto foi abandonado e continuo bem
  - Mandela, mesmo tendo toda exclusao toda aquele grito. permaneceu insistindo,
  - Se fosse um vilao seria vilao independentemente,
- 1g
  - perspectiva interna como se asssemelha a vida real,
  - nao vai as raizes do real problema que é o preconceito intrinseco com a
    elite que é o real rpoblema.
- POI(Brito)
* WO - Brito
- o objetivo é entender quais fatores que afetam a arte e a sociedade
- ate mesmo no caso marxista
- vilao é o antafgonista, trazer o exemplo do coringa, é fazer naturalmente a
  gente ta tratando de um vilao.
- o bem é o imperativo categorico eu faço pq eu acredito que é o certo
- o mal é o que foge daquela narrativa
- mecanismos de narrativa que nao mostram as circunstancias sao piores
- um vilao que tá seguindo a logica da oposicao
  - uma das frases mais conhecidas do valdemort, nao existe o bem e o mal, só
    tem poder
  - o vilao na cabeça dele n é um vilao, assim como no caso do marxista, eles
    nao sao os viloes das herois, mecanismos dentro da cabeça do vilao,
  - jornada do heroi matrix e hp
  - jornada do vilao
    - aquela que mostra as perdas, os cenarios que ele viveu, e o qq ta na
      cabeça dele em primeiro lugar. com a jornada do vilao, n demonstramos
      apenas pq ele deve ser perdoado, o cerne da questao
      - impactando dentro da sociedade, ao adentrar dentro dessa narrativa, nao
        repetir na propria sociedade
        - essa pessoa é corrupta mas qualquer um que chegar no poder faria a
          mesma coisa
          - O SISTEMA FAVORECE ISSO, pqp agr faz sentido
          - a gente nao teria a ideia, brasileiro ta elegendo corrupto, e nao
            vai mudar nunca. o qq a 2 op ta desenhando aqui pra mesa, vc
            enquanto cidadao precisa entender o sistema. Tem aquele governante,
            qual o background, quais sao os sistemas ao qual ele ta inserido,
            nossa proposta é muito mais profunda, vetor dentro de mudança dentro
            da sociedade.
          - se eu ver alguem roubando ou matando, o mal n é o do primeiro
            vingadores que sao aliens, o thanos que tem todo aquele background
            de perda, e portanto a gente pode evitar aquil odentro da sociedade.
- Poi 2g > se o rico ta sendo vilao pq ele é rico, ele ta sendo vilao por causa
  das condicoes de onde ele ta, pessoa que era pobre fica rico e começa a
  oprimir. a teoria do palco a gente é influenciado pelas pessoas que
  compartilham pelo mesmo palco. Propoe mudança para a sociedade, nenhuma
  circunstancia onde ela tá.
