* ECAQ comunidades que foram vitimas de atrocidades deveriam enfatizar a narrativa da "banalidade do mal" na hora de interpretar essas atrocidades
Infoslide: Banalidade do mal é a ideia de que as grandes atrocidades da história
não foram cometidas por pessoas que são inerentemente más, mas  por agentes que
engajam nesses comportamentos sem pararem para refletir na sua moralidade, na
maior parte das vezes por burocratas que só querem avançar suas carreiras, o mal
nesse caso é banalizado.
** PRIMEIRO MINISTRO
- As pessoas nao sao intrinsdicamente mas, adquirem certas condutas conforme o
  contexto Exemplos: Pessoas normatizam o fascismo, as pessoas passam por um
  processo de socialização Ex: Oriente médio
- As coisas más que existem no mundo, não foram cometidas pelas pessoas, mas no contexto
- A gente acredita nisso, porque quando a gente acredita nisso, no contexto mas
  nao nas pessoas, a gente foca em compreender o sistema, combate mais
  eficazmente a conduta e aquilo que foi feito, e não coloca na pessoa a responsabilidade
- Pq quando a gente coloca na pessoa a conduta, a gente faz com que existem
  sempre medidas paleativas para demonizar a pessoa e n necessraiamente o problema
- Porque as pessoas morrem mas as ideias ficam, a gente deixa de lado o sistema,
  passa a entender que o problema é nela e nao no contexto
- Descontrsução da propria ideia
- Narrativa do impossivel: Ideia de que as pessoas sao intrinsceamente mas, a
  gente nao consegue compreender, que pessoas do nosso lado estao sempre
  suscetiveis a coisas más, quando a gente tem uma sociedade que foi oprimida,
  se ela coloca o problema na pessoa n consegue entender o sistema, coloca um
  distanciamento da pessoa sobre o problema, o problema continua na sociedade e
  qualquer um pode adquirir aquele determinado tipo de pensamento.
- Isolamento da situação, isso nunca vai acontecer comigo ou com meu vizinho,
  culpar as pessoas é personaificar o problema, mas o problema esta mtu alem.
- Extende ainda mais a problematica, quando a gente começa a personaificar, e a
  gente nao entender que uma estrutura imperialista capitalista, e começa a
  culpar os portugueses e aristocratas, inimigos sao sempre os portugueses, e
  nao a estrutura, que fazem as pessoas fazerem isso
- Quando uma pessoa começa a tomar esse discurso, a sociedade tem uma
  necessidade de culpar as pessoas
- POI(Juan): Se o discurso é mais facil de ser entendido ele vai ser mais facil de ser entendido
- POI(Daniel): Prejudica uma analise fatica daquilo, esse é seu ponto? A gente não
  consegue entender a maximização
- A gente reduz o problema a essa pessoa, a gente reduzindo as pessoas, impede
  uam analise mais profunda do caso, consegue que seja um pouquinho mais
  eficiente, ao tentar destrir a estrutura.
** LIDER DE OPOSIÇÃO
- Existe engajamento em relação as pessoas, as pessoas se identificam com a
  religiao machista, casos de hitler, as pessoas engajavam, na propria alemanha
  existia uma identificacao entre os alemoes do que em relacao aos proprios
- Banalizacao do mal n é uma imposição, existem dentro das pessoas um viés para
  aquilo, nós temos o mal dentro de nós.
- Liberar os rancores, existem um consentimento entre a autoridade, hierarquia e
  as pessoas que estao sendo subjulgadas.
- A narrativa n é simplesmente imposta, as pessoas n compram do nada, esta em
  grande parte dentro delas.
- Pessoas inclinadas para o mal, questao individual, elas procuram os lideres
  messianicos, n é só uma questao de impor uma hierarquia, existem N fatores que
  geram a esse lugar, a população comprar é o principal dele.
- POI: A 50 anos atrás quando o Brasil era muito mais machista, as pessoas sao
  habituadas a viver com o problema -> Não é que todas as pessoas fossem
  machistas, a compra dessa ideia pela população.
- Existe uma barganha pelo o que é oferecido nessa sociedade, e pelo o que a
  pessoa
- Essas narrativas de banalidade do mal, em ultima instancia quem comete
  atrocidade no campo de batalha sao pessoas, trazer para pessoa aquele peso. A
  decisao final é dela. Ela simplesmente nao se concretiza. Existe uma compra
  das pessoas, o individual é crucial, é mais crucial que a propria estrutura.
- Ela entende que matar uma pessoa é errado.
** ADJUNTO DE PRIMEIRO MINISTRO
- Você reproduz um comportamento machista porque as pessoas só tocam as proprias
  vidas sem refletir pela moralidade daquilo.
- A Narrativa que as atrocidades pessoas horriveis, mtu improvavel que aquilo
  aconteca de novo, ninguem se considera mal, mas na verdade tem risco delas
  cairem dentro dessa narrativa
- Um lider fascismo europeu pode ocorrer
- Muito mais importante do que julgar os outros, é valorar como bons ou ruins
  culturas, e nao tanto pessoas, sao as culturas que geram esses problemas, o
  que aconteceu é completamente inaceitaval. O problema foi as pessoas não
  aceitarem os pontos
- Nao refletem sobre a propria moral
- As noções de moralidade sao moldadas pelo contexto social
- Para ver se um discurso de odio aparecer, cortado pela raiz
- Pensamentos que geram atrocidades sao graduais, começam pequenos e vao sendo
  aceitveis, e a janela do que ta acontecendo vai se deslocando. As pessoas se
  baseiam no que os outros.
- A gente terceiriza para comunidade a nossa visao de moralidade
- Lá no começo quando uma coisa era ruim mas n parecia mtu ruim, n foi cortada
  pela raiz
- POI:Estevao -> Mas o grupo que foi atingido, porque isso é relevante para ele
- As pessoas dessas comunidades mais que ninguem repudiam essas atrocidades,
  relacionam essas atrocidades com o que mais horrivel com o ser humano, se voce
  convence essas pessoas que elas mesmas poderiam ter engajado num regime
  genocida
- Se vc convence essas pessoas muito boas, ela vai ter um nó na cabeça, vai
  apssar a ser muito mais vigilante em relação aquilo
- Se as pessoas ao seu redor nao forem vigilantes, essas pessoas mais sensitivas
  vao ser mais suscetiveis.
- Ela vai rejeitar essas narrativas.
- Atitude de não refletir sobre a propria moral, nao repetindo narrativas. Muito
  importante que essas pessoas saibam disso. Blindando essa comunidade de uma
** ADJUNTO DE LIDER DE OPOSIÇÃO
- Quebra do simbolo, independente da maldade ou bondade ser inerente
- A gente tem que criar uma imagem maligna, para que a sociedade crie uma
  repulsa sobre aquela conduta.
- Ela nao tem a percepção de como a macroestrutura ta se moldando, o discurso se
  insere aos poucos, dentro da sociedade, justamente pela gradatividade, quem
  esta inserido dentro da sociedade tenha capacidae de perceber.
- Se eu estou inserido dentro da sociedade eu tenho dificuldade de percepcao,
  com a demonizaçao de um simbolo
- EU faço isso evitanto a banalização do mal
- Eu abrando isso
- Se eu parto do pressuposto que aquele que fez uma atrociade histórica, aquele
  individuo(Hitler) é negativo, mal per si. Eu crio uma facilidade para as
  pessoas identifiquem aquele simbolo, e ver que aquele simbolo fosse reprimido
- É por isso que é muito mais facil que eu me mova contra o hitler do que contra
  quem gerou o nazismo
- COnsido atingir mais pessoas, entender melhor
- Mesmo nao atingindo a macroestrutura naquele macromomento
- Diferente se eu só atacar a macroestrutura, nao vai abranger as pessoas.
- POI: IRIS -> Demonização do simbolo por coisas que não sao pessoas, o problema
  se atacar um simbolo mas não atacar uma pessoa -> Esse simbolo é muito mais
  palpavel para entender que aquilo seja repudiado
- Eu crio melhor uma compreensão de quem praticou a sociedade
- Se os grupos que sofreram a marginizacao, criam uma narrativa que aqueles
  individuos nao sao tao mals assim, eu diminuo o impacto na sociedade que
  praticou a sociedade, eles tem consciencia dos impactos negativos, mas nao
  tanto aqueles que tem lugar de fala.
- Se o grpo não demoniza a situação -> Algo nào tao ruim quanto deveria
- Se eu crio uma narrativa que os agentes do conduta eram meres trabalhadores
  agindo em ordens -> Eu enfraqueco a divida historica daquele povo.
- Eu tenoh que respeitar aquele povo em ultima instancia.
** MEMBRO DO GOVERNO
- Case 1 gof -> Blindar sociedade, ver que aquilo n aconteca de novo
- O que é esse debate? -> O que é melhor apra essas comunidades, essas
  sociedades se preocupam com duas coisas -> Pacificação do ambiente, e evitar
  que existam novos grupos.
- Essa moção nao é sobre provar o que é o certo
- Narrativas comunitarias -> As pessoas que vao viver aquela narrativa, vao
  tomar como verdadeira, vao reagir sua vida cotidiana, exemplo o ensino da
  história como é diferente em outros lugares.
- A narrativa criada dentro da comunidade
- 1 OP -> A narrativa da banalização, ainda que n seja mal, pode cometer atrocidades
- 1 OP -> Em ambos os cenarios, vai identificar que a atrocidade aconteceu
- 1 OP -> Divida historica é sobre reparação, a narrativa n viria impedir a
  narrativa histórica.
- Criar uma sociedade determinada a refletir com cautela a interação entre os
  grupos, voce meramente cria a narrativa do nós contra eles. Esforço reflexivo
  das causas(1 DEF)
- Pessoas agiam pelas proprias razoes -> Pessoas vao entender, entender que o
  ser humano é capaz de entrar por cima do outro pelas proprias razoes
- Busca desenfreada das proprias razoes, e n ignorar os meios que vao levar
  aqueles fins
- a GENTGE vai construindo na identidade daquele povo uma preoucupacã́o social,
  individuos mais empaticos, n basta ser mal para cumprir uma atrocidade
- Basta fazer algo acaba ferindo os outros
- Sociedade mais empatica
- POI:Estevao -> Grupos que sofreram esse tipo de catastrofe, marginalizados e
  burros -> Se um grpo n tem capacidade de entender uma narrativa comunitaria,
  ele n vai entender nenhuma das duas.
- Compreender de que forma o agressor
- Mais importrante que perceber que o individuo ta sendo influenciado, os
  individuos nao vao ser influenciados, as pessoas n vao ficar suscetiveis para
  coisas quele discurso
- Quando a gente abandona o cenario do governo, nada pode ser feito, a partir do
  momento aquilo simplesmente, jsutificado pelas violencias. Sociedade
  extremamente violenta.
** MEMBRO DA OPOSIÇÃO
- Fun;çao social do mal -> Vc conseguir no imaginario popular algo que é
  naturalmente reprovavel
  - Algo pequeno e dizer que ele é mal fosse algo grande, n é qualqeur fato
    historico, sao atrocidades, genocidios, preconceitos, assassinatos em massa,
    quando vc liga essa atrocidade e liga a uma coisa de mal, todas as coisas
    que possam gerar o mal, capacidade de gerar o mal
  - Ideia do mal é uam criacao da sociedade, dentro do imaginario popular uma
    atitude extremamente reprovavel, voce pede que sejam criadas excusas, no
    final aquilo é um mal e deve ser afastado.
  - No ponto do governo, uma visao analitica uma matou mais que a outra, isso é
    afastado com o conceito do mal.
- POI Iris -> Essa demonizaçao precisa necessariamente a uma pessoa -> Erro da
  defesa, a uma pessoa -> A partir do momento em que fica ligado aquela pessoa,
  fica ligado a figura, n é o hitler, é o que ele fez, é o que ele representava.
- Vc reforça na mente dos executores a necessidae de reparação, vao entender que
  aquilo foi ruim independente da analise
- HOje alemanha teve uma visao analitica, mas isso n jsutifica os atos que
  aconteceram, acima de tudo aquilo foi um grande mal.
- Novas medidads para os mesmos fins.
- Fazer a sociedade buscar o bem com outros meios Exemplo: Testes com animais
- DItadura meio para disciplinar os 3 poderes e as instituicoes, por isso foi
  justificavel -> Depois que ela foi banalizada -> Sociedade encntrou meios
  alternativos chegar nos mesmos fins. Pq entendeu que aquilo era o mal
- POI: Danilo -> N ta dizendo que a atrocidade foi ruim, se foi inerentemente
  mal. -> A premissa dos pontos do governo -> Se vc determina o mal, vc impedfe
  uma analise analitica do mal
- Entender que aquilo foi um mal, entender aquilo mais.
- Mal algo banal, o bom se torna a excecao, o dificil, no imaginario popular, é
  mtu comum fazer o mal, do que fazer o bem. O que vai ser pensado, talvez n
  seja tao ruim n seja tao reprovavel
** WHIP DO GOVERNO
- Banalidade do mal é uma ideia das grandes atrocidades, em grande parte, os
  agentes sao importantes para entender. Pessoas botaram as vontades individuais
  acima do mal
- Funcáo social do mal, reduzindo os acontecimentos a uma figura má -> O mal tem
  raizes, mas ele tem catalizadores -> A gente n consegue de fato entendfer as
  raizes por traz disso(1 def)
- Atos individuais daquela pessoa foram colocadas a frente
- Caso da primeira oposição -> Ele n se decide se o mal é intrinseco ou
- Facilidade de identificar os simbolos, se a gente atribui uma pessoas, lideres
  messianicos, o impacto da narrativa é menor
- N estamos falando apenas, essas narrativas vao ser passadas.
- POI: ITALO -> Se eu crio um simbolo é mais facil de identificar mais facil de
  combater -> Mtu mais facil seguir aquela pessoa, seguir hitler, ideia
  personaificada.
- POI: Estevao -> O contrario do mal banal é a personificacao do mal -> Vcs que
  fazem isso
- Narrativas comunitarias, evite que as historias tendem a se repetir
- Sociedade determinada a refletir com cautela, efeito reflexivo, esses atos nos
  ensinam o que precisamos frear, nossos desejos individuais, frente a questao coletiva.
- Combate vai ocorrer de forma natural, n violencia unica forma.
- Individuos que entendem que o mal deve ser personalizado ->
** WHIP DA OPOSIÇÃO
- O que aquele povo que sofreu tudo aquilo deve -> Prevenir isso de acontecer de
  novo -> Pequenos pensamentos intolerantes, pode ser dentro dos gpos que
  oprimiram -> Pensamento intolerante sobre os nazismo um judeu
- O mal é mais instintivo, masi facil de absorver, absorvem um conceito basico
  que aquilo é ruim
- Personificaçao -> N foi o que o Daniel, a gente ta falando que totalitarismo é
  ruim, vc n ta fazendo necesariamente cvom uma pessoa, pessoas morrem mais
  ideias ficam
- Falar que uma ideia é ruim, ideia é má, ao ter como ponto unico.
- Prevenir que o grande mau venha contra mim
- N pode deixar a desejar, qeu aquele tipo de acontecimento aconteca
- aO acontecer empatia com o intolerante, possibilidade de n lembrar do que
  aquilo que aconteceu com ele
- Personificacao é ruim -> N é uma figura é uma ideia, o mal é o comunismo.
- Mal que gerou determinadas atrocidades, grupo judeu, grupo judeu vasi ser
  suicida, que propage coisas contra o proprio social
- O que é melhor para esse grupos marginalizados, ver como foram, um mal unico,
  grandioso, n pode abrir espaço que ele foi algo ruim.
- Medidas que vai tomar para evitar aquilo, é mtu risco
- POI: Antes dessas desgraças que o grupo seja visto como um só -> Ele n é igual
  ao povo que o machucou -> Povo morto com as camaras de gaz -> Mais facil de
  perpetuar dentro das proprias gerações
- N fazer que aquilo se perca, o que tem mais impacto é a figura do mal
- N esqueça o que aconteceu com ela.
