* Mocão -> Esta Casa lamenta a predominância da narrativa do bem vencer sobre o mal na literatura infantil
** Qual a função da infância?
Senhora presidenta, a infäncia tem uma função muito específica no
desenvolvimento de uma criança, nós acreditamos que a infância serve para
preparar a criança para a vida adulta. Simulando situações que ela vai enfrentar
em um ambiente mais saudável e menos perigoso.
1. Atividades do dia a dia na maioria das brincadeiras como a de boneca
2. Experimentar questões de trabalho em equipe e organização em tarefas em
   grande parte dos esportes
3. E uma versão da moralidade encarnada na sociedade só que mais digerida
** Qual a função das histórias infantis?
Ensinar as crianças sobre as situações da vida, nós acreditamos que essas
histórias tem uma função primordial de oferecer uma maneira fácil de digerir
sobre os problemas que ela vai encontrar.
Nós acreditamos que essa criança precisa já estar preparada para a adolescência,
onde ela vai enfrentar todo tipo de injustiça, de falta de moralidade, e de
coisas ruins.
Nós não acreditamos ser o nosso fardo dentro desse debate defender histórias em
que o vilão mate o heroi a sangue frio. Mas situações mais fáceis de digerir
como a cigarra preguiçosa da história acabar não precisando pedir ajuda da
formiga.
Ou a lebre acabar ganhando a corrida contra a tartaruga.
** Por que isso é importante?
Porque nós temos dois benefícios, a longo prazo nós temos uma exposição mais
gradual desses tipos de acontecimentos para a criança, principalmente levando em
conta a situação atual onde a maioria dos pais acaba por isolar a criança do
mundo principalmente devido a medo da violência e outras coisas ruins.
Uma criança que antigamente já tinha convivio com o mal, seja no mínimo lidando
com os bebados do bar da esquina hoje em dia já não tem mais isso porque ela
passa boa parte do dia em casa seja com o tablet com o videogame.
O segundo ponto é fazer com que a própria criança consiga agir melhor nas
situaçoes de injustiça que ela lidar. Nessas histórias na maior parte das vezes,
o mal perde por acaso do destino.
1. A cigarra se prejudicando por causa de uma nevasca
2. O lobo perdendo porque do nada aparece o caçador
3. A branca de neve precisando de um principe que aparece do nada pra salvar ela
O resultado portanto são histórias em que para que o mal sempre perca, o autor
acaba necessitando usar do acaso ou do destino para fazer isso acontecer.
Obviamente que isso náo é a regra, mas acaba acontecendo devido a essa exigencia. A
consequência portanto é que os herois não tem agência nessa derrota, isso cria
um certo censo de apatia, semelhante a quando os pais ensinam as crianças a não
revidarem do bullying, e invés disso simplesmente chamarem os professores que na
maioria dos casos não ajudam na situação.
** Conclusão
Uma predominancia de histórias com finais tristes portanto traz dois benefícios,
um a longo prazo e outro a curto prazo, no curto prazo a criança se torna mais
capaz de lidar com os pequenos problemas que ela lá enfrenta no dia a dia.
A longo prazo ela fica melhor equipada a lidar com as frustrações que ocorrem
principalmente na adolescência, e uma adolescência mais saudável
consequentemente tem extrema importância em uma vida adulta melhor
Por último nós não acreditamos que existam outras alternativas para a criança
ser exposta de forma pequena e saudável a esses problemas, principalmente porque
na vida real os pais e educadores já tendem a tentar proteger essas crianças ao
máximo, tornando portanto improvável que ela tenha acesso a esse tipo de
ensinamento, se não em ambientes as quais os pais não controlam.
