#+TITLE: DebatreOnline17_02_2020

* Doutrinação não dá problema
1. Mais uma vez o JL não entende
2. Essas crianças estão em locais isolados, no interior
3. Só o fato dessa criança ter sido ensinada que a teoria do criacionismo invés
   da evolução
4. Como o dano causa? -> Exemplo -> O cara que não atingiu seu principal
   potencial dentro da Escola, descobre com 30 anos que isso aconteceu em grande
   parte pq ele continua na igreja, esse cara tomou consciência que os danos
   aconteceram -> Ele perdeu 10 anos de oportunidades da vida dele, por causa da
   religião -> Pronto mostrei um exemplo.

* Educação religiosa é importante pra criação
1. O JL não entende que a moção tá tratando de um caso em que a criança não tem
   acesso a nenhum outro tipo de educação
2. Ninguém tá falando pra gente falar pra criança que Deus está morto e que nós
   o matamos, ou que se Deus tiver vivo ele vai precisar se ajoelhar em perdão
3. Mesmo se a gente for doutrinar a criança enquanto ela tá com 4 anos, falando
   que Jesus salvou todo mundo
4. Ainda assim

* Pq esses pais tem dever?
1. Nós consideramos que é um direito de todo ser humano ter dada a possibilidade
   de atingir ao seu máximo potencial
2. Nós acreditamos que o principal maneira de conseguir isso é ter acesso ao
   número máximo de experiencias, principalmente no quesito educação
3. Nós acreditamos que os pais enquanto aqueles que colocaram essas crianças no
   mundo, tem em conjunto com o Estado uma obrigação de auxiliar na manutenção
   desse potencial
4. Nós acreditamos que doutrinar significa justamente retirar a possibilidade
   dessa criança atingir o seu máximo potencial
5. Diferentemente de um pai normal, o pai nesse caso tem condições financeiras
   de oferecer mais do que ele dá, ele justamente não tem

* Danos financeiros a essa criança
1. Danos economicos com base na educação dela
2. Atividades extra-curriculares -> Teatro pode ser coisa de viado, ciências
   podem ser consideradas coisas do demônio
3. Os cursos que essa criança vai escolher -> Por exemplo um ensino técnico
4. Tudo isso são danos econômicos, que quando você vai colocar na balança eles
   tem uma capacidade destrutiva semelhante a danos advindos de abusos ou de
   mals tratos

* Danos morais
1. Exemplos: Crianças trans que são criadas dentro do ambiente religioso
2. Crianças homosexuais
3. Crianças deficientes que consideram isso como um castigo de Deus
4. Tudo isso efetivamente não pode ser retirado de algo semelhante a abusos
   psicológicos que efetivamente iriam querer dizer em algo semelhante a um
   conselho tutelar

* Possível efeito backlash
1. País que se consideram religiosos -> Contra a medida, iriam ver como
   perseguição religiosa
2. Na maioria das democracias ocidentais liberais -> Que tem um judiciario
   minimamente funcional, para esse tipo de medida -> As pessoas que seriam
   efetivamente afetadas são o minimo do minimo
3. Por que? -> Pq assumindo que os pais querem o melhor para os filhos -> No
   mundo digital e moderno atual -> Esse tipo de doutrinação principalmente que
   advem de pontos de vistas alternativos, ele n é visto como algo desejavel
   
* Dissuador contra o estilo de vida religioso
1. Nós consideramos isso bom
2. Religião é uma merda, só presta pra ter filme do Fernando Meirelles
3. Principalmente esse tipo de coisa -> Pensamento acrítico
4. Isso significa que nào há nem mesmo uma reasignificação dos ensinamentos
   religiosos para se adaptar a vida real
5. Exemplo: Assumir que Deus não criou o mundo em 6 dias, mas na verdade os dias
   pra Deus são diferentes
6. Ou relativizar certas passagens do antigo testamento que falam de cidades
   inteiras sendo transformadas em sal
7. Por que? -> Pq esse tipo de relativização advem justamente de quando você tem
   pensamento critico o suficiente pra achar que aquilo tá errado, mas não o
   suficiente para achar que o sistema todo está errado
8. Ou seja, no caso da crianção de pessoas extremamente religiosas ->

* Pq é diferente do conselho tutelar?
1. Pq nós consideramos que a retirada dessa criança do lar e colocada dentro do
   sistema configuraria em um trauma maior do que o que a gente tá tentando solucionar
2. O que eu quero dizer com isso? -> A alternativa é justamente colocar essa
   criança dentro de um sistema que só vai fazer a criança sofrer
3. O perpetuador do crime na verdae se dá bem, pq ele consegue no pior dos casos
   ter mais dinheiro extra no banco, pq não tá criando uma criança
4. Enquanto que no nosso mundo, você efetivamente cria um desincentivo a uma
   série de abusos -> No mundo atual, os abusos não podem ser combatidos, pq na
   maioria dos casos, a pena só acontece para a vítima
5.
