* Moção: ECAQ democracias segulares com religiosas substanciais devem criar tribunais especiais onde os litigios possam ser resolvidos com base na lei religiosas
** Melhor caso possível-> A pessoa está lá por vontade própria
Tribunais, imigração

** Assumir o melhor caso possível
1. Esses tribunais são efetivos
2. As pessoas que estão neles estão lá por livre e espontanea vontade
3. Todos concordam com os litígios
*** Aonde estes tribunais vao ser aplicados
Democracias seculares
De onde vem as comunidades religiosas desses paises? -> Imigração, os nativos
são sao seculares, ateus, etc
Esse estado estaria cedendo sua soberania, o poder de jurisdição -> Capacidade
de julgar os litigios
A gente está assumindo que esses tribunais teriam maiores poderes do que os
atuais tribunais de arbitragem -> Afinal não faria sentido que eles fossem
criados se ja existem arbitros
A retórica do ódio, vem principalmente quando é visto que os imigrantes não
estão se tornando nativos -> Exemplos: Trump reclamando do fato dos imigrantes
não terem capacidade de falar ingles, LaPen reclamando do grande influxo de
minorias muçulmanas que não apreciam a cultura francesa. Não é surpreso portanto
que esteja havendo uma renascenca de valorização da cultura tradicional(Musica
classica, história local(Exemplo o uso de iconografia das cruzadas por
movimentos de extrema direita como Deuls Vult e o termo sarracenos))
Tudo isso é uma resposta ao entendimento de que a cultura desses paises está
sendo de alguma forma suplantada pela dos imigrantes.
A partir do momento em que o Estado cede o poder da racionalização do uso da
força, que é a jurisdição, capacidade de julgar, você tá basicamente dizendo pra
todo mundo que essa religião está acima da lei.(Mesmo isso não necessariamente
sendo verdade)
**** Por que isso é importante?
Porque nós estamos falando da grande maioria das pessoas religiosas desses
paises estão nessa situação, afinal, os nativos ou são ateus, ou são não
praticantes, ou seja, jamais buscariam esses lugares em primeiro lugar.
*** Nós queremos tirar o poder desses lideres religiosos
Nós da 1 oposição acreditamos que no geral as instituições religiosas fazem mais
mal do que bem(Lideres islamicos que apoiam questoes de terrorismo, lideres
evangelicos apoiando fundamentalismo relioso, contra aborto etc) -> Nós
acreditamos que as variações que nào tem esses problemas são justamente as
variações que não iriam em primeiro lugar pedir acesso a esse tipo de tribunais.
A questão é, a maior parte das novas gerações dessas culturas estão saindo desse
tipo de fundamentalismo, mas isso se deve em principal ponto pelo
enfraquecimento da religião frente aos outros poderes da sociedade(Seja o
proprio Estado, seja o capital, seja outras forças culturais)
A partir do momento em que você adiciona esse poder a esse grupo, você aumenta o
poder desses grupos religiosos fundamentalistas, e percebam que isso afeta
também as pessoas que não escolheriam esses tribunais em primeiro lugar, visto
que, o maior poder desses grupos frente a sociedade extrapola para outras
façetas da vida social. Seja as pessoas que fazem parte da comunidade mas não
querem se submeter aquela ótica religiosa, seja as novas gerações que agora vão
ter que viver em um mundo onde essas instiuições são agora muito mais fortes,
diminuindo portanto a sua possibildade de ver com outros olhos a situação.
*** Refutações
1. Ele fala como isso é bom por permitir que litigios que não são abrangidos
   pelo judiciario possam ser apreciados -> Mas a moção não está tratando desses
   casos em que o judiciário não aprecia  o litigio, porque eles já acontecem.
   A moção diz respeito aos casos em que existem uma concorrencia de
   competencias, e no caso faria com que o poder judiciario se afastasse do
   litigio, não sendo permitido de julgar aquilo.
2. A gente pode desafogar o judiciario -> Irrelevante, a moção não diz respeito
   apenas ao Brasil, nós precisamos ter uma perspectiva global.
