* ECAQ empresas globais de tecnologia (Apple, Google, Netflix, etc) deveriam recusar exigências dos governos nacionais de censura ou edição de seus aplicativos/conteúdo.
** Primeiro Ministro
Quem é que faz essas demandas? -> Paises em conflito, ou que tem governo
autoritário.
Por que fazem essas demandas? ->
**** Usar a importância global dessas empresas
Tem que mostrar autonomia das empresas, que tem peso muito maior do que os
governos, Porque atingem todo mundo dentro do globo. Se a gente aceita a demanda
específica, estamos dando um pé atras na nossa própria autonomia. Só pra atingir
um público mais específoco.
**** Mostrar submissão, e usar como doutrinação da população
Primeira coisa é se mostrar como submisso ao governo. Só significa que o governo
tem mais força do que ele realmente tem. Isso já tira autonomia e liberdade
dessa empresa. Perde capacidade de criticar o governo. Impedindo que as críticas
chegam a população.
Forçando empresa a assumir um partido, um viés político, que já é extremo, só
pra atingir mais um público.
**** POI
Não é só sobre governos autoritários, França, Brasil, EUA. -> São políticas de países que querem passar algum tipo de mensagem diplomática.
Caso não se submeta, a gente tá mostrando um outro lado para a população, o que
é bom pra ela engajar, ou apoiar, uma noção maior, mais comparativo para
analisar o próprio governo.
*** Cenário possíveis
1. Valor global, no pior cenário não vasi ser tão ruim para seu bolso, porque
   ela não vai criar rixa com outros governos
2. O conteúdo já foi consumido, se precisou ser deletado, a pessoa vai ter
   incentivo para engajar, maior ativismo político.
3. Melhor destrinchado pela dupla
** Lider de Oposição
*** Como essas plataformas funcionam?
Direcionamento de conteudo especifo, procurar comina na Russia é diferente do
Brasil, elas já fazem isso hoje em dia, adaptar o algoritmo, essas empresas já
agem dessa forma.
Essas empresas já são parceiras do governo, vide elas retirando ofensas, Mark
Zuckberg indo ao congresso, essas mepreas entendem que é melhor ceder do que não
ceder, no pior cenário elas vão impedir que as empresas ajam. Muito simples pro
governo usar um grande firewall pra impedir.
*** Lucro
As empresas não devem recusar porque tem risco para seu valor de mercado, e
novos mercados
*** Efeitos econômicos
Boicote que isso pode acontecer, população normalmente concorda com o governo,
discordam das políticas de privacidade do Facebook, povo Russo concordando com o
Putin, usando de forma maniqueista de formas privilegiadas.
Bloqueios de mercado, o que mais importa para empressas de tecnologia são
usuários, usuário é o grande valor, através dele que elas conseguem tanto
dinheiro, ela vai ter menos usuários. Isso pode afetar o valor de mercado dessas
empresas. O valor de mercado automaticamente tende a cair. Elas necessitam ser
globais. O que vai acontecer é um boicote governamentas.
**** POI ->
Os usuários podem cruzar informação para perceber que a empresa é duas caras,
Taiwan é parte da China ou não.
*** Questão de imagem
Se nào retirarem do governo, a imagem das empresas vai estar como americanizada
ou europeia, a representação cultural já não acontecem. Os paises ditatoriais já
não tem poder de produção. Se essas empresas não cederem pra uns governos e não
para outros.
** Adjunto de Primeiro Ministro
1. Concessão já ocorre -> Não é uma negociação, é uma exigência de retirada de
   conteúdo. Nós reconhecemos que a adaptação já ocorre, é diferente de
   pesquisar arroz e feijã́o, não apareceria o arroz e feijão. -> Em primeira
   instância retira toda a capacidade crítica da população. Censura clara, afeta
   diretramente a capacidade crítica do indivíduo.
   POI: Crítica não existe porque já é uma visão americanizada, e não global ->
   Não cabe a crítica, se a empresa tem uma essência americanizada, faz parte
   que o Estado que queira receber esse produto. Abrir mão da autonomia e
   liberdade é algo muito importante.
Crimeia e Russia -> Automaticamente tá tomando o partido da Ucrania, abrindo mão
de um mercado consumidor, tá mostrando pra Russia que ela tem um poder de
decisão dentro do próprio aplicativo. Abre um precedente, cascata de exigências.
Não necessariamente isso é favorável. Exemplo: Netflix deixa do que ela quer
fazer, e o passa a ser o que o governo quer, descaracteriza a essência, apenas
um pau mandado. Por outro lado um produto integro, é muito mais fácil vender um
produto padronizado do que conceder essas exigencias, e ter que personificar
cada um dos seus produtos para cada país.
** Adjunto de Lider de Oposição
Uma empresa que tem interesses econômicos, que não importa se a população for
alienada ou burra.
1. Ponto do rafael -> O ato político de recusar um governo é mais evidente do
   que ficar se escondendo.
Nosso caso não é defender X, mas não se opor a Y.
2. Criar cadeira de cooperativismo e fuder a autonomia -> Só porque o governo
   fez uma vez, não significa que ele faz é maior. Nos casos em que o dano for
   mínimo você não deve recusar.
3. Doutrinação não é importa para empresa, vender pra fanático é muito bom.
*** Recusar é um ato simbólico
A gente tá lidando com governos que não lidam com a melhor maneira com as
coisas, tendem ao autoritarismo, governos por si só, vão verificar aquilo como
ato político, diferentemten da população, é diferente do governo que está
diretamente afetado, vai ter um interesse muito maior. Se importar muito mais
com a recusa. Afetado diretamente por esses conflitos. As pessoas são afetadas o
tempo todo.
Estado vai querer controlar a narrativa, pra controlar a população, extremamente
importante manter a narrativa. Mero risco da Porta dos Fundos(Risco para
empresas) -> Pessoas vão fazer boicote a essas empresas(GLobo recebendo boicote
por causa do Governo Bolsonaro) -> Empresas tem grandes concorrentes.
POI: Crimeia e outros aliados da Crimeia não vão se opor(Ponto do Daniel) -> Na
Crimeia vai estar como se não fosse da Russia.
Exemplos: Huawei, levando ataques do Trump.
** Membro do Governo
*** Finalidade das empresas
*** Só importa com as empresas como stakeholder do debate
Ricas PARA CARALHO, stakeholder decisivo desse debate é o usuário final, em
particular o desses países.
1. Empresas globais(Samsung, Xiaomi, Huawei, Piratebay, Weechat) -> Mesmo essas
   empresas tem capital aberto, via de regra não tem dono, maior acionista da
   Apple é o fundo soberano da Noruega, Ongs e caralho a quatro. Essas empresas
   são marcadas foco no cliente.
Chefe da empresas é o consumidor, consumidores que produzem, as páginas que a
gente vê e tals. Usuários são os protagonistas dessas empresas. Essas empresas
estão mais bem preparadas por colocarem usuário no centro. Essas empresas tem o
dever moral de proteger os usuários, se elas não atenderem os usuários elas tem
o dever. Elas devem a existência aos usuários, monopólio é frágil, numa
competição de WC3 um usuário falou Free Tibet, backlash gigante. Consumo verde,
buy local e o caralho. COnsumidor cada vez mais consciente. Não ceder a governos
autoritários. Usuários precisam ter a possibilidade de receber conteudo
diferente do governo.
Usuário pode ir a contrário, critiar o youtube, pode ir pro concorrente, usuário
pode reagir, em relação aos governos, usuários podem usar criptografia, dark
web, criptomoedas, usuário tem poder de resistência, não é forte sozinho, essas
empresas tem vínculos importantes, colocando o usuário no centro. Esses países
são mais dependentes do que os governos são dependentes, que precisa ser usado
pelo bem do usuário, que são quem fizeram as empresa cresceram no primerio
lugar. Ter contato com tudo.
** Membro da Oposição
Por que devem abaixar a cabeça? -> Para o motivo de não serem acusadas de
hipócritas, para quando paises democráticos exigam coisas boas para
democracia(Censurar fake news, apagar gatilhos, posts terrorismo, legislação de
direito ao esquecimento)
Quando a gente dá margem para empresas poder escolher qual ação ela vai
rejeitar, a gente dá margem para crítica de hipocrisia, que diminui
probabilidade dela passar, que gera maior dano a essas empresas.
POI: O conteudo é consumido, corrigido pelos proprios usuarios, Pq o usuario é
mais confiavel que o usuario? ->
1. Se a gente for numa lógica principiologica, qual de fato vai ser o impacto
   efetivo da empresa tomar essa medida, de violar uma superpotencia, Russia e
   China. Esses paises já fazem ampla violaçào de liberdade de expressão. Vários
   paises autoritarios fazem perseguiçao, você não vai melhorar a situação
   daquela população, não vai mudar a situação deles. Mesmo no melhor cenário em
   que a gente consiga fazer com que a população engaje, tenha uma ampla
   engajamento, exemplo Primavera Arabe, não conseguiu uma democracia efetiva.
2. Mesmo que gere uma revolta, essa revolta vai ser mitigada, se a gente não
   encapar uma ideia de hipocrisia
3. A empresa quando nào toma partido, pode lavar as mãos, e se isenta de crítica
4. Mesmo se ela perder alguns clientes, o que ela ganha de apoio de alguns
   usuarios ela perde de vários outros.
*** Mecanismo
Bancadas de extrema direita em democracias consolidadas, tende a apoiar esses
regimes, e que são mais contra essas regulações de combate a fake news, e
discurso de ódio, tem uma ação deliberada, perde muito apoio da população,
passam a acusar essas empresas de hipocrisia, só em benefício próprio, menos
legitimidade.
Fake News pode mudar rumo de eleições, espalhar mentiras anticietificista, gera
incentivo para discurso de ódio, maior ameaça a minorias, gera uma narrativa que
não permite que essas empresas sejam reguladas pelo Estado.
** Whip do Governo
Nos vivemos num cenario cruzamento de dados, fuder hong kong, esse não é um
debate sobre minucias e algoritmos de facebook, censurar criticas ou verdades,
principal stakeholder é os usuariosm, valor social das empresas. Vamo dizer se o
Facebook abre os dados? -> Vamo levar em conta a NSA, se as empresas achassem
moral e valido para elas darem os dados, infrigirem os acordos com os usuários.
Netflix e o Hassan -> Hassan fez um episódio sober a Arabia Saudita matando
jornalista, cenário global netflix tirou de todos os países, era uma crítica
válida, democrática, em relaçao ao colaborador(Hassan), a liberdade do Hassan
que ele acreditou que ia ser divulgado foi cortada.
Lucro não é o unico fator, WHatsapp negando acesso a dados só pela liberdade dos
usuários, deve aos usuários, a partir do momento em que o usuário vê que as
empresas tão baixando a cabeça, pode rolar um boicote dos proprios usuarios,
isso vaza, usuarios de todo o mundo.
A legitimdade nào tá com os Estado, tá com os usuarios, quem compra produtos da
APple que acreditam que ela vai manter os dados, a 1 Op, a um boicote as pessoas
verem. Ainda que nos países pequenos, ver que essas empresa nos países. Criam um
sistma, as informações vazam, Crimeia de um lado e Crimeia do outro, opositores
podem nao gostar, melhor situações de neutralidade.
Visões americanizadas -> Vários seriados islamicos, 3%, Narcos, etc. Plataformas
globalizadas.
Segunda Op -> Trabalha num cenário de fake news, zuckberg
POI: Um aumento na acusaçào de hipocrisia, diminui legislações fake news sem
acusação. -> Não é uma acusação de hipocrisia, Arabia Saudita e Russia são
extremamente autoritários, fere vários princípios que a segunda op coloca.
No cenário da op primavera arabe nem teria começado, no cenario de vcs isso
estaria impossibilitado. O cenário de vocês que agrava os mecanismos.
**  Whip da Oposição
*** eFEITO REVERSO
N é pra ter postura politizada -> Recusar valores locais e da população que
concorda com -> É um ato político per si.
N tem problema acontercer boicote -> O proprio consumidor -> Conteudo ofensivo
vai permanecer.
*** Caso do 2 gov
Dever moral das empresas -> Toda vez que a gente concorda com a moção -> Pop
seja mais zelada, ainda que o usuario pode boicotar e criticar, o problema vai
continuar, n é apenas a gente deixando de consumir, que o problema vai mudar.
POI: Se o whatsapp te censura vc vai pro telegram e se o governo te censura ->
Mesmo se eu n tiver nenhuma alternativa, o whatsapp n vai deixar de existir, o
problema vai ser o mesmo, a pop seja ainda mais prejudicada.
Mesmo se for possível de resolver, problema vai continuar, o problema central de
direitos humanos, se voces querem propor o direito dos usuarios, como que isso
aconteceria? usuario ainda esta sofrendo danos, e n vai ser poupado de algo
acontecer.
1. Hipocrisia -> Sempre que n se submetem, ou que lavam as suas mãos, elas vão
   fazer com que esse problema n seja apenas prolongado, sofra com os danos, n
   apenas o boicote vai acontecer, hackeamento desses sistemas, China e Russia,
   vao reagir ainda mais, população vai continuar se fudendo.
2. Forma branda -> Forma branda, o Estado vai fazer de forma muito pior, vai
   fazer de forma muito pior, no cenario do governo as empresas n vao poder nem
   mesmo ser utilizados no priorio pais.
3. Construçaão das narrativas -> Os discursos de odio vao ser ainda mais
   justificadas, vao acontecer ainda mais.
