#+TITLE: MocaoGuia
Boa noite a todos, gostaria de declarar meu nome prazer em estar nesse debate,
saudo meus colegas da bancada oposta, a mesa adjudicadora e a plateia que
abrilhanta esse debate.
* Case - 1G
- Dever Jornalistico de um Jornalista
  - Impacto Individual -> Se realizar enquanto jornalista, desgosto de viver na mentirea
    - Vamos lá, como que a gente vai tentar pesar essses principios, e como a
      gente ganha nesse caso?
      - A moção é de agente, e nós não temos dados o suficiente pra saber o
        quanto esse jornalista tá envolvido no proprio afazer do jornalista, o
        Rena fala do arqueiro do filosofo, mas isso só assume num nundo em que
        esse cara internaliza esse tipo de ética que nem é muito usado na
        sociedade moderna.
      - (T)No nosso case entretanto, todo mundo considera que falar a verdade é um
        bem em si mesmo, eu podia até citar Kant mas isso aqui nao é 2017. O
        case que o Estevão fala portanto se torna mais importante, porque tem
        mais probabilidade desse ser humano seguir esse principio.
      - (T)Mas mesmo se não seguir, se a gente entender eses principio como algo
        imposto para esse individuo e não algo que ele internaliza, o nosso
        ainda é mais importante, porque antes de ser jornalista o individuo, é
        bem, individuo, desde que ele nasce ele tem o nosos principio imbuido
        nele, enquanto que o deles só nasce a partir do momento em que ele
        percebe que não sabe o que fazer na faculdade e decide fazer jornalismo
        porque alguma tia disse que ele escrevia bem.
      - E mesmo assim se a gente levar em conta o principio do profissionalismo
        como tão relevante, ao mesmo tempo o case do Estevão se mostra relevante
        nesse caso, justamente porque significa que se o jornalista tem nao só
        dever com a verdade, mas com o jornalismo que no nosso mundo é o meio
        pelo qual a verdade se manifesta dentro da esfera publica, significa que
        o jornalista tem uma obrigação moral de garantir um jornalismo melhor, e
        mais produtivo, portanto nós também ganhamos na esfera social que foi o
        case do Rena e da Jess da arte.
      - Nada indica que esse impacto se concretiza como a oposiçao trouxe, e é
        algo que não é necessario pro nosso caso funcionar justamente porque nosso
        caso utilitarista assume apenas os ganhos ao jornalista e no case social,
        nós assumimos apenas o ganho para o proprio jornalsita que está
        diretamente ligado pra a moção.
    - O Rena fala como a gente usa isso para subrepuljar o WOody Wallen,
      subrepuljar o Heidegger, subrepuljar o JK Rowling sendo transfobica
    - Mas pensa ai, assumindo que a cultura de cancelamento já existe, e que ela
      existe apesar de todos os mil e 1 exposed sobre outros tipos de artistas
    - Artistas esses que são tão basilares, que são tão importantes quanto, nada
      na moção indica que esse autor vai estar um patamar acima de pessoas como
      MOnteiro Lobato na sociedade brasileira, ou literalmente a JK Rowling pro
      mundo inteiro.
  - Cultura de inclusão, de perdão, de conciliação, uma cultura realmente
    empatica e de real diversidade
* Case - 1O
- Assumindo que o Jornalista tenha revelado por meros motivos utilitaristas
- Moção é "EC revelaria..." -> não "ECAQ o jornalista deveria revelar", isso
  sifniica que a moção é perfeitamente plausivel num mundo da moção que o
  jornalista enquanto sendo apenas um individuo mas o individuo que mais é
  diretamente ligado a moção, seja um stakeholder extremamente relevante.
  - Mesmo se a gente assumir isso
    - Perceba que eles falam que as pessoas vão ficar delusionadas, mas vamos
      lá, a JK Rowling passa todo dia no Twitter falando que mulheres trans não
      são mulheres, e faz isso pra um publico jovem e de elite, que também está
      no twitter, e coincidentemente é o mesmo publico do movimento de debate, e
      literalmente semana passada a gente teve um torneio totalmente sobre harry
      potter com a jessica chorando no final.
    - O Estevão também responde isso com os casos de autores que são separados,
      ou nos casos em que as pessoas vão simplesmente mudar de autor, imagina se
      esse é um autor de genero de adolescente e o impacto é esse povo ir ler
      livro de gente, só com isso a gente leva o debate.
- Eles não dão motivo nenhum para provar porque a legião de fãs é o stakeholder
  principal, eles não explicam porque o dano dessas pessaos é maior, ou se tem
  algum principio por trás. ->
  - E mesmo nesse caso a gente ganha porque prova que a história pode até
    melhorar, ganhar mais fãs.
- A Justiça é superfula
  - Mesmo se essa justiça for superfula, a oposição assume que a função de uma
    lei de que é apenas vingança, mas isso não é verdade, o processo também tem
    o objetivo de dar fechamento para a sociedade como um todo de que aquele
    sistema está funcionando.
  - Se a mera reparação ou vingança do dano fosse o que deve haver, as vítimas
    no nosso sistema penal poderiam por exemplo decidir não prestar queixas em
    muitos crimes, no exemplo da moção, eu n posso pedir pra uma pessoa que
    tentou me matar não seja presa, não existe isso. Justamente porque o sistema
    penal enquanto sistema depende de que a justiça sempre tente solcionar e dar
    fechamento aos crimes.
    - Percebam o quão importante é isso, literalmente todas as sociedades
      modernas, assumem esse mesmo principio, ninguem pode eximir o perpetuador
      de uma tentativa de assassinato, nem mesmo a vítima, isso mostra que o
      eleitor médio por conseguinte tem esse principio, o que prova a
      plausabilidade dessa minha refutação, enquanto que a extensão,
      literalmente todas as sociedades implica no impacto dessa refutação.
  - Op também fala que existe casos em que o principio da verdade não se aplica,
    danos de serviço publico, isso se assume nos casos em que o jornalista não
    tá revelando sei lá algum fato privado de um politico, ou casos em que o
    jornalistas evitavam tirar foto do roosevelt de cadeira de roda, mas aqui a
    gente ta falando literalmente de um assassinato.
    - Mas veja bem, eles falam de interesse publico, mas calma gente, não só as
      familias que tiveram os familiares mortos, mas literalmente todo mundo que
      conviveu com esse artista, ou literalmente a legião de fãs tem interesse
      em saber, eu por exemplo quando descubro que alguma banda que eu gosto foi
      cancelado(Ex: Carne Doce, Apanhador SÓ), eu deixo de ouvir esses autores.
      Eu tenho interesse em saber se esse cara fez merda, até porque é bem
      possível que a familia desse cara continue recebendo royalty, eu não quero
      dar meu dinheiro pra essa obra.
* Case Estevao
- Poder ameaçado -> Necessidades de conteudo rapido, raso e reforço a opinioes
  previamente estabelecidas.
* Case 2Op
- As pessoas não sabem diferenciar o artista da obra no Brasil -> O  fato de eu
  e Estevao sermos brasileiros não implica que a moção é no Brasi.
- Ela fala do Monteiro Lobato ser racista e ser cancelado como algo ruim, sendo
  que o "cancelamento" do Monteiro não implicou numa discussão sobre racismo,
  sobre eugenia no Brasil dos 1920, o MOnteiro Lobato ser cancelado foi bom, não
  foi ruim.
- Vamos lá, o cara não tá falando da traição de subcelebridade, ele tá falando
  literalmente de um assassinato.
