#+TITLE: Debate04

- Disclaimer - Qualquer contrapartida que a oposicao trouxer, implica necessariamente neles provarem porque essas contrapartidas seriam viaveis
  + Nos acreditamos afrofuturismo é interessante por si só
  + Porque tem coisas que todo mundo gosta, naves espaciais, experimentos cientificos loucos, etc
  + Nos acreditamos que o afrofuturismo ele é uma estetica que apela para os que as pessoas gostam de ver, mas dentro de umas perspectiva africana
- Segundo disclaimer
  + Pq nos acreditamos que o papel midiatico do afrofuturismo é o mais importante?
    - Pantera negra é um fenomeno global
    - As artes de afrofuturismo no reddit ganham milhares de upvotes
    - É o que afeta a maior parte da populacao
    - É a grande midia
- O afrofuturismo tem uma serie de vantagens
  + A gente tem a vantagem normal de toda arte que representa minorias
  + Representatividade
  + Vc se ver no outro
  + Poder consumir produtos que mostrem ideais positivos e que principalmente as criancas e jovens possam se espelhar
  + O pantera negra é um excelente exemplo disso
  + Mas nos temos dois beneficios apenas com o afrofuturismo
    - Primeiro ponto
      + Ele se apropria da ficcao cientifica -> Boa parte dos grande blockbusters hoje em dia, grandes obras tem algum grau de ficcao cientifica
      + E a maior parte dessa estetica sempre foi de homens brancos
        - Pq? -> Quem tinha dinheiro, quem tinha condicoes de estudar
        - Ex: Asimov, Arthur C Clark, Philip K Dick
        - O futuro na midia, nunca pertenceu aos negros, ele sempre pertenceu majoritariamente a brancos e asiaticos, que sao aqueles que detem o conhecimento cientifico no ocidente
        - O Afrofuturismo é bom porque ele coloca os negros numa posicao no futuro, ele é especialmente forte porque nos podemos ver paises majoritariamente negros dando certo, como a propria Wakanda, que nos podemos tracar um paralelo com Botsuana ou a Etiopia, exemplos de paises que ja foram muito pobres mas que hoje em dia estao no caminho pra o primeiro mundo
        - Mas nao só isso, como ele mostra o passado -> O Afrofuturismo traz também  o passado nesse caso, a gente tem que entender que essa discrfepancia entre sociedades africanas e europeias é algo relativamente recente.
          + Mali, Egito, Aksum, foram todos grandes imperios no continente africano, e que sao completamente esqueicidos -> Pelos proprios filhos da diaspora africana
          + Essa ideia da ancestralidade do afrofuturismo traz de volta esses Estados que mostraram avanços, a biblioteca de Timbuktu era uma das mais renomadas na Idade Media
          + O afrofuturismo resgata isso, mostrando de como numa epoca anterior, antes da opressao europeia, os negros foram inovadores, foram matematicos, foram cientistas, tudo isso é resgatado
            - Que tem o impacto de diminuir narrativas de superioridade branca com base em poucos seculols de historia
            - Tem o segundo impacto de mostrar o poder eque esses povos tem que ter
            - Por ultimo ele traz uma construcao social comum para povos que tiveram sua cultura completamente esquecidas
              + Os filhos da diasposra nao sabem quem sao seus ancestrais
    - Segundo ponto
      + Na estetica da ficcao cientifica
      + O principal qualidade de algum personagem
      + Inteligencia
      + Perspicacai
      + Capacidade de navegar dentro do mundo tecnologico
      + Entretanto, tradicionalmente o homem e mulheres negros jamais tiveram nenhuma dessas caracteristicas
      + Os grandes herois da cultura negra sempre foram musicos e atletas
      + Nunca houveram grandes cientistas negros para as criancas se espelharem, é por isso que em parte o NeilDeGrasse Tyson mostrou tanta força
      + Pq era uma necessidade que jamais foi suprida
      + O afrofuturismo mostra que a crianca negra pode ser uma cientista, pode ser uma engenheira, isso é importante porque muitas vezes a unica visao de sair da situacao de pobreza dessas comunidades é pela musica ou pelo esporte, motivo pelo qual tantos jovens negros lutam pela NBA por exemplo.
      + No Afrofutirismo os negros sao os cientistas, Wakanda é mostrada enquanto uma sociedae extremamente avançada, em que os cientistas ocidentais nao conseguem nem mesmo ficar perto.
  + Esses dois pontos sao exclusivos dessa apropriaçao do futuro por esssa estetica
  + Isso sao os casos de afrofuturismo de ficcao cientifica positiva
  + Nos ainda temos ficcao cientifica negativa
  + Ex: Cyberpunk, qeu tenta mostrar os problemas ocasionados pela dependencia humana da tecnologia, ex: Blade Runner
  + Ou seja, ele trata
