#+TITLE: Final
* 1G
- Larga medida pelo apoio da Russia
  + reussia fornecia crude oil e ele vendia para o ocidente
  + levou a uma estagnacao desse mesmo pais
    - ele deixou de conseguir receber esse oleo da russia, a propria economia da russia, visto como um corrupto.
    - manifestantes pelo valor ocidental. poderam entao entra na uniao europeia, improvaveis de desistir. candidatos considerados como viaveis
    - essas pessoas passaram a ter fome, como alguem que esta a perder.
    - agentes que cada vez se revoltam mais, policiais que nao querem continuar a bater nos seus cidadaos. o proprio exercito
    - como o ocidente olha pra isso
      + efetuar sancoes economicas contra esse pais.
    - russia
      + a russia se manteve esse pais. ele traiu o putin ele precisava de apoio quando invadiu a ucrania
        - 1 realpolitik
        - 2 putin queira manter um regime semi autoritario -> o problema é que ele sabe que isso envolve vc dar voz aos protestos pro-Uniao Europeia, existe um risco politico, um calculo.
* Nosso case
- NOS NAO PRECISAMOS DEFENDER O LYUSHENKO CONTINUAR TORTURANDO E BATENDO EM VELINHA DE 60 ANOS
- o 1g precisa provar como o lyushenko consegue ele consegue manter o minimo de ativos financeiros, de um minimo de poder, ou de ter algum papel na transicao democratica
- Por que um ditador tende a permanecer no poder?
  + Ele tende a permanecer no poder quando ele sabe que vai permanecer com os seus ganhos materiais
  + Um ditador ele tende a extrair, extrair e extrair do Estado onde ele está
  + Cenario ditadura militar brasileira
    - Pq nos acreditamos ser improvavel?
      + Pq muitos do protestos envolvem uma maior aproximacao com a uniao europeia
      + Politicas liberalizantes
      + A bielorussia diferentemente do brasil tem uma populacao relativamente educada
      + Fruto do sistema educacional sovietico
      + Nao acreditamos que isso é viavel nesse caso
  + O que na verdade é viavel?
    - vamos pegar o exemplo da hungria e polonia
    - O que vc pode fazer é mostrar pequenas conseções no sistema politico e judiciario
    - MAS ao mesmo tempo
      + o que vc pode fazer é aparamentar o sitema politico com seus aliados
      + como?
        - diminuir os termos na suprema corte colocando seus aliados
        - mudando as regras de financiamento de partidos
        - mudando as regras de demonstracao na rua
        - ou seja, vc cria uma casca de democracia, mas que na verdade nao é democracia
        - ex: polonia, orban na hungria, o proprio putin na russia
        - o que vc faz é aproveitar o apoio nas zonas rurais, visto que, os protestos tendem a se concentrar nas cidades.
        - entao vc se mostra enquanto alguem que consiga fazer concessoes, vc pode ate eventualmente montar um sistema de accountability votacao que seja controlado por ele
        - perceba como o cenario atual ele ainda tem uns anos no mandato
        - se ele pega os protestos e diminui, ele é visto como alguem que parou
        - ele pode colocar algo semelhante como a china bota a cujlpa em lideres locais
  + pq nos acreditamos que isso é mais factivel do que vc renunciar completamente
    - o problema é que quando vc renuncia, vc vira um ditadorzinho no quintal do putin
    - vc perde completamente a qualquer utilidade possivel pra o putin
    - mais importante
      + vc perde uma coisa muito importante
      + SEGURANÇA ALIMENTAR
      + a bielorussia tem um grande problema chamado chernobyl
      + chernobyl destruiu completamente o solo daquele pais
      + isso significa que eles nao conseguem ter seguranca alimentar
      + pq é tudo umas batatas verdes que brilham no escuro
      + a questao é que a russia tem esse tipo de segurança
        - justamente por eles serem um dos maiores produtores de grao ainda com a perda da ucrania
        - isso se torna mais importante com o aquecimento global e a retirada da camada de gelo da siberia que possibilida a utilizacao daquilo como terra aravel
      + alem disso a russia tem oua coisa
        - a bielorussia tem um problema, faz frio pra caralho lá
        - isso significa que na maior parte do ano, eles sao dependentes do gas russo
        - na europa a maior parte do
  + o que nos acreditamos que seria um cenario factivel
    - o lyukeshenko ele abdica
    - a russia pega, inventa alguma desculpa pra invadir a fronteira
    - alguma minoria russa que nao gosta da tomada de poder, e invade
    - o que nos temos é um cenario de guerra civil semelhante ao cenario da ucrania
    - com uma diferenca, a bielorussia é quase um pais inventado, eles falam russo, eles tem a mesma cultura, eles desde o seculo 18 vivem sob a aegis do imperio russo
    - ou seja, se o putin quiser, ele consegue proteger minoria russa ate a fronteira com a polonia
    - isso significa que eles tem capacidade de nao só criar um conflito localizado como o da regiao da donbass, como efetivamente um conflito completo
