#+TITLE: Debate03

* Nosso case
  + De um lado nós temos paises em desenvolvimento controladas por elites extrativistas, que nao se importam com o país etc VS de um lado nós temos uma politica economica controlada por elites extrativistas que também não se importam com o país, a unica diferença é que essas elites falam ingles, e tem muito menos incentivos de ver o país crescendo.
  + O que o Daniel traz sobre politica moneteria enquanto ferramenta de crescimento
    - Como que os paises sairam da pobreza? -> Coreia do Sul, Taiwan, China etc
    - Esses países não tem muitos atrativos para um investidor estrangeiro inicialmente
      + Pq?
        - Pq nao tem ambientes de negocios consolidados
        - Nao tem expertise
        - Nao tem infraestrutura
        - E como portanto eles fazem ganham esse tipo de coisa?
          + Eles atraem investidores oferecendo um maior retorno pra compensar pelo risco
          + É por isso que hoje em dia nós temos paises desenvolvidos com taxas de juros negativas -> Pq esses paises são tão seguros, mas tão seguros, que as vezes compensa eu perder um pouco menos que a inflação, só pra mantar meu dinheiro liquido
          + Os paises em desenvolvimento não tem a mesma capacidade -> Então por exemplo, se eu sou a Etiopia, e eu quero financiar um projeto de irrigação, ou algo do tipo, eu preciso captar recursos, o meu país por si só não tem recursos, então eu preciso captar eles no estrangeiro, pra isso eu vou ter que tacar as taxas de juros lá em cima, só que no mundo do governo é impossível eu fazer isso, por que quem controla a taxa de juros nesses países é o FED americano.
* 1G
- Mesa -> Dolarizacao nao acaba com instabilidade -> A Grecia tinha uma economia com base no euro, com um banco central estavel, cheio de especialistas, basicamente o cenario do governo, isso nao impediu o pais de se endividar, de entrar em crise, o que impediu foi tirar completamente qualquer mecanismo da grecia de conseguir reverter essa crise. Porque se antes a grecia podia fazer operacoes no mercado de cambio, mudar coisas na taxa de juros, e outras coisas, isso nao exsite no cenario do governo. Respondendo o POI do Guia pro franco, com a politica monetaria, eu consigo revertar crises causadas por outros motivos ou ate mesmo por motivos externos.
- Ref, o governo Brasileiro e Argentino sao excecao, não a regra, a esmagadora maioria dos paises em desenvolvimento experimentam a decadas taxas de crescimento mais de 5%, seja na india, africa ou o resto da america latina.
- O Guia basicamente trata como se a maior parte dos paises subdesenvolvidos fossem uma loucura igual o Brasil/Cuba/Zimbabue -> A real é que a grande maioria das populações do terceiro mundo, vivem em países com alto grau de crescimento economico, e com governos minimamente competentes, mais de 1 bilhao de pessoas na India, quase 2 bilhoes na africa onde a grande maioria dos paises crescem a 5/6/7% o resto da america latina, Peru e Bolivia crescendo a 5% ao ano. Incompetencia no mundo subdesenvolvido é excecao nao regra.
- Cenario de crises ciclicas -> A lógica é que isso mina a propria confianca com a transicao -> Paises em desenvolvimento sao paises em desenvolvimento -> A gente nunca pensa a longo prazo -> Cenario de moedas fracas que geram alta inflação e menor variação cambial -> Alguns investidores preferem paises desenvolvimento -> Blz ->
- Variacao cambial com base nos comoditties -> A lógica se o petroleo aumenta o preço em dolar, aumenta dobrado, quadruplicado naqueles países -> Mas perceba o que o Guia fala, ele fala que o principal acontece no case dos comodities -> Mas ora, a maior parte dos paises em desenvolvimento são exportadores de comodities, isso significa portanto que quando você tem um caso de desvalorização cambial, isso é na verdade bom, porque significa que de repente a soja, a celulose brasileira fica muito mais competitiva no mercado internacional. Ex: Foi o quanto as empresas de celulosa brasileiroas se valorizaram com a queda d odolar. O Visnadi fala que isso gera comodidade, a questão é que com essas vendas qeu eu consigo ganhar dinheiro pra me industrializar.
  + A gente vive num contexto de financeirizacao de comoddities -> O Daniel fala isso -> Quando vc tem um cambio dolarizado, quando vc tem uma alteracao nessa comoddities, é diretamente impactada na economia, quando voce tem um cambio, uma moeda local, voce pode suavizar esses choques na populacao local
- A gente ganha maior estabilidade -> Nós não concordamos com isso, porque essencialmente os interesses dos EUA são diametralmente opostos para os interesses dos paises em desenvolvimento.
- Atracao de capital estrangeiro -> A gente tem governos populistas, e instaveis, o problema é, esses governos populistas vao continuar, eles continuam mantendo controle do orçamento publico, da politica fiscal, da politica de infraestrutura -> Ou seja, antes você tinha uma vantagem que era só sua, que era a capacidade de aumentar a taxa de juros, o problema é que agora o retorno é o mesmo, porque em ambos os casos a taxa de juros é igual, por que agora os paises subdesenvolvidos nao podem controlar mais a taxa de juros, mas o risco continua sendo muito maior.
- Nós temos uma diminuição na fuga de capital -> Mas pega um exemplo Tomas -> Um individuo, vamos chamar ele de CC, CC tem um dinheiro pra investir, ele tem a escolha de investir isso na iBovespa brasileira, ou na Bolsa americana, de um lado nós temos instabilidade na bolsa brasileira em ambos os cenarios, por que os Guido Mantegas vao continuar existindo. -> O que impede esse CC de investir na bolsa americana? É justamente o cambio, porque quando o cambio tá alto não vale a pena comprar dolar e investir na S&P 500, o problema é que quando você dolariza completamente a economia, você aumenta muito mais a fuga de capital, porque o impedimento anterior que era o cambio -> Isso cria uma dimensao ate mesmo politica -> Porque agora você pega as pessoas que tem dinheiro em um pais, os poupadores, e voce desvincula essas pessoas do futuro do país -> Num mundo em que essas pessoas investem no proprio pais 1 - Voce tem os ganhos pra toda a população, afinal acho que nao preciso explicar como investimento gera melhora na vida das pessoas 2 - Essas pessoas agora não tem mais interesse no futuro do país, por que agora o futuro delas independem do futuro do país -> E isso é extremamente importante porque o grande problema desses paises envolve elites que não se importam com o futuro do país, a dolarização acaba com o minimo de incentivo pra eles se importarem. Ou seja, o grande problema que sao a falta de instituicoes politicas inclusivas, aumenta mais ainda, porque não existe incentivo nenhum pras elites quererem melhora do país.
* 1O
- O Nicholas fala muito sobre como a hegemonia americana tende a cair, mas em nenhum momento ele explica porque os EUA nao sao confiaveis, o que nos acreditamos que o Guia explicou muito bem porque eles tendem a ser confiaveis, mas o nosso mecanismo é diferente, de como os interesses dos EUA são diametralmente opostos ao dos paises subdesenvolvidos. -> COisa que só o Daniel explica(O FRANCO FALA NUM POI QUE ELES TRATARAM DE DESVALORIZACAO MAS É MENTIRA). Os EUA querem uma moeda estavel. Só o Daniel explica como a politica monetaria que um pais subdesenvolvido usa para crescer economicamente, basicamente entrando dentro das cadeias de producao global, e exportando, foi assim com Japao, China, Taiwan, assim sao que eles conseguem começar a fazer trocas economicas, ganhar expertise, ir pouco a pouco produzindo coisas mais complexas, industrias, setor de serviços etc. Só que não tem como eu desvalorizar meu cambio, se eu não controlo minha moeda. Ou seja, aqui o Daniel dá muito mais analise sobre porque o EUA quer uma coisa e o pais subdesenvolvido exatamente oposto, o EUA quer moeda valorizada pq é o lastro do mundo, e o pais subdesenvolvido quer o contrario. Ele fala disso também quando a gente tem a dolarizacao dos comoddities, o que é extremamente impactante, paises como Venezuela, Oriente Medio, tem as vezes 20/30% do seu orcamento baseado em um unico comoditty. Ou seja, mesmo quando o EUA ta fazendo tudo certo, ainda sim esses paises podem se ferrar. E perceba também Tomas, como isso vai direto na metrica do Guia de estabilidade, porque com isso nos mostramos que o pais perde estabilidade quando se dolariza9
-
* 2G
- PROTECIONISMO nao tem nada a ver com a moção, eu posso ter protecionismo com dolarizacao, protecionismo é politica fiscal, eu ainda vou poder enfiar barreira alfandegaria ate 60% igual o brasil faz mesmo com economia baseada em dolar. Ou seja, tudo que o Visnadi falou sobre protecionismo tá simplesmente fora do debate.
- O Visnadi fala sobre itens tecnologicos mais caros, maquinarios robos etc -> Ao mesmo tempo em que esses países vai ser mais caro de comprar esse maquinario, significa que vai ser mais competitivo vender os produtos agricolas desses paises quando a moeda ta subvalroizada -> A questao é que, a maior parte dos paises subdesenvolvidos nao tem nem expertise pra utilizar esse maquinario, boa parte da agricultura e extrativismo de paises subdesenvolvidos ainda é feita por metodos arcaicos, nao por falta de maquinario, mas porque eles nem expertise pra usar esses maquinarios tem. Ou seja, no mundo deles eu nao vou poder vender meus produtos, e nao vou ter condicoes de comprar nada porque eu simplesmente nao tenho ninguiem no meu pais que saiba usar.
- Ele fala que você pode perder o dinheiro do investidor estrangeiro, mas quando eu posso investir tanto num pais com muita estabilidade, expertise, tudo de bom VS um pais pobre, com muito risco, eu vou precisar de algum incentivo pra investir, e justamente a subvalorizacao da moeda se torna esse incentivo, porque eu consigo com os meus dolares, comprar muito mais produtos do que conseguiria comprar num pais desenvolvido.
- O incentivo é simplesmente FICAR RICO, virar desenvolvido, quer mais incentivo que isso? Fora que essa ideia de industria ser melhor n tem nada a ver, ate hoje o principal exportacao dos EUA é o petroleo que é um comodity.
