#+TITLE: Debate02
* Nosso case
- Majoritariamente questoes de politicas, feita por homens que estao no poder.
  + Mais visibilidade
  + Fazerem açoes concretas e objetivas
  + Nao tem homens desconstruidos
    - Medidas positivas para os proprios negocios deles -> Diferenca salarial pode ser negativa para o proprio negocio -> Serem mais produtivas mesmo quando tem filhos
    - Os CEOs podem trazer maio enfoque para assedio naquelas empresas, trazer mais politicas de promocao para mulheres de liderança, politica ativa de diversidade.
    - Politicos podem dar mais voz para as mulheres. principalmente quando a gente vê o problema da representacao feminina na politica
- O que nos acreditamos serem os maiores desafios enfrentados pelas mulheres hoje em dia
  + Igualdade salarial de genero -> Mulheres tendem a ganhar menos pelos mesmos empregos, isso é algo que afeta todas sem excecao e é muito malefico porque implica em menores condicoes de vida, de saude, de qualidade de vida para essas mulheres
    - Um estudo que saiu essa semana, mostrou que 40% de todos os ganhos economicos dos EUA nas ultimas decadas foram devidos a insercao de mulheres e minorias na economia
    - O proprio Shinzo Abe, ex PM do Japao, empurrou agressivamente a insercao de mulheres no local de trabalho, tentando quebrar esteriotipos. justamente pra tirar o Japao do marasmo economico.
    - Nesse caso a gente ganha -> Pq se vc for analisar a renda das mulheres ao longo da vida, na maior parte do tempo elas sao iguais -> Ate o momento em que elas ficam gravidas, devido a esteriotiposdo papel da mulher, as mulheres perdem muita renda quando tem filhos e os homens nao, principalmente pelo tempo gasto cuidando das crianças. Como paises do norte europeu resolveram isso? Dando o mesmo tempo de licenca maternidade tanto para homens e para mulheres, o que acabou com a diferenca salarial. -> Ou seja, vc teve uma solucao que melhorou a vida dos homens, e que acabou com ums dos maiores problemas femininos.
  + Falta de representacao no ambiente politico
    - Mulheres tendem a nao ser representadas no parlamento
      + Homens negros, indigenas, amarelos tem o mesmo problema
      + Ou seja, existe uma interseccionalidade entre esses dois grupos
  + Falta de rfepresentacao na economia
    - Mulheres por exemplo trabalhando 60 horas em sweatshops, algo que é a mesma pauta do movimento anticolonial
  + Percebam que em todas essas pautas, que afetam mulheres pobres, vulneraveis, em locais com muito mais violencia de genero do que no ocidente, onde as mulheres tem o mesmo nivel de direitos do que uma mulher inglesa a mais de 1 seculo atras, essas sao os stakeholders portanto mais relevantes e com isso nos ganhamos o debate. Ainda mais quando estamos falando de um movimento global, visto que, está sendo promovido pela ONU talvez a organização com maior capilaridade global para atingir varios locais.
* 2o
- Recursos limitados -> Todo esforco para mulheres noa posicao de lideranca
- Homens tendem a nao querer falar sobre os proprios privilegios -> Aqui a gente tem um bagulho de teoria dos jogos -> Individualmente eu concordo que um homem ter que por exemplo ceder uma vaga pra uma mulher, porque ele sabe que os outros homens nao vao fazer o mesmo, MAS, MAS, quando a gente tem uma organizacao como a ONU Mulheres, que tem carater global, e que tentam agir com base em politicas publicas, o que nos temos é um cenario em que todo o SISTEMA é mudado, Ex: A questao da licença paternidade, porque nesse cenario, todos os homens abrem mão dos seus privilegios ao mesmo tempo, o que a gente tem nesse cenario é uma vantagem pra todos os homens devido a ganhos economicos que o Daniel traz, entao por isso que uma organizacao grande, global e qeu haje com base em politicas publicas, consegue resolver essa questao dos privilegios. Justamente porque vc tá mudando o sistema de uma vez, acabando portanto com os interesses individuais.
* 1g
- construcao de homens desconstruidos -> luta patriarcal -> vantagem a partir do mov feminista no passado. -> a corrosao ocorre devido a esse compartilhamento de valores.
  + PERCEBA -> OS NOSSO ARGUMENTOS NAO VAO ATRAZ DO BOM SENSO E BONDADE DOS HOMENS, MAS DOS INTERESSE DOS PROPRIOS HOMENS, ISSO É MAIS IMPORTANTE, PORQUE NOS CONSEGUIMOS ATINGIR LOCAIS EM QUE ESSE TIPO DE PAUTA FEMINISTA NAO CHEGOU, SEJA EM LOCAIS RURAIS DO TERCEIRO MUNDO, SEJA EM LOCAIS MAIS CONSERVADORES, OU SEJA, OS NOSSOS ARGUMENTOS MOSTRAM QUE PRATICAMENTE TODOS OS HOMENS PODEM SER CONVENCIDOS, OS ARGUMENTOS DO 1G DEPENDEM DESSES HOMENS SIMPLESMENTE SEREM LEGAIS. E JÁ ESTAREM EM ALGUM LOCAL EM QUE O MOVIMENTO FEMINISTA TENHA AGIDO COM FORÇA, OU SEJA, NO GRANDE ESQUEMA DAS COISAS, OS ARGUMENTOS DELES SÓ FUNCIONAM EM POUCOS PAISES, NO NOSSO A GENTE CONSEGUE FAZER ELE FUNCIONAR EM TODO O GLOBO, E PRINCIPALMENTE NO TERCEIRO MUNDO, QUE É ONDE OS MAIORES ABUSOS CONTRA OS DIREITOS DAS MULHERES OCORREM. ATE MESMO O EXEMPLO QUE O DANIEL DÁ DE MASCULINIDADE TOXICA, IMPLICA EM HOMENS DESCONSTRUIDOS QUE NAO GOSTEM DE SER O MACHAO, NO NOSSO MUNDO, ATE O TIOZAO BOLSONARISTA VAI QUERER MAIOR CRESCIMENTO ECONOMICO.
# - capital politico para o movimento feminista
# - desmoralizacao do machismo estrutural
#   + orgulho hetero e tals -> só mostram que já vai existir resistencia natural pros homens, n explicam pq um tiozao bolsonarista vai ser convencida por um menino de 18 anos com camisa "Eu sou feminista, vai encarar" -> preconceitos por força e poder -> nos acreditamos que os interesses economicos/politicos e sociais que o Daniel traz, são muito mais relevantes do que qualquer tipo de esteriotipizacao de masculinidade toxica.
* 1o
- Discussao sobre aliados -> Criacao sobre homens -> Masculina e liderada por homens(Vamos lá, a organizacao foi criada pela ONU MULHERES, nao foi pela ONU HOMENS) -> Nos nao acreditamos que efetivamente existe roubo de pauta, pelo simples motivo que do mesmo jeito que homens não tendem a ouvir mulheres, as mulheres vao sempre preferir ouvir outras mulheres, na escolha entre um homem falando e uma mulher falando, a mulher vai escolehr a outra mulher, pelo simples fato de que ela vai se ver, vai falar igual.
  - É o mesmo fato de que qualquer tentativa de formação de paz por ocidentais em paises orientais nao funciona, porque vc nunca vai conseguir convencer alguem que n tem nada de semelhante contigo, a acreditar em qualquer pauta. Da mesma forma, qualquer homem que chegue numa aldeia na indonesia pra falar de feminismo vai ser visto como piada pelas mulheres, mas talvez não pelos homens. Mesmo se houver uma diminuicao em recursos escassos da ONU, vamo lá, homens ainda são metade da populacao mundial, como vc vai te um movimento social que nao dialoga com metade da populacao mundial. AInda mais quando a gente vê que hoje em dia com internet, radio, tv, nao é tao caro assim vc colocar mulheres e homens para falar.
  - E percebam o que a Ruth fala, tratando que dificilmente homens tem mulheres que admiram, justamente porque os homens nao levam as mulheres a serio, é que a gente precisa de homens pra dialogar com eles.
  - Nesse CENARIO QUE É MUITO DIFICIL DESCONTRUIR ESSE HOMEM -> É JSUTAMENTE O CASE DO DANIEL, IR ATRAZ DO EGOISMO -> A RESPOSTA DO POI DELA FOI BASICAMENTE QUE DEVIDO A DIFICULDADE DE DESCONTRUIR MUITOS HOMENS, A GENTE PRECISA FOCAR NAS MULHERES -> MAS O DANIEL TRAZ MECANISMOS DE COMO DÁ PRA VC DESCONSTRUIR, NAO FOCANDO NE ETICA E BONDADE DOS HOMENS, MAS LITERALMENTE NO ESTOMAGO.
  - Vc só consegue chegar numa camada mais conservadora usando uma mensagem mais diluida, vc nao precisa disso, por que vc consegue como o Daniel falou, encontrar pontos de encontro entre homens minorias e mulheres minorias, assim como casos em que vc consegue nao encontrar interseccionalidade entre os problemas, mas em que a resolucao dos problemas das mulheres acaba por beneficiar as mulheres.
