#+TITLE: Debate01

* Por que a academia é o que mais importa nesse debate
  + ECL o predominio da historia comparada em Estudos
    - 1 - Todo e qualquer mecanismo que qualquer lado trazer, tem que sempre partir do ponto de partida da academia, justamente porque esses estudos, essa ideia vem da academia, a após isso ela é transmitida para outras partes da sociedade
  + 2 - Todo e qualquer impacto em outros aspectos da vida social vai necessariamente vir diluido, justamente por causa da falta de alcance da academia principalmente em paises historicamente com baixa educação como na america latina, portanto, onde o impacto é mais forte é dentro do contexto da academia.
  + 3 - Inferencia Causal -> Como a gente consegue ver se algo é verdadeiros nas ciencias sociais? -> Como podemos definir causalidade vs casualidade? -> Não tem como eu reproduzir experimentos na sociedade, então o qeu eu faço? -> Eu procuro contrafactuais -> Eu pego um contexto extremamente semelhante, mas com uma pequena diferença Ex: Melissa Dell economista americana que estudou as minas de potosi, em que ela observou vilas que eram exatamente iguais em todos os contextos, literalmente km de distancia, mas uma estava dentro duma area de trabalhos forçados e a outra não, na epoca da colonizacao, o que ela fez foi justamente generalizar tudo, e pegar as diferenças enquanto exceção e não regra, e assim que se consegue entender quando um evento teve ou não efeito no contexto, e o grau desse efeito. Com esse experimento ela conseguiu analisar exatamente qual foi o efeito dessa instituição no bem estar das pessoas naquela região, mesmo seculos depois.
    - Aqui a comparativa -> No framework deles, tudo é diferente no começo,e depois vc procura semelhanças, no nosso tudo é semelhante, e vc procura as diferenças pra explicar eventos, o nosso é melhor para entender porque você foca apenas nas diferencas que voce quer entender, no mundo deles n tem como saber que diferenca tem impacto, pq sao tantas.
* 1G
- Fatos Historicos podem ser diferentes e isso deve ser levado em conta
  + ALEXIA FALOU A METRICA DELES - Entender seus fins e motivos para conseguir entender o futuro
  + Assumindo esse cenario da Alexia, a história essencialmente perde todo o seu poder prático -> Ex: Pra você retirar lições da história, você necessariamente precisa generalizar coisas, por que do mesmo jeito que eu fazer uma comparação entre a Colombia e o Peru do século 20 eu vou precisar retirar alguns detalhes, do mesmo jeito se eu quiser explicar eventos na Colombia de 2010, usando a Colombia do século 19, eu vou ter que também retirar alguns detalhes., detalhes até maiores já que existe uma diferença muito maior entre eras temporais diferentes e locais diferentes.
- A Inaam fala como a comparativa é esteriotipada
  + Nós não acreditamos que os esteriotipos da America Latina são gerados por esse tipo de esteriotipo
  + Ela falha em deifnir como algo no ramo MERAMENTE academico -> Vai causar efeitos tais na sociedade como um todo, as pessoas que acreditam que Buenos Aires é a capital do Brasil -> Não são aquelas que são membros da academia, isso é fruto da falta de educação no geral dos americanos e europeus, não de algo que se resume a academia. Perceba que elas nao trazem mecanismo pra mostrar como esse contexto especifico da academia, é transmitido para o imaginario popular, e iso era necessario.
* 2G
- Se você não entende o momento anterior, você não consegue formular politicas publicas -> Mas é justamente por isso
- Não tem como a gente usar o presente de experimento -> Por que? Porque experimentos sociais tendem a envolver milhoes de pessoas morrendo, então a gente precisa saber quando uma politica publico funciona e quando ela não funciona, se eu só olhar pra o Brasil, imagine um Brasil daqui a 100 anos atras, e a gente precise descobrir se dar aportes direto pras familias pobres(O Bolsa Familia) funciona ou nao, no mundo do governo, a gente não vai saber qual foi o impacto do Bolsa Familia, se a gente não puder comparar com locais que são muito semelhantes, mas que não tiveram esse tipo de politica publica, no mundo do governo a gente não tem a maior parte dos historiadores se debrucando por esse tipo de questão, recebendo verba pra estudar isso, recebendo bolsa(ou seja, a gente quer que seja a predominancia mesmo) e portanto não tem como a gente medir o impacto dessse tipo de politica publica, a não ser testando diretamente, o que obviamente n é ideal.
- A Alice fala que a gente precisa fazer grupo de controle com outros paises, o problema é que os nucleos sao os mesmos, instituicoes politicas extrativistas, nao importa o dolar, coisas como personalissimo, desenvolvimentismo, falta de independencia de judiciario, sao coisas muito mais nucleares. Do que um dolar, que é muito mais consequencia do que causa dos problemas. E o proprio exemplo da dolarizacao é perfeito, porque da pra gente estudar como o plano real salvou a economia brasileira, porque a argentina ficou com essa economia justamente por nao ter tido o mesmo tipo de atitude que o brasil
- Os paises do AL também sao o melhor grupo de contrle porque é muito mais facil pra um brasileiro entender o contexto da colombia do que de botsuana, por causa de lingua, exchanging cultural, economico, muito mais facil estudar uns aos outros.
- Nos nao compramos essa ideia de que nos nao fazemos troca com Europa e China por causa de algum tipo de solidariedade americana, esse tipo de fechamento comercial é algo simplesmente que se resume a Brasil e Argentina, muito mais por causa de um dominio de desenvolvimentismo na academia economica brasileira, do que qualquer tipo de estudo histórico, até por que Peru, Colombia, Chile sao paises extremamente abertos, colombia tem livre comercio com os EUA até o talo, e onde essa narrativa ainda existe.
* 1O
- 1O essencialmente debate "ECAQ a historia comparada é mais correta que a especifica" -> Entretanto em nenhum momento eles fazem o link entre uma historia verdadeira, e uma historia que traz beneficios no mundo de hoje, é possível existir um mundo em que a Historia Comparada fosse completamente falsa, só trouxesse resultados incorretos, mas sua hegemonia ainda sim trouxesse beneficios práticos para a sociedade latina.
