#+TITLE: Debate05

* Case
- Caracterizacao -> Agente externo intervindo numa região de conflito -> Case que possa ser trazido pelo outro lado -> Precedente -> Efetivamente voce tem um pais tendo seu governo sendo literalmente invadido por paises vizinhos que nao necessariamente tem interesse na manutencao de um status quo benefico para aquele povo
  - Duas coisas
    - 1 - Nos acreditamos que a CEDEO tem total e completa legitmidade pra fazer esse tipo de acao
      + Visto que os paises se juntam nesse tipo de coisa por livre e espontanea vontade
      + Pelo proprio infoslide já mostra que existe precedente pra intervencao militar desses paises em seus membros, a criacao de um mecanismo de forcas militares conjuntas nao se cria da noite pro dia, portanto a gente pode assumir que isso já tinha sido acordado pelos membros
    - 2 - Mesmo assumindo que eles nao tem total legitmidade
      + Percebam que a moção diz respeito a um agente especifico -> A CEDEAO, ou seja, mesmo que isso nao for completamente interessante pro Mali, nos temos que asssumir que o que realmente importa, a métrica desse debate é o que vai nos interesses da CEDEAO.
- Por que isso vai no interesse da CEDEAO
  - 1 - Motivo classico
    + Esse tipo de instabilidade -> Governos militares -> Juntas militares -> Tendem a nao oferecer nenhum tipo de accountability, e mais importante, tendem a ter uma politica externa muito mais agressiva
      - Pq
        + Logica militar
        + Hierarquia
        + Resolver tudo na porrada
      - Pelo infoslide a gente pode assumir que o minimo de representatividade e sociedade civil existia antes da deposição, visto que havia um governo e um parlamento, que eu assumo que era eleito
  - 2 - Alem disso nos temos a questao do terrorismo
    + O Mali tem muitos grupos de insurgentes, com laços com al qaeda, estado islamico etc
    + O que um golpe militar causa
      - Causa instabilidade
      - O governo militar nunca vai representar os interesses de todas as camadas da populacao
      - A gente vai ter um pessoal que tá muito puto com a deposicao
      - Esses governos tendem a ser extrativistas
        + Justamente porque pra financiar esse tipo de tomada de poder
        + Vc precisa oferecer algum tipo de recurso para os seus apoiadores
        + Ex: Gana na decada de 60, o economistas americanos nao conseguiam entender porque os governantes faziam politica economica claramente errada de contlar os precos de produtos agricolas para subsidiar o preço do pao nas cidades, e a resposta é, o fato de que esses governantes precisavam do apoio das cidades pra se manter no poder, justamente pela falta de legitmidade geral
        + Significa que governos ditatoriais tendem a ser extrativistas
        + Vc vai estar extraindo de alguem -> Mais propenso ao terrorismo
    + E pq isso é ruim?
      - Pq o terrorismo ele se expande para todas os paises em volta
      - Recentemente nos tivemos ate mesmo pessoal militar americano sendo morto no Niger lutando contra terroristas
      - Isso se torna mais importante, com a Isis e a al-qaeda perdendo espaço no oriente medio, signifnica que eles vao prcurar outras areas, a a africa ocidental se torna perfeito pra isso
      - Portanto é no interesse da CEDEAO intervir nesse sentido
  - Alem disso nos temos um outro fato importante
    + A intervencao rapida, eficiente e tempestiva, implica em vc nao dar municao pra potencias estrangeiras(leia-se a franca) virem a intervir na regiao
    + a gente já teve intervencao francesa no pais, na republica centro africana, e em varios outros paises da reigao ou proximos
    + a partir do momento em que a CEDEAO deixa de intervir, vc cria o espaço pra esas potencias europeias que ainda tem muita relacao com as antigas colonias intervirem
    + pq isso é ruim pra CEDEAO
      - Pq vc cria um cenario em que cada vez mais se a intervencao francesa for bem sucedidade, como foi bem vista a do mali e a da republica centro africana
      - vc cria um cenario em que a opiniao publica nesses paises ocidentais passa a cada vez mais ser conivente com esse tipo de intervencao
      - e isso é muito ruim independentemente de o pais no CEDEAO ser uma ditadura ou uma democracia
      - Pq ninguem quer ter seu pais invadido -> Ou seja, no pior dos cenarios em que esses governos nao querem intervencao -> é melhor o vc ter uma intervencao de uma liga de paises da regiao, com interesses da regiao, intervindo, do que uma franca, reino unido da vida fazendo o mesmo.
      - pq? -> pq no cedeao eu tenho poder de influenciar na formacao da instituicao, nas regras dos tratados, etc
      - No cenario do governo, em que quem controla como essa intervencao acontece, é um pais que nao tem nenhum  interesse necessariamente na manutencao dos interesses dos outros paises da CEDEAO.
