#+TITLE: Semi
* CASE NOSSO
- Um mundo sem a formulacao de da lamentacao divida
  + um mundo com menos influencia da religiao no Estado
  + pq? -> pq quando deus é legislador, e a lei divina é sempre suprema, nao tem como haver discrepancias entre a lei terrena e a lei divina, justamente pq qualquer punicao terrena nuca vai se equiparar a punicao eterna.
  + pq leis divinas sao piores?
    - menos racionais
    - so podem ser mudadas por interpretacao
    - dogmas, vc pode questionar um rei, mas vc nao pode questionar deus
    - hinduismo, lei grega, romana, eram sociedades mtu bem formuladas e que n tinham esse tipo de coisa
    - e por que esse tipo de religiao é ate melhor do que as religioes teistas
      + pq a barreira de entrada é menor?
      + o que nos acreditamos que seja o melhorforma de construir coesao social e comunidades duradouras?
      + é vc ter uma framework minimo, mas que esse framework seja o mais abrangente possível
      + pq?
        - principal forma de destruicao de uma comunidade é o sectarianismo, é a destruicao interna
        - é quando um grupo nao ve no outro como parte da sua comunidade
        - e pq as religioes em que deus é o legislador sao problematicas nesse aspecto?
        - pq elas criam simplesmente regras demais, para eu ser cristao, eu preciso seguir aqueles dogmas aquelas leis
        - pra eu ser budista, eu n preciso seguir muita coisa
        - ex: muitas familias dalit na india, se convertem pra o budismo, pra se livrar do sistema de castas hindu, justamente pq a barreira de entrada é muito baixa
        - e isso tem milhares de impactos
          + vc tem menos conflitos internos, pq todo mundo ve o outro como igual
          + vc tem maior resistencia contra ameacas externas - pq pra vc resistir a uma ameaca externa vc precisa ter o maior numero de soldados, de membros engajados possivel, e a melhor maneira de vc fazer isso é se todo mundo acreditar que faz parte daquilo.
* 1G
- Eles trazem EC Lamenta a religiao, embora as religioes do
- Metrica - O que faz as pessoas tomarem melhores acoes
- Paises laicos por causa de pessoas religiosas naqueles locais -> Fala de Estado como nao sendo laico
- Ser humano ao longo das eras -> Construcao estatica da moralidade -> A base dos conceitos ainda permanece o mesmo, interpretacao que se baseia nos seres humanos.
  + Ex: Escravidao, interpretacao daqueles escritos que justificava a escravidao
- Dissonancia cognitiva
  + Voce fica sempre com receito de estar fudendo algum preceito -> Sera que eu estou fazendo algo errado ->
- POR QUE AS RELIGIOES COM TEORIA DO MANDAMENTO DIVINO, CRIA SOCIEDADES MENOS LAICAS, QUAL MECANISMO QUE ELES DAO?
  + Nos damos mecanismo lei divina VS a lei terrana.
  + O que é o mecanismo da lei divina vs terra -> Essa ideia de que como a lei divina ser um dogma, e mais importante, MEDO DE PUNICAO, norma só existe com coerção Se vc fizer X, Y vai acontecer, logo  é condiçao sinequanon pra lei existir uma sanção.
  + Logo como a punicao divina é impossivel de fugir, ela sempre acontece, até pq deus é onipotente, significa que ela sempre vai ser mais poderosa que a sancao terrena.
  + isso significa que vc tende a ter estados menos fortes, que foi justamente o que 1g nao explicou, a ruth fala apenas que n tem estado laico pq tem muito cristao, mas a questao é o que o daniel fala de que com a lei divina é sempre superior, isso significa que o estado sempre vai ser sequestrado pela religiao, justamente por nao ter força frente a lei divina.
- Case que ganha esse debate
  + Construcao estatica da humanidade, ninguem consegue ter acesso a vontade de Deus, escrituras e interpretacao.
  + Os crentes acreditam numa objetividade moral que é pautado naquelas escrituras. Com base nos interesses das instituicoes. Interesse das instituicoes é se expandir, conseguir mais fieis. A palavra de deus.
- COmparativo
  + A palavra de deus passa a ser interpretativa, por ser muito mais facultativa, tenho mais incentivo para questionar as autoridades, questionar os meus lideres.
* 1O
  + A palavra de deus, sobre muito mais sobre amor do que sobre violencia, texto sagrados vs mandamento de deus.
    + Nos achamos isso meio errado, porque em toda a biblia nos temos uma serie de cenarios em que Jesus, ou algum profeta que tinha relacao com Deus, seja de voce condenar adulterio, comer porco, et, quando Jesus fala algo que você não deve fazer, você assume que o que ele tá falando é algo que deve ser seguido. Esse afunilamento da 1O é injusto e simplesmente falso.
      - Pensa ai, como que os mandamentos de deus sao jogados? é deus dando os as 10 tabulas pra moises, mas isso tbm é uma historia, do mesmo jeito que quando vc tem um profeta sendo encontrado por um individuo, e falando sobre sodoma e gomorra(aqui a gente tem um mensageiro direto), e qualquer coisa que jesus falar tbm pode ser considerado como lei moral,(pq? pq jesus é um ser perfeito, e sendo um ser perfeito significa que tudo que ele faz é o máximo moral), elas nao explicam como essas duas anedotas da biblia sao diferentes.
    + Justamente porque nessas religioes os Deuses sao perfeitos
    + É diferente quando a gente tem a Iliada ou a Odisseia, em que o que voce tem sao efetivamente historias que extraem uma significado, mas que nao envolvem nenhum mandamento.
    + Ela fala que isso foi essencial pra essas sociedades sobreviverem
      - Mas vamo lá, a moção asssume que nem toda religiao é assim
      - A gente tem o Budismo por exemplo, o Shintoismo, as religioes que envolvem Shamanismo, isso tudo sao sociedades que se desenvolveram, que prosperaram, que criavam arte, tecnologia, tudo igual os cristaos. Os mongois construiram o maior imperio contiguo da historia, o budismo é mais antigo até que o cristianismo, o japáo tem uma sociedade milenar.
    + Depois ela fala que as leis sao revistas
      - Mas pensa lá mesa, o que é mais fácil, eu revisar uma lei criada por HOMENS, que todo mundo admite que sao falhos, que erram, que sao limitados VS eu tentar REINTERPRETAR, uma palavra do ser que é literalmente perfeito. Mesmo se Deus nao fosse perfeito, ainda sim toda interpretação, envolve uma moldura, ou seja, eu tenho a norma, e ela me permite um numero de finitos de intepretação, mas que ainda limita essa interpretacao, enquanto que no nosso mundo nos temos leis que podem ser MUDADAS, o que significa que temos possibilidades infinitas.
    + Eles foram importantes ao longo da historia humana
      - Vc nao mantar, vc nao roubar, a gente dá exemplos de religioes que tem isso, e tem a mesma coisa.
      - a gente mostra como na real, esses mandamentos envolvem vc criar mais sectarianismo, que é a maior fonte de desgraças da humanidade, quando vc pensa no exemplo da Julia sobre escravidao
      - "A escravidao foi pq os europeus nao viam os negros como gente" -> Mas justamente, um dos motivos pra eles serem vistos como animais, era porque eles nao eram vistos como membros daquela comunidade, guerras religiosas a mesma coisa.
* 2O
- Individuos nao estao se comprometendo apenas com o que eles pensam -> Mas Tomas, as pessoas tendem a ser morais quando elas estao trabalhando em grupo, porque a atitude racional tende a ser vc manter o grupo, já que num sistema de contrato social, em que é muito dificil vc mudar de grupo, o que vc precisa fazer é geralmente andar na linha, o problema é que a moral NORMATIVA RELIGIOSA, ela implica em vc fechar as comunidades. O que causa guerras e atos horriveis entre grupos, ou seja, quando a gente ta falando de moral INTRAGRUPAL nos temos em ambos cenarios pessoas tendendo a ser minimamente legais, pq nao é racional, e quando é racional matar alguem vc sempre consegue achar algo na religiao pra te justificar. Quando a gente ta falando de guerras INTERGRUPAIS, vc tem algo muito pior, porque o numero de grupos é muito mais fragmentados.
- Quando a gente tinha o imperio mongol por exemplo, que deixava vc ter qualquer religiao desde que pagasse os impostos, no cenario da oposicao, a gente tem um cenario de imperios espanhol ou portugues, que efetivamente catetizava as pessoas, e onde era impossivel fazer parte daquela instituicao politica e se tornar membro da comunidade.
