#+TITLE: Debate Online 06 de Março de 2020
* Framing
** RefutaçÕes
Se o caso do Franco fosse verdade, de que o mais provável é que as empresas que
fossem canceladas, e que tudo ia ficar com elas no foco, as empresas
simplesmente não investeriam em ONGs, empresas são organismos vivos com milhares
de funcionários, e com corredores e corredores de analistas, publicitários etc,
que trabalham justamente pra evitar esse tipo de coisa, sendo que ONG não tem
esse tipo de recurso, ou seja, a ONG que vai ser cancelada.
E no pior caso, se a ONG não conseguir se manter sem o patrocinio da empresa,
nós preferimos isso, pq significa que os doadores fisicos da empresa vão para
outras ONGs, ONGs que conseguem utilizar seus recursos mais eficientemente, nós
na verdade preferimos um mundo com poucas ONGs gigantes, pq escala é sinonimo de
eficiencia, vc consegue fazer o mesmo, com poucos recursos.
** Pq nós acreditamos que doadores físicos tendem a ser melhores do que doadores empresariais
Qual o grande questionamento do debate? Se o ganho de orçamento extra advindo do
influxo de grandes somas de dinheiro de uma empresa, vale a pena.
Pq nos acreditamos que por uma métrica meramente orçamentária, não vale a pena?
A forma que uma ONG consegue oferecer real mudança no mundo é por meio de longo
planejamento, e trabalhos continuos, política pública baseada em evidencias, não
é atoa que o maior trabalho de alivio a pobreza, que ganhou o Nobel de 2019
advednho de anos de experimentos feitos ao longo de meses cada um.
Empresas necessariamente indicam volatilidade -> Pq? -> Pq quando a ONG passa a
ter acesso a um grande doador empresarial, significa que toda sua fonte de
rendimento vem de um ou poucas fontes. Afinal, se ela está conseguindo ganhar
seu dinheiro, é bem provável que ela não vá se dar ao trabalho de correr atrás
de doadores físicos.
E pq doadores empresariais são piores? Pq empresa implica em volatilidade, só
olhar pra bolsa brasileira, caiu 12% perdi dinheiro pra caralho vou chorar. A
partir do momento em que a sorte de uma empresa passa a ir pro mal, ela vai
retirar aquele patrocinio, pq n é algo necessário, o problema é quando vc só tem
3 ou 4 grandes doadores, se você não tem certeza do seu orçamento, vc passa a
fazer ações muito mais no curto prazo, do que algo que só vai precisar de
investimentos continuos por 5, 10 anos.
E em relação ao investidor físico? -> Se um investidor físico quebra, e você tem
milhares e milhares de outros pequenos investidores físicos também, o único
jeito de você não conseguir acesso a um fluxo de orçamento continuo, é se a
economia como um todo quebrar, onde nesse caso o patrocinio empresarial também
acabaria.
Não só isso, como no caso do investidor físico, esse é um cara que muito
provavelmente não tem interesses excusos em investir numa ONG, OU SEJA, ele
precisa ser convencido que aquela ONG tá mostrando resultado, coisa que a
empresa não precisa. Isso significa que existe uma verdadeira competição entre
ONGs pela conquista de investidores físicos leais e continuos, o que melhora no
geral seja qualquer o problema que essas ONGs estejam tentando resolver.
** Quais os casos principais?
Empresas que exploram recursos naturais no terceiro mundo doando para ONGs que
Empresas poluidoras que se usam de ONGs ambientais
aliviam a fome e miséria nesses locais, afinal a maior parte das ONGs envolvem
alivio a pobreza
E um disclaimer do caso do Arthur, caguei pra ONG que vive onde a Volkswagen tá
sendo sediada, to nem ai pra ONG que age em país de primeiro mundo, as ONGs que
realmente importam são as grandes ONGs que tiram dinheiro do primeiro mundo e
levam pro terceiro, para locais com gente realmente vulneráveis que realmente
precisam e de onde o dinheiro vai ser mais útil.
** Pq nos acreditamos que ganhamos em ambos?
*** No primeiro caso em relação a ONGs cujo objetivo é aleviar a pobreza
Como essas empresas lucram? Conseguindo explorar ao máximo os recursos naturais
desses locais, entretanto para ter acesso a esses locais, na maior parte dos
casos sao remotos, em florestas, desertos etc. Eles precisam ter acesso as
comunidades que vivem lá, seja em comprar as terras, seja em conseguir mão de
obra, seja em não ter toda uma comunidade efetivamente boicotando seus projetos
de infraestrutura.
E como a ONG entra nessa estrutura? As ONGs funcionam como ferramenta de
inserção dessas empresas dentro desse contexto, na maior parte dos casos ONGs e
grupos de missionarios, funcionam como único link entre essas comundiades e o
mundo exterior, a única escola, a única igreja, o único hospital dessas
comundiades é fornecido por essas ONGs, a partir do momento em que essas
organizaçòes passam a ter acesso a investimento empresarial, vc cria uma relação
de dependencia, isso significa que a empresa passa a ter acesso e legitimação em
relação a essas comunidades.
No pior dos casos, você não vai ter ninguém pra denunciar esses abusos, já que
uma das funções das ONGs é justamente denunciar a exploração feita pelas empresas.
Qual o impacto? Vc passa a ter muito mais empresas tendo livre acesso a
exploração de recursos naturais, e exploração de mão de obra barata, isso
significa que os stakeholders mais importantes para a propria ONG acabam por
serem afetados.
E qual a extensão do impacto? Nós acreditamos que esse argumento se aplica em n
casos, seja na República Democrática do Congo, um dos paises mais populosos e
mais pobres do mundo. Seja na Indonesia em relação ao Oleo de Palma, e que é o
quarto país mais populoso do mundo.
*** Segundo caso o das ONGs ambientais
Nós acreditamos que o aquecimento global e as mudanças climáticas são um
problema global, e de responsabilidade das grandes poluidoras, nós acreditamos
que elas tem o incentivo pra sempre se evadir de sua responsabilidade. Exemplo a
VOlkswagen carros feitos evadir teste de emissoes
Como elas fazem isso? Evitando a ira dos governos, isso é especialmente
importante, num mundo em que existe uma onda ambientalista no primeiro mundo,
sede das empresas(Partido verde na europa e new green deal nos EUA)
A partir do momento em que essas empresas sao vistas pela opiniao publica como
inofensivas, vc tem uma diminuição nesse tipo de legislação.
Como elas agem portanto? Elas seriam forçadas a no melhor dos casos pegar esse
dinheiro, esses bilhoes investidos em marketing, a Red Bull por exemplo envolve
uma grande porcentagem do seu lucro em marketing, poderia ser investido em
tecnologia pra efetivamente amenizar o problema.
