#+TITLE: Debate_02
  - Caso 1 Op
    - Pra vc ter uma industrializacao voce precisa ter tecnologia -> Precisa
      importar a tecnologia
    - Cidades servem para articular a movimentacao economica
    - Essas cidades possuem escolas melhores e hospitais melhores
  - Caso 2G
    -
  - 1 OP basicamente falou que as cidades grandes sao mais ricas e portanto
    melhores, jogando buzzwords como articulacao e expertise, nós vamos explicar
    POR QUE elas sao sempre mais ricas e porque em todo qualquer caso vai ser
    menos  eficiente constuir difusamente do que em um só local.
    - É preciso explicar porque as cidades por definicao oferece saude melhor, a
      1 Op fala apenas que essas cidades tem hospitais melhores, mas o caso do
      governo é justamente o de ofecer hospitais melhores nas cidades menores.
  - Cracterizacao cidades
    - Nós negamos essa premissa da Jessika de que as condições de vida nas cidades
      são piores, é simplesmente falho, o estado mais pobre do Brasil não é Rio de
      Janeiro, é o Maranhão.
    - A gente tem que entender que as cidades sao o maior motor de crescimento
      economico de um pais
    - Muito embora existam maneiras de encurtar distancias hoje em dia, a gente
      pode ver como a produtividade em home office é prejudicada
    - As cidades oferecem uma oportunidade unica de inidivduos se encontrarem
    - De empresas encontrarem o maior numero possivel de candidatos a vagas de empregos
    - De ideias entrarem em contato
    - Não só isso como cidades fornecem economias de escala
      - Seja em arranhas ceus em vez de casas que possibilitam maior economia de
        espaço, grandes cidades possibilitam a verticalizacao ao extremo das
        habitacoes, cidades pequenas onde é mais caro por exemplo pegar os insumos
        e pre-moldados para esses locais afastados. Uma cidade grande vai ter
        suas empresas de infraestrutura SEMPRE TRABALHANDO, nunca ociosa, o que
        por si só já diminui os custos.
      - A populacao ficar aglomerada em sardinha é na verdade algo bom, e no pior
        dos casos, se a gente não conseguir fazer isso, do mesmo jeito que a gente
        consegue construir numa cidade 100 km distante, a gente pode fazer a mesma
        construção nos arredores desssas grandes cidades, crescendo horizontalmente.
      - Seja em transporte publico invés de carros que são menos poluentes e
        ocupam menos espaço, e com custo baixo conseguem servir milhares de pessoas
      - Até mesmo em serviços públicos no geral, se eu construo um hospital numa
        cidade grande, isso significa que eu consigo garantir que a maioria dos
        leitos vao ser usadas em qualquer exato momento, justamente porque tem
        muita gente doente, numa cidade média para pequena eu nao consigo fazer o
        mesmo, Um exemplo disso é no Brasil: Onde boa parte dos hospitais em
        locais afastados encaram um tremendo subuso de recursos. Ou seja, num
        cenario em que tanto a cidade grande quanto a média não tem hospitais,
        porque eu consigo afetar mais pessoas com um hospital criado numa cidade?
      - Percebam que esse mecanismo de, se eu tenho muita gente, eu consigo tá
        sempre usando todo serviço na capacidade máxima -> Significa
        necessariamente que eu to gastando menos recursos. Ou seja, gastando
        meno CO2.
    - Imagine o seguinte cenario, eu sou alguem que decide abrir uma empresa, e eu
      estou numa cidade media para menor
      - Eu vou ter dificuldade para encontrar mão de obra qualificada. Por que? ->
        Porque somente cidades relativamente grandes conseguem comportar
        universidades e centro de educação técnicos E por que somente cidades
        grandes conseguem fornecer educacao, na maior parte dos casos
        universiddades sao os maiores empregadores numa regiao, voce precisa de
        milhares de alunos, coisa que n haveria no mundo do governo -> Que é justamente de onde
        essas empresas vão poder puxar a mão de obra. (1 O n explicou)
      - Eu vou ter dificuldade para acesso as cadeias de produção globais ->
        Justamente porque essas grandes cidades se encontram em locais
        estrategicos Ex: Lagos no delta do rio niger, londres as margens do tamisa
        etc (1 O n explicou)
      - Eu vou ter dificuldade em ter acesso a outras empresas, já que uma cidade
        pequena só tem um numero limitado de empresas antes que o mercado fique
        saturado, numa cidade pequena eu só vou poder ter um fornecedor de
        insumos, porque mais de um não tem como a empresa lucrar. (1 O n fala)
      - Ou até mesmo transferir os meus produtos para o resto do país, justamente
        porque eu vou ter que atingir milhares de localidades diferentes agora,
        visto que os consumidores vao estar espalhados (1 O n fala)
      - Isso tudo também funciona para uma empresa estrangeira que precisa se
        instalar no país, se você tem uma supermetropole que concentra todo o
        talento e negocios da região, fica muito mais fácil eu me instalar. Não é
        dificil portanto entender porque todos os bancos estrangeiros quando vao
        querer fazer negocios na uniao europeia vao para Londres.
      - É um ciclo vicioso portanto -> Você aumenta o número de empregos num local
        -> As pessoas vão pra lá -> O fato de terem mais pessoas -> Torna o local
        ainda mais atrativo.
    - Isso é particularmente importante em um país subdesenvolvido como a moção
      - O que é um pais subdesenvolvido? É um país pobre, que não tem condições
        materiais de fornecer uma vida digna para sua população
      - Portanto o foco deve ser antes de tudo como esse país vai conseguir sair
        do ciclo de pobreza, e para isso ele deve conseguir fornecer os melhores
        serviços com o menor custo e conseguir crescer economicamente, justamente
        fomentando negócios
    - Algumas pessoas vao ser deixadas de lado?
      - Por exemplo pessoas com familias já estruturadas e que portanto não
        conseguem se deslocar para tentar a vida nessas grandes cidades
      - SIM
      - Entretanto nós acreditamos que no comparativo nós vencemos esse debate
      - Por que?
        - 1 - Nós estamos falando de mais ganho no geral, porque se com a mesma
          quantidade de recursos finitos eu consigo melhorar a qualidade de vida
          de mais pessoas. Pessoas essas que nós não acreditamos que o governo
          possa prova que são menos importantes do que aqueles que se encontram
          mais afastados.
        - 2 - Mesmo se a gente assumir que eles sao mais importantes -> No nosso
          mundo o que nós teriamos é na verdade uma melhor qualidade de vida para
          essas pessoas, porque a gente vai ter o que acontece toda vez que um
          país se urbaniza, os filhos das familias vao para as cidades em busca de
          melhores condicoes de vida, e ao conseguir isso eles passam a enviar
          dinheiro para suas familias, e isso só é possível com essas cidades
          sendo muito mais capazes de fornecer riqueza do que várias cidades
          medias espalhadas pelo paísl.
        - 3 - Essas pessoas que nao tem condicoes de se movimentar para as cidades
          no primeiro momento, isso só vai acontecer a curto prazo, porque a longo
          prazo seus filhos vao passar para essas cidades, e vao formar familia
          lá, ou seja esse problema depois de uma geração ele desaparece completamente.
