#+TITLE: Debate_03

- Mulheres menos favorecidas n tem condicoes de arcar com isso
- No final das contas exclui todas que nao se encontram no padrao
- Nao resolve o problema, porque assumi que os homens continuam sendo os
  definidores da mulher subir na vida ou nao
- Cria rivalidade feminina
- Exclui outras correntes de feminismo, porque essa tem broader apeal das
  grandes marcas
- Mov feminista se focar a infraestrutura da sociedade do que a superestrutura,
  traz outras pautas secundarias(Bota em foco)

* Case
- Afirmação Central -> O lipstick feminismo necessariamente implica em uma
  exclusão das outras pautas de feminismo, relegação delas a espaços de baixo
  acesso, exclusão de mulheres e numa deturpação dos valores do feminismo
- Um disclaimer -> Nós acreditamos que a mera existencia dessa narrativa, que
  embora no primeiro momento não obrigue todas as mulheres aderirem, uma vez que
  a narrativa se desenvolve, ela acaba por obrigar as mulheres a aderirem.
- A SEXUALIZAÇÃO OU A TRADIÇÃO NÃO DEVEM SER O PONTO DE UNIÃO DENTRO DO
  MOVIMENTO FEMINISTA, AS MULHERES JÁ TEM O SEU ELO:  A OPRESSÃO é implausível
  pensar que as mulheres não vão ter com o que se unir
e ela é ainda muito mais efetiva e inclusiva dentro do movimento
- Por que ele exclui outras pautas?
  - Quais sao ascaracteristicas?
    - Utilizacao maquiagem
    - Roupas sexualmente apelativas
    - Sexualidade no final
    - O que tudo isso tem em comum?
      - Tudo sao coisas que envolvem grandes empresas, grande capital, e
        midiatizacao do feminismo
      - E isso é essencial porque é a partir disso que esse feminismo toma o
        lugar dos outros, e foi algo que o 1 GOV nao trouxe.
      - Pq?
        - Pq tudo é algo que pode ser vendido
        - Não existe nada no feminismo negro, que possibilite a Avon, Natura,
          L'Oreal, consiga vender não só enquanto produto, mas enquanto narrativa.
      - Qual a consequencia?
        - As empresas empurram guela abaixo o feminismo que mais lhe convem
        - Outras vertentes sao excluidas
          - Radfens
          - Feminismo negro
          - Feminismo colonizado etc não tem esse appeal
- E qual o problema disso?
  - Porque ele faz com que as pautas do feminismo se tornem coisas secundarias
    - Nós concordamos que a mulher deve poder vestir a roupa que quiser
    - Nós concordamos que a mulher deve poder usar maquiagem e se sentir bem
    - Entretanto, nós acreditamos que num contexto de recursos finitos, é
      preciso lutar pelo mais importante
      - Coisas que nós consideramos mais importantes?
        - Diferença salarial
        - Violencia domestica
        - Lutas de mulheres nos paises subdesenvolvidos
          - Ex: Mulheres no Paquistao que só querem estudar
    - E nao só isso, como as pessoas que passam a controlar esse feminismo, tem
      todos os interesses do mundo de efetivamente impedir o avanço desses
      outros feminismos
      - Por que?
        - Por que esses feminismos envolvem acabar com as opressoes em outros
          campos das vidas das mulheres, e que na maior parte das vezes essas
          grandes empresas se alimentam desse tipo de exploracao, ou seja, é o
          mesmo que você dar controle do movimento abolicionista para um senhor
          de escravos.
        - A Zara nao tem interesse na luta das mulheres por melhores condicoes
          de trabalho, justamente porque eles se aproveitam desse trabalho
          escravo pra poder vender camisa escrita Girl Power.
        - Ou seja, nao só nao ajuda as outras lutas, como efetivamente atrapalha elas.
  - E por que é mutualmente exludente?
    - Se fosse possível lutar por tudo ao mesmo tempo, tudo bem
    - Não teria problema nenhum, mas mesa, note a importancia portanto do
      mecanismo de roubo da narrativa por grandes empresas.
    - Entretanto, a partir do momento em que o que está sendo midiatizado, uma
      jovem de 15 anos quando entra na internet, é aquilo que ela tá vendo pela
      primeira vez é esse tipo de feminismo, necessariamente as mulheres que estao sendo
      introduziadas ao movimento passam a ter aquilo como norte
      - Embora em certos casos ela possa ser mudada -> A gente tem que entender
        que é muito dificil o ser humano mudar de opiniao -> Por  dois mecanismos
        - Confirmation bias -> A gente acaba por considerar verdadeiro tudo que
          vai encontro com nossas ideias e como falso tudo que nao vai
        - Todo ser humano se considera enquanto ser moral -> Mudar de opinião,
          necessariamente implica na mulher ter que admitir que todo esse tempo
          ela estava errada.
        - Portanto a primeira introdução é essencial.
      - Quando caso não fosse midiatizado de nenhuma forma, elas teriam essa
        introduçao em outros campos
      - Universidades
      - Nas escolas
      - Centros comunitarios
      - Grupos de mulheres etc
      - Ou na propria internet
  - Qual os impactos pratica na vida das mulheres?
    - Nas mulheres que conseguem se encaixar nesse feminismo lipstick
      - Leia-se
      - Mulheres que tem condições de atender esse padrão da industria da moda
        - Elas passam a acreditar que estao fazendo sua parte, quando na verdade
          estao se subjulgando a uma industria da moda, QUE NA MAIORIA DAS
          VEZES, SAO CONTROLADAS POR HOMENS
        - Ou seja, ela vai passar a vida dela toda lutando pra poder usar
          minisaia do trabalho, e não vai estar olhando pro fato do colega de
          trabalho dela ganha mais pelo mesmo trabalho.
    - Nas mulheres que não se encaixam no padrão
      - Você tem o problema das mulheres que se encaixam, elas tao achando que
        algo tá sendo feito, quando as coisas que realmente as oprimem está
        sendo continuamente criado
      - Você cria uma espécie de frustração, porque se numa narrativa menos
        mainstream, para ser feminista basta que uma mulher se veja enquanto
        mulher, agora ela precisa se considerar um ser sexual. Só que ser um
        ser sexual não é algo que abarque todas as mulheres
        - Se você for gordinha
        - Se você não for branca
        - Se você não tiver condicoes de comprar tudo que esse lipstick
          feminismo exige.
        - Iso significa portanto que essas mulheres se sentem excluidas, num
          mundo em que todas as vertentes tivessem igual espaço, isso nao seria
          problema, mas a caracteristica marketavel do lipstick impede isso.
