#+TITLE: Debate_04
* 1 Gov
- Pais beligerantes, pipipopopo
- Nós não acreditamos nesse ponto de que a Russia vai entrar em guerra com a
  Arabia Saudita, porque simplesmente isso n é plausivel, a queda dos preços é
  muito mais algo feito por AMBOS OS PAISES para acabar com a produção de xisto
  de petroleo, feito pelos EUA. Eles já trabalharam juntos antes pra fazer a
  MESMA COISA em 2014, quando a crise da venezuela começou.
* Case
- Quais os interesses do ocidente?
  - O ocidente quer antes de tudo um oriente medio estável
  - No pior dos casos, o controle das armas que sao usadas, faz com que o
    ocidente tenha o minimo de capacidade de interferir nas questoes externas da
    arabia saudita
  - A segunda coisa que o ocidente quer é uma Russia e China que não sao capazes
    de exercer a sua hegemonia na regiao
    - Seja no regime de Assad no caso da Russia
    - Seja no apoio ao regime do paquistao da China
- Vamos fazer comparacao de cenarios
  - Cenario em que essa armas deixam de ser vendidas
    - ALgumas premissas
    - Arabia Saudita tem muito dinheiro
      - Eles nao vao deixar de produzir petroleo, eles nao vao deixar de ter reservas
      - Isso significa que eles vao buscar essa capacidade belica em outros locais
      - Leia-se Russia e China
- Por que nos acreditamos que russia e china sao piores?
  - Ambos os paises nao tem opiniao publica
  - Mecanismo
    - Assumimos que Estados sao entidades sem moral
    - Procuram seus proprios ganhos
    - Seus proprios interesses
    - Entretanto, pessoas tem moral, sejam os governantes e sejam a opiniao publica
      - A opiniao publica é o que freia os paises de agirem completamente
        enquanto maquinas utilitaristas
      - Russia e China n tem isso
      - Logo, Russia e China tem uma tolerancia maior a violacoes aos direitos
        humanos, em suas fronteiras e nesse caso importante nas fronteiras alheias
        - Ex: China financiado o gneocidio de darfur em 2010
      - Obs: N estamos querendo dizer que o ocidente é bonzinho e maravilhoso.
        Eles fazem coisas horriveis, MAS NO COMPARATIVO isso é consideravelmente mitigado.
    - QUais as consequencias
      - O MINIMO DO MINIMO DE INFLUENCIA BENIGNA que o ocidente tinha, acaba
        completamente a partir do momento em que eles nao tem poder de barganha
      - Esses regimes podem entao se sentir com menos freios, para amplificar o
        massacre de Houthis no Yemen por exemplo.
      - O cenario atual é ruim, mas pode ser pior
      - O caso da Russia é pior ainda, porque a gente vai ter o segundo maior
        exportador de petroleo do mundo(Russia), tendo alto poder sobre o maior
        exportador(Arabia Saudita) -> Isso significa necessariamente que agora a
        gente tem um pais também beligerante, também autoritário, que agora
        controla não só a sua produção de petroleo, como também a produção de
        outro pais. -> Se antes a gente tinha o minimo de estabilidade porque
        ninguem tinha muito poder sobre tudo, agora a gente não tem mais isso.
- Por que nos acreditamos que o cenario onde a arabia n cosnegue essas armas é
  pior ainda
  - Nós acreditamos que Estados sao mais violentos quando tendem a se sentir acuados
  - Ex: Aleamanha nazista tinha uma ideologia de que o bolchevismo ia dominar tudo
  - Ex: A Ameaça do comuinismo EUA decada de 60
  - Ex: O proprio ataque do iran as instalacoes sauditas envolvia eles se
    sentirem acuados pelas movimentacoes militares do EUA, e pelo ataque amissil
    matando o lider da guarda revolucionaria, tudo isso sao demonstracoes nao de
    força mas de fraquezz
- Qual a consequencia?
  - Estados na busca de poderem se sentir seguros acabam por tomar medidas
    violentas preventivas
  - Uma Arabia Saudita que nao se esnte protegida pela aegide do Ocidente, é um
    arabia saudita que se sente acuada
  - Coisas que podemos portanto acreditar que seriam mais comuns
    - Arabia Saudita financiando grupos rebeldes em outros locais
    - Tomada de governos locais
    - Uma postura mais agressiva dentro do mercado global de petroleo
    - E no caso extremo, o desenvolvimento de um projeto nuclear
  - O fim de acordos de armas, é uma demonstracao de saida do ocidente de
    proteger a arabia saudita
  - A Arabia Saudita, na década de 60/70 financiou o projeto nuclear do
    paquistao em troca de expertise e de uma promessa de ajuda em um futuro
    projeto saudita
  - Isso é documentado
  - A partir do momento em que a Arabia Saudita se vê sozinha diante de uma
    ameaça Iraniana, ela vai passar a tomar das mesmas táticas feitas pelo Irã
    - Leia-se movimento para produzir uma arma nuclear
- Em última instancia nós não acreditamos que a moção tenha capacidade de
  mudar os abusos cometidos pela arabia saudita contra os seus cidadãos
  - Seja tratamento com mulheres
  - MInorias religiosas
  - Jornalistas etc
  - No pior dos casos isso aumenta, porque a casa real vendo-se acuada, precisa
    demonstrar forças justamente para evitar ameaças externas
  - E mesmo se a gente assumir que vai melhorar
    - A gente tem que entender que o lobby armamentista é talvez o lobby mais
      forte em washington
    - O que isso significa?
      - Que a partir do momento em que a gente impede a lockheed martin, a
        northrop, a boeing vendam armas para arabia saudita
      - O que vc vai ter é que a gente vai escoar essa produção para outros
        conflitos, seja na africa, seja em outros paises do oriente medio,
        justamente pq eles vao ter essa avenida de comercio fechada.
