#+TITLE: Debate02

* PM - Takerou
- Cultura pop se faz oir arterfatos culturais de consumo em massa.
- Representatividade representacao de certos grupos é condensada numa unica entidade, numa personagem por exemplo.
- Intrinscamente ruins
  + Lesbicas > Quando a lesbica morre isso no fundo representa, redencao pelo seu pecado que seria a propria homosexualidade, no fundo essa representacao é algo profundamentente LGBTfobico, com origens religiosas em que um individuo LGBT só teria a sua propria morte como caminho para se redimir dos seus pecados.
  + Gays -> LGBTfobico
    - Representacao confunde genero com sexualidade, feminilidade é algo promiscuo, relacionado ao arquetipo da serpente da eva, já começa profundamente machista, essa esteriotipacao se associa com os gays, criando-se entao algo que já começa machista e transforma-se profundamente LGBTfobico
    - Viloes feminilizados > representa um desvio, que se manifesta na vilanidade
- POI Joao Pedro -> Como que vai trazer o onus representatividade seria pior do que com esteriotipos que vc considera ruins ->
- Impactos -> Intrinsecamente ruins e negativas > Colocam essas pessoas em caixinhas, limitam a socializacao das pessoas, por meio da disseminacao em massa esses esteriotipos e imagens enviesadas vao se inputando na cabeça das pessoas.
- Pq nosso cenario é melhor?
  + 6 minutos
  + permitiria que o povo criassem essas imagens, nao baseado em imagens enviesadas, e em preconceitos, as pessoas criariam a sua imagem empiricamente, por meio da socializacao, criando-se entao um ambiente de socializacao mais saudavel, tanto pro LGBT que nao sofre na colocacao em caixinhas. Base
* LO - Grp
- o movimento quer se acolhedor, angariar pessoas, ser normatizador, pessoas sejam tratadas cmoo normais
- é melhor narrativizar algo equivocado do que demonizar algo complexo
- ter palco é mais importante num mundo unicultural.
- se eu vejo alguem participando de umna narrativa, dificuldade, dentro de uma serie eu vejo que aquela pessoa tem poder, eu posso parecer com aquilo, eu me sinto empoderado, o worst case, a pessoa que é contratada nao é LGBT(isso n é worst case) a pessoa pode ser um membro da comunidade LGBT, mesmo esteriotipada pode iunfluenciar de formas de poder, dar palco pra minorias.
- poderia ter visibilizacao de alguem, a gente prefere um mundo em que seja esteriotipada, mas a pessoa que é contratada.
- worst case pessoa é desconciente da pauta
  + comunidadde lgbt consume mais a cul.tura pop que qualquer pessoa, pacto mais coeso, mais expressividade, pauta minoritaria, nada é mais facil, sempre vao cobrar que acoes sejam mais condizentes pra sua pauta. Jean Wyllis representava a comunidade LGBT, a gente pode mesmo que ele seja um agente ruim, mais conversacao, ou credibilizacao, transformar aquele agente esteriotipado, a gente pode inclusive ver se aquilo é coadizente, pode conversar agora de maneira mais direta. ver que um LGBT existe e tem poder de fala.
- POI 2G -> Mais empoderamento, vcs precisam defender uma representatividade problematica -> Como reduzo o onus, empresa surfando no hype moral, midia quer agregar o maior numero de hype, vista como morais, natura aumentando as vendas dela com a tammy gretchen, agrega um publico a comunidade LGBT, sofrer cobrança dessa comunidade, esse esteriotipo nao confirma o que nos realmente somos, a gente pode fazer algo que eles querem, um agente que pode ser instrumentalizado, pelo menos no nosso cenario a gente tem uma conversacao sobre isso.agregar mais pessoas.
- essa cobranca gera ressignificacao
  + no nosso cenario a gente tem uma ponte para ssociacao, no worst case nos vamos ter noçao de existencia e normalizacao, eles podem ser esteriotipados, mas ainda estao na mesma narrativa e papel, eu consigo entender o que ela está lá, o dano que vc tem é as pessoas desconhecerem, e afirmarem por valores proprios, valor biblico, merecem morrer.
* DPM - Victor
- a visibilizacao permite um incentivo e aceitacao para esses grupos, essa visibilidade promovida pelo pink money, promover esteriotipos mais lucrativos, ele sempre vai estar presente, nao sao visando a promocao mas o lucro das empresas, isso nada difere da promocao que as religioes promovem de esteriotipos de LGBTQs.
- no caso das midias pops elas recebem a vantagem lucrativa de representar de como elas querem.
- se for mais luicrativo promover um trejeito, aquilo vai ser promovido(pq é provavel)
- se eu sou gay e sou serio, a primeira impresao só por saberem que eu sou gay, o meu contratador nao é serio.essas pequenas caixinhas limitam a vida e comunidade.
- POI 1O -> No nosso cenario o contratador vê como ele quiser, ou de maneira oculta, herege ruim > a muito tempo na grecia antiga era comum a sexualidade ser aberta, a representatividade forçada até dá força para religioes, elas colocam como gays numa caixinha, religioes passam a promover dentro dos seus tempos, reliigoes limitam.
- é mais lucrativo promover de outra forma?(pq?) -> a primeira impresao vai ser de forma midiatica, nao por um amigo ou amiga.
- equilibrio da representatividade pop, promocao > esteriotipos sao caixinhas que limitam. nem todos os grupos tem ideias iguais ao que a midia promove, nao conseguem igualmente influente do que a midia passar sua ideia para sociedade. limitar a midia cada um pode promover quem é por dentro.
- nao representar forçadamente para permitir o povo nao criar esteriotipos, forma empirica, nem todo esteriotipo é ruim, mas todos eles prejudicam os gays. é inevitavel que a tentativa forçada de criar esteriotipos.
* DLO - Pazin
- afetadas pela cultura pop pessoas jovens, 30/40 anos. tem uma cabeca minimamente aberta.
- pq que o movimento lgbt existe?
  + comunidade lgbt já existe mas nao estava unida, mas n tinha palco, n tinha capacidade de organizacao
  + objetivo do mov é juntar e agregar, pra promover direitos, o meio pelo qual mov lgbt faz isso, visibvilizacao, só existe pra dar visibilizacao, palco e voz é muito importante, pessoas sirvam local e palco para falar, mesmo que xista uma estigmatizacao, poder que é representado.
  + cognitive ease
    - eu vejo que as pessoas existem, independentemente de eu ser a favor ou nao, eu sou obrigado a ver eles, eu sou forçado a ver, essas pessoas estao aparecendo ali, mais filmes, eu vejo mais vezes, eu me familiarizo, quanto mais eu vejo algo mais eu tenho conciencia inconsciente, aproximo de entender que aquilo é aceitavel. situacoes que vemos como familiaridade
  + no melhor caso a pessoa esta com uma mente aberta, consegue ver debates nas redes sociais, busquem esse debate, busquem se aprofundar, no pior cenario uma pessoa que nao quer aceitar, a pessoa nao aceita de qualquer forma, mesmo sendo preconceituosa, ela ta vendo que existe uma mudança, uma pressao social pra aquela pessoa nao externar aquele tipo de coisa, debate das redes sociais, n consigo fugir desse debate, o grupo sao os mesmos que estao na cultura pop, toda vez que a gente tá numa manifestacao, as pessoas estao debatendo nas redes sociais, eu consigo ter um acesso a esse debate que eu n teria. consegue promover esse debate
  + poi 2g -> simplesmente pq vai ter aproximacao, é mais provavel que isso diferencie > no status quo o estigma ja existe, nao dao nenhuma alternativa, retiram a exposicao, no cenario de vc é um status quo de moralismo de pessoas mais conservadores, nao tao vendo lgbts, nao tem acesso ao debate publico, no nosso por mais que algum tipo de estigmatizacao os prconceitos nao ficam velados, os preconceitos nao sao gerados pela cultura pop(boa), vcs nao mostram como eles podem se modificar.
  + mesmo que eu amente a estigmatizacao, dar visiblidade, possibiltar o debate, mostrar que está sendo mainstream.
  + os lgbts se sentem mais representados, o pantera negra, assim como o filme da beyonce, as pesoas se verfem na cultura, se vrem como herois, dar exemplo, essa representatividade nao existe no cenario de vcs.
* MG - victor
- a gente concorda com o que a 1op falou, essa questao de inserir os gays mas que permitisse o debate, foi muito bom para os gays, so que o status quo hoje em dia é diferente nos anos 80, é que eles já tem uma boa representatividade na sociedade, papa falando do papa sendo aceitado, a gente já tem uma representatividade muito grande, como continua com o esteriotipo ele vai fazer com que piore a imagem dele.
- dificil quebrar um esteriotipo, muito complicado, o esteriotipo levado como mulherzinha, presente no inconsciente popular ate hoje, é uma coisa que pega, Ex: do crô em fina estampa, o namorado ninguem lembra. quando tu foge do padrao, ele fica muito mais inconsciente coletivo
- assimilacao no inconsciente desses esteriotipos, incoscinente coletivo
  + quando a gente escuta muitas vezes alguma coisa, associar gays a serem uma pessoa desse tipo, ele vai associar gay com o uma mulherzinha, n vai olhar como igual, a gente tem isso entrando no inconsciente coletivo. perpetuacao dos preconceitos ao longo das geracoes.
- poi pedro > nao é mocao de medida, a gente tem varios mecanismos de atores sociais, pq nao pode ser mudado -> justamente por causa da psicologia, as coisas entram no insconsciente coletivo da sociedade, vc assimila com isso. vai continuar tendo uma discussao de representatividade.
- impacto maior dificuldade dos homosexuais se assumirem, nao se identificam com essa maneira esteriotipada, será que eu sou gay mesmo, vc nao se vê enquanto gay,
- preconceito com o mercado de trabalho, quer ser tratado de igual pra igual(lol 1g)
* MO - joao pedro
- já estamos estabelecidos numa sociedade hteronormativa, brasil um dos paises que mais matma gays, homosexualidade ainda é crime.
- 1g esteriotipos negativos dessas pessoas
  + retirada da representatividade, as pessoas vao continuar com impressoes negativas, imagem equivocada, é uma visao que nao é desses esteriotipos, é de decadas em que a igreja catolica terminaram como um pecado uma questao que vc tem que viver em celibato, vc deve negar seus desejos.
- 2g
  + que gay é conectado a feminilidade, as lesbicas sao conectadas ao fetiche, as lesgbicas sao fetichidas.
  + questionamento sobre sexualidade é super normal
  + falar que gays querem ser iguais a todo mundo, ele fala algo de black lives matter, n entendi.
- feminilizacao nao é um fator negativo, existem muitos gays que sao femininos, a grande maioria, eles sao a linha de frente pra bater com o preconceito, isso é um direito que eu tenho.
- no meio gay existe uma homofobia por baixo dos panos, os gays que sao masculinos, eles sao super valorizados, eles sao tratados como algo mais sedutor, é um fetiche que existe, mas isso nao tem nada a ver com representatividade de gays, a representatividade é positivo mas nao deve ser a unica
- bury your hands foi feito para evitar que autores, e serem atacadas, forma de escapatoria, valcula de escape, retirar representatividade da cultura pop, gays nao assumidos encontram coragem na cultura pop, forma de normalizacao da homoafetividade, a gente ta falando de uma representatividade que abrange muito mais.
* WG - eduardo fabres
- disclaimer > as culturas pop estende influencia para populacao mais velha(pq?)
- a existencia da influencia desses movmientos numa populacao mais > um inconsciente > vc nao ver como uma pessoa normal > tá representando o cro, e o seu pai vai lá e debocha do cro, vc reforça preconceito.
- memoria coletiva
  + pop mais velha vai reforçar os preconceitos, e vai reforçar os preconceitos
  + pessoas mais jovens vai tirar o processo de assimilacao, como as pessoas tem referencia a ti, o que tá sendo representado na televisao n é positivo
- assimilacao ao desumano
  + a pop lesbica é associada a tristezxa, mesmo que elas sejam sexualidas, ocorre processo de desumanizacao, gay é extremamente desumanizado, a nossa consequencia clara, dfificuldade de ver um ser movimento, cria esteriotipos, o que aquela popualcao ta falando agente nao leva tao a serio, a gente reforça os preconceitos, dificuldade de aceitacao que vem de um processo que reforcá preconito
- 1op
  + cenario de conversa > esse nao é o pnto fundamental do debate, isso pode acontecer em ambos os cenarios, cobrar a inexistencia de uma representatividade,
  + conseguir resignificar a pauta > victor apresenta mecanimsmo de assimilacao do preceontio
  + mesmo se eles estarem lá eles vao estar fazendo um bom papel > ainda que a gente tenha a associacao, n é necessariamente isso, gerar conscientizacao é algo que gera, hoje em dia  agente tem mensagem correta. n é uma dependencia necessaria
  + mecanismo psicologico de familerizacao > isso n necessarimente é verdade, familiraziacao acontece quando o hmem hetero ve o homem hetero, diferenciacao homem hetero ve um homem gay, o que os diferencia é a masculinidade.
  + POI Pazin -> Preconceito nao é controlado, como vcs promovem a mensagem se nao existe felipe neto > vcs nao provaram pq nao existe felipe neto, a populacao lgbt funciona por si.
- 2op
  + todo mundo concorda que representatividade importante,
* WO - gabriele
- 1g
  + nao traz nenhum argumento qual seria a alternativa(na vdd elas trazem)
  + a gente poderia ter um regreso do que a gent tem hoje,
  + joao pedro fala da crescente dos lgbts na cultura pop, cresceram a partir do esteriotipo, esse cessamento de representatividade nao se mostra como benefico.
- 2g
  + desumanizacao da pop lgbt, o 2g ta fazendo uma desumanizacao da comunidade lgbt, pq tratar como mulher seria uma coisa ruim
  + poi eduardo > a gente n defendeu que isso é verdade mas que isso processo de representatividade -> mas ao trazerem sem explicar qual foi p pale deessa desumanizacao vc pode sim colocar implicitamente que essa desumanizacao acontece dentro do que vcs estao falando.
  + isso acontece quando vcs colocam o cro, o cro é uma figura esteriotipada, vcs nao colocaram ele como uma pessoa que aparece muito na novela, pq ele nao seria aceitavel dentro da comunidade lgbt(wtf)
  + a gente ta falando que exsite essa representatividade mas que nao sao a melhor maneira,conhecer empiricamente a comunidade LGBT, pq as pessoas se fecham nas proprias bolhas, é o que a gente tem hoje mas nao tem coisa boa
  + crescente dos papeis lgbts atraves dos esteriotipos que a gent tem hoje, atraves dos papeis que a gente tem, a gente tem uma grande ascencã́o de outras figuras lgbt que promove expansao da representatividade, sem excluir uma parte que mostra, uma parte que é muito importante(gays feminilizados)
  + podendo trazer um retrocesso de direitos e visiblidade.
