#+TITLE: Debate01

* PM - GRP
- FHC Governo - LRF, maior atrativo de investimento, desemprego altissimo, divida absurda com FMI, aumento de imposto. Aumento da divida externa no geral, dificuldade de estabilizar a moeda.
- Numero de agentes estaveis
  + Tem o EUA e o Mexico, EUA gerador do consenso de washington, principal atrativo do cenario internacional, a gente poderia comprar e vender produtos com eles. A gente agora é participante do mesmo projeto de vcs.
  + Comprando coisas mais caras - Melhor comprar mais caro, tendo consecao e liberdade de troca, EUA maior credor do FMI, conversar  divida externa de maneira mais melhor de bom. A gente pode reduzir a divida, o que aumenta os impostos
  + AGENTEs estaveis tem mercados estaveis -> As multinacionais produzem mao de obra, e produtos, mais estabilizada, podem confluir os lucros e as despesas, se eu to em todo canto, au amortizo os danos.
    - As multinacionais querem aprimorar o pais, pq eu śo posso extrair mao de obra se eu ajudo a mao de obra
    - Só extraio se a estrutura for estabilizada, com ja vai ter um alinhamento geopolitico, os recursos podem ser direcionados de maneira cara, elas vao agora estruturar melhor esse pais para poder lucrar, de maniera indireta por competicao interna.
    - Mercado interno podem acabar com o monopio por meio de competicao, eu preciso abrir o mercado que seja competitivo o suficiente pra nao dar lucro pras multinacionais, se eu sou o estado, faz com quer eu compita internamento.
- Pq nao rola no mercosul
  + N sao estaveis, desenvolvimento semelhante ao brasil, ja eram endividados e se endividarem mais
  + Disclaimer: n vamos se distanciar do mercosul, mas nao necessariamente a gente seria inimigo do mercosul, ainada pode ter uma asencao internacional, ainda pode comercializar com eles. agora a gente pode fazer isso melhor pq tem um desenvolvimento economico melhor. Trickle down.
  + mercado muito mais estavel e consolidado pode endurecer nosso mercado, direta ou interna.
  + como q tava o mercosul dessa epoca?
- pq nois ganha o debate? aproximacao ideologica com paises com mais estabilidade, no ganho pragmatico a gente tem todo esse desenvolvimento, alem disso a gente pode manter as aliancas com mercosul, mas nao tem todos os beneficios exclusivos do nosso estado.
* LO - Dafne
- metrica a longo prazo, subordinacao economica, politicas economicas, entrada de empresas e tals
- perfil economico
  + eua com mexico na nafta, entre um pais menos poderoso e um mais poderoso, basicamente vc tem um cenario do eua se utiliza caracteristicas economicas, p[ra ] se utilizar da mao de obra barata pra colocar empresas, coloca um propositov muito especifico, acaba gerando empregos de forma limitada, acaba tendo algum nivel de geracao mas sao de má qualidade.
  + sucateamento das empresas nacionais -. quando tem a entrada de produtos em sen entrada tarifaria, produtos entrariam aqui com precos muito mais baratos, fazendo com que nossas empresas morram, nossas empresas tenham menos vantagem, viria com competidor externo, n incentiva, vc mata elas em primeiro lugar, empresas americanas n tem interesse, sufucamente das empresas, n tem incentivo apra empresas se desenvolvmerem.
  + o brasil exportando muito mais comodities, cenario em que vc nem tem tanto incentivo, incentivo para exportar comodities, soja e tals, crescimento do agronegocio, desinstrulizacao, vc incentiva esse cenario de criacao de um pais qeu se pauta na agricultura, o que amta a agricultura familiar
  + trickle down é algo que n é comprovado, eles n explicam como isso melhora a vida das pessoas, o que a gente ta querendo dizer as empresas que se instalam aqui n tem interesse na infraestrutura daquele pais, limitado para investir na infraestutura que beneficia ela.
  + vc teria um enriquecimento da classe mais alta e um acirramento da classe social mais pobre, fuga de capital do proprio brasil, governo brasileiro ficaria mais fraco ainda, enrriquecimento de uma calsse muito especifica, quando vc liberaliza, vc teria uma enfraquecimento do governo, vc teria uma menor possibilidade de taxar essas empresas. e a gente ta falando do cenario mais desejavel para desenvolver sua industria, que ele n pode competir, e é muito mais facilidade de comprar esses produtos, vc n poderia ter essa taxacao dessas empresas, n teria a mesma capacidade de melhorar essas estruturars, condicoes estruturais.
  + no mercosul a gente tá num lugar de poder muito maior, sempre sob influencia dos eua, comprometem nosso desenvolvimento estrutura, situacao mais confortavel de exportador de comodity, se tuliizando dessa mao de obra barata
  + cria estruturas deficientes a longo prazo que seriam a longo prazo ruim.
* DPM - Pazin
- pq no nosso cenario tem um bloco economico que é mais forte, mais prospero, fazer com que seus paises tenham uma estabilidade economica maior. geram maior prosperidade mesmo nos paises subdesenvolvidos
- esses paises a diferenca de desenvolvimento é positivo
  + os paises subdesenvolvidos tenham um mercado maior, nos temos mais paises maior demanda, incentiva uma producao maior, faz com que a gente tenha nichos de mercado que possam ser aquecidos, venda de produtos fundamentalmente, como que isso acontece? esses paises de desenvolvimento difererntes tem necesidades diferentes, n é um pais qeu vai ter a mesma producao que o pais, brasil consegue exportar soja, essa exportacao consegue suprir uma necessidade que os EUA nao consiga suprir internamente, quando a gente tem essa disparidade a gente consegue vender muito mais.
  + quando nos temos paises subdesenvolvidos que precisam desass relacoes, paises que sao subdesenvolvidos, esses paises tem necessidades parecidas com o brasil, o fato que quando a gente tem semelhanca economica, n conseguimos nos complementar enquanto economicas.
  + se eu to exportando soja, cafe, petroleo, eu consigo fazer com que aqueles paises comprem, mercado enorme, isso nos gera, aumentar a arrecadacao do pais, possa ter desenvolvimento economico, esses investimento fazemc om que eu desenvolva meu pais.
  + engajando com 1 op -> como capital entra e mata empresas pequenas -> precisam de invesimtneot as empresas pequenas, pra conseguir se desenvolver, o governo só consegue fornecer ese tipo de beneficio, se ele é um pais subdesenvolvido que foi industrializado, quem vai comprar? uma grande potencia que vai produzir aquela comodity, como isso posibilita que eu consiga desenvolver, investir, dar credito, tenha credito, controlar melhor meu sistema monetario, isso faz com que esses gastos publicos necessitam, pequenas empresas tenham poder de prosperar.
  + eu n tenho recurso pra financiar a industrializacao, se essas empresas internacionais n tem intencao pra desenvolver o cenario industrial, ninguem vai, precisa que o estado faça essas modificacaoes. é a partir dai que a gente consegue um cmoercio mais fortalecido, fazendo com que essa geracao movimente, ciclo virtuoso.
  + acontece no cenario de disparidade
  + medidas sociais conseguem funcionar no nosso cenario
    - diminuicao das taxas, o que mais determina é a circulacao de moeda, que eu tenha os recursos necessarios, para que eu possa inv estir nessas medidas, eu consigo fazer com que o desenvolvimento nos podemos fazer com que essa movimentacao interna do mercado e a arrecadao a partir dfa taxacacao dos produtos internos, e dar investinmento em politicas publicas
* DLO - Brenda
- curso pra extrair minerio com mais eficiencia, n tem investimento de fases mais tecnologicas, pouco interessante, competir com eles, eles sufocam essa parte da nossa economia
- ja é tendencia dos paises em desenvolvimento para serem agroexportadores, quandoa  gente se unisse com o alca isso iria piorar, condenar a gente a nossa maneira
- mercado mais estavel, dependencia intensa é problematico, nos condena a maior unicidade economica, o que a gente consegue desenvolver ao longo da ihistoria, é multiplicidade de area que eles inverstem.
- essas relacoes já ocorrem, é um pouco de aumento disso,
- importante esclarecer incentivo para fazer as coisas qeu a gente já faz, ficar preso em agronegocio e comodity, mas é badvibes no longo prazo, destroi com meio ambiente, acaba com recurso natural, inclusive para melhorar qualidade de vida da populacao
- beneficios
  + alca
    - parceiro solido estabelecido, negocios da alca sao bastante convenientes para o EUA, sem circulacao de pessoas, as pessoas sao a força de trabalho, a forca de trabalho é relevante,
    - diminuicao tarifaria
      + os eua conseguiria comprar a nossa soja de uma maneira mais eficiente, o que a gente cvonseguiria, um escopo de produtos industrializados, isso acaba nos condicionando, n é a coisa que majoritariamente consumido n é iphone, sao coisas que veem de outros parceiros, a gente acredita que isso é a maelhor opcao(por que nao tem os problemas do eua)
      + de fato a gente ta falando um bloco de organizacao algo normal -> sem haver relacao de dominancia e poder, zona de disputa de influencia, todo mundo sabe que a gente tem muita coisa para oferecer, producao interessante, é extremamente bom que a gente n esteja na asa do eua, consegue virar uma area de disputa, UE sabe que isso, a CHina sabe.
      + POI(Arhutr) -> Australia e nova zelandia, ricos com comodities -> bastante peculiares, ja tinha uma base grande com ovelhas, situacao diferente, condicionado a esses produtos.
- maleficios
  + alca
    - as ouras potencias, nao conseguem disputar mercado aqui, pq tem beneficios muito grandes pro EUA, posicao muito confortavel, mesmas garantias e incentivos, acontece com o mexico, eua moldou o projeto economico do mexico, esse projeto economico é ruim pq condena pequenas empresas condenadas a sobreviver na base do BNDES.
    -
* MG - Arthur
- paises que vendem produtos agricolas sao subdesenvolvidos e que produtos industriais sao desenvolvidos
  + hoje em dia mudou muito
  + nossa economia é baseada em agricultura e a gente ganha dinheiro pra caralho.
- questao economica
  + produtividade, mtu dinheiro na agricultura, industria e servicos sofrem problema de produtividade, o que o brasileiro faz em 8 horas europeu faz 2 horas, paises que tem tecnologia sao muito mais produtivos, esse problema da tecnologia atenuado importante se a gente entrasse na alca, a gente conseguiria comprar tecnologia de lá, a gente ganha dinheiro produzindo mais com muito mais qualidade.
  + o mexico historicamente nunca foi potencia economica na america latina, entretanto cquando fez parceria economica com EUA, o mexico é tao bom quanto o brasil, mas n tem potencial economico que a gente tem. els usam estigma pra justificar que é ruim pra fazer parceria economica com EUA.
  + alca era uma grande oportunidade aproveitar um boom economico, crescimento global, sobrando dinheiro no inicio dos anos 2000, a gente teve um crescimento economico mas caiu quando o mundo caiu junto, com a chegada de tecnologia a chance da gente conseguir um boom economico, alem de melhorar a questao da agricultura, a gente n só aproveitaria o mercado dos EUA, a gente ia destruir a agricultura dele
  + vendendo tecnologia, brasil maior produtor de tecnolgia agricultura do mundo, embrapa é foda, a gente n só ganha dinheiro vendendo comodity, mas vendendo tecnologia extremamente cara, quantidade de dinheiro absurda.
  + EUA é historicamente desde pos segunda guerra, procurando grande aliado economico, com fortalecimento da UE a inglaterra veio cada vez menos autonomia praa aliancas politicas, EUA n tem um grande parceiro economico e politico, a gente se botar como essa perceiro, o EUA teria uma grande parceria economica com, o EUA bre muitas portas politicas no muindo, facilitaria entrada na OCDE, facilitaria contato com a europa, se a Europa quisesse negociar com o EUA teria que coisasr com alca
  + hoje em dia mercosul tem que sentar pra negociar, todo mundo é muito ferrado, ninguem abre mao de nada, quando a gente tivesse na mesa com EUA, todos paises sulamericanos, se uniriam para defender os interesses da america do sul.
  + forma de melhorar nossa economia.
* MO - Liana
- com alca a gente teria com paises mais desenvolvidos, mercosul paises do mesmo nicho, economias subdesenvolvidas parecidas
- sistema de alavancagem entre paises, em detrimento do alca, zona de conforto, como brasil depende da manufatura canandens.
- logica brasileira, manufatura brasileira é pouca, quando a gente diminui ainda mais as tarifas, facilitando ainda mais a deendencia, com que a gente diminui tarifas, isso vai gerar uma comodidade ainda maior de comodities, e nao foco em producao, produtos americanos e canadenses produzidos em larga escala, o proprio eua já é um grande desenvolvedor, quando a gente escolhe o alca importa manufatura americana. é mais motivo de se manter zona de conforto, produtos baratos, cenario de nao industrializacao, e pq é que é tao ruim a gente exportar somente cmodities? -> todas as comodities tem baixo valor agregado, valor que vc adiciona para cda etapa de producao, tem as peças tem a montagem, varias pessoas envolvidas, um produto n tem eesa cadeira de pessoas envolvidas, adiconar valor a mais, entao a gente tá adicionando menos valor, n tá enriquecendo, desincentivo para a gente comprar isso.
- qual a importancia do mercado proprio consolidado
  + a gente n escolhe o alca, a gente tem mais chances de ter um mercado proprio consolidado, mas a gente n vai ter uma falta total de desenvolvimento industrial, pq q é tao ruim? sao justamente esas comodities, incentiva nosso desenvolvimento tecnologico, gerar tanto emprego, quanto menos valor agregado, a gente tem empregos que geram empregos melhores, mais numerosos e pagam melhores, a gente n depende de outros paises, a gente pode ter varios problemas aqui.
  + um pandemia, entendi nada, ate questoes
  + pq a gente escolhe o mercosul?
    - vai ter alguma troca, a gente n tá ficando na dependencia, percebam hoje em dia esses paises desenvolvidos continuam comprando comodities, independendo do que, esses paises desenvolvidos continuam comprando as nossas comodities, vale a pena, qpe vao vender por uj valor muito mais alto, alavancagem em conjunto, alguma importancia economica maior.
    - quando o mercosul, a gente n quer mais desestimulos para industrializacao, a gente contina exportando cmoodities,
    - a gente mostra todos os mecanismos(na real só um)
- POI 1G - Multiplicidade n acontece em nenhum cenario, necessidades sao as mesmas- > n verdade nao
* WG - Vitoria
- cenario retrospectiva
  + esse ponto seria negativo, tem que mostrar como seria neutro ou positivo se mantivesse no mercosul
- 1op
  + mexico, sim o mexico melhorou com ajuda dos eua, mexico n tá perfeito, mas mtu melhor que antes, potencial muito menor que o do brasil, mexico tem um problema ser muito proximo dos eua, fuga de pessoas
  + a gente vai ter um problema tecnologico, n desenvolver a nossa tecnologia, mercosul n ajudou a gente a desenvolver nenhuma tecnologia, as poucas coisas que a gente desenvolve pq teve muiot incentivo estatal, ex: caminhao, n tem uma economia desenvolvida, mercosul comprar com a china inves de comprar com o mercosul.
  + qual o problema do cmodity, ela nao responde -> crise ecologica muito grande, os commodities vao se tornar cada vez mais importante, e a tecnologia pra desenvolver esses produtos, o queia acontecer é que o EUA ia depender da gente pra comida, o que é positivo pra gente, consegue ter mais dinheiro,
  + inves de pagar taxas de importacao, comprar tecnologia, poderia comprar maquinario, comprar coisa pra caralho, facilitar focar ainda mais em comodity, na tecnologia de comodity.
  + mercosul n melhorou tecnologia brasileira, desenvolveria tecnologia.
- 2op
  + comodity é ruim
  + a gente n vai ter incentivo de melhorar tecnologia, zona de confoto que é comodity, o que a gente vai fazer é deixar comida mais barato, transporte mais barato, producao mais barata, vamo produzir meios de transporte, embalagens e todo dipo de coisa. rede ao redor dos comodities, a gente consegue vender essa rede, muita tecnologia em transporte.
- POI 1OP -> mexico cresceu mas muito menos que qualquer tecnologia do mesmo tamanho -> mexico n tem potencial, n tem espaco pra trair petrleo, n tem potencial igual outras economicas america latinas.
- 1g
  + msotrar como tecnologia vai melhorar, n dependendo de empresa, melhorando as coisas que a gente já faz bem, alem disso a gente mostra como politicamente vai ser muito positivo, relacao politica com outros paises.
* WO - Rached
- 1g
  + multinacionais, beneficiando se as empresas americanas -> situacao pior do que antes, as multinacionais exerceriam uma competicao, desigualdade, mercado interno muito menos desenvolvido
  + pq multinacionais tem tantas vantagens ->
    - investimento do governo
    - jutos mais baixos seguranca
    - importancia proprio pais
    - produzir em maior escala
    - cenario pior que o que a gente tem hoje
    - consequencia é maior deendencia, inseguranca interna e conomica, qualquer momento pode sair de um pais, dependencia de termo de legislacao, pedir muitos favores(njovo fudido), impede de criar mercado interno forte, pode gerar tipo de emprego, no longo prazo a gente perde atuonomia economica. alem disso elas geram grande numero de desemprego, pq elas impedem qeu outras empresas menores possam concorrer com elas.
    - varios prejuizos em relacao as comodities
      + agricultura monocultural, desenolve apenas um tipo de produtos, qualidade de empregos, volatilidade das comodities, cenario de maior apego das comodities,
      + e em relacao a cadeia de producao - menor valor agregado -> cria uma cadeia de producao com muito menos pessoas, vc se industrializa menos, criadoras de manufatura, n simplesmente essa comodity, importancia de ter uma industia de grande valor agregado.
    - tecnologia do 2g
      + e nao é bom importar tecnologia, menos incentivo de produzir a propria tecnologia, mais barato ainda de importar tecnologia, menos incentivo de desenvolver tecnologia, mais barato aqui
      + agricultura, n sao comparativos, cenario que a gente adotaria a alca, e n adotaria, diferença é minuscula do que a gente venderia ou nao(arthur falou isso), os eua ainda precisam da comodity, conseguiria mais dinheiro, seria uma diferenca minima,
      + importacao de tecnologia, as comdities continuariam sendo vendidas, a gente continuou vendendo comodity.
      + comparando com 1 oposicao
        - n explica pq n teriamos tamanho desenvolvimento
        - o problema n é na comodity, é ficar na dependencia, só é gerada, aumentada na alca, mais acesso a produtos com baixo custo. nosso govbernos nao teriam nocao de desenvolvimento nacional.
