#+TITLE: DT1
- Refutacoes pro 1 GOV
  - As igrejas mudam
    - Blz, mas elas tambem mudam pro pior, o islam por exemplo passou desde apos
      a revoluacao iraniana um processo de cada vez maior fanaticismo, seja com
      o wahabismo da arabia saudita, seja com a mudança de dogmas na religiao
      xiita por causa do da acenção do aitolah. Beirute antigamente era por
      exemplo considerada a Paris do oriente. Mulheres no Iran da decada de 60
      nao precisavam usar nem mesmo a hijab.
    - Segundo que religiao nao é igual shampoo pra voce trocar, religiao
      é muito sobre cultura, sobre os seus pais, sobre a sua comunidade, ninguem
      sai de uma religiao e sai intacto, porque na maior parte das vezes voce é
      excluido daquela comunidade.
    - Todas as refutacoes previas dela envolvem "a mais tem outras religioes que
      nao sao assim", mas tem religioes que sao, e esse nucleo fanatico é quem
      ativamente causa mudanças porque é quem tá engajado, justamente por ser fanatico.
  - Depois ela fala sobre valores comuns
    - O proprio exemplo da China é o melhor exemplo, um pais que teve sua
      religiao constantemente esmagada, e o que sobrou foi justamente a retirada
      da parte religiosa, e ficou a filosofia, os valores, sem toda a inutlidade
      da religiao.
    - E ela parte com base em todo essa contrucao de ideia capitalista onde o
      valor do individuo é medido apenas com base na produtividade, mas ora,
      literalmente toda a lógica do calvinismo religiao dominante no EUA, é que
      a produtividade não é mero fator social, mas SINAL QUE VOCE É ESCOLHIDO
      POR DEUS. a europa é extremamente ateia, e tem uma cultura de produtividade muito mais saudavel
      que o EUA por exmemplo.
- Disclaimer 1 - A moção trata de ascenção, o processo que deve ser discutido
  portanto não é uma mera comparação de mundos, embora isso esteja dentro da
  moção, mas o proprio processo de ascenção e como ele causa mudanças na
  situação fática, isso significa que não é nosso onus assumir que 100% das
  pessoas vao aderir a esse tipo de visão, assim como não é onus do governo
  assumir que 100% das pessoas no mundo deles vao ser fanaticos religiosos a la
  ISIS, a mocão permite um certo grau de sutiliza justamente por causa da
  palavra acençao. Se esse fosse o debate, a moção seria EC prefere viver em um mundo...
- Disclaimer 2 -> Nos nao acreditamos que a visão do Dawkins ela vai se
tornar a majoritaria -> Pq? -> Pq a maioria das pessoas não vai acabar por
querer gritar pra todo mundo envolta que a gente precisa ser intolerante, até
porque a maior parte da populacao é religiosa -> O que isso significa? Significa
que vai acontecer o que acontece atualmente, o Dawkins grita pra Deus e o mundo
que religiao é horrivel a anos, e ainda assim uma pequena parcela é que
realmente considera aquilo verdade e se imbui desse tipo de ideologia. Porque
ninguem vai querer bater boca com a familia na ceia de natal só por causa de
religiao, uma minoria vai fazer isso.
- Caracterização sobre que tipo de pessoas vao aderir -> Pessoas com um certo
  grau de instrução, progressistas, e não só isso, mas pessoas que já tem uma
  certa tendencia a serem mais radicais em seus posicionamentos ideologicos em
  todas as esferas, do contrario elas só seriam aquele agnostico normal que todo
  mundo conhece e n faz mal a ninguem, o proprio Dawkins é o melhor exemplo disso,
  essas pessoas acabam por geralmente serem cientistas, intelectuais,
  jornalistas, etc. Pessoas que tem uma certa influencia no discurso público,
  justamente as pessoas que tendem a estar dispostas a quebrar com 2000 mil anos
  de tradição de uma forma tão radical.
- Terceiro disclaimer -> O mundo que o governo defende é um mundo igual o atual,
  só que sem o ateismo a la richard dawkins, ou seja, eles nao oferecem um mecanismos contra
  a loucura dos religiosos, eles só mostram porque os ateus dawkins sao ruins
  tbm, e tentam ganhar o debate mostrando que eles sao piores que os fanaticos
  religiosos,
  O que nos oferecemos na 2 Oposicao, é justamente um
  mecanismos para negar ambos os fanatismos, seja o religioso seja o ateu.
- E por que nos consideramos que ter uma pequena parcela da esfera publica como
  esse tipo de visão MANIFESTADAMENTE INTOLERANTE, e aqui nós assumimos que
  essas pessoas vao ter preconcito com religioso, não vão gostar de religioso
  etc. Vao achar crente burro e catolico culpado enrustido.
  - Por que nos acreditamos que isso seja bom?
    - Porque pessoas radicais, tendem a ter uma paixao, uma garra, uma gana
      maior no que diz respeito a suas bandeiras e aos inimigos com quais elas
      lutam.
    - E quais seriam os inimigos nesse caso?
      - O fanatismo religioso
        - Coisas como laicidade do Estado
        - Zonas na europa em que a sharia é aplicada informalmente
        - Na maior parte dos casos o anticientificismo caracteristica da maioria
          dos fanaticos religiosos
      - Tudo isso acontece e sao coisas que esse tipo de pessoa necessariamente
        iria contra
      - Por que nos acreditamos portanto que nesse mundo nós não teriamos um
        alto grau de intolerancia contra as religioes?
        - 1 - Porque essas pessoas seriam uma minoria como minha caracterizacao explicou
        - 2 - MAIS IMPORTANTE -> Porque essas pessoas vao ter pautas e coisas
          mais importantes para lutar do que um mero religioso de esquina, que
          vai pra missa mas usa o sabado pra tomar uma cachaça no bar da esquina.
      - Um mundo em que essa acençao ocorre se caracteriza pelo o que portanto?
        - Nós temos um certo CONTRAPESO contra o fanatismo religioso, para cada
          fanatico religioso que queira criacionismo nós vamos ter um outro
          fanatico que quer proibir o culto religioso, esses dois malucos se anulam.
        - Que impactos portanto nos podemos ver?
          - Maior luta contra os maiores absurdos da religiao, ao mesmo tempo em
            que os fanaticos do outro lado vao lutar contra os maiores absurdos
            desses fanaticos ateus
          - Justamente com base nesse processo de intensa luta entre os dois
            lados, a gente consegue que ambos os absurdos de cada lado sejam
            mitigados, e o meio termo prevaleça.
          - E porque os lados iriam lutar entre si e não contras os moderados?
            Justamente porque se você odeia tanto a religiao, ou odeia tanto os
            ateus, você vai lutar contra quem? Justamente contra o exemplo mais
            caricato, mais absurdo do outro lado, no caso dos ateus dawkins os
            fanaticos a la ISIS, e no caso dos fanaticos a la ISIS, os ateus dawkins.
