#+TITLE: DT2

- Acordos de livre comercio, trocas de intercambio cultural, etc
- Crescimento a longo prazo, metrica desse debate
- Caracterização
  - Paises arabes
    - Sao paises com mais laços culturais
    - Existe uma intensa troca entre paises muculmanos e asiaticos, devido as peregrnacoes
    - Sao paises que tendem a ter uma economia mais ou menos semelhante
  - Grandes potencias
    - Qual o clash -> Voce ter as vantagens de uma potencia, vantagens
      economicas VS Autonomia
    - China e India
      - Ambos esses paises tem um problema especifico
      - Minorias, Chinesas e Indianas, muito chines na indonesia, muito indiano
        na malasia etc, por que isso é ruim? Devido colonizacao, trocas
        comerciais no oceano indico
    - Russia nos nao consideramos tao relevante porque a vantagem da potencia é
      o poderio economico
      - O poderio economico por sua vez da russia seria equivalente a o de uma
        arabia saudita ou no futuro paquistao
  - Por que nos acreditamos que a autonomia nesse caso é mais importante, mais relevante
    - Nós nao acreditamos que é nosso onus afirmar que esses paises nao vao ter
      comercio normal com as grandes potencias -> Até porque todo mundo troca
      coma as grandesp potenciass, todo mundo troca com a china, compra produtos
      de lá
    - O que nos acreditamos é que
      - 1 Nao vai ser tao intenso
      - 2 Nao vai acontecer tanto em outras areas
        - Culturais
        - Armamentistas etc
  - Por que nos acreditamos que isso é bom?
    - Nao existe nenhum motivo para acreditar que esses paises potencias tem
      interesse de serem bonzinhos
    - Ate porque a sua populacao nao se importa, populacao, governos utilitaristas
    - Nos paises islamicos por sua vez
      - Um governo é formado por pessoas, e essas pessoas nem sempre racionais
      - Nem sempre racionais, significa que elas vao levar em conta seus laços afetivos
      - Por que? Religiao é algo muito presente
        - É Preferivel a puniçao terrena do que a religiosa(Eternidade)
    - A situacao se agrava quando a gente leva em conta as minorias nesses paises
      - Assim como os governantes dos paises arabes tambem tenderiam a
        beneficiar os paises arabes
        - Pq? -> Por causa dos proprios laços entre a populacao, que nao
          gostaria de ver exploracao
          - 2 -> Por causa da pequena disparidade entre economias
      - As minorias se tornam fator de instabilidade
        - Esses paises na sua maioria tem um balanço de poder fino e delicado
        - Se voce ver uma entrevista com o ex PM malaio, ele bota a culpa o
          tempo todo nos nativos dominantes por o paise nao ter deslanchado
        - Sendo ate extremamente xenofobo
        - Essas grandes potencias naturalmente iriam tender a influenciar as
          suas minorias locais
          - Justamente por ter uma maior proximidade, muitos ainda contem laços
            com o pais natal
          - A China faz muito isso centros confucionistas
          - QUal o impacto portanto?
            - É que com esse estreitamento voce já tem uma porta de entrada para
              essas grandes potencias, já que muitas vezes essa minorias estao
              em grande cargos no governo -> O PM que eu falei anteriormente
              acredito que tinha decendencia Tamil, que é lá da India
            - Isso significa que essas trocas deixam de ser meramente
              comerciais, culturais e etc
            - E passa a aver um auto grau de neocolonizacao, justamente porque
              essas potencias tem condicao nao só de fazer trocas, como adentrar
              no interior dos corpos governantes
              - O que por si só já é ruim, mas aumenta de grau ainda mais,
                quando a gente analisa o possivel efeito backlash nisso
              - Por que? QUem vai se beneficiar nisso tudo sao as minorias
                chinesas, indianos Semelhante a quando a China vai pra Angola, e
                quem faz todo os grnades projetos de construcao civil sao
                chineses, os nativos sao usados apenas como mao de obra
              - Isso significa que voce tá beneficiando uma minoria em
                detrimento da outra, é dividir para conquistar, é literalmente o
                mesmo esquema do que quando os ingleses colocaram os tutsis no
                controle de ruanda mesmo sendo minoria
              - E um pais dividido nao tem condicoes de crescer naturalmente,
                jsutamente porque essa violencia(n to falando necessariamente
                fisica) gera uma grande instabilidade dentro do governo, o que é
                benefico para essas grandes potencias, justamente porque
                significa que é mais facil ainda de controlar
                - O petroleo na malasia
                - As iplantacoes de oleo de palma na indonesia
