#+TITLE: Treino_30_04_2020

- Nós não acreditamos que esses paises tem os melhores interesses do resto do mundo
  - As instituições seriam basicamente regidas pela China
  - Forneceriam um jeito de ditadores receber auxilio financeiro
  - Contrafactual
    - Um mundo em que esses paises agem dentro das organizações já existentes
    - Neocolonialismo na Africa
  - Na maior parte dos casos esses países não tem um setor financeiro equiparado
    para comportar esse tipo de ação
  -

* Disclaimer
- Qual o contrafatual?
  - Os BRICs entrarem dentro dessas organizacoes, e colocarem seus investimentos
    no cenario atual, portanto no geral, a pilha de dinheiro não mudaria, a
    deputada fala que não tem dinheiro pra todo mundo. Mas não teria mais ou
    menos dinheiro no geral.
  - A China, India, Russia não são bonzinhos por si só, se a Argentina continuar
    não tendo credibilidade economica, eles não vão emprestar por bonança de
    seus corações, eles não dão nenhuma garantia disso, além de que por algum
    motivo pais subdesenvolvido vai ajudar pais subdesenvolvido.
  - Os BRICs não sao relevantes, porque nenhum desses paises precisa de
    emprestimo externo a anos, o Brasil não tenta tomar um emprestimo desde o
    começo dos anos 2000.
- Cenário mais provável
  - China constitui a maior parte do poderio economico do bloco
  - O pib do brasil é menos de 2 trilhoes de dolares
  - russia 1.5
  - africa do sul 500 b
  - China mais de 14 trilhoes se vc equalizar com poder de compra
  - Portanto -> Controlado pela China
    - China n tem excrupulos
    - Sudao, Darfur, 2010
    - Coreia do Norte, presente
  - Qual a função desses mecanismos
    - Framework global de comercio -> OMC
    - Fornecer dinheiro para países pobres -> FMI
  - Por que em ambos os casos é pior?
    - O FMI fornece dinheiro com bases em garantias
      - Muitas vezes liberdades civis, democracia, etc
      - Disclaimer
        - N estamos falando que esses paises são bonzinhos
          - No comparativo, melhores que a China
          - Pq? -> Opiniao publica tem moral, governos não
          - Sociedade civil forte
          - Ex: Alemanha negando a venda de tanques Leopard para a Arabia
            Saudita após backlash
      - A China e seus minions no caso não teriam o mesmo escrupulo
      - Portanto qual a consequencia?
        - Anti-democracias passam a ter uma alternativa ao FMI
    - Algo semelhante já ocorre quando a gente trata de infraestrutura,
      democracias falhas como Angola, Djibuti, Eritreia usam de muito dinheiro
      Chines, que faz uma especie de neo-neo-colonialismo
    - Portanto qual o impacto?
      - Diretamente na vida das pessoas que vivem sobre esse tipo de regime, que
        é a maior parte do mundo subdesenvolvido
      - Antes ao menos tinham certas concessoes
  - E no caso da OMC
    - Qual a função da OMC?
    - Criar um framework global que promova o comercio livre e sem restrições
    - Por que? Pq é apenas com o comercio livre e especialização que os paises
      começam a poder sair do buraco da pobreza
      - Ex: Vietnam, Taiwan, India, só passaram a sair da situacao de miseria
        quando adentraram as cadeias globais.
    - A China por sua vez, já demonstrou não conseguir compactuar com esse
      framework global. Ex: Nos anos e anos em que eles desvalorizaram a própria
      moeda em prol de vantagens competitivas. Ou quando eles ativamente passam
      a fazer parte de espionagem industrial
    - Qual o problema portanto? Que com a China emcabeçando uma nova OMC, o que
      você tem é eles tendo mais poder ainda de forçar vantagens competitivas
      artificiais, o que prejudica justamente os paises que estao tentando
      entrar no mercado global agora.
    - Esses paises não vão conseguir competir com uma China que além do seu
      poderio industrial tem uma moeda desvalorizada.
      - No mundo atual, a China fazendo parte da OMC, esses países ao menos
        poderiam levar ela a corte de arbitragem. E não se enganem em achar que
        os paises mais fracos não conseguem. Ex: Brasil ganham casos do milho.
    - Qual o contrafatual portanto?
      - Um mundo em que nós temos um único contexto de instituições, as atuais,
        mas que agora teria diversos polos de influencia, o EUA, a Europa, a
        China, o Japão, cada um controlando uma parte. Portanto nenhum dos
        paises conseguiria impor sua vontade. Isso portanto seria benefico até
        menos para os países que continuassem nas redes ocidentais, porque uma
        influencia Chinesa ou Indiana, seria capaz de coibir abusos maiores.
