#+TITLE: Treino Diario 23_09_2020

* Alguns disclaimers
Qual o comparativo? -> Nós não acreditamos que o comparativo correto a ser
tomado nesse debate é o entre Ciencia, tecnologia, matematicas biológicas etc,
mas na verdade entre as Humanas e certas humanas aplicadas, vide Direito,
Administração, Economia e etc
Diferente das primeiras, essas últimas que podem ser transformadas em valores
monetários, e quantificadas em capacidade de produzir dentro de um sistema
capitalista. Note que isso significa que o que está ocorrendo não é um aumento
geral de cursos e as humanidades estão apenas se mantendo, mas na verdade
estudantes estão saindo das humanidades em direção a esses cursos, ou seja, a
mudança ocorre em detrimento
Segundo ponto nós podemos assumir que Estudantes ao longo do tempo provavelmente
tem interesses similares, n há nada que assuma o contrário, isso significa que
as mudanças ocorrem por causa de forças mercadológicas
Note também que isso não significa que existam mais empregos para esses tipos de
graduações, mas que na verdade as forças mercadologicas tem o incentivo de criar
cada vez maior um numero de invididuos capazes de assumir esses cargos, o que
consequentemente aumenta a oferta de trabalho, enquanto a demanda continua a
mesma, o que força esses individuos portanto a trabalhar por cada vez menos,
visto que, agora existe sempre o medo da substituiçao, isso pode ser notado em
estágios cada vez pagando menos, o salário médio de um advogado iniciante
diminuindo cada vez mais etc.
* Mecanismo
Qual o mundo em que nós defendemos? -> Um mundo em que decisões políticas da
classe dominante são mais questionadas, e que no geral envolve seres humanos,
sentirem um nível de "preenchimento" maior.
Estudar qualquer graduação muda a sua formação de pensamento, isso significa que
só se você estuda Economia, Direito, você só passa a traduzir todas as
interações e acontecimentos do mundo factual em forma de valores economicos, do
mesmo jeito que se você apenas estudar direito, a probabilidade de você traduzir
as ocorrencias do mundo real na forma de axiomas de lei é bem maior. E também a
forma de você tentar resolver os problemas que ocorrem Exemplo: Quem não conhece
aquele estudante de direito que acredita que tudo se resolve com uma lei?.
As humanidades por sua vez, tem dentro de si analise crítica e subjetiva da
sociedade, a partir do momento em que nós perdemos a parcela da população que
tem a capacidade de fazer esse tipo de decisão, sem muitas vezes a encarar em
termos econômicos, nós perdemos necessariamente uma parte muito importante da
formação de agenda e opinião na esfera pública. Passa a ser ônus da oposição
portanto provar como isso se mantem num mundo em que as humanidades estão
severamente diminuidas.
* Como isso prejudica individuos?
O dinheiro por si só não preenche o ser humano, questões como qual o objetivo da
vida, porque nós estamos aqui, de que forma as relações de poder influenciam o
indivíduo.
1. As humanidades fornecem esse tipo de resposta, mais do que esses outros tipos
   de graduações, justamente porque a partir do momento em que elas não dão
   lucro(que nós consideramos na verdade algo bom) signfica que elas não tem a
   influencia do mercado corporativo dentro dos cursos(Coisas como empresas
   juniors, aulas magnas com empresarios etc) Isso significa que nós garantimos
   uma parcela da população que não vai ter a economia como fim em si mesmo,
   isso pode trazer problemas? Sim Por exemplo: Aquele bacharel em filosofia que
   não conhece o conceito de escacez e que portanto quer um salario minimo de
   5000 mil reais, mas isso não é um problema num mundo em que também existem
   graduações em economia, e direito, o problema como eu falei no começo do meu
   discurso é que esses cursos estão aumentando em detrimento das humanidads.
2. O impacto disso portanto, envolve também a diminuição de qualquer valor que
   não pode ser quantificado Ex: Democracia.
