#+TITLE: PM_Gui

EC apoia a ploriferaçaõ do uso de drones

- Senhor presidente, pra entender esse debate nós precisamos entender o razão de
  existir dos drones, e de como se dá essa ploriferação
  - Qual o contrafactual aqui?
    - Mundo sem os drones
    - O mundo sem os drones é o mundo das decadas de 90 e 80
    - Nesse mundo, as operações de contra-insurgencia, os ataques dos EUA nos
      paises do oriente medio eram feitos como
      - Nós tinhamos o auxilio de tropas no chão em conjunto com o uso massisso
        de supremacia aerea e de artilharia
      - Os exercitos do mundo sempre preferiram jogar bombas nos seus inimigigos
        a mandar a nata de sua juventude(Caso da Op de diminuição das guerras)
      - Nós precisamos entender que o verdadeiro contrafactual aqui é que invés
        do uso de drones o que nós vamos ter é uma continuação do uso de
        aeronaves e de artilharia(quem matou o lider da guarda revolucionaria, n
        foi os Navy Seals, foi um missel tomahawk)
        - E nos possiveis casos em que tropas de verdade precisem ser usadas, o
          mundo também não é o mesmo, a maior parte dessas tropas vão ser ou
          milicias irregulares ou mercenarios contratados
- Ganhamos o debate portanto provando porque os drones são a substituição desses
  dois metodos de fazer guerra, e como no caso eles são melhores que ambos
- A gente precisa entender que o drone não veio pra substituir o soldado raso
  atual, pelo menos dentro do contexto atual de ploriferaçao.
- O drone substitui o avião
- Inves de mandar um F-16 jogar milhares e milhares de toneladas de explosivos
  sob um determinado local voce manda um drone predador sobrevoar aquela area
  por horas e horas, e quando tiver certeza do alvo vc solta o missel
  - Pq os drones sao melhores
    - Drones conseguem sobrevoar por horas e horas seguindo o alvo, coisa que um
      avião não consegue justamente pq tem um ser humano lá em cima
    - Drones conseguem voar muito mais baixo, o que significa que eles conseguem
      ser muito mais precisos
      - Pq? Pq nao tem um ser humano lá em cima que pode ser abatido por um
        missel stinger que qualquer taliban consegue levar no ombro
    - Drones por serem menores(jusmente por nao ter todo o equipamento pra
      manter um ser humano vivo a altitudes imensas e velocidade 4/5 acima da
      velocidade do som) -> Isso signfica que eles conseguem ser furtivos, o que
      também faz com que consigam ser mais precisos
    - Em resumo, enquanto que se eu quisesse matar um lider terrorista na decada
      de 90 eu jogava toneladas e toneladas de explosivos a uma altitude
      gigantesca(onde a precisão vai pro saco) > Agr eu boto um predador pra
      stalkear esse cara por horas e horas, até que ele esteja sob uma area o
      mais deserta possivel e eu ataco ele
- A op pode falar que prefere que seres humanos façam as operações (boots on the
  ground) mas 1 eu ja falei que a ploriferação nao vem pra substituir os seres
  humanos, mas caso eventualmente chegue a ser, nos preferimos, porque 1
  - O caso de que esses soldados vao voltar pra casa, o pessoal vai ver o horror
    pipippopo e vai acabar a guerra
    - É algo que funciona na decada de 70 quando os jovens americanos fugiam da
      draft pro vietnam
    - Mas os protestos ensinaram algo pra esses paises, que vc só deve usar
      nacionais em situaçoes muito especificas
    - A resposta foi o que?
      - Mercenarios e insurgentes
      - Blackwater é a maior parte do iraque
      - Insurgetens por exemplo no caso do enclave de donbass na ucrania, nao
        sao russos lutando, sao ucranianos
      - Mas pq nos preferimos drones?
        - Pq o ser humano ele é falho, ele faz merda, ele confunde uma criança
          com um graveto com uma criança com um RPG
        - Ele acha que todo mundo é seu inimigo
        - Ele nao respeita as regras de engajamento
        - Ele estupra
        - Ele mata só por odio
        - Ele pilha vilas ele faz tudo isso
        - Ainda mais esses soldados modernos que não lutam por nenhum pais
          apenas por dinheiro e que não respondem a nenhuma corte internacional
          nem a nenhum tratado
        - O drone por sua vez não faz nada disso, a unica vantagem possível do
          ser humano sob a maquina era pra ele morrer e fazer com que a galera
          de volta pra casa repense a situação, só que no mundo moderno, nem
          mesmo isso funciona, pq quem volta pra casa mutilado é um mercenario
          que na maior parte das vezes nem da nacionalidade do pais atacante é,
          ou algum miliciano local que ninguem se importa.
