#+TITLE:  EC lamenta o conceito de martírio (sofrer tormentos/morrer por defender uma causa política ou religiosa)

-> Martire atrelado ao extremismo -> Forma de glorificar e convencer as massas
de uma ideologia -> Pra cada caso em que martires são colocados como ruins
existem casos em que ter um martire é bom
-> O GUi fala de como os martires engessam as sociedades impedindo essas pessoas
de serem criticadas, mas ADVINHA, o Estado Nação moderna é uma mentira, a
nacionalidade Francesa, Brasileira, Alemã foram todas criadas, algumas dessas
tao cedos a dois seculos atrás
- E esse tipo de mentira não é ruim, pq ela cria uma racional coletiva entre as
  pessoas, e ela adiciona algo em comum entre individuos, a partir do momento
  que os martires passam a ser utilizados enquanto ferramente agregadores de
  pessoas, ou seja, nossos pais poderiam nao se considerar iguais e se odiarem,  mas a partir
  do momento que nós somos incutidos nessa ideologia nós de repente não nos
  odiamos mais.
  - O martire não é a unica das mentiras contadas para formular qualquer
    sociedade,
  - Coletivismo n é ruim, ideologia nacional n é ruim, é a base do mundo
    moderno, se algum dia a gente conseguir criar uma sociedade global sem
    fronteiras, essa sociedade tbm vai ser fundada em ideologia, e tbm vai ser
    fundada em mentiras.
- O Gui fala que os EUA tinham martires dos EUA, e que por isso tinha o
  segregacionismo e caralho a quatro, mas isso é completamente idiota, pq a
  gente pode voltar alguns anos atras, e ai a gente acha o que? Que martires os
  escravagistas usavam? -> As elites já tem todos os incentivos para oprimir o
  outro lado, sabe quais sao os incetivos? ganhar dinheiro, poder terra,
  influencia, ninguem precisa de idelogia pra escravizar terceiros, os
  incentivos materiais já sao gigantes.

- Disclaimer -> Todo homem bomba é um martire mas não necessariamente todo
  martire é um homem bomba
  -> N precisamos defender atentado terrorista
  -> Atentado não é ruim por causa da ideia de martirio -> Matar centenas de
  pessoas

  -> Caracterização
  - Quando ocorre o martirio?
    - O ser humano tem uma tendencia a autopreservacao
    - Instinto
    - Significa que o martirio é algo muito forte
    - Significas que a pessoa pra se matar por algo deve realmente se importar
      com aquilo
    - Mais importante, ela nao deve ver outa forma
      - ?
      - Martires sempre vem do lado mais fraco de uma situacao
      - Martires religioso no imperio romano
      - Martires hereges igreja catolicas
      - O jovem na tunisia que tocou fogo a si mesmo e começou a primavera arabe
      - O martirio é uma consequencia n uma causa de uma situacao muito maior
      - Pq nos acreditamos que na maior parte dos casos a causa dos martires é
        em menor ou maior parte justa?
        - Pq ninguem que tá ganhando vira um martire
        - Se vc precisa morrer por algo, significa que vc n vê nenhuma forma de
          mudar a situacao de onde vc tá
        - O martire ele advem de um profundo desencato quanto ao contexto social
        - Por isso que a concepcao atual advem
          - Dos monges tibetanos tocando fogo a si mesmo protestando a ocupacao chinesa
          - Dos jovens no mundo arabe contra a opressao
          - Qualquer ser humano que consiga ver a situacao mudando dentro do seu
            espaço de vida, vai querer continuar vivendo pra ver aquilo, entao
            possivelmente n vai se matar
          - Portanto o martire é sempre o lado mais fraco
          - E pq o lado mais fraco tende a ser mais justo?
            - Embora existam algumas ocasioes em que o mais forte tava certo
              - Ex: INvasao do camboja pelo vietnam, pra acabar com o khmer vermelho
              - Na maior parte dos casos
                - A gente ta tratando de exploracao
                - Imperialismo
                - Subjulgacao de povos
                - Tudo aquilo ruim
                - POrtanto principiologicamente, o martire tende a ser justo
                - O que anula qualquer idiea do governo de que essas pessoas
                  estao sendo enganadas fs qq
                - Sao pessoas que preferem o seu pais, o seu povo a sua propria vida
                - E isso é principiologicamente correto a partir do momento em
                  que a causa é justa e que a pessoa n tá levando ninguem junto
- Segundo o martire ele é efetivo para chamar atenção da comunidade internacional
  - Toda sociedade tem seus martires, seus herois, seus simbolos
  - O Brasil por exemplo tem tiradentes
  - Isso significa que em todo grau, existe uma grande identificação entre
    pessoas e martires, porque todo povo tem seus martires jogados dentro do
    imaginario popular desde cedfo
    - Ainda mais se referindo a cristãos
  - Isso significa que quando um monge se queima pra todo o mundo ver
  - Isso faz com que os individuos de sociedades democraticas parem para olhar
  - E em sociedades democraticas, embora exista a ideia de realpolitik e que os
    governos tendem a ser meramente utilitaristas
  - Eles ainda respodem as pressoes internacionais
  - O governo pode falar que isso não tem respaldo na realidade
  - Mas se a gente for pegar, toda as lutas de descolonização pós segunda
    guerra, tiveram em grande parte apoio popular da população, principalmente
    americana, o Truman só apoiou o Nasser na crise do Suez, porque o grande
    publico americano também via a frança e a inglaterra como meras potencias imperialistas
  - E nao precisa nem mesmo ser o governo, os cidadaos diretamente
    - IRA na Irlanda, financiado irlandeses nos proprios Estados Unidos
  - O proprio rechaço internacional ao regime da tunisia, que inclusive
    conseguiu ser um dos casos bem sucedidos da primavera arabe, foi em grande
    parte devido a imagem daquele jovem vendedor se matando.
