#+TITLE: EC ACREDITA QUE OS ESTADOS UNIDOS DEVERIAM FORNECER VISAS PARA TRABALHADORES TEMPORÁRIOS, PELOS QUAIS AS LEIS DE SALÁRIOS MÍNIMO NÃO SE APLICARIAM
O que nós nos propomos a provar aqui?
Que isso não necessariamente diminuiria a quantidade dos outros tipos de visas,
na verdade teriamos apenas um aumento
Que isso necessariamente n implicaria em uma diminuição nos empregos acima de
salário mínimo para os nativos americanos
E que no pior caso, mesmo se diminuisse nós ainda assim preferimos um cenário
onde isso acontece

* Antes de Tudo
Dislaimer -> Algumas coisas sobre o status quo
1. Como nós acreditamos que isso iria ocorrer mais provável? -> Que nós teriamos
   fornecimento massivo de vistos para estes trabalhadores, caso isso n seja
   verdade, n faz sentido a moção existir, nem pro governo nem pra oposição
2. Como os vistos atuais de trabalhadores temporários sao fornecidos? ->
   Trabalhadores com alto capital tecnologico -> Da India, CHina, com capacidade
   tecnologica, diploma terciario, ou que foram patrocinados por uma empresa
3. Nós acreditamos que nossa moção pelo contrário iria na verdade atingir
   aqueles trabalhadores que no atual status quo entram de forma ilegal dentro
   do país, justamente por n ter a opção de entrar por nenhum dos outros vistos
   atuais, por n ter esse capital tecnológico
4. Os EUA estao hoje em dia com uma das menores taxas de desemprego da história,
  beirando o pleno emprego(4% mais ou menos), isso vai se tornar importante mais
   pra frente
* Primeiro onus a provar
Porque n vai prejudicar os outros trabalahdores que estao vindo com vistos
temporários -> O salário minimo ele serve para proteger aquele tipo de
trabalahdor de onde existe uma reserva de mão de obra gigante dentro do mercado,
ou seja, onde o empregador pode simplesmente demitir, e no outro dia ter alguem
desempanhando as mesmas funções, que geralmente n exigem conhecimento técnico
especializado, portanto essa medida n iria prejudicar os trabalhadores que
entram temporáriamente pelo sistema atual, ela serveria apenas para agregar
aqueles que hoje em dia entram ilegalmente
* Segundo onus
Por que isso n necessariamente implica numa diminuicao nos empregos acima do
salário minimo -> Justamente por causa da baixissima taxa de desemprego que eu
falei anteriormente, nós acreditamos que o mais provavel que esses trabalhadores
desempenhem é justamente no setor rural, onde eles já tem a expertise necessaria
para trabalhar nas plantações, como muitos mexicanos hoje em dia já trabalham no
setor agricula americano
Por que isso é importante? Pq existe uma falta de mao de obra nesse setor, a
medida serve para preencher essas vagas que não estao sendo preenchidas,
justamente porque existe um grande exodo rural das pessoas que saem das areas
rurais para as grandes cidades, os jovens americanos já não tem interesse de
entrar nesses lugares
* Mas mesmo se diminuir
Nós acreditamos que a qualidade de vida de uma pessoa que vive na classe média
de um país como GUatemala, Honduras, Mexico ainda assim é menor do qeu a grande
parte da vida de um americano -> Por que?
1. VIolencia, Honduras por exemplo tem uma taxa de homicidios que passa dos 100
  por 100 mil habitantes
2. Impossibilidfade de acesso a certos bens de consumo -> Como geladeiras,
   eletrodomesticos, internet etc, devido principalmente a desvalorização das
   moedas locais e relativo menor poder de compra, exemplo Brasil(DOlar a 4 reais)
3. Piores serviços públicos, justamente devido a uma grande massa de pessoas
   pobres que não tem condições de arcar com um Estado fornecendo educação e
   saneamento básico(coisas que tem nos EUA, saúde é nos admitimos ser ruim em
   ambos os casos)
 Ou seja, comparativamente, os ganhos de qualidade de vida que vao ser
   experimentados pelo mexicano ou hondurenho que sai de uma situação de
   verdadeira guerra e caos social para uma situação de relativa estabilidade
   mesmo dentro da pobreza, é maior do que a queda na qualiudade de vida de uma
   americano que teve todo e qualquer vantagem na vida, e que agora n tem
   condiçoes de conseguir um emprego
   O que torna a medida ainda moral, visto que, comparativamente, devido ao
   maior acesso a conbdições de crescimento na vida, perpetuada entre o
   americano e o cidadão de primeiro mundo, qualidade de vida desse americano
   que foi em grande parte adquirida por processs de exploração e roubo de
   recursos desses mesmos individuso que agora buscam uma vida melhor
   Medida moral
   Republica das bananas, tira e bota qualquer presidente em prol do lobby das
   empresas de fruta
   Dividas extratosfericas por meio de mecanismos como o BM e FMI
   Incentivo a guerrilhas e guerras civis como a situação nos contras no
   nicaragua
 .
