#+TITLE: Treino Diario 3 de Abril de 2020
* Moção:
EC apoia a rápida eliminação global de barreiras tarifárias e não tarifárias
para liberar o comércio
* Case
- WTO modeo todo para o resto do mundo
  - Ok ter politicas anti-dumping
  - Controle sanitário
  - No PIOR do PIOR dos casos, nós vamos aceitar tipos de barreiras Ex:
    Segurança alimentar
- Por que nós acreditamos que barreiras tendem a ser ruins?
  - Em países subdesenvolvidos a maior parte das barreiras não envolvem politica
    economica baseada em dados
  - Mas na verdade barreiras arbitrárias impostas por grupos de interesse, que
    invés de buscar aumentar a produtividade, preferem solicitar ao congresso e
    ao executivo a imposição dessas barreiras
  - Exemplos: Lojas americanas, positivo, CCE, o setor automobilistico, todos
    esses setores e firmas recebem benefícios a no mínimo uma década, e até hoje
    não tem capacidade de competir com o resto do mundo. Isso acontece porque
    para essas firmas é muito mais barato pagar alguns milhões de suborno para
    meia duzia de deputados, do que investir bilhões em tecnologia e expertise,
    algo que nem mesmo pode dar certo no futuro.
  - Por que nós acreditamos que isso é o mais comum?
  - E qual o mecanismo que faz com que esse subdesenvolvimento se mantenha?
    - Por que nós podemos dividir a economia de um país desse em dois setores, o
      setor que consegue acessar a imposição de barreiras, e o setor que não
      consegue.
    - Exemplo: Aqui no Brasil o setor agricula é o que tem a menor taxa de
      subsídio, enquanto que o setor de insumos e maquinas tem uma taxa absurda
    - O problema é que naturalmente o setor de agricula precisa comprar maquinas
      e insumos ele vai ser obrigado a
      - 1 - Comprar da empresa que está sendo protegida, e que portanto tem
        produtos de menor qualidade, visto que, não existe nenhum incentivo a
        essas firmas melhorarem seus produtos. Já que existe uma reserva de mercado
      - 2 - Comprar do mercado externo, o problema é que naturalmente esse
        mercado externo vai ser mais caro, justamente por causa das tarifas de
        importação, o resultado portanto é que você acaba com a produtividade
        dos setores que não precisam de ajuda, para compensar por aqueles a qual
        a ajuda jamais servirá de algo.
    - Isso nos leva ao por que setor setores são mais eficientes e outros não?
      - Nós precisamos entender que cada país tem suas vantagens competitivas, o
        Brasil jamais vai ter condições de competir com a China no mercado de
        microcips, porque a china não tem apenas dinheiro, eles tem acesso
        privilegiado a outros países capazes de fornecer peças e matéria prima,
        a china tem expertise, a china tem mil e umas vantagens que jamais vao
        ser superadas pelo Brasil.
      - E o que os países subdesenvolvidos tem? Mão de obra e recursos naturais.
        - Existe a ideia de que o setor extrativista seria de alguma forma pior
          do que o setor de manufatura, e que somente países que tem industria
          conseguem ser desenvolvidos.
          - Por que esses setores forneceriam maior valor agregado
            - Falso
              - 1 Porque o setor extrativista hoje em dia tem tanta
              tecnologia e expertise quando o industrial
              - 2 Porque não é porque uma tonelada de microchips vale mais que
                uma tonelada de soja que significa que microchips sao melhores
                de serem produzidos, porque a demanda por soja é muito maior,
                portanto é preciso produzir muito mais dela.
        - O que nós acreditamos que seria o cenário mais provável para um país
          subdesenvolvido?
          - No primeiro dos casos nós esses país começando pela manufatura de
            produtos menores, por causa da mao de obra barata, semelhante ao que
            a China era a um tempo atrás e progressivamente enquanto a expertise
            e investimento externo vai sendo acomulado indo para produtos mais complexos
          - No segundo caso, que seria o do Brasil, nós teriamos a falencia de
            firmas ineficientes num primero perído, mas posteriormente nós
            teriamos os setores as quais nos temos vantagens estratégicas
            conseguindo crescer graças ao melhor acesso aos mercados globais, e
            portanto absorvendo a perda de empregos inicial.
