#+TITLE: Teste

Sr Presidente
Russia
Modelo: Financiamento direto, não vai envolver a escolha das publicacoes, apenas
em quais veiculos jornalisticos investir

Porque é legitimo: UE já se autopromove pros seus Estados, por exemplo fazendo
campanha para mostrar os beneficios de fazer parte, a partir do momento em que a
extremadireita é diretamente contra a UE, a UE estaria apenas se defendendo
enquanto mecanismo.


* Por que nós acreditamos ser o melhor?
- Governo Russo
- Influencia
- Maior parte dos partidos de extrema direito
- Ex: Nigel Farage e o partido Brexit
- A satira tende a atacar os extremos, no pior dos casos, esses jornais poderiam
  até mesmo criticar a UE
- Ou seja, se a extrema-direita tem por trás todo um aparato de informacao e
  guerra jornalistica de uma das maiorias potencias do mundo, que tem interesse
  direito na dissolucao da UE.
- Isso significa que o mais lógico é
- Mas nós acreditamos que como a extrema-direita é 1 - Um problema maior 2 -
  Vende mais porque as coisas sao mais absurdas
- Quando você satiriza esses veiculos, você acaba por descredibilizar eles, e
  qual o mecanismo?
  - Todo ser humano tende a querer ser identificado pelo grupo enquanto um
    membro válido
  - E entre as caracteristicas de um membro válido são a de ter qualidades como
    inteligencia e discernimento
  - A partir do momento em que se começa a veicularizar satira
  - Esses pensamentos sao ridicularizados
  - A Europa é um local com alto grau de instrução
  - A ideia é impedir que essas pessoas espalhem suas opinioes
  - E essas opinioes passem a ser consideradas normais
  - Se eles tiverem vergonha de veicular suas opinioes, isso significa que
    existe efetividade
- Portanto qual o contrafactual? Cenario do nosso mundo
  - Nós temos um mundo em que embora uma parcela que já seja adepta dos ideais
    de extremadireita talvez fique mais fanatico ainda. Alguém que apenas
    começou a ter contato com isso, seja por causa da sanção social, dissuadido
    a não expressar isso. E em muitos casos a mudar de opinião pela própria
    pressão coletiva.
    - Até por que um movimento poltiico só ganha força quando ele passa a ser
      aceito pela camada mais rica da população, a camada mais rica. Ex:
      Protestos Dilma, quando era só a ralé em 2013, não tinha problema, mas foi
      só o condominio de luxo ir pra rua de verde e amarelo, que apresidente caiu.
- E qual seria o mais provavel que tome o lugar?
  - Maior do que a ascenção dos partidos de extrema-direita são a ascenção dos
    partidos verdes, isso se deu justamente porque está deixando de ser cool ser
    de extrema direita. NO nosso mundo nós temos uma prevalecencia ainda maior
    desses partidos, justamente porque quem é jornalista tende a ser
    naturalmente mais progressista, ou seja, os verdes nao vao ser tao
    ridicularizados, o que seria bom para a propria UE, visto que a maioria dos
    partidos progressistas tendem a
