#+TITLE: EC APOIA O USO DE POLICIAMENTO "OLHO NO CÉU" EM ÁREAS URBANAS COM ALTOS ÍNDICES DE CRIMINALIDADE
Espero que tenha entendido essa porra
Porque mais crimes serem resolvidos
Porque no comparativo a privacidade importa menos e como o impacto desse
argumento é mitigada
Porque ela implica em uma menor violência policial, e menor probabilidade de
assassinatos

* Ponto 0 -> O que nós entendemos como policiamento olho no céu
- Uso massivo de drones
- Substituição do agente urbano por um drone que vai fazer boa aprte do
  patrulhamento nas ruas, deixando o policial para poder ficar parado, e só agir
  quando for necessário
- Voo constante e indiscriminado de drones

* Ponto 1 -> Porque mais crimes serão resolvidos
- A verdade é que a grande maioria dos crimes não são resolvidos
- Porque a maioria dos crimes são cometidos e logo após o perpetuador foge na
  neblina sem ser visto
- O tempo entre a vítima fazer um BO e a policia estar ciente do acontecimento
  -> Acaba por ser tanto que a possibilidade de se achar o criminoso se torna
  praticamente nula
- A baixa probabilidade acaba criando um vies na população de que chamar a
  policia é inutil
- O que cria menos Boletins de Ocorrencia, o que acaba criando um ciclo vicioso
  que acaba em menos crimes sendo solucionados
- Como a moção muda esse cenário?
  - Primeiro lugar um só policial passa a ser capaz de patrulhar várias áreas diferentes
  - Isso significa que a probabilidade dele encontrar um crime logo após ou
    durante o seu acontecimento se torna muito maior, e quanto mais rapido o
    crime é percebido pela policia, menos longe o criminoso vai ter fugido, o
    que significa em maior probabilidade de ser pego
  - Segundo lugar o drone consegue ver muito mais, justamente por estar no céu,
    isso significa que caso o cirme ocorra é muito mais fácil se manter na cola
    do criminoso, e posteriormente pegalo com seres humanos de carne e osso do
    que numa perseguição policial que muitas vezes é falha
* Ponto 2 -> Porque os medos de privacidade não são importantes
1. Nós acreditamos que no comparativo, o valor das possiveis vidas que serao
   salvas, e o valor abstrato da privacidade, por si só já é maior, e portante
   merece maior proteção, pela própria moral vigente
2. Nós acreditamos que como a moção traz áreas de alta criminalidade, a maior
   parte dos estabelecimentos vai ter algum tipo de camera, o que significa que
   caso um crime ocorra, vai haver uma gravação, a diferença portanto se torna
   entre você ter acesso a filmagem 5, 6 horas depois da gravação, ou você ter
   aceso enquanto ela estiver ocorrendo.
   - Em ambos os casos a perda de privacidade é igual, a diferença é que em um
     você tem maior probabilidade de resolver o crime
* Ponto 3 -> Porque significa menor violencia policial
- Nós acreditamos que boa parte da violencia policial, advem de agentes públicos
  que tem medo da comunidade em que trabalham, justamente por preconceitos,
  racismo estrutural e outras coisas.
- No pior dos casos a moção retira esses agentes públicos de boa parte de
  contato com essa comunidade em situações de patrulha, eles ficariam maior
  parte do tempo monitorando os drones.
- Isso significa menores numero de situações onde um policial em encontro com
  um morador local acabe por se sentir ameaçado, e acabe partindo para a
  violência, no pior dos casos gerando a morte, quantos foram os casos em que um
  policial por estar com medo da propria comunidade acabou por confundir um
  celular, ou furadeira com uma arma.
- No melhor dos casos, esse policial acaba por ter mais tempo para fazer o tipo
  de policlamente que ativamente previne crimes, coisas como ações na
  comunidade, seja com os lideres locais, seja nas escolas, seja nos centros comunitários
- Esse tipo de ação acaba por cria confiança entre a agencia pública e os
  moradores, diminuindo o  medo dos policiais, aumentando a probabilidade da
  comunidade ser de alguma forma ajudante dos policiais o que no geral diminui a
  violencia entre policial e morador, quanto a violencia entre morador e morador.
- Por que acreditamos que a moção daria mais tempo para o policial? ->
  Justamente porque agora invés de ser preciso pelo menos dois policiais em cada
  carro para patrulhar uma quantidade X de quarteiroes, agora vc só precisa de
  um unico policial, cuidando de 4 drones para atingir o mesmo efeito de 8
  policiais anteriorment.
- Isso significa que existe uma maior disponibilidade de policiais para fazerem
  trabalhos que muitas vezes n sao considerados prioridades em comparação com a
  patrulha, para agora o fazerem.
