#+TITLE: TH opposes the centrality of sport to national identity

- Um jogo entre Serbia e Bosnia na copa do mundo, não é apenas um jogo, é quase
  uma encenação de conflitos passados, as emoções são as mesmas, o ódio é o
  mesmo, e a necessidade de provar pro outro lado a sua superioridade é a mesma.
- Futebol é um jogo de soma zero
- A equipe diferente, é nós ou eles
- As equipes representam países, as equipes representam regiões, as equipes
  representam extratos sociais, as equipes em alguns locais chegam a representar etnias
- Como o esporte afetas as pessoas?
  - Esporte é religião, em vários locais, a irracionalidade é a mesma, a
    linguagem é diferente, igual a religião suas decisões no esporte são também
    definidas pelo contexto em que você vive, para muitas pessoas o time de
    futebol é aquele em que o pai levou para assistir seu primeiro jogo.
  - O futebol portanto tal qual a religião, passa a ser afetado por fenomenos
    históricos-sociais, isso pode ser exemplificado em um jogo de futebol entre
    equipes árabes e israelenses, o principal grito que você vai ouvir numa
    arquibancada ou vai ser Morte aos judeus ou morte aos árabes.
  - Além de ser religião, o esporte também é grupo, as pessoas tendem a ter a
    necessidade de fazer parte de um grupo, e não só isso, elas tendem a
    necessidade de serem valorizadas por esse grupo, o Esporte por sua vez
    fornece esse tipo de sentimento de união, o problema ocorre que geralmente
    pessoas que fazem parte de um grupo tem cada vez mais os seus pensamentos
    indivíduais extirpados(E aqui um disclaimer, eu não to falando de todo mundo
, mas existe sim uma classe que identifica o Esporte como algo a mais), isso
amplifica ainda mais o ódio entre extratos sociais, uma vez que, pessoas
irracionais tendem a ter um ódio maior, justamente pra provar pra esse grupo,
que elas merecem ser valorizadas(Ex: Mesmo mecanismo que faz jovens de 18 anos
virarem maquinas de guerra para proteger seu grupo, ou que faz protestos se
tornarem violentos quando um dos membros é atacado)
- Mas diferente de um conflito, da negociação, da politica, o Esporte é um jogo
  de soma zero, não existe possibilidade de uma arranjo que beneficia ambos os
  lados. Portanto, a vitória do outro necessariamente significa a minha derrota,
  a derrota portanto transfere aquela emoção e irracionalidade para outros
  aspectos da vida. -> Em último caso isso aumenta a retórica de Nós VS Eles,
  dentro da esfera pública, não só nos discursos dos indivíduos, como até mesmos
  nos discursos de figuras públicas, justamente por causa desse tipo de
  linguagem ser algo esperado pelos constituintes. -> Os políticos que tem
  interesse de se reeleger, portanto, são obrigados a abraçar esse tipo de
  retórica, apenas para agradar sua base.
- A influência do Esporte na política entretanto não para aí, nós também podemos
  analisar a influência da política no Esporte.
  - A partir do momento em que o Esporte atinge o nível de predominância na
    identidade nacional de um país. O que nós temos é a politização do Esporte.
  - O que nós queremos dizer por isso? O maior exemplo se torna a copa do mundo
    de 1978 na Argentina, onde a junta militar com o objetivo de apaziguar a
    nação comprou a copa do mundo para a Argentina.
  - Qual o mecanismo? Nós acreditamos que os políticos tem o interesse de se
    reeleger, nós acreditamos que o Esporte é unicamente valoroso para esses
    interesses, uma vez que ele tem curtissimo prazo, tal qual um show de
    carnaval, os benefícios de usar o Esporte são percebidos imediatamente pela
    populacã́o, diferentemente de uma obra de saneamento ou educação que só
    começa a dar resultados apenas depois de muitos anos, o Esporte portanto
    permite um político de oferecer o que a população quer, sem muito custo e
    com resultado imediato.
  - Qual o impacto disso? -> Nós temos portanto uma renegação de outras
    políticas públicas, que efetivamente melhoram a vida das pessoas, em
    detrimento de uma satisfação a curto prazo que no longo prazo só destroi as
    contas públicas.
  - Que exemplos nós temos disso? Tanto as olimpiadas de 2016 quanto a Copa do
    Mundo de 2014 envolveram gastos em infraestrutura massivos e
    injustificáveis, e que só forneceram ganhos ao PT que conseguiu vender essa
    ideia pro resto do Brasil.
- O que nós acreditamos que substituiria o Esporte?
  - Nós acreditamos que literalmente qualquer coisa que não envolva um jogo de
    soma zero e essa natureza competitiva forneceria uma avenida melhor de
    identidade nacional
  - Coisas como nacionalismo civico básico, valores e cultura compartilhadas,
    orgulho de grandes feitos da nação, forneceriam algo melhor ainda.
