#+TITLE: R1

* PM - Victor
- salvar vida em mais de um esentido
  + vida biologico -> perpetuacao do genes, reproducao, com valvula ela pode reproduzir, pode escolher genes melhores, selecao de melhores genes. n ter os mesmos problemas que ela, pode dar tudo errado, só que mesmo assim ela vai atringir o sentid biologico de vida.
  + vida qualitativo -> n adianta viver mil anos, se n tiver qualidade de vida, ela tem um romance, uma pessoa que ela ama, eles querem formar uma familia, ela pode viver só esses 10 anos, viver com o amor da vida dela, n vai consumir tantos remedios. ela vai ter o suficiente.
- sentido qualitativo de vida melhor.
- stephen hawking já queria logo casar quando descobriu qeu tinha doença, pelo menos casar com o amor da minha vida, mesmo sabendo que tinha risco de vida ele teve varios filhos.
- pode perder apoio de extremistas mas dane-se eles. todo mundo ocnhece alguem que come carne, caso que sensibiliza. n vai perder tantos seguidores.
- pode viver o resto da vida frustrada, no pior cenario ela vai ter uma vida melhor com qualidade de vida melhor. em todos os sentidos de vida, vc ter menos tempo mas ter maior qualidade vai ser benefico para evolucao humana.
- nao poderia fazer isso com uma valvula dfe escape, em prol da ruth a gente é a favor que ela use uma valvula de porco.
- depois pode usar outas tecnologias pra usar os proprios genes
* LO - Luisa
- literalmente n fala que ela vai morrer, questao de plastico é permanente e ela vai ter que tomar remedio, valvula de corpo vai ser trocada de 10 em 10 anos, em nenhum momento a vida dela vai acabar. entre fazer uma cirurgia e tomar um remedio.
- questao qualitativa -> questao darwinista, expectativa do mundo > a gente n vai ser mais feliz pra ter filho, n tem essa necessidade biologica, nos nao somos animais, pensando em outras coisas, valores mtu mais importantes, do que valores biologicos.
- 1 > Pessoa autonomia, crenças dela
  + claramente tem crencas, cre no veganismo, a partir do momento em que vc esta comendo carne, ato similar ao assassinato, crime contra a natureza, pq isso é importante? ela colocar uma protese de corpo vai contra o amago do que ela quer. o gov defende que ela vá contra algo que tá dentro do seu amago. a partir do momento que ela tem uma pessoa, ela é constituida pelas suas crenças, deve ter orgulho, deve ter autoconfianca e crença, a partir do momento que ela ta acreditando no que ela faz, a gente nao sabe se a ruth quer, se olhe no espelho a minha vida só esta a partir do momento em que eu estou usando na carne dfe outro animal, ruth vai ter que se eolhar no espelho todo dia, a partir do momento em que ela vai se odiar no futuro.
- 2 > relacionamento é consenso
  + defesa de uma pessoa que tem suas crencas suas fés e tem que ver e acreditar a aprtir daquilo, vc nao quer fazer uma pessoa viver semelhante a um assassinato, os relacionamentos nao sao feitos da forma que uma pessoa quer, consenso, que ponto a gente tá fazendo isso se sacrfifica de tal forma, só está vivo a partir do momento que vc faz algo que considera assassinato, a moção até fala que n tem chance de adoçao.
    - faz uma inseminacao, barriga de aluguel, in vitro(nao pode)
    - ele se apaioxonou pelas crencas, por quem ela é, o amor da vida dela, apesar de entender, entender que aquilo é parte de quem ela é, se odiar no espelho o tempo todo
    - poi victor > usar valvula de porco n faz contra a parte dela -> ainda sim que ela ta usando isso, ela ta indo contra, os veganos vao contra toda industria da carne, n melhora na cabeça de um vegano, acredita tao fielmente, vai cometer um assassinato.
    - pessoa se olhar no espelho todo dia.
* DPM - Levino
- morrer consideracao do pior cenario, possibilidade que temos que colocar, problema de saude grave.
- todo mundo toma remedio, esse n é qualquer tipo de remedio, problema de coracao, cardiaco mtu grave, naturalmente esse tipos de remedios n sao comuns, sao fortes, impactam na saude, tratamento forte, muito intensivo. se vc dixa de tomar um remedio vc pode morrer. vida mais tranquila é bem danado.
- O qq é a ruth > relacionamento, tem um engajamento forte com a causa vegana
  + pode gerar um ganho de vida qualitativo, medicamento tao forte dfe remedio.
  + tem uma familia, tem a busca do marido de ter um filho > essa chance de reproducao é muito grande, possibilidade é uma chance, a possibilidade de ter filho é uma opcao, no momento que ela é tirada, só pq ela pode nao querer agora n signifca que ela n queira no futuro, já é muito impactante, frustracao do marido, isso é bem negativo, gera impotencia, falta de capacidade. perder a chance de se reproduzir é uma limitacao a autonomia da ruth. autonomia limitada.
- cirurgia de 10 em 10 anos, periodo longo, mesmo que tenha um riscos é mais positivo, vida mais estavel, equilibrada, cirurgia é pontual, controlado, perigo constante, esse tipo de tratamento n é tao bom assim.
- POI 1OP > Como que fazer uma cirurgia, risco, no coracao, mais qualitativo que tomar um remedio > Medicacao bem controlada, é um risco, é uma dependencia, cirrugai é algo pontual, risco de 10 em 10 anos.
- Veganismo(6 MINUTOS) > urgencia, vida ou morte, precisar sobreviver(nao), publico pode parar de seguir ela, mal ver ela, muitos que vao se compadecer, do que condenem ela, situacao demergencial, deixar de seguir elas.
- Reproducao > Pode ter outras opcoes(nem precisava refutar) > inseminacao artifical é um risco maior, muito mais cara, e trabalhoasa
* DLO - Caroline
- A Ruth é uma pessoa de principios, possui valores, entende, tem consciencia ambiental, consciencia social.
- Valvula de porco é melhor do que a valvula de plastico por ter mais medicamentos > a cada 10 anos vc tem um risco, vc vai ter que tomar uma porrada de medicamento no pos-operatorio, risco da saude e psicologico, sobre a saude psicologica tao importante quanto a saude fisica. saber que vc tem uma valvula de porco dentro do corpo.
- Se a anvisa permite, é porque funciona, traz boa qualidade de vida, pessoa de principios, de valores, entende que n é tudo.
- Relacionamento é consenso, mesmo sendo o amor, tem que entender, seria um tanto quanto toxico, esperar que estar casado, implique em ter filhos, ele n pode esperar isso dela. tem que dar um pouco, pra receber um pouco.
- se ele gosta tanto de criança, existem outras formas, barriga de aluguel(nao pode, é adocao), pensar que somos simples animais é retrogrado, optar por uma barriga de aluguel, ela é uma pessoa com consciencia ambiental, só vai aumentar, engajar tanto financeiramente quanto pessoalmente.
* MG - Takerou
- Sacrificar certas coisas pra seguir certos sonhos que guardamenos, a ruth deveria sacrificar a conviccao, sacrifgicar o imperio de midias de influencer, sonho dela de ter filhos, diferente do que a 1op diz, n tá sendo obrigada, a propria mocao diz que ela ama crianças, sonho dela de ter crianças.(quem ama é o marido)
- os sonhos sao maiores que as ideologias, pq sao flexiveis.
- 1 - o veganismo é uma ideologia insustentavel, nos somos a favor dos animais, nos pensammos que vegniamos é algo radical demais, escandalo de uma influencer vegana estava comendo carne, pq a dieta vegana dela estava sendo insustentavel para saude, comer coisas de origem animal, nesse caso valeria a pena desistir de uma ideologia, a valvula de porco só adiantaria, pessoas gravidas mesmo sendo veganas tem que comer produtos de origem animal, pra suprir vitaminas, teria que mudare essa dieta.
- 2 - deveria dessitir o imperio de midias, a ruth seria mtu mais feliz, tendo uma vida de familia, tendo crianças que ela ama,vida familiar feliz, vivendo pelas aparencias e se preocupando pelos likes, temos muito casos de influencers que tem depressao, fruto dessa epoca das midias sociais, vida de aparencia, preocupadas com likes, com o que vai acontecer com a carreira pq é mtu volatil, vivendo uma vida deprimida triste, frustrada. A Ruth já naturalmente ama crianças
- POI 1OP > Compara usar partes de animais com assassinato > poderfia flexibilizar, lutando pelos direitos dos animais, conciliando com o sonho dela individual
- No nosso cenario a ruth seria uma pessoa feliz, com sonho de vida, nada impediria que depois de ter filhos ela mude essa valvula de corpo por uma de plastico.(Já matou o porco)
* MO - Joao Pedro
- A mocao nao fala que o sonho da ruth é ter filhos(já tinha percebido)
- No melhor cenario > status quo machista > patriarcado > maternidade compulsoria > enxergamos mulheres como invalidas e sem filhos > a maior realizacao da vida delas é ter um filho no final, ruth é uma mulher que pode muito bem ser realizada sendo ativista vegana > sendo blogueira.
- o que é veganimos > mtu mais abrangente do que comer carne > questoa moral de matar um animal > agronegocio e uso de agua > desmatamento em massa >
- 2g fala que veganimos é insustentavel > n estamos pra discutir isso > Esta casa COMO Ruth escolheria a valvula de porco ou plastico
  + Ruth é vegana am,a ser vegana, homem decidisse corpo dela, ter filho tbm é uma decisao irrevesivel, o que é relevante é o marido quer ter filho, Ruth estaria mtu mais feliz da possibilidade de ter filho do que poder escolher.
- Suposto amor da vida dela > mas se o amor apenas quer ela com uma valvula de corpo, ele n é o amor da vida dela, se ele querer reconhecer os riscos, medo de perder sua esposa em cirurgias de risco.
- Carreira que é apenas likes, nos compramos esse tradeoff ela tem esses riscos, mas é uma carreira, carreira de policial tbm tem diversos riscos, valvula de plastico é melhor, n é APENAS UMA VEZ, mas 10 em 10 anos.
- Conviccoes pessoais, batalhou muito para convicoes, n é o homem que vai ter o canal vaginal dilatado 10cm pra sair uma criança de lá.
* WG - Gabriela
- 1op qualidade de vida -> cirurgia tem risco, andar na rua tem risco, em questao dos remedios, se um remedio é tao forte a ponto de te deixar infertil, o quao forte é esse remedio(n necessariamente)
- troca de valvula ortea, 5 semanas, uma vida inteira tomando remedio.
- Opcao de escolha, valvula de plastico sendo permanente, tirando uma escolha, marido pode estar forçando a ter filhos, a solucao de plastico ela é permanente,  intuitivo a ruth casar com alguem que compartilha objetivos e sonhos dela. ruth n casaria com alguem que vai contra tudo dela.
- reproduzir n é uma necessidade, ela n precisa se repdoduzir ou ter filhos, a gente tem um status quo machista, a valvula de porco daria uma opçao pra ruth. a valvula de plastico tiraria o direito de escolha.
- assassianto pra cumprir o que o marido quer, casaria com alguem que compartilharia com seus convicoes
- POI 2O > Poderia botar uma valvula de porco e depois plastico -> A mocao n traz que a infertilidade trazida pelo medicamento, a valvula de porco precisa ser trocada, ela pode sim colocar a valvula de plastico.
- Veganismo é uma corrente ideolgoica, abrir mao de algumas coisas concluir um sonho, que pode ser objetivo de vida dela. reducao do consumo, poder ser um processo reverso, pode ser uma ativista e concluir um sonho.
- No periodo de gravidez, poderia engravidar se ela quisesse, voltar a consumir alguns produtos, suplementos vitaminicos, b12, ferro e caralho a quatro, n poderia adotar, no nosso cenario ela tem a opcao de escolha.
- Escolha de vida com o marido dela
* WO - Pedro Henrique
- 1GOV n tem preocupacao com coisas que importam pra Ruth, Ruth ser vegana, passa pelo cenario do governo, relativizado de maneira mujito facil, intencao do marido, infoslide é machista, tornar ruth uma reprodutora, uma chocadeira, satisfazer o marido.
- Melhor cenario governo > tem interesse em ter filho com marido, pouco numero de seguidores > conviver e se olhar no espelho, tem que continuar trocando, essa valvula, crescimento exponencial.
- Pior cenario > coloca valvula de plastico > e deseja ter filhos > a unica coisa que vai ser tirada é a questao da maternidade, emprego e principios intactos, ou esse amor é condicionado a ter ou nao filhos ou ele n é real
- POI 1G > sabendo que todos os remedios passam pelo processo de cobaia -> nao sao todos os remedios, a ruth como uma pessoa desse meio, ela vai ter essa preocupacao, n teria preocpuuacao, se ela já é vegana, n vai fazer esse tipo de esqueci
- veganismo perspectiva interna de contemplacao, ta deixando de contribuir, faz uma propagacao, isso é o sustento dela, causa de vida, n é simplesmente trabalho. preocupado em qual é a melhor opçao pra ruth, a unica pespectiva, unica coisa que ela traz sobre a ruth, negar o veganismo,.
- explica pq ganha do 1g mas isso ta claro
- 1op tenta esboçar, n traz pressao da sociedade(mas o joao pedro n explica)
