#+TITLE: DebateTreino10_06_2020
- Nós acreditamos que a métrica desse debate é o que é melhor pro movimento
  feminista como um todo, nós não acreditamos que essas artes tenham como alvo
  classico homens, portanto não acreditamos em efeito backlash ou nada do
  genero. O que torna nosso caso o mais impactante do lado da oposição porque
  nós vamos tratar dentro dos termos do governo.
  - O que refuta essa ideia do 1 Gov de que a moção afeta os homens, até porque
    o publico geral desse tipo de midia não são homens heteros, acho bem dificil
    o tio do zap que é machista, é alguém que seja publico da Beyonce, no pior
    dos casos ele vai ver exatamente como a Sabrina disse, como uma piada, do
    mesmo jeito que mulher mandando em homem não é considerado empoderamento, é
    considerado piada.
- Afirmação
  - Mirroring simplifica o discurso feminista, reduzindo a um classico embate
    entre homens e mulheres
  - Reduz a causa feminista a atitudes micro, quando boa parte dos reais danos
    estao no plano macro
  - O que nós acreditamos ser o objetivo do movimento feminista?
    - Não a subjulgação da mulher contra o homem, mas a subjulgacao da mulher
      contra a estrutura
    - Quando a Beyonce faz um videoclipe em que ela encarna uma policial mulher
      que faz todas as atitudes descritas da moção, mas a sua linha de roupas
      continua escravizando mulhers no Sri Lanka. Isso não é feminismo
    - Por que nós acreditamos que a causa é reduzida nesse sentido?
      - Nós acreditamos que tão importante como a formulação de soluções para os
        problemas de qualquer grpo social, é a formação de agenda.
        - Conceito de ciencia política, antes mesmo de discutirmos o que fazer
          em relação a algo, é preciso discutir o que merece a atenção dentro da
          miriade de problemas da sociedade
        - Tanto pro parlamento quanto pra um movimento social
        - A partir do momento em que a narrativa dominante dentro da midia é
          esse tipo de feminismo
          - Nós acreditamos que isso acaba subconcientimente por influenciar a
            formação de agenda dentro dos movimentos, ou dentro das proprias mulheres.
          - Ser empoderada deixa de ser por exemplo ter o mesmo salário que um
            homem, ter a capacidade de ocupar as mesmas posicoes que um homem
          - E passa a ser ter tido como aceito pequenas atitudes, que no final
            das contas não interferem em nada com o sistema como um todo
            - Por que nos acreditamos que a presença desse tipo de midiatizacao
              necessariamente exclui outros tipos?
              - Justamente porque é facilmente marketavel, grandes artistas como
                a Beyonce ou a propria Rihanna em Man Down, já se usam desse
                tipo de midiatizacao, porque vende
                - Porque no curto prazo dá uma certa sensação de felicidade,
                  voce enquanto mulher ver aquilo, até porque é algo que te
                  acontece diariamente
                - E porque é mais fácil de explicar, voce nao precisa adentrar
                  em outras áreas do conhecimento, n precisa analisar
                  privilegios etc.
              - A partir do momento em que Rihanna e Beyonce tornam-se icones
                feministas, mulheres que não tem incentivo nenhum a quebrar
                outros tipos de subjulgação da mulher. Até porque a maioria
                delas se aproveitam desse tipo de exploração
                - Vc influencia a tomada de decisoes no geral
                - E voce marketiza o feminismo, agora quem dita a formação de
                  agenda, do movimento sao grandes empresas que não tem
                  interesse nenhum nos outros tipos
                - Outros movimentos de base, que tem interesse em outras pautas
                  portanto passam a ter comparativamente o mesmo espaço
                  - Ex: Se uma mulher é 80% do tempo exposta aos problemas de
                    catcalling, mainsplanning e apenas 20% do tempo exposta a
                    outras vertentes. Quando ela for decidir no que lutar, vai
                    ser mais fácil ela ir pro que é mais fácil
                    - 1 Ela conhece
                    - 2 Ela vê que o resto da sociedade tá lutando contra isso
                    - 3 Isso pode ser lidado sem grandes modificacoes na
                      sociedade, apenas modificacoes em comportamentos individuais
                  - Comparacao de mundos portanto
                    - Um mundo sem mirroring, é um mundo em que outros tipos de
                      problemas entra no spotlight. Justamente porque eles nao
                      precisam competir com esse tipo de atitude tao marketavel.
                    - Um mundo em que os homens enquanto individuos não são
                      vistos como maiores inimigos. Esse tipo de redução de
                      feminismo por exemplo, coloca homens negros como inimigos,
                      quando na verdade, as mesmas estruturas e ferramentes que
                      sao usadas para oprimir mulheres, também sao usadas da
                      mesma forma para oprimir esses homens.
                      - 1 - A mesma diferença salarial que existe entre homens e
                        mulheres, existe também entre homens brancos e homens
                        negros. Seja devido a uma série de comportamentos que
                        impedem que homens negros avancem na carreira.
                        Caracateristicas que sao exaltadas nos homens brancos,
                        nao sao consderadas como boa para homens negros e
                        mulheres(Assertividade ser vista como histeria, ambição
                        ser vista como avareza etc)
                      - 2 - A mesma forma como os crimes perpetuados por homens
                        contra mulheres(violencia domestica) os crimes
                        perpetuados por pessoas brancas contra pessoas negras
                        também são ocultados(Seja a policia seja por exemplo o
                        caso de como homens brancos nao vao presos e homens
                        negros sim)
                      - 3 - A mesma forma como mulheres sao sistematicamente
                        excluidas do processo de decisao politica, homens negros
                        também são, e pelas mesmas ferramentes. Considerar
                        candidatos negros e mulheres como menos capazes, por
                        motivo algum senao o genero e a cor da pele.
