#+TITLE: THWCreatePublicHousingForThePoorInWealthyAreas

- Onus de imposto seja o mesmo
  - Não haja onerosidade -> Mas o Estado não tem poder pelos estabelecimentos privados
  - As pessoas precisam de retribuição daqueles que os causaram mal -> Isso só
    vale se essas pessoas realmente tiverem uma vida melhor o que no nosso caso
    vamos mostrar que não existe.
- 2 Afirmações
  - Construir esse tipo de habitação ignora as especificidades das populações pobres
    - Senhor presidente
    - Ricos tendem a ter carro X Pobres tendem a andar de onibus
    - Ricos tendem a usar o sistema de saude privado X Pobres tendem a usar o
      sistema de saude publico
    - Pessoas ricas tendem a viver longe do centro da cidade, comparativamente
    - Na decada de 60 nos EUA -> Influxo de negros do Sul para os grandes
      centros hurbanos
    - Locais onde pessoas brancas e de clase media viviam
    - Resultado? -> White Flight
    - No pior dos casos, o que acontece é que essas pessoas simplesmente fogem
      desses locais, como semrpe o fizeram na histórai.
    - O mesmo ocorre no Brasil, imigração nordestina e dos negros, os famosso
      cortiços, ou as favelas no Rio
      - Onde os ricos do Brasil vivem, longe dos centros urbanos, nos seus
        condominio de pedra e cimento, isolados do resto da sociedade
      - E aqui refuta o ponto do Brito -> Os melhores hospitais, as melhores
        escolas FICAM NO CENTRO, mas ninguem mora no Centro, o centro é o local
        onde tem justamente esses serviços públicos, mas as pessoas efetivamente
        não moram majoritariamente nesses locais, justamente pra você fazer um
        conodminio, com piscina, quadra de tenis, caralho a quatro, não tem.
      - Por que eles fazem isso? -> Medo da violencia, amenidades melhores, e
        PORQUE ELES PODEM -> Como assim?
        - Transporte pessoal(Carro)
        - Implica em possibilidade de morar mais longe da cidade
        - Isso é particularmente importante nas nossas cidades brasileiras que
          não foram feitas para abrigar pedestres
      - Na comparativa nos temos os pobres
        - Que trabalham precisam se deslocar até o centro da cidade
        - Essas pessoas precisam ter acesso ao transporte publico
        - Redistribuir essas pessoas para as áreas mais ricas das cidades,
          implicaria em coloca-las perto dos ricos
        - O problema?
          - Nenhum das vantagens de viver nesses locais é boa para os pobres
            - Custo de vida é necessariamente mais alto
            - As amenidades em sua grande maioria estao dentro desses
              condominios fechados ou desses suburbios(Caso EUA)
            - A unica coisa que você faz é coloca-las dentro de um local com um
              acesso muito pior, e mesmo se criar um plano de transporte urbano
              você vai precisar deslocar essas linhas
            - Com o dinheiro que você gasta, você vai ter que compenar o custo
              de vida mais alto
            - O que você vai ter é uma presença massiça da policia nesses locais
              - Visto que
              - Os moradores desses condominios vão ter o maior medo dom undo
                desses habitantes, e vão usar do seu poder politico para
                imprimir opressão policial, maior ainda do que essas pessoas já
                sofrem no status quo, onde a violência só atinge pobres.
              - E refutação integrada ao Brito sobre a questão de maior
                segurança público, o que na verdade vai ser pior.
  - Constribui para a quebra dos laços que mantem uma comunidade pobre sobrevivendo
    - O que isso implica?
    - TIrar essas pessoas dos seus locais
    - Colocar essas em um canto onde elas não vivem
    - Longe de suas comunidades
    - Longe dos estabelecimentos que eles conhecem a vida toda
    - Isso é particularmente importante no caso de pessoas mais humildes?
      - Por que?
      - Porque essas comunidades justamente por causa do descaso do Estado,
        acabam se autoorganizando entre si para suprir o minimo de apoio para os
        seus membros
      - Eu não to aqui com uma visão ufanista de pobres como seres maravilhosos
        que cuidam entre si
      - É condição sinequanon para um comunidade que não tem apoio do Estado,
        que seus membros cuidem dentre si
        - Isso vai desde
          - A Pegar fiado no mercadinho da esquina
          - A uma das mães da rua fica na calçada olhando as crianças brincarem
            enquanto as outras podem trabalhar(Cuidado comunitário das crianças)
          - Isso tudo é algo que é quebrado a partir do momento em que você
            transplanta elementos dessa comunidade para outro canto
          - O problema é
            - Esse pessoal vai continuar sem ter voz no Estado
            - Pq voz implica em organização e dinheiro
            - Ou seja, a vida material deles não vai mudar, vai na verdade
              piorar como eu falei na questão do custo de vida e transporte para
              o centro
            - E agora a alternativa que eles tinham que era a comunidade formada
              naquele local, é de repente torada ao meio, porque não tem como
              você transplantar uma favela inteira para um bairro, simplesmente
              não tem espaço, ou seja, voce vai dividir essas pessoas.
