#+TITLE: DebateTreino01_Abril_Salas
Moção: EC urbanizaria e reconheceria favelas (e.g construir infraestrutura,
dar títulos de propriedade,  permitir oferecimento de serviços) em detrimento de
transferir gradualmente seus moradores para conjuntos habitacionais

Chair: CC
- Antonio Murilo e Marcus Felipe - 2O
- Dennis e Bel - 1O
- Maju e Karol - 2G
- Sabrina e Neri - 1G

Chair: Jessica
- Danilo Ferreira e Yuri - 2G
- Tobbias e João - 2O
- Paulo e Gustavo - 1O
- Carol e Guilherme - 1G

* Debate
** PM
- Dar titulo de propriedade, liberar os cartórios que a sua casa é seu terrenos,
segurança juridica e economica
- COnstruir infrestrutura
- Qual o nosso pior caso? Trafico dominando -> Já é o atual, e eles já liberam a
  construção de esgoto e escolas(Esse é o pior caso?)
- Acesso ao capitalismo
  - Segurança juridica, essa casa é sua, esse esgoto é seu, antes o governo
    podia chegar e tomar sua terra, com essas medidas, e construcao. Fazer com
    que a gente tenha a segurança juridica naquele terreno.
  - Favelados tem muito empreendedorismo
    - Ex: População alugando a sua casa, legalizar esse comércio. Tenham mais
      acesso a crédito, aumentar o empreendedorismo.
    - Ex2: Restaurantes, turismo nas favelas, comidas tipicas da favela
    - Se transferir para os conjuntos habitacionais
    - Perder todo empreendedorismo
  - Estancar produção de riqueza
  - POI: O cara pode ainda assim ir pro restaurante, e pegar um onibus. Nada
    garante que a pessoa vai ter um ponto bom.
- Caso proposto pela oposição -> Favela para conjuntos habitacionais, ruim para
  o proprio governo. Mais fácil passar os postes, do que comecar do 0
- As favelas sao no centro, mais fácil elas se deslocarem, conjunto habitacional
  sao longes, pq sao terrenos baratos, gentrificacao da população. Jogando 15/20
  minutos para 2/3 horas de transporte. Capital de tempo desfavoravel para ele.
  Tempo que ele tava estudando.
** LO
- Refutações
  - Dif transporte -> Mesmo que isso seja isolado -> Tirando de área de facção
    -> É preferível a perder meu tempo, seguir os tramites burocráticos que a
    facção coloca. Existe uma série de regras no domínio daquele território.
- Duas métricas
  - Melhor qualidade de vida
  - Mais custo eficiente
    - Um governo com recursos limitados, são várias de uma cidade. Cada centavo
      mal gasto, menos vidas impactadas de vida ruim
  - Pq conj habitacional é mais eficiente
  - DOis tipos de favela
    - Offlimites -> Morros, áreas de risco, encosta de morro, uma chuva pode
      causar deslizamento. Áreas de preservação.
      - Pq é preferível ->
        - Mesmo com infraestrutura, tirando custoeficiente -> Mais perigosa,
          ainda vai ser área de risco, menor qualidade de vida no geral.
        - É bem mais fácil fazer infraestrutura nesses locais -> Construir um
          saneamento -> Uma favela que tá no morro
        - Custo no geral para aquela cidade -> Algo mais caro de se fazer, mais
          caro de conectar, do que colocar duma área mais plana, todo um
          planejamento
        - Uma favela que está numa área de rio, manancial -> Governo tem um gasto a mais.
    - Área pobre que não está em área de risco
      - Dominio do tráfico -> Ele que escolheu aquele local -> Pode ter
        capacidade de controle.
        - Tirando da área de influencia -> Tirando essas pessoas dessa regiao,
          dessas vidas melhores -> Discurso da possibildiade de escolha
          estratégica.
        - Tenho a capacidade de escolher um local melhor.
        - Case padrão -> Mais na média -> Pode escolher um terreno mais barato,
          mais fácil de conectar os serviços de saneamento. Tenho a liberdade de
          escolher menor necessidade de infraestrutura.
          - Ainda existe possibilidade da favela ser distanciada.
** DPM
- Afastar masi ainda essas pessoas de sociedade, e n ter convivio com outras pessoas.
- Favela walkinjg tour
  - A importancia de investir de todos esses terrenos -> Beneficio tanto
    economico quanto social
    - Turismo que já existe. Os gringos vem de fora.
    - Qual o benefício de reconhecer -> Pessoas que não chegam se quer qualquer
      serviço básico -> Se essas pessoas vao ser mandadads para um conjunto
      habitacional
      - Como vai ser tao distante se os terrenos sao mais baratos? N entendeu
    - Como vai garanti que as pessoas nao acompanhem as pessoas para conj
      habitacional?
    - Reconhecer a cultura brasileira para gringo ver água de coco -> Pessoas
      conhecem o funk mas é um funk mais elitizado -> Eles tem uma visao daquela
      criminalidade do rio de janeiro.
    - Esses espaços foram perdidos para zonas mais perigosas, tráfico e milicia.
      Não garante. Conjuntos habitacionais pequenos???
    - Afastamento social
      - Afastar elas socialmente, do conjunto que elas já vivem, manda
        simplesmente pra um conjunto habitacional, como a propria europa faz,
        ela esconde a populacã́o periférica, vc não vê uma favela na Europa. Pq
        elas estao jogadas num conjunto habitacional -> Quais as consequencias
        dessas pessoas?
      - Vc tira aquelas raizes daquela pessoa. Pessoas que vivem numa area
        perifericas, afastam elas e jogam numa area mais zuada. Exclusao,
        Excluir todas as pessoas.
      - A forma mais barata -> Admite que é mais barato
      - POI: Impacto social é mais important do que uma melhora objetiva -> É
        uma melhora sair daquele local que vc conhece a anos, e simplesmente ser
        mandado pra um conjunto habitacional.
      - Urbanizar, reconhecer, das oportunidade, uma forma mais bonita, sem
        risco, gringos que conheceram e acabaram morrendo.
** DLO
- Afastamento social -> Vai fazer as pessoas ficarem tristes -> Delegarem ao
  esquecimento -> Pressupondo governo mau pra mim -> Governo tá fazendo
  deliberadamente -> Eu teria que assumir minimamente nesse caso que essa
  melhora de infrastrutura não vai ser tão boa
  - Mesmo nesse pior caso -> Pq não é tão impactante -> Falham em mostrar uma
    piora objetiva na qualidade de vida -> Só colocam uma coisa sobre mais tempo
    pra transporte(N é tão relevante) -> Segundo dada pelo governo, ele não
    colocou de qualquer forma. Ele não vai só botar um cimentinho para dizer que
    tá feito.
- Nada impede que as façõ̀es vao pra outros local -> Nós temos um maior controle
  governamental -> ALgo legalizado -> Pessoas estao em um limbo legal -> Governo
  por falta de verba para fiscalizar -> Acaba simplesmente deixando elas lá. ->
  Quando coloca a população numa área legalizada -> Sabe onde é -> Planejou ->
  Assumir um conjunto habitacional -> Minha casa minha vida -> A galera foi pra
  lá -> Governo quando estabelece -> Estabelece seu próprio dominio territorial
- Impacto saudade de casa -> Tirar do local que elas cresceram -> Para eles me
  provarem que esse governo é verdadeiro -> Derrubar as duas métricas que foram
  trazidas -> Qual cenário coloca uma melhor vida -> Ela pode sentir saudade de
  casa, mas não é algo anormal do ser humano mudar de local -> Pior caso
  possível pessoas que sao filhas de militares, se adaptam ao novo estilo de
  vida -> Muito mais fácil se adaptar se o novo estilo de vida é melhor.
- A partir do momento que vc está tomando a posicã́o mais cara, vc éstá
  impactando menos vidas. Pq devo levar em conta a saudade de uma pessoa ->
  Contra a vida de outras pessoas.
- POI: Se o tráfico ganha venda de drogas, se o consumidor se mudou também -> Pq
  a milicia não vai se mudar pro local -> No seu caso continua a milicia.
- Não provam nada em relação ao turismo -> Ninguem se importa a imagem do gringo
  em relação ao Brasil. O proprio melhoramente descaracterizaria a favela -> Ele
  vai pra favela pelo cristo ou pelo pão de açucar.
** MG
- Questao historicas de como as pessoas chegaram ea essas favelas -> Processo de
  urbanizacao acelerada -> Foram marginazliadas dessas sociedade -> Essas
  pessoas construiram suas vidas nesses locais -> Apego sentimental e
  pertencimento sobre o lugar
- Tudo invovolve o home seeking > Essas pessoas foram marginalziadas e excluidas
  -> Por muito tempo da sociedae -> Excluir elas novamente -> Construitram suas
  vidas seus trabalhos -> Toda a questao cultural que foram formados nas favelas
  -> Terá uma baixa.
- Vao conseguir ter seus empregos, e tudo garantido -> Vao ser colocadas em
  outros lugares, como a gente sabe que esas pessoas sao marginazliadas -> Será
  que elas vao ser aceitos -> Empregadores de outros lugares.
- Titulos de propriedade -> Vao poder dizer qeu aquela casa pertence a eals ->
  Vai dar um melhor sensacao de pertencimento.
** MO
- Conceito de gentrificaco que foi utlizado -> Urbanizacao é a linguagem de uma
  elite que busca excluir
  - Quando vc aumenta os bagulhos, aumenta o preço, e com isso a quantidade de
    conhecimento para viver naquele local -> Niveis de salario para aquele lugar
  - A urbanizacao é um fator da elitização, é a arquitetura das elites, e isso é
    um fator extrermamente importante
  - Conceito da cidade é agregador, junta todas as tribos. Isso vai nos dizer o
    que? Ao a gente não ter pessoas de baixa renda, e nenhum tipo de aporte, a
    exclusao. Vai excluir o ser desses ambientes.
  - Urbanizar não é apenas danosos para o ambiente, mas para as pessoas que vao se
    sentir ruim nos proprio ambiente, ali vai tá cheio de gente de outas
    realidade, afetando o psicologico dessas pessoas
  - A urbanizacao que o governo quer levar até a favela, vai tirar completamente
    esse conceito e ser danoso pra isso.
- A falta do poderio estatal ali
  - Diversas forças arbitrarias -> Trafico milicias -> Governo vai ter um
    problema de garantir os direitos basicos -> Fornecer poder que o governo
    alternativo -> Regras arbitraria -> Construir conjuntos habitacionais é uma
    maneira eficaz -> Tira de um local que tá enrraizado -> Um lugar muito mais
    acessível -> Lugar vai conseguir entrar lá -> Garantir os direitos básicos
    -> O tráfico n é apenas uma questao de mudança -> A gente tem um ponto de
    tráfico -> Tira toda a base -> O trafico é um aporte de defesa -> Se esconde
    atrás de população -> Ponto do conjunto habitacional
  - ALgumas pessoas comprar drogas vai ser distante, nao vai ter a força o
    conjunto de situacoes que vai conseguir
  - Tira as condicoes favoraveis -> Favela já é um ambiente estigmatizado pela
    milicia ou trafico
- Gearia uma autonomia da comunidade
  - Seu zé pode ter uma mecearia na esquina -> Pode botar o preco que ele quiser
    -> Os transportes, valores intersubjetivos -> O que vai se adaptar melhor na
    realidade daquelas pessoas -> Impacto extrememante positivo -> Tira essa
    liberdade dessas pessoas.
  - Conceito da infrestruturea -> Contruir infraestrutura é dificl -> Ignora
    conceitos geograficos, capaz de colocar saneamtno, esgoto, etc, e não tem
    nada a ver com o conceito de afastar, mesmo que as pessoas, se a gente
    conseguir urbanizar, fator de risco.
** WG
- Os problemas relativos as diferencas dos moradores, vao muito alem da questao
  economica -> Aprofundamos essa analise psicologica
  - Depressao -> Retirada de pessoas de sua rotina geral, impacta profundamente
    o ser interior delas. Ainda nessa questao psicologica que GUilherme fala, as
    situacaoes objetivas superariam e as pessoas se sentiriam melhor, por
    estarem morando não mais nas favelas. Imaginem só, como ficaria a situação
    daqueles que possuem. Além da questoa sentimental, possuem mais de um
    terreno na favela. Aquele que já foi investido dinheiro, pode até ser um
    comercio de onde a pessoa sobrevive. Conseguiu se estabelecer investiram
    dinheiro. E cibsegyuran conquistar com muito suor e dificuldade, o comercio
    delas, ai elas sao realocadas, para esses locais de transferencia? Como fica?
  - Sem documentacao sem segurança juridica, como elas comprovariam, e teriam
    proporcional aos seus terrenos originais, a clientela nao só da propria
    favela, mas as pessoas perto, essa pessoa vai ficar insatisfeita. Cai na
    questao dos imapctos psicologicos, todo seu esforço foi jogado pro lixo,
    como se ela foi um mero objeto do governo, qualquer momento possa deslocar.
  - Vai ter a fomentação desse comercio, vai se sentir satisfeita, agraciado, a
    qualidade de vida com a fomentacao vai ser melhorada.
  - Questao da onerosidade -> Bastante mitigadas -> Projetos uma das coisas mais
    caras -> Poderiam ser feitos -> Com parcerias com universidades publicas
  - Valorizacao daquela área daria um retorno economico para o governo a longo
    prazo. O governo mais tarde vai poder cobrar, um IPTU mais caro. Arrecadar
    impostos divernos, como o IPTU.
  - Enquanto isso, na realocacao nos perderiamos tudo que foi construido. O
    impacto social e psicologico seria profundo, ocasionando depressao e ataques
    de panico.
** WO
- Favelados sao empreendedores -> Trafico -> Crime organizado _> Empreendimetno
  carro chefe -> Causa da morte de agata e tals, todo discuso mostra que o
  empreendimento, n tem como competir com o outro trabalhgo. Empreendimento é
  fetiche de burgues. -> N consegue competir com a galera -> Falha economica é o
  unico destino.
- O que faltou falar do Guilherme -> Falta realocar sistemas já estabelecidos ->
  Vai realocar tudo -> Replicar modelos de praça -> Tá implicito na moção -> A
  estrutura vai manter
- Falar em urbanizar a favela é trazer uma lignagem que serve de instrumento as
  elites -> Entrar na favela -> Falar em urbanizacao é criar outra favela, outra
  margem???????
- Favela walking tour -> COisificacao, rico gosta de tirar foto do instagram, n
  é eficaz, manter sob as rédeas da sub oposição -> Manter um discurso
- Urbanizar é reconhecer cultura brasileira -> A forma da urbanizacao é a forma
  da burguesia -> ELa afasta a burguesia -> Essa contextualizacao como
  instrumento da elite -> Quando a gente urbaniza a gente destroi tudo que não
  cai na forma
- Titulo de propriedade é um valor quase nulo -> E dominadas pelas elites ->
  Ascenção dessas pessoas na
- VAalores subjetivos -> O apreço n é algo eterno imutavel -> Mantem os mesmos
  circos sociais, vai ter depressao e crise de ansiedade.
- Uma pessoa n adquire depressao, a aspectos objetivos. fora do escopo da
  suadade -> Acesso a saude, segurança, etc. VAer os filhos prosperaem
  economicamente muito melhro que ver uma pracinha
- Como a urbanizacao -> Se conjunto -> Essa linguagem das elites, eles sao mais
  autonomos -> N vai ter a linguagem da urganizacao -> N vai ter necessidade de
  gentrificar o ambiente -> TOda a estrutura de comercio local vai ser mantida.
- POI Sab -> Mudar de cidade é uma coisa comum -> Pessoas que sao serem
  obrigadas a sairem -> Transferir gradualmente
